### ISSUE TITLE
`@JsonIdentityInfo` does not work with `java.net.URI`, even with `SerializationFeature.USE_EQUALITY_FOR_OBJECT_ID`

### ISSUE THREAD

**Issue by PrajwalGonsalves** [FasterXML/jackson-databind#1002]
I have created a few simple Pojo models and have made the "URI" attribute as the JsonIdentityInfo for all the objects. I have created 2 objects with the same "URI", as per the documentation, serializer should serialize these two objects as one because the URI is the same but this does not happen. Further, during deserialization it says that there are two objects with the same uri. Below are the pojo models used. 

```java
package com.datamodel;

import java.net.URI;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "uri")

public class Element {
    private URI    uri;

}
```

```java
package com.datamodel;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "uri")

public class Block extends Element {

    private String               name;
    private final List<Property> properties = new ArrayList<>();

}
```

```java
package com.datamodel;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "uri")

public class Property extends Element {
    private Block type;
}
```

```java
package com.conversion;

import java.io.File;
import java.io.IOException;
import java.net.URI;

import com.datamodel.Block;
import com.datamodel.Property;
import com.fasterxml.jackson.core.JsonGenerationException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class ObjectToJsonTest {

    public static void main(String[] args) throws IOException {

        // Child block 1 with URI as "BlockUri"
        Block block1 = getBlock("Block1", "BlockUri");
        // Child block 2 with URI as "BlockUri"
        Block block2 = getBlock("Block2", "BlockUri");
        // Parent block
        Block compositionBlock = getBlock("WrapperBlock", "CompUri");

        // Property is a wrapper for block1
        Property property = new Property();
        property.setUri(URI.create("PropURI"));
        property.setType(block1);

        // Property is a wrapper for block2
        Property property2 = new Property();
        property2.setUri(URI.create("Prop2Uri"));
        property2.setType(block2);

        // Adding child blocks with their wrappers
        compositionBlock.getProperties().add(property);
        compositionBlock.getProperties().add(property2);

        ObjectMapper objectMapper = new ObjectMapper();
        File file = new File("file.json");
        file.createNewFile();
        objectMapper.writeValue(file, compositionBlock);
        objectMapper.readValue(file, Block.class);

    }

    private static Block getBlock(String name, String uri) {
        Block block = new Block();
        block.setName(name);
        block.setUri(URI.create(uri));
        return block;
    }
}
```

1. When i write the compositionBlock object, the following is written into the file:- 

```json
{
  "@class": "com.datamodel.Block",
  "uri": "CompUri",
  "name": "WrapperBlock",
  "properties": [
    {
      "@class": "com.datamodel.Property",
      "uri": "PropURI",
      "type": {
        "@class": "com.datamodel.Block",
        "uri": "BlockUri",
        "name": "BlockName1",
        "properties": []
      }
    },
    {
      "@class": "com.datamodel.Property",
      "uri": "PropURI",
      "type": {
        "@class": "com.datamodel.Block",
        "uri": "BlockUri",
        "name": "BlockName2",
        "properties": []
      }
    }
  ]
}
```

As we have already given the annotation @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "uri"), objects with the same uri should be serialized as a single object and not two separate objects. 
For example in the code above, property1 and property2 have the same uri's. Yet, they are serialized as 2 separate objects.Am i missing something or is there a bug in the jackson implementation. 

Because of this wrong serialization, deserialization fails with the below exception :- 

```
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Already had POJO for id (java.net.URI) [com.fasterxml.jackson.annotation.ObjectIdGenerator$IdKey@638e58f7] (through reference chain: com.datamodel.Block["properties"]->java.util.ArrayList[1]->com.datamodel.Property["uri"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1428)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:308)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithObjectId(BeanDeserializerBase.java:1036)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:154)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:126)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:84)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:956)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:234)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:206)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:106)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:306)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithObjectId(BeanDeserializerBase.java:1036)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:154)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:126)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:84)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:956)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:41)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2115)
	at com.conversion.ObjectToJsonTest.main(ObjectToJsonTest.java:46)
Caused by: java.lang.IllegalStateException: Already had POJO for id (java.net.URI) [com.fasterxml.jackson.annotation.ObjectIdGenerator$IdKey@638e58f7]
	at com.fasterxml.jackson.annotation.SimpleObjectIdResolver.bindItem(SimpleObjectIdResolver.java:20)
	at com.fasterxml.jackson.databind.deser.impl.ReadableObjectId.bindItem(ReadableObjectId.java:66)
	at com.fasterxml.jackson.databind.deser.impl.ObjectIdValueProperty.deserializeSetAndReturn(ObjectIdValueProperty.java:92)
	at com.fasterxml.jackson.databind.deser.impl.ObjectIdValueProperty.deserializeAndSet(ObjectIdValueProperty.java:82)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:306)
	... 22 more
```

Could you please tell me if this is already a bug or am i missing something.

**Comment by cowtowncoder** [comment]
I think your problem is that you do not have unique ids for blocks; both specify id of "BlockUri", and deserializer notes this: it can not resolve same id to two different objects.

**Comment by PrajwalGonsalves** [comment]
Exactly, that was my point. If i have one URI for two objects, the serializer should have serialized both the objects as the same. That doesn't happen and only while deserialization, the mapping fails

**Comment by PrajwalGonsalves** [comment]
Probably the earlier example was a little too long . I've created a simpler one below. 

package com.datamodel;

import java.net.URI;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "uri")
public class Element {

    private URI    uri;
    private String name;
}

-------------------------------------------------------------------------------------------------------------------------------
package com.datamodel;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

public class CustomObjectMapper extends ObjectMapper {

    private static final long serialVersionUID = -1889881835475513634L;

    public CustomObjectMapper() {
        super();
        this.enableDefaultTypingAsProperty(DefaultTyping.JAVA_LANG_OBJECT, JsonTypeInfo.Id.CLASS.getDefaultPropertyName());
        this.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        this.enable(SerializationFeature.INDENT_OUTPUT);
    }
}
-------------------------------------------------------------------------------------------------------------------------------
package com.conversion;

import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;

import com.datamodel.CustomObjectMapper;
import com.datamodel.Element;
import com.fasterxml.jackson.core.JsonGenerationException;
import com.fasterxml.jackson.databind.JsonMappingException;

public class JsonToObjectTest {

    public static void main(String[] args) throws JsonGenerationException, JsonMappingException, IOException {

        Element element = new Element();
        element.setUri(URI.create("URI"));
        element.setName("Element1");

        Element element2 = new Element();
        element2.setUri(URI.create("URI"));
        element2.setName("Element2");

        List<Element> elements = new ArrayList<>();
        elements.add(element);
        elements.add(element2);
        File file = new File("file.json");
        CustomObjectMapper objectMapper = new CustomObjectMapper();
        objectMapper.writeValue(file, elements);
        objectMapper.readValue(file, Element[].class);

    }
}
------------------------------------------------------------------------------------------------------------------------------


After serializing this my file.json contents is as below:

[ {
  "@class" : "com.datamodel.Element",
  "uri" : "URI",
  "name" : "Element1"
}, {
  "@class" : "com.datamodel.Element",
  "uri" : "URI",
  "name" : "Element2"
} ]

NOTE: Though the URI is the same, jackson maps it as two separate elements, it should have ideally mapped it like this :

[ {
  "@class" : "com.datamodel.Element",
  "uri" : "URI",
  "name" : "Element1"
}, "URI" ]

**Comment by cowtowncoder** [comment]
No, that's not how it goes. Objects must BE same, not just happen to have same id. Jackson does not do de-duping or canonicalization; identity handling refers to Object identity, not equality of id properties or such.

**Comment by PrajwalGonsalves** [comment]
Ok. I was just checking how i can override the object equality checking(overriding the .equals method) and found this:  https://github.com/FasterXML/jackson-databind/issues/270  

Now i have added a overridden method in my element class, to say that two objects are equal if their uri's are equal: 

 @Override
    public boolean equals(Object object) {
        if (object == this) {
            return true;
        } else if (object == null || !(object instanceof Element)) {
            return false;
        } else {
            Element element = (Element) object;
            if (element.uri.toString().equalsIgnoreCase(this.uri.toString())) {
                return true;
            }
        }
        return false;
    }


and configured my objectMapper to : 
objectMapper.configure(SerializationFeature.USE_EQUALITY_FOR_OBJECT_ID, true);

Even now the serialization output is the same as earlier.

**Comment by cowtowncoder** [comment]
Ok. Yes, with that feature it would seem like code should work. I'll have a look. Thank you for the additional information.

**Comment by cowtowncoder** [comment]
@PrajwalGonsalves Ah. You do also need to implement `hashCode()`, for example as:

        @Override
        public int hashCode() {
            return uri.hashCode();
        }

because otherwise it won't be found from a `HashMap`

And one more problem that may affect testing is use of root-level `List` -- I used `Element[]` for my test, and when `hashCode()` is specified it passes.

It is possible to make root-level `List` work too, but if so, type must be explicitly specified by something like:

        String json = mapper.writerFor(new TypeReference<List<Element>>() { })
           .writeValueAsString();

Either way, I think the usual "if overriding `equals()`, also override `hashCode()`" applies here.

**Comment by cowtowncoder** [comment]
I _think_ things should work, with added information on settings, and requirement to ensure that id values are both equal and give same hash code; latter needed since they are used as keys in a `HashMap`.
