### ISSUE TITLE
JsonTypeInfo.As.EXTERNAL_PROPERTY does not work with a Delegate

### ISSUE THREAD

**Issue by alexwen** [FasterXML/jackson-databind#1003]
I am using a library which generates the Jackson deserialization code as a delegate. I have created a class here which simulates this format:

```
public class HeroBattle {

    private final Hero hero;

    private HeroBattle(Hero hero) {
        this.hero = requireNonNull(hero);
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.EXTERNAL_PROPERTY, property = "heroType")
    public Hero getHero() {
        return hero;
    }

    @JsonCreator
    static HeroBattle fromJson(Delegate json) {
        return new HeroBattle(json.hero);
    }

    public class Delegate {
        @JsonProperty
        @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.EXTERNAL_PROPERTY, property = "heroType")
        Hero hero;
    }

    public static void main(String[] args) throws IOException {
        ObjectMapper mapper = new ObjectMapper();

        final String json = mapper.writeValueAsString(new HeroBattle(new Superman()));
        final HeroBattle battle = mapper.readValue(json, HeroBattle.class);

        assert battle.getHero() instanceof Superman;
    }

    public interface Hero {
    }

    public static class Superman implements Hero {
        public String getName() {
            return "superman";
        }
    }
}
```
This results in the following exception:

```
Exception in thread "main" java.lang.IllegalStateException: No default constructor for [simple type, class HeroBattle]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:211)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeWithExternalTypeId(BeanDeserializer.java:652)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:262)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2161)
	at HeroBattle.main(HeroBattle.java:43)
```

**Comment by cowtowncoder** [comment]
Ok that may be a bug. One thing you may want to try is to add `mode` property for `@JsonCreator`, with value `Mode.DELEGATING`. It should not be necessary, but with possibility of confusion between single-property creator and delegating one that could be one reason for failure.

I assume this is (or can be reproduced) with Jackson 2.6.3?

**Comment by alexwen** [comment]
Yes, sorry should have said the version. I originally found the issue in 2.4.6 but verified it in 2.6.3 as well.

Specifying Mode.Delegating does not change the exception that is thrown.

**Comment by cowtowncoder** [comment]
I can reproduce the issue locally; added a failing unit test. No idea yet as to what causes this.

**Comment by cowtowncoder** [comment]
Actually looks like this specific combination of "exotic" features is just not yet supported, unlike, say, property-based creator and external type id. Will try to see if it'd be easy enough to add support.

**Comment by cowtowncoder** [comment]
Took a while to figure this out, but I think I solved it the way it should be solved; test had one minor flaw (no setter for `Superman`), but after fixing that also test passes.

**Comment by alexwen** [comment]
Awesome! Thanks for the fix!
