### ISSUE TITLE
Jackson fails to read XML file it writes based on JAXB annotations

### ISSUE THREAD

**Issue by rpatrick00** [FasterXML/jackson-databind#1004]
I have a simple test at https://github.com/rpatrick00/jackson-polymorphic-test where I am trying to use polymorphic types using JAXB annotations.  The code works fine with straight JAXB but Jackson 2.6.3 is failing to read the file that it wrote.  The file that Jackson with JAXB annotations wrote looks like this:

<pre>
&lt;?xml version="1.0" encoding="UTF-8" standalone="yes"?&gt;
&lt;company&gt;
    &lt;computers&gt;
        &lt;desktop id="computer-1"&gt;
            &lt;location&gt;Bangkok&lt;/location&gt;
        &lt;/desktop&gt;
        &lt;desktop id="computer-2"&gt;
            &lt;location&gt;Pattaya&lt;/location&gt;
        &lt;/desktop&gt;
        &lt;laptop id="computer-3"&gt;
            &lt;vendor&gt;Apple&lt;/vendor&gt;
        &lt;/laptop&gt;
    &lt;/computers&gt;
&lt;/company&gt;
</pre>

When trying to use Jackson to rads the file back in, it fails with the following:

<pre>
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (FIELD_NAME), expected START_OBJECT: need JSON Object to contain As.WRAPPER_OBJECT type information for class test.Computer
 at [Source: company-jackson.xml; line: 4, column: 9] (through reference chain: test.Company["computers"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:946)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:91)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromObject(AsWrapperTypeDeserializer.java:49)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:992)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:247)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2620)
	at test.RunThis.readJacksonFile(RunThis.java:84)
	at test.RunThis.main(RunThis.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
</pre>

Maybe I am just doing something stupid but it seems like Jackson should be able to read a file that it generated.

**Comment by cowtowncoder** [comment]
@rpatrick00 General idea is indeed that Jackson should read content it writes, at minimum.

What would be necessary here however is definition of Java classes, and code invoked, ideally simplified as much as possible to reproduce the problem.

**Comment by rpatrick00** [comment]
@cowtowncoder, the github project I pointed you to is a VERY simple reproducer that has been stripped down to the essentials needed to reproduce the problem.  There was no way for me to attach the project to the issue so I just pointed you at it.  Is there a better way to do this?

**Comment by cowtowncoder** [comment]
@rpatrick00 Sorry, my bad. Read this too quickly and missed the link. Thank you for providing the repro project.
