### ISSUE TITLE
NullPointerException at AsPropertyTypeDeserializer.java:92

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-databind#1055]
While deserializing a class, I get the following exception:

```
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.taxsimulator.configuration.ScenarioConfiguration["years"]->java.util.ArrayList[0]->com.taxsimulator.configuration.YearConfiguration["workerToOperations"]->com.taxsimulator.configuration.Operations["typeToOperation"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1474)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:411)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.datatype.guava.deser.GuavaImmutableMapDeserializer._deserializeEntries(GuavaImmutableMapDeserializer.java:47)
	at com.fasterxml.jackson.datatype.guava.deser.GuavaImmutableMapDeserializer._deserializeEntries(GuavaImmutableMapDeserializer.java:15)
	at com.fasterxml.jackson.datatype.guava.deser.GuavaMapDeserializer.deserialize(GuavaMapDeserializer.java:124)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:461)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:411)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:461)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:376)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1511)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1181)
	at com.taxsimulator.util.Json.from(Json.java:61)
	at com.taxsimulator.FitnessFunctionDebugger.main(FitnessFunctionDebugger.java:22)
Caused by: java.lang.NullPointerException
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:92)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131)
	at com.fasterxml.jackson.datatype.guava.deser.GuavaImmutableMapDeserializer._deserializeEntries(GuavaImmutableMapDeserializer.java:49)
	at com.fasterxml.jackson.datatype.guava.deser.GuavaImmutableMapDeserializer._deserializeEntries(GuavaImmutableMapDeserializer.java:15)
	at com.fasterxml.jackson.datatype.guava.deser.GuavaMapDeserializer.deserialize(GuavaMapDeserializer.java:124)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:461)
	... 26 more
```

Most of the stack-trace is Jackson-specific so I think this might be an internal bug in the way Guava ImmutableMaps are deserialized.

**Comment by cowwoc** [comment]
It looks like this is caused by the following sequence of events:

1. Given:

```
@JsonTypeInfo(use = JsonTypeInfo.Id.CUSTOM)
@JsonTypeIdResolver(OperationTypeIdResolver.class)
public interface Operation
```

2. StdTypeResolverBuilder line 65 gets invoked: `_typeProperty = idType.getDefaultPropertyName();` but for `JsonTypeInfo.Id.CUSTOM` the returned value is `null`.
3. This is passed down to `AsPropertyTypeDeserializer` which assumes that `_typePropertyName` is not null. Explosion ensues.

**Comment by cowwoc** [comment]
On second glance, maybe it's enough to simply swap the `equals()` condition.

Also, this bug impacts version 2.7.0-rc2 so it might be prudent to fix this before making the final release.

**Comment by cowwoc** [comment]
It turns out this was caused by a combination of user error and lack of validation on Jackson's part.

Notice that in my code I specified `@JsonTypeInfo(use = JsonTypeInfo.Id.CUSTOM)` without providing the property name. Once I set the property name the exception no longer occurred.

Expected behavior: Jackson should validate that `property` is set for the `CUSTOM` mechanism. If it is not, Jackson should throw a clear exception indicating that the parameter is mandatory.

**Comment by cowtowncoder** [comment]
@cowwoc Sounds like this should be improved. At this point a simple reproduction would be much appreciated, and if so fix/improvement could make it in 2.7.0 final.

**Comment by cowwoc** [comment]
Here is the testcase you requested:

```
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.DatabindContext;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonTypeIdResolver;
import com.fasterxml.jackson.databind.jsontype.impl.TypeIdResolverBase;
import com.fasterxml.jackson.datatype.guava.GuavaModule;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import java.io.File;
import java.io.IOException;

public final class Main {

    @JsonTypeInfo(use = JsonTypeInfo.Id.CUSTOM)
    @JsonTypeIdResolver(OperationTypeIdResolver.class)
    public interface Operation {

        double getAmount();
    }

    public final class OperationTypeIdResolver extends TypeIdResolverBase {

        @Override
        public String idFromValue(Object value) {
            return idFromValueAndType(value, value.getClass());
        }

        @Override
        public String idFromValueAndType(Object value, Class<?> suggestedType) {
            return "test";
        }

        @Override
        public JsonTypeInfo.Id getMechanism() {
            return JsonTypeInfo.Id.CUSTOM;
        }

        @Override
        public JavaType typeFromId(DatabindContext context, String id) {
            return context.constructType(String.class);
        }
    }

    public static void main(String[] args) throws IOException {
        ObjectMapper objectMapper = new ObjectMapper().registerModule(new Jdk8Module()).
                registerModule(new GuavaModule());
        File in = new File("candidate.json");
        objectMapper.readerFor(Operation.class).readValue(in);
    }
}
```

Where `candidate.json` is:

```
{
  "workerToType": 
  {
  },
  "years": 
  [
    {
      "number": 35,
      "workers": 
      [
      ],
      "hierarchy": 
      {
        "childToParent": 
        {
        },
        "parentToChildren": 
        {
        }
      },
      "workerToOperations": 
      {
        "Sole-Proprietorship": 
        {
          "typeToOperation": 
          {
          }
        },
        "Employee": 
        {
          "typeToOperation": 
          {
          }
        }
      }
    }
  ]
}
```

Let me know if this works for you.

**Comment by cowtowncoder** [comment]
Thanks!

**Comment by cowtowncoder** [comment]
Improved a bit to avoid NPE, hopefully give better hint at what is going on.

**Comment by JavaHelper** [comment]
How to solve below error in Spring Boot ?

Failed to write HTTP message: org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: (was java.lang.NullPointerException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException)
