### ISSUE TITLE
CUSTOM TypeInfo leads to property getting serialized twice

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-databind#1056]
1. Given the testcase on https://github.com/FasterXML/jackson-databind/issues/1055#issuecomment-166760172
2. Provide `@JsonTypeInfo` a property name of "amount"
3. Serialize the class
4. Notice that "amount" shows up twice in the output.

Meaning, "amount" gets added to the JSON map once by `@JsonTypeInfo` and once by the implicit `@JsonProperty` on `getAmount()`.

Expected behavior: JSON map should only contain a single instance of the property.

As a side-note, I'm not sure that the produced output (with duplicate keys) is even legal JSON.

The workaround is simple, add `@JsonIgnore` on `getAmount()`.

**Comment by cowtowncoder** [comment]
Does this even require use of custom type info?

**Comment by cowtowncoder** [comment]
Test case from #1055:

-----

```java
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.DatabindContext;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonTypeIdResolver;
import com.fasterxml.jackson.databind.jsontype.impl.TypeIdResolverBase;
import com.fasterxml.jackson.datatype.guava.GuavaModule;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import java.io.File;
import java.io.IOException;

public final class Main {

    @JsonTypeInfo(use = JsonTypeInfo.Id.CUSTOM)
    @JsonTypeIdResolver(OperationTypeIdResolver.class)
    public interface Operation {

        double getAmount();
    }

    public final class OperationTypeIdResolver extends TypeIdResolverBase {

        @Override
        public String idFromValue(Object value) {
            return idFromValueAndType(value, value.getClass());
        }

        @Override
        public String idFromValueAndType(Object value, Class<?> suggestedType) {
            return "test";
        }

        @Override
        public JsonTypeInfo.Id getMechanism() {
            return JsonTypeInfo.Id.CUSTOM;
        }

        @Override
        public JavaType typeFromId(DatabindContext context, String id) {
            return context.constructType(String.class);
        }
    }

    public static void main(String[] args) throws IOException {
        ObjectMapper objectMapper = new ObjectMapper().registerModule(new Jdk8Module()).
                registerModule(new GuavaModule());
        File in = new File("candidate.json");
        objectMapper.readerFor(Operation.class).readValue(in);
    }
}
```

with `candidate.json` of:

```json
{
  "workerToType":  { },
  "years":  [
    {
      "number": 35,
      "workers":  [ ],
      "hierarchy":   {
        "childToParent":  { },
        "parentToChildren": { }
      },
      "workerToOperations":   {
        "Sole-Proprietorship":  {
          "typeToOperation":   { }
        },
        "Employee":  {
          "typeToOperation":  {  }
        }
      }
    }
  ]
}
```

**Comment by cowtowncoder** [comment]
@cowwoc Looks like test is missing definition of `Operation` implementation type. But as to duplicate, `@JsonTypeInfo` should use `As.EXISTING_PROPERTY` for `include` to avoid duplicate.

**Comment by cowwoc** [comment]
@cowtowncoder I can't use `As.EXISTING_PROPERTY` because the property contains an enum value, not a class name. Meaning, Jackson might be able to serialize/deserialize the enum value, but it won't then know what class name should get deserialized for each corresponding enum value. That's why I went with the `CUSTOM` mechanism.

**Comment by cowtowncoder** [comment]
@cowwoc what I mean is that inclusion defaults, as per:

    public As include() default As.PROPERTY;

and there is no custom value for `include`. This determines how inclusion occurs, and NOT what the id handling mechanism is. So I think you do need to override this as `EXISTING_PROPERTY`, while retaining custom id handler mechanism.

**Comment by cowwoc** [comment]
Sounds good. I'll give this a try. You should probably alter the Wiki + Javadoc documentation accordingly (give users a hint they might need to alter this related property at the same time).

**Comment by cowwoc** [comment]
Oh, this is also problematic... the Javadoc for `As` reads: `Note that for type metadata type of Id.CUSTOM, this setting may or may not have any effect.`

So actually I can't use this property, can I? :)

**Comment by cowtowncoder** [comment]
@cowwoc let me put it this way: if this setting did not have any effect, who would be writing duplicate value? Your code doesn't do it; and default property handler would only write one copy. So type (id) serializer must be doing it.
At worst case, setting would have no effect; as things are, it defaults to `As.PROPERTY`, and that is specifically not what you want if you have explicit property with same name -- this will lead to duplicate.

**Comment by cowwoc** [comment]
Using `include(EXISTING_PROPERTY)` seems to work. Thanks!

**Comment by cowwoc** [comment]
Actually, I just got an exception with the above configuration. Here is the exception:

```
com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (VALUE_NUMBER_INT), expected FIELD_NAME: missing property 'type' that is to contain type id  (for class com.taxsimulator.candidate.WorkerPlan)
 at [Source: C:\Users\Gili\AppData\Local\Temp\TaxSimulator1239130669627445742.json; line: 38, column: 12] (through reference chain: com.taxsimulator.candidate.TaxPlan["years"]->java.util.ArrayList[0]->com.taxsimulator.candidate.YearPlan["workers"]->java.util.HashSet[1]->com.taxsimulator.candidate.CorporationPlan["children"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:946)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:149)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:84)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:247)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:378)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithObjectId(BeanDeserializerBase.java:1071)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:122)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:93)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:247)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:378)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:378)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1511)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1181)
```

Here is the JSON file being deserialized:

```
{
  "years": 
  [
    {
      "number": 0,
      "workers": 
      [
        {
          "@id": 1,
          "id": "Employee",
          "operations": 
          [
            {
              "type": "BUY_RRSP",
              "amount": 1000.0,
              "childIndex": 0
            }
          ],
          "children": 
          [
          ],
          "type": "EMPLOYEE"
        }, 
        {
          "@id": 2,
          "id": "Corporation",
          "operations": 
          [
            {
              "type": "BUY_RRSP",
              "amount": 1000.0,
              "childIndex": 0
            }
          ],
          "children": 
          [
            1
          ],
          "type": "CORPORATION"
        }
      ]
    }
  ]
}
```

The error complains a missing property "type" but if you walk the object graph you'll find that it exists. Any ideas?

**Comment by cowwoc** [comment]
I figured out how to work around this problem, but I'm still not sure why it's happening.

I have concrete classes Employee, Corporation which extend AbstractWorker, which implements interface Worker.

Worker had annotations:
`@JsonTypeInfo(use = JsonTypeInfo.Id.CUSTOM, property = "type", include = JsonTypeInfo.As.EXISTING_PROPERTY)
@JsonTypeIdResolver(WorkerTypeIdResolver.class)`

AbstractWorker had annotation:
`@JsonIdentityInfo(generator = IntSequenceGenerator.class, property = "@id")`

For some reason, moving all the annotations to `Worker` made the problem go away. Any ideas why?

**Comment by cowtowncoder** [comment]
@cowwoc Not sure why that would have significance here, because structurally there should be no difference (unlike if, say, type information was included as wrapper element or array). So not immediately obvious what the difference is. There are no custom deserializers either, which can sometimes cause issues due to subtle bugs (code advancing token stream inadvertently).

**Comment by cowwoc** [comment]
Closing this issue for now. I'll reopen it if I see it again.
