### ISSUE TITLE
SubType information omitted when serializing object in generic wrapper

### ISSUE THREAD

**Issue by guspower** [FasterXML/jackson-databind#1094]
Given:

```groovy
    static class Wrapper<T> {
        final T value

        Wrapper(T value) {
            this.value = value
        }

        static <T> Wrapper<T> wrap(T value) {
            new Wrapper<T>(value)
        }
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME)
    @JsonSubTypes([
        @JsonSubTypes.Type(value = TypeA, name = "type-a"),
        @JsonSubTypes.Type(value = TypeB, name = "type-b"),
    ])
    abstract class Base {
        String name
    }

    class TypeA extends Base {}
    class TypeB extends Base {}
```

When:
```groovy
    def 'cannot unmarshall generic type containing object mapped by annotation'() {
        given:
            def mapper = new ObjectMapper()
            mapper.enable(SerializationFeature.INDENT_OUTPUT)

        and:
            Base typeA = new TypeA(name: 'typeA')
            Base typeB = new TypeB(name: 'typeB')

        and:
            String typeAJson = mapper.writeValueAsString(Wrapper.wrap(typeA))
            String typeBJson = mapper.writeValueAsString(Wrapper.wrap(typeB))

        when:
            Base actualTypeA = mapper.readValue(typeAJson, mapper.typeFactory.constructParametrizedType(Wrapper, Wrapper, Base))
            Base actualTypeB = mapper.readValue(typeBJson, mapper.typeFactory.constructParametrizedType(Wrapper, Wrapper, Base))

        then:
            actualTypeA.name == typeA.name
            actualTypeB.name == typeB.name

    }
```

Then:
```groovy
com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class informa.GusSpec$Wrapper<informa.GusSpec$Base>]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: {
  "value" : {
    "name" : "typeA"
  }
}; line: 2, column: 3]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1106)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3731)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2762)
```

Version 2.6.2

Is this actually a bug or a usage fault?

**Comment by cowtowncoder** [comment]
Actually, this is usage. When serializing, type erasure makes type of value you pass to basically be `Wrapper<?>`, which is taken to mean about same as `Wrapper<Object>`. Since `Object` base type does NOT have polymorphic type handling enabled, type id serialization is not applied.

There are ways to fix this, by forcifully specifying type used for root value, although as general best practice I would recommend trying to avoid use of generic types for root values -- they lead to many problems, and I've found it easier to just use concrete wrapper types.

But to solve this particular case, two main ways:

1. Create single-use type like `class MyStringWrapper extends Wrapper<String> { }`; type information will be retained as it is not generic (but super-type information gives all necessary generic typing!)
2. Use `ObjectWriter`, with `mapper.writerFor(type)`; type can be either `TypeReference` or `JavaType`; instances of latter constructed using `TypeFactory` (instance obtained via `ObjectMapper.getTypeFactory()`

**Comment by guspower** [comment]
Hi @cowtowncoder - thanks for your response. We opt'd for solution 2 as we can get the type at render time. Type erasure strikes again!

**Comment by cowtowncoder** [comment]
@guspower glad you got it working. Type erasure can be nasty, and this is the biggest problem wrt Jackson.
