### ISSUE TITLE
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token

### ISSUE THREAD

**Issue by vrkmurali** [FasterXML/jackson-databind#1149]
Currently I am working on rest service, while consuming the service getting error.

public String userName;
public String refernceNumber;  
public String requestType;  
public String fullName;  
public String dateOfBirth;  
public String placeOfBirth;  
public String gender;   
public String nationlaity;   
public String telphoneNo;  
public String mobileNo;  
public String note;  
public String email;  
public String processId;   
public List<DocumentDTO> attachmentsList; 
and my documentdto is like

private String doumentNameEng;  
private Integer documentId;  
private String fileName;  
private MultipartFile attachment;  
private String ticketNo;
private String dmsRefId;

enter code here   
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token at [Source: org.apache.catalina.connector.CoyoteInputStream@1171c8a3; line: 1, column: 233] (through reference chain: com.micd.process.dto.applcation["attachmentsList"]) at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164) at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:575) at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:569) at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:259) at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217) at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:207) at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23) at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464) at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:98) at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295) at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121) at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888) at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2094) at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.readJavaType(MappingJackson2HttpMessageConverter.java:168)

help me to getout from this error, unable to understand this eror.

i am new to this rest service and can you help me to resolving error, y its givng error for attchmentList.

**Comment by cowtowncoder** [comment]
@vrkmurali Exception says it all: content you have has a JSON String value, but POJO structure excepts a `List`. So there is some kind of structural mismatch. Without seeing JSON content it is impossible to know what exactly happens.

But this sounds more like a usage question, not a bug, so please use mailing list (`jackson-user@googlegroups.com`) for future questions.

**Comment by vrkmurali** [comment]
Thanks , i will send  mail.
