### ISSUE TITLE
com.fasterxml.jackson.databind.JsonMappingException: [Ljava.lang.String; cannot be cast to java.lang.String (through reference chain: java.util.Properties["names"])

### ISSUE THREAD

**Issue by ljubad** [FasterXML/jackson-databind#1174]
There is possible bug introduced in tags/jackson-databind-2.6.0:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.fasterxml.jackson.databind.ser.TestArraySerialization
Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.365 sec <<< FAILURE! - in com.fasterxml.jackson.databind.ser.TestArraySerialization
testStringArrayInMap(com.fasterxml.jackson.databind.ser.TestArraySerialization)  Time elapsed: 0.016 sec  <<< ERROR!
com.fasterxml.jackson.databind.JsonMappingException: [Ljava.lang.String; cannot be cast to java.lang.String (through reference chain: java.util.Properties["names"])
	at com.fasterxml.jackson.databind.ser.std.StringSerializer.serialize(StringSerializer.java:49)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFieldsUsing(MapSerializer.java:664)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:467)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:29)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3525)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2915)
	at com.fasterxml.jackson.databind.ser.TestArraySerialization.testStringArrayInMap(TestArraySerialization.java:89)
```

In tags/jackson-databind-2.5.5 serialization works correctly and result example is:

`Running com.fasterxml.jackson.databind.ser.TestArraySerialization
{"names":["david","filip","ivan"]}`

Here is custom testing code that proves this possible bug:

```java
public void testStringArrayInMap() throws Exception
    {
        Properties map = new Properties();
        map.put("names", new String[]{"david", "filip", "ivan"});
        System.out.println(MAPPER.writeValueAsString(map));
    }

``` 

I tested this on Ubuntu Linux and Windows 7 with java 8

Simple workaround for this problem is to use java.util.HashMap instead of java.util.Properties.

**Comment by cowtowncoder** [comment]
This is a bug in usage: both keys and values of `Properties` should be `String`s, and not other value types.

**Comment by JacksonTi** [comment]
You made a mistake by tring to use java.util.Properties as String.
There is a similar question in Stackoverflow.
https://stackoverflow.com/questions/21988512/jackson-deserialization-exception-when-trying-to-serialize
