### ISSUE TITLE
`@JsonSerialize(as=superType)` behavior disallowed in 2.7.4

### ISSUE THREAD

**Issue by markwoon** [FasterXML/jackson-databind#1231]
#1178 fixed the problem with collections, but I'm seeing a problem with individual objects.

I'm getting:

```
com.fasterxml.jackson.databind.JsonMappingException: Failed to widen type [simple type, class org.pharmgkb.model.AccessionIdentifier] with annotation (value org.pharmgkb.model.BaseAccessionIdentifier), from 'getReference': Class org.pharmgkb.model.BaseAccessionIdentifier not a super-type of [simple type, class org.pharmgkb.model.AccessionIdentifier]

	at com.fasterxml.jackson.databind.AnnotationIntrospector.refineSerializationType(AnnotationIntrospector.java:821)
	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.refineSerializationType(AnnotationIntrospectorPair.java:488)
	at com.fasterxml.jackson.databind.ser.PropertyBuilder.findSerializationType(PropertyBuilder.java:194)
	at com.fasterxml.jackson.databind.ser.PropertyBuilder.buildWriter(PropertyBuilder.java:73)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._constructWriter(BeanSerializerFactory.java:805)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:608)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanSerializer(BeanSerializerFactory.java:388)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanSerializer(BeanSerializerFactory.java:271)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:223)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:157)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1215)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1167)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:490)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:688)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:107)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1428)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1129)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1001)
	at org.pharmgkb.jackson.JacksonTest.testModelObjects(JacksonTest.java:48)
```

On something like:

```
public class Foo {
  @JsonSerialize(as = BaseAccessionIdentifier.class)
  @JsonDeserialize(as = BaseAccessionIdentifier.class)
  public AccessionIdentifier getReference() {
  }
}
```

```
public interface AccessionIdentifier {
}
```

```
public class BaseAccessionIdentifier implements AccessionIdentifier {
}
```

**Comment by cowtowncoder** [comment]
Thank you for reporting this. Looks like this could be related to delegation via annotation introspector pair.

**Comment by cowtowncoder** [comment]
I can reproduce this easily, nothing to do with introspector pair delegation; also fails with master (2.8.0-SNAPSHOT).

**Comment by cowtowncoder** [comment]
Ok yes, my bad. Just had not extended this to `as` or `keyAs` cases, just `contentAs`.
