### ISSUE TITLE
JsonUnwrapped not working properly with ConstructorProperties

### ISSUE THREAD

**Issue by lukaszrek** [FasterXML/jackson-databind#1274]
After migrating to Jackson 2.7.5 from Jackson 2.6 I found weird interaction between JsonUnwrapped and ConstructorProperties. See following test.

```
public class JacksonTest {

    @Test
    public void shouldDeserializeValueObjectWithUnwrappedProperty() throws Exception {
        ObjectMapper mapper = new ObjectMapper();
        Outer outer = mapper.readValue("{ \"value\" : 1, \"nested1\" : 2, \"nested2\" : 3 }", Outer.class);

        assertThat(outer.value, is(1));
        assertThat(outer.nested.nested1, is(2));
        assertThat(outer.nested.nested2, is(3));
    }

    @RequiredArgsConstructor
    private static class Outer {
        private final int value;

        @JsonUnwrapped
        private final Nested nested;
    }

    @RequiredArgsConstructor
    private static class Nested {
        private final int nested1;
        private final int nested2;
    }
}
```

Just for clarity, after delomboking, value objects have following definitions:

```
    private static class Outer {
        private final int value;

        @JsonUnwrapped
        private final Nested nested;

        @java.beans.ConstructorProperties({"value", "nested"})
        public Outer(int value, Nested nested) {
            this.value = value;
            this.nested = nested;
        }
    }

    private static class Nested {
        private final int nested1;
        private final int nested2;

        @java.beans.ConstructorProperties({"nested1", "nested2"})
        public Nested(int nested1, int nested2) {
            this.nested1 = nested1;
            this.nested2 = nested2;
        }
    }
```

Running test gives stack trace:

```
com.fasterxml.jackson.databind.JsonMappingException: Could not find creator property with name 'nested' (in class com.egnyte.delphi.cloudapp.common.jackson.ObjectMapperProviderUnitTest$Outer)
 at [Source: { "value" : 1, "nested1" : 2, "nested2" : 3 }; line: 1, column: 1]

    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:261)
    at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1233)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:553)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:227)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:142)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:406)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
    at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
    at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:475)
    at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3890)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3785)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2833)
```

I found workaround for this problem. I need to add `@JsonProperty` annotation to field annotated with `@JsonUnwrapped` :

```
    @RequiredArgsConstructor
    private static class Outer {
        private final int value;

        @JsonProperty("nested")
        @JsonUnwrapped
        private final Nested nested;
    }
```

With this addition test passes. However it would be nice if `@JsonPropery` is not needed here.

**Comment by cowtowncoder** [comment]
Hmmh. That is odd. Basically name of unwrapped property should be mostly ignored (it's a placeholder really). Well, sort of; I guess in this case it is unfortunately needed to link the logical property, passed via constructor. So I guess this is a problem. There are some observed issues with linking creator properties to non-creator properties, related to resolution of creator properties, and the whole system needs to be rewritten. But due to complexity that will be done at earliest for 2.9. So your work-around is good to have for now.,

**Comment by wayerr** [comment]
I found same issue, debugging show that, `creatorProps` array (in `com.fasterxml.jackson.databind.deser.BeanDeserializerFactory#addBeanProps`) contains, very strange property:
`[creator property, name '@JsonUnwrapped'; inject id 'null']` but code try to find `[Property 'nested'; ctors: [parameter #0, ...`. So adding `@JsonProperty("nested")` force creator property name and therefore fix issue.

**Comment by wayerr** [comment]
But i see that it marked as bug and will raise error in future version at https://github.com/FasterXML/jackson-databind/commit/2e7f74f7f759a8d3e89f124e18d23134c60d4d08

right?

**Comment by cowtowncoder** [comment]
@wayerr Most likely yes. Ideally it should be supported, eventually, but probably not before 3.x. The current implementation of unwrapped properties can not be made to support this reliably.

**Comment by cowtowncoder** [comment]
I think there is another issue noting problems between `@JsonUnwrapped` and `@JsonCreator`, so closing this issue as duplicate (or now).
