### ISSUE TITLE
Exception while deserializing JSON into object

### ISSUE THREAD

**Issue by arunodavid** [FasterXML/jackson-databind#1314]
I'm trying to deserialize JSON String into object like {"name":"testname", "value":"testvalue"} into object as defined in the following. But since it has overloaded method it throws following exception

code:
-------
ObjectMapper objectMapper = new ObjectMapper(); 
objectMapper.readValue("{\"name\":\"testname\", \"value\":\"testvalue\"}", A.class);

Exception:
-----------
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addDeserializerConstructors(BasicDeserializerFactory.java:388)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:319)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:263)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:263)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:168)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:405)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:354)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:267)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:247)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:146)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:2990)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2884)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2034)

@JsonInclude(Include.NON_EMPTY)
class A {

@JsonProperty("name")
private String name;

@JsonProperty("value")
private String value;

@JsonProperty("car")
private Car car;

public A(@JsonProperty("name") String name,  @JsonProperty("value") String value){
   this.name = name;
this.value = value;
}

public A(@JsonProperty("name") String name,  @JsonProperty("value") String value,
@JsonProperty("car") Car car){
   this.name = name;
this.value = value;
}

//getters for all 3 members, annotated with @JsonIgnore

}

**Comment by cowtowncoder** [comment]
Which version?

**Comment by arunodavid** [comment]
Jackson-databind: 2.2.3

**Comment by cowtowncoder** [comment]
@arunodavid That version is 3 years old, not maintained for quite a while. Please try upgrade; most likely problem has been resolved since then.

**Comment by unhuman** [comment]
I found the problem is having more than one @JsonCreator constructor.
