### ISSUE TITLE
Deprecated findSerializationType might be breaking refineSerializationType (v2.8.1)

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1338]
(reported on `jackson-users` mailing list)

I get the following exception in a custom Serialization:

```
com.fasterxml.jackson.databind.JsonMappingException: Can not refine serialization key type [simple type, class java.util.Currency] into java.lang.String; types not related
        at com.fasterxml.jackson.databind.AnnotationIntrospector.refineSerializationType(AnnotationIntrospector.java:891)
        at com.fasterxml.jackson.databind.ser.PropertyBuilder.findSerializationType(PropertyBuilder.java:188)
        at com.fasterxml.jackson.databind.ser.PropertyBuilder.buildWriter(PropertyBuilder.java:75)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._constructWriter(BeanSerializerFactory.java:818)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:609)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanSerializer(BeanSerializerFactory.java:390)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanSerializer(BeanSerializerFactory.java:273)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:225)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:159)
        at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1272)
        at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1222)
        at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:499)
        at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:697)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:270)
        at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3672)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3030)
```

I've created a repo in https://github.com/JonyD/my-app with a failing test.
The pom.xml is a bit messy but it's important because of dependencies.

just do "mvn clean install" to run the failing test.
I hope this helps and hope you can find the bug.

Notice that with jackson version 2.4.6 the test passes, but with version 2.8.1 it does not.

**Comment by cowtowncoder** [comment]
Ok; the problem is not with Jackson I think, but in annotations used in model. Specifically:

```java
	@JsonSerialize(keyUsing=CurrencySerializerAsField.class, keyAs=String.class)
	public Map<Currency, BigDecimal> getRevenue() {
   		return revenue;
	}
```

which claims that for serialization, keys of type `Currency` should be cast into `String` for serialization.
This is impossible, you can not cast `Currency` into `String` as they are not related types (or more specifically `String` is not a sub-class of `Currency`).

In this case, `keyAs` should simply be removed as it serves no purpose. I assume 2.4.6 simply ignored that annotation.
