### ISSUE TITLE
NPE with JsonBackReference when deserialized when using Lombok

### ISSUE THREAD

**Issue by davinkevin** [FasterXML/jackson-databind#1342]
Hello, 

I've a problem while trying to upgrade from Jackson 2.6.x to Jackson 2.8.1. This upgrade is linked to a change of version of spring-boot. 

While everything was working in 2.6.x, The deserialization is totally broken for me in 2.7 and 2.8.1. When I try to deserialized an entity having a @JsonBackReference annotation, I have a NullPointerException. 

```
java.lang.NullPointerException
    at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.constructSettableProperty(BeanDeserializerFactory.java:733)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addReferenceProperties(BeanDeserializerFactory.java:643)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:230)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:141)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:406)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
    at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
    at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:442)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:196)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:26)
    at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:680)
    at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:444)
    at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.construct(PropertyBasedCreator.java:79)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:606)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:296)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
    at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
    at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:475)
    at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3890)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3785)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2833)
    at com.github.davinkevin.issueJackson.entity.PodcastTest.should_serialized(PodcastTest.java:24)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

I've extract the entity in a separate project to verify if the spring environment was a source of the problem, but this NPE also appear in a simple project.  

You can find the sample project here : https://github.com/davinkevin/issue-jackson-deserialize-2.7

The test which causes this problem is : 

```
    @Test
    public void should_serialized() throws IOException {
        /* Given */
        String podcastAsText = "{\"hasToBeDeleted\":true,\"cover\":{\"id\":null,\"url\":\"https://yt3.ggpht.com/-2eu-eG4PLa8/AAAAAAAAAAI/AAAAAAAAAAA/FZUzswUhAmI/s100-c-k-no-rj-c0xffffff/photo.jpg\",\"width\":200,\"height\":200},\"url\":\"https://www.youtube.com/channel/UC_yP2DpIgs5Y1uWC0T03Chw\",\"type\":\"Youtube\",\"title\":\"Joueur Du Grenier\",\"description\":\"Test de jeux à la con !\"}";

        /* When */
        Podcast podcast1 = objectMapper.readValue(podcastAsText, Podcast.class);

        /* Then */
        assertThat(podcast1).isNotNull();
    }
```

and you can find here the entity [Podcast](https://github.com/davinkevin/issue-jackson-deserialize-2.7/blob/master/src/main/java/com/github/davinkevin/issueJackson/entity/Podcast.java) and [Item](https://github.com/davinkevin/issue-jackson-deserialize-2.7/blob/master/src/main/java/com/github/davinkevin/issueJackson/entity/Item.java). 

I've searched for an issue linked to that, without success in StackOverflow and in the issue tracker.

Thanks for your help

**Comment by Serializator** [comment]
I found [a guide](http://www.baeldung.com/jackson-bidirectional-relationships-and-infinite-recursion) where they used the `@JsonBackReference` in the parent class (`Podcast`) and `@JsonManagedReference` in the child class (`Item`).

I tried both of the orders and using the `@JsonBackReference` in the parent class caused the field to stay `null` after deserialization and using `@JsonManagedReference` in the parent class (`@JsonBackReference` in the child class) threw the same exception as you posted above.

It would be lovely if someone could point out which order is the one that should be used.

**Comment by cowtowncoder** [comment]
@Serializator parent class should have `@JsonManagedReference`. Parent is the one that is reached first when traversing object graph. So the guide got it right.
You can look through unit tests to see other simple usage.

**Comment by Serializator** [comment]
@cowtowncoder Is there any chance that you might know a reason why a field annotated with `@JsonManagedReference` doesn't get deserialized and stays null and when `@JsonManagedReference` isn't used it does actually get properly deserialized?

_Sorry for not providing any information on how I use it, I'm currently not on my PC._

**Comment by cowtowncoder** [comment]
@Serializator nope

**Comment by cowtowncoder** [comment]
I can not reproduce this without having access to non-Lombok classes.
I would need a test case with explicit annotations, post-processed.

Lombok itself is, at this point, a royal total PITA for me since it seems to produce no end to problems.
So I suspect is it somehow involved here.

**Comment by davinkevin** [comment]
Yeah, it seems to be linked to creation of constructor with lombok. 

But, if you use annotation like this `@NoArgsConstructor @AllArgsConstructor(access = AccessLevel.PRIVATE)`, the code works with lombok and Jackson.

I don't know what is the difference between hand-writing code and generated code from lombok and Jackson in this case...

**Comment by cowtowncoder** [comment]
Ok, one other thing that may allow working around this issue: `JacksonAnnotationIntrospector` has method "setConstructorPropertiesImpliesCreator" (default to true), calling it with `false` may solve the issue as well. This method was added in 2.7.4 as (it's hoped) short-term work-around before figuring out how to proceed with it.

**Comment by cowtowncoder** [comment]
I think the underlying issue has to do with `@JsonBackReference`, Lombok, creator properties (via `@ConstructorProperties` being detected), and suppression of matching field. I added some minor error handling improvements which should make it easier to see where the problem occurs (NPE is about as useless a thing as one gets), but I hope this will also help reproduce the issue without Lombok, first, and see how to resolve it.

There is the whole question of handling of creator properties (and not just wrt Lombok... other issues)  but I think this particular problem is a secondary manifestation.

**Comment by cowtowncoder** [comment]
@davinkevin @Serializator It would be nice to see if 2.8.3 behavior works better, and gives more information on the issue. I don't have much to go on at this point otherwise.

2.9 will also add `MapperFeature.INFER_CREATOR_FROM_CONSTRUCTOR_PROPERTIES`, disabling of which prevents use of `@ConstuctorProperties`. This could help solving some of the issues as well.

**Comment by cowtowncoder** [comment]
Unfortunately I can not reproduce this right now. While I hope that latest version (2.8.6 as of now) works better -- and would appreciate confirmation or refutal -- I have to close for now. May be reopened or refiled with a reproducible use case, ideally without Lombok dependency; but if dep needed, then unit test and suggestion of dependency additions for test.

**Comment by acaliaro** [comment]
I have had the same problem.

My solution is:

remove 

@AllArgsConstructor
@NoArgsConstructor

and create them in code
