### ISSUE TITLE
Unexpected token (END_OBJECT), expected FIELD_NAME: missing property '@type' that is to contain type id

### ISSUE THREAD

**Issue by hhimanshu** [FasterXML/jackson-databind#1350]
I am trying to write code that uses `Jackson` to serialize/deserialize the objects to/from `File`.

The objects are Polymorphic in nature.  My interface looks like  

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY)
    @JsonSubTypes({
            @JsonSubTypes.Type(RemoteDataSource.class),
            @JsonSubTypes.Type(FileDataSource.class)
    })
    public interface DataSource {
    }

and the implementations as  

    public class FileDataSource implements DataSource {
        private String path;
        private String delimiter;
        private String fileNamePattern;
    
        @JsonCreator
        public FileDataSource(@JsonProperty("path") String path,
                              @JsonProperty("delimiter") String delimiter,
                              @JsonProperty("fileNamePattern") String fileNamePattern) {
            this.path = path;
            this.delimiter = delimiter;
            this.fileNamePattern = fileNamePattern;
        }
     ...
    }

and  

    public class RemoteDataSource implements DataSource {
        private String host;
        private int port;
        private String userName;
        private String password;
    
        @JsonCreator
        public RemoteDataSource(@JsonProperty("host") String host,
                                @JsonProperty("port") int port,
                                @JsonProperty("userName") String userName,
                                @JsonProperty("password") String password) {
            this.host = host;
            this.port = port;
            this.userName = userName;
            this.password = password;
        }
    
       ...
    }

and in `WorkflowConfig` use them  

    public class WorkflowConfig {
        private String name;
        private DataSource dataSource;
    
        @JsonCreator
        public WorkflowConfig(@JsonProperty("name") String name,
                              @JsonProperty("dataSource") DataSource dataSource) {
            this.name = name;
            this.dataSource = dataSource;
        }
      ...
    }

and then I write my test which looks like  

     @Test
        public void testSerializeAndSerializeFileDataSourceFromFile() throws Exception {
            File fileDataSource = temporaryFolder.newFile("fileDataSource.json");
    
            DataSource dataSource = new FileDataSource("/tmp/", ",", ".*");
            WorkflowConfig config = new WorkflowConfig("fileWorkflowConfig", dataSource);
    
            ObjectMapper mapper = new ObjectMapper();
            mapper.writeValue(fileDataSource, config);
    
            assertTrue(fileDataSource.length() > 0);
    
            DataSource readDataSource = mapper.readValue(fileDataSource, DataSource.class);
            assertNotNull(readDataSource);
        }

and it fails as  

    com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (END_OBJECT), expected FIELD_NAME: missing property '@type' that is to contain type id  (for class com.datasources.DataSource)
     at [Source: /var/folders/g3/wtbqfj7d5fsbkz1gm74kqy380000gn/T/junit5577276768876379004/fileDataSource.json; line: 1, column: 123]
    
    	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:261)
    	at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:1340)
    	at com.fasterxml.jackson.databind.DeserializationContext.reportWrongTokenException(DeserializationContext.java:1196)
    	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:157)
    	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:105)
    	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:142)
    	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:42)
    	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
    	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2731)
    	at com.workflow.WorkflowConfigTest.testSerializeAndSerializeFileDataSourceFromFile(WorkflowConfigTest.java:55)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
    	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
    	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
    	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

When serialized, the data on file looks like  

    {"name":"fileWorkflowConfig","dataSource":{"@type":"FileDataSource","path":"/tmp/","delimiter":",","fileNamePattern":".*"}}

I believe `Jackson` needs the `@type` information to construct the right object back.  

But from application perspective I do not need the information, so I used  

    @JsonIgnoreProperties(ignoreUnknown = true) 

However I am believe I am making mistake, what can I do now?

The complete codebase is on [GitHub][1]. you can see the failing test there

  [1]: https://github.com/101bits/jackson-serialize-polymorphic-objects

**Comment by cowtowncoder** [comment]
Use of `@JsonIgnoreProperties` should not cause the problem (if I understand question correctly); it only ignores properties it does not recognize. But it can often hide real mismatch problems, like misspelled properties (like say `type` vs `@type`).

If you wanted to allow missing of `@type`, you could specify default implementation to use in absence of that property, like:

    @JsonTypeInfo(....., defaultImpl=StdImpl.class)

in which case such instance would be created.

Finally, which version of Jackson are you using?

**Comment by hhimanshu** [comment]
These are my dependencies

```
<dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
            <version>2.8.1</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
```

**Comment by hhimanshu** [comment]
My tests were wrong, they were asserting wrong types. It is fixed now. The link to change is https://github.com/101bits/jackson-serialize-polymorphic-objects/commit/b7d8750679908ed897441d965e290e3471727c63?diff=split

Closing the issue

**Comment by cowtowncoder** [comment]
@hhimanshu Good! Thank you for verifying this.
