### ISSUE TITLE
Overlap between `@JsonTypeInfo.As.PROPERTY` indicated type id and field with same name results in `UnrecognizedPropertyException`

### ISSUE THREAD

**Issue by khogeland** [FasterXML/jackson-databind#1410]
(version 2.7.8)

The following code accidentally includes a duplicate "source" field as a result of `PROPERTY` instead of `EXISTING_PROPERTY` in the `@JsonTypeInfo` annotation. Deserialization results in a misleading `UnrecognizedPropertyException`.

EnvironmentEvent:

``` java
@JsonTypeInfo(use=JsonTypeInfo.Id.NAME, include=JsonTypeInfo.As.PROPERTY, property="source")
@JsonSubTypes({
        @JsonSubTypes.Type(value = ApiEvent.class, name = "API"),
        @JsonSubTypes.Type(value = BackendEvent.class, name = "BACKEND")
})
public abstract class EnvironmentEvent {
    private String environmentName;
    private LocalDateTime timeUtc;
    private String message;

    protected EnvironmentEvent() { } // for deserializer
    protected EnvironmentEvent(String env, LocalDateTime time, String msg) {
        environmentName = env;
        timeUtc = time;
        message = msg;
    }

    @Nonnull
    public String getEnvironmentName() { return environmentName; }

    @Nonnull
    public LocalDateTime getTimeUtc() { return timeUtc; }

    public abstract EnvironmentEventSource getSource();

    @Nonnull
    public String getMessage() { return message; }
}
```

BackendEvent:

``` java
public class BackendEvent extends EnvironmentEvent {
    private String status;

    private Object resultData;

    protected BackendEvent() {} // for deserializer

    public BackendEvent(String envName, LocalDateTime timeUtc, String message, String status, Object results)
    {
        super(envName, timeUtc, message);
        this.status = status;
        resultData = results;
    }

    public static BackendEvent create(String environmentName, String message, String status, Object results) {
        return new BackendEvent(environmentName,
                LocalDateTime.now(Clock.systemUTC()), message,
                status, results);
    }

    @Nonnull
    @Override
    public EnvironmentEventSource getSource() {
        return EnvironmentEventSource.BACKEND;
    }

    public String getStatus() {
        return status;
    }

    public Object getResultData() {
        return resultData;
    }

    @Override
    public String toString() {
        return String.format("(%s): %s", status, getMessage());
    }
}
```

Test case:

``` java
ObjectMapper mapper = ObjectMapperFactory.buildObjectMapper();
EnvironmentEvent event = new BackendEvent("foo", LocalDateTime.now(), "hello", "bar", null);
String ser = mapper.writeValueAsString(event);
mapper.readValue(ser, EnvironmentEvent.class);
```

```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "source" (class xxxxx.event.BackendEvent), not marked as ignorable (5 known properties: "status", "environmentName", "timeUtc", "message", "resultData"])
    at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
    at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:851)
    at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1085)
...
```

**Comment by cowtowncoder** [comment]
Yes, I can reproduce this. The thing that might work here would be to indicate that property `source` is ignorable property, at deserializer level, since polymorphic handler will be separate and work before content serialization, and before deserialization, so it wouldn't be affected.
I'll have to see how `EXISTING_PROPERTY` manages to handle this; perhaps it simply omits type-id handler on serialization.

**Comment by cowtowncoder** [comment]
Ok. Well... so, `AsExistingPropertyTypeSerializer` actually blocks writing, always. So mechanism would not work for regular `PROPERTY` handling, where ignoral should occur at value serializer.

**Comment by cowtowncoder** [comment]
Looks like this passed on 3.0... odd.

**Comment by cowtowncoder** [comment]
Ah. Only because of change to `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` defaults: once enabled, fails as it used to.

**Comment by cowtowncoder** [comment]
Ok back at this again: I think the proper thing to do is to fail with exception if there is conflict between regular property and type id -- on serialization: definition should instead use `EXISTING_PROPERTY` in such case.

Will see if I can get Claude to figure this out :)

**Comment by cowtowncoder** [comment]
Ok, close enough; got PR (#5757) that works; not as minimal as I hoped but will do: goes in 3.2.0.
