### ISSUE TITLE
Unable to deserialize collection of concrete subclass when using defaultImpl

### ISSUE THREAD

**Issue by michaelaberman** [FasterXML/jackson-databind#1488]
This worked in the last 2.7, but is broken in both 2.8.0 and 2.8.5.

I have a field parameterized with a concrete subclass of a base class annotated with `@JsonTypeInfo`, and I am trying to deserialize a collection that contains only that specific class. In 2.8.x, the `readValue` method fails with `com.fasterxml.jackson.databind.JsonMappingException: Class JacksonSubclassCollectionTest$SomeBaseClass not subtype of [simple type, class JacksonSubclassCollectionTest$SomeSubClass]`. This doesn't appear to happen without `defaultImpl` (but I have legacy data with no `type` field that I need to be able to keep deserializing in other contexts). Full stack trace follows example.

```
public class JacksonSubclassCollectionTest {
  public static void main(String[] args) throws Exception {
    ObjectMapper mapper = new ObjectMapper();

    SomeContainer container = mapper.readValue("{\"collection\":[{\"type\":\"SUBCLASS\",\"field\":7}]}", SomeContainer.class);

    System.out.println(container.collection.get(0).field);
  }

  @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", defaultImpl = SomeBaseClass.class, visible = true)
  @JsonSubTypes({@JsonSubTypes.Type(name = "SUBCLASS", value = SomeSubClass.class)})
  public static class SomeBaseClass {
    @JsonTypeId
    public String type;
  }

  public static class SomeSubClass extends SomeBaseClass {
    public int field;
  }

  public static class SomeContainer {
    public ArrayList<SomeSubClass> collection;
  }
}
```

```
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Class JacksonSubclassCollectionTest$SomeBaseClass not subtype of [simple type, class JacksonSubclassCollectionTest$SomeSubClass]
 at [Source: {"collection":[{"type":"SUBCLASS","field":7}]}; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:296)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:269)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:475)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3890)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3785)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2833)
	at JacksonSubclassCollectionTest.main(JacksonSubclassCollectionTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.IllegalArgumentException: Class JacksonSubclassCollectionTest$SomeBaseClass not subtype of [simple type, class JacksonSubclassCollectionTest$SomeSubClass]
	at com.fasterxml.jackson.databind.type.TypeFactory.constructSpecializedType(TypeFactory.java:359)
	at com.fasterxml.jackson.databind.jsontype.impl.StdTypeResolverBuilder.buildTypeDeserializer(StdTypeResolverBuilder.java:118)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findTypeDeserializer(BasicDeserializerFactory.java:1363)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findPropertyContentTypeDeserializer(BasicDeserializerFactory.java:1526)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.resolveMemberAndTypeAnnotations(BasicDeserializerFactory.java:1841)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.constructSettableProperty(BeanDeserializerFactory.java:735)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:226)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:141)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:406)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	... 12 more
```

**Comment by cowtowncoder** [comment]
Unfortunately this is probably same as #1339 and is not as much a bug than eager validation feature.
As per #1339 I hope to (eventually...) improve things so that validation of type compatibility is deferred, but the issue here is that usage is problematic: although you are asking for `SomeContainer`, base type for polymorphic handling is really `SomeBaseClass`, and if `type` is missing, that's what you would get.
Since that would result in a cast exception, code throws an exception.

Earlier versions (2.7 and prior) did not do such validation, which allowed code to work (at least until one entry was missing `type`).
With 2.8 compatibility check is made, related to other type handling changes (related to type resolution improvements in 2.7). Intent was to more gracefully handle assignment incompatibilities.

On short term I would suggest that you change your code to bind using `SomeBaseClass` as target class, and just doing explicit cast. It's bit ugly, but will work the same on both 2.7 and 2.8.
Longer term I hope to improve handling here, but that may take time and is not guaranteed to get in 2.8 branch.

Thank you for reporting the problem; I hope my explanation helps.

**Comment by dialtahi** [comment]
Is still broken in jackson 2.8.10

**Comment by cowtowncoder** [comment]
@dialtahi Of course. If it was fixed there would be update here.

**Comment by blop** [comment]
Guys, this is a BIG regression for people upgrading from 2.7.

If you have some class with a List<> and another with a Set<>, using a SimpleAbstractTypeResolver that provides the defaultImpl as ArrayList and HashSet, it just does NOT work anymore.

**Comment by cowtowncoder** [comment]
@blop what you describing sounds different from the original report, so I would suggest filing a separate issue with reproduction. The issue as described here is very unlikely to be addressed until 3.x, but if what you experience is different there might be possibility of a fix.

**Comment by KroligG** [comment]
Look like this is fixed by https://github.com/FasterXML/jackson-databind/issues/1565. At least updating to 2.9.6 fixed same issue for me.
