### ISSUE TITLE
NPE in deserialization with parameter names module

### ISSUE THREAD

**Issue by khogeland** [FasterXML/jackson-databind#1503]
Minimal repro:

```java
public class Broken {
    public InnerClass innerClass;

    class InnerClass {
        public Generic<?> generic;
        public InnerClass(@JsonProperty("generic") Generic<?> generic) {}
    }

    static class Generic<T> {
        public int ignored;
    }

}
```

```java
        ObjectMapper mapper = new ObjectMapper();
        String ser = mapper.writeValueAsString(new Broken());
        mapper.readValue(ser, Broken.class);
```

Produces:
```
java.lang.NullPointerException
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.resolveType(BasicDeserializerFactory.java:1866)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.constructCreatorProperty(BasicDeserializerFactory.java:848)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._checkImplicitlyNamedConstructors(BasicDeserializerFactory.java:558)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addDeserializerConstructors(BasicDeserializerFactory.java:525)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:321)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:252)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:221)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:143)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:406)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:444)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:948)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:446)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:296)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3908)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3803)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2797)
```

Does not occur when inner class is static, or with objects that don't have type parameters.

**Comment by cowtowncoder** [comment]
Also reproducible, and comes down to the nasty discrepancy between JDK reporting one more parameter for constructors of non-static inner classes (including infamous hidden `self` reference), BUT NOT reporting it when accessing actual parameter types!
The significance of generic type is probably just that that triggers type resolution.

**Comment by cowtowncoder** [comment]
Will also fix, for now, by preventing use of constructors of non-static inner classes: since they can not really even be supported via Creator functionality (as they absolutely require "parent" this pointer, access to which is only available via `InnerClassProperty`) there isn't much use.
Doing this will prevent this misleading exception as well.
