### ISSUE TITLE
Deserialization broken after upgraded from 2.5.0 to 2.6.0 of jackson-databind

### ISSUE THREAD

**Issue by ravirajamiyer** [FasterXML/jackson-databind#1541]
Hello, 

We recently had to upgrade from jackson-databind 2.5.0 to 2.6.0. Unfortunately it broke a REST API built on the Spring MVC. We tracked down the reason to be problem in deserialization of a JSON data after out Jackson upgrade. The same REST end-point was working perfectly. What could have been different. Please excuse me for obfuscating the package names for security reasons.

Here is the error message, and the class code snippets

Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (END_OBJECT), expected FIELD_NAME: missing property '@class' that is to contain type id  (for class java.lang.Object)
 at [Source: [B@65e7aa15; line: 6, column: 64] (through reference chain: com.xxx.xxx.xxx.PolymorphicValueWrapper["value"]->com.xxx.xxx.xxx.RemoteRequest["map"]->java.util.LinkedHashMap["payload"])

Here is the snippet of class definitions used:

@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public  class PolymorphicValueWrapper {
    @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
    private Object value;
    public Object getValue() {
        return value;
    }
    public void setValue(Object value) {
        this.value = value;
    }
//.........
}

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class RemoteRequest extends ARemoteObject {

// .....
}

@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class ARemoteObject implements Serializable {	
	 @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS,  include = JsonTypeInfo.As.PROPERTY,  property = "@class")
	private Map<String, Object> map = new HashMap<String, Object>();

	public Map<String, Object> getMap() {
		return map;
	}

	public void setMap(Map<String, Object> map) {
		this.map = map;
	}
//...

}

**Comment by cowtowncoder** [comment]
Unfortunately I can't really help without actual full test case.

**Comment by ravirajamiyer** [comment]
I tried to use versions later that 2.6.0 including 2.6.6 and 2.7.0. The same problem exists. Here is the JUnit case that works fine with the JSON data provided with 2.5.0. I have provided the failure stack trace below when we switch to 2.6.0:

**JUnit Test Class**

`package com.test;

import static org.junit.Assert.assertTrue;
import java.io.File;
import java.io.InputStream;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.apache.commons.io.FileUtils;
import org.junit.Test;
import com.test.RemoteRequest;
import com.fasterxml.jackson.databind.ObjectMapper;

public class PolymorphicSerializationTest {
	
	@Test
	public void testSerialization() throws Exception {
        InputStream fileIn = this.getClass().getResourceAsStream("/data.json");

        ObjectMapper mapper = new ObjectMapper();
        PolymorphicValueWrapper zoo = mapper.readValue(fileIn, PolymorphicValueWrapper.class);
        assertTrue(zoo != null);
        assertTrue(zoo.getValue() instanceof RemoteRequest);
        RemoteRequest rr = (RemoteRequest) zoo.getValue();
        Map<String, Object> maps = rr.getMap();
        Set keys = maps.keySet();
        assertTrue(keys.contains("@class"));
        assertTrue(keys.contains("command"));
        assertTrue(keys.contains("payload"));
        assertTrue(keys.contains("sub_command"));
        
        Object listData = maps.get("command");
        assertTrue(listData instanceof List);
        Object payload = maps.get("payload");
        assertTrue(payload instanceof Map);
        Map payloadMap = (Map) payload;
        assertTrue("used for this request".equals(payloadMap.get("not").toString()));
	}
}
`

**Dependent Classes**

`
package com.test;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class AnObject {
	
	 @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS,
             include = JsonTypeInfo.As.PROPERTY,
             property = "@class")
	private Map<String, Object> map = new HashMap<String, Object>();

		public Map<String, Object> getMap() {
			return map;
		}

		public void setMap(Map<String, Object> map) {
			this.map = map;
		}
}

package com.test;

public enum ERemoteCommand {
	
	TASK_A(true),
	TASK_B(true);
	
	boolean taskCheck;
	
    ERemoteCommand(boolean taskCheck) {
        this.taskCheck = taskCheck;
    }
}

package com.test;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public  class PolymorphicValueWrapper {
    @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS,
            include = JsonTypeInfo.As.PROPERTY,
            property = "@class")
    

	private Object value;

    public Object getValue() {
        return value;
    }

    public void setValue(Object value) {
        this.value = value;
    }

	@Override
	public String toString() {
		return "PolymorphicValueWrapper [value=" + value + "]";
	}
}

package com.test;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class RemoteRequest extends AnObject {

}
`
**The JSON request in the "data.json" file**


`
{"value": {"@class": "com.test.RemoteRequest",
             "command": "TASK_A",
             "map": {"@class": "com.test.RemoteRequest",
                     "command": ["com.test.ERemoteCommand",
                                 "TASK_A"],
                     "payload": {"not": "used for this request"},
                     "sub_command": "CHECK_CONN"}}}`

Error Message while running the JUnit test with jackson-databind 2.6.0

com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (END_OBJECT), expected FIELD_NAME: missing property '@class' that is to contain type id  (for class java.lang.Object)
 at [Source: java.io.BufferedInputStream@685e95ae; line: 6, column: 64] (through reference chain: com.test.PolymorphicValueWrapper["value"]->com.test.RemoteRequest["map"]->java.util.LinkedHashMap["payload"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:946)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:149)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:101)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:165)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:554)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:497)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:341)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:122)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:93)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:165)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:554)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:518)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2796)
	at com.test.PolymorphicSerializationTest.testSerialization(PolymorphicSerializationTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by cowtowncoder** [comment]
@ravirajamiyer  Ok, I think I can reproduce the issue. Thank you for providing the test case!

**Comment by cowtowncoder** [comment]
Looking at the test, I do not think use case itself is valid. What Jackson guarantees is that kind of output it produces it will be able to read back; but I do not see that given JSON is something Jackson would produce -- contents of `map` property do not match with `Map` (allegedly it should be `com.test.RemoteRequest` which is not a `Map`).
So as far as I can see, given JSON contents are malformed with respect to polymorphic type handling.

There is still something odd going on regarding handling, as the error message given is wrong, so I will look into this bit more, but I don't think usage indicated can be supported. I don't know why I did not fail obviously with 2.5; I am guessing this happened to accidentally work in the way that produced results you saw. But that is not what should work given class definitions and JSON input.

**Comment by ravirajamiyer** [comment]
Thank you for taking a look at this. I do agree that this is a quirky use case. This is a legacy code that I inherited, and altering the use case has far reaching impact.

**Comment by cowtowncoder** [comment]
@ravirajamiyer Yes legacy code is difficult thing.

One thing that could still help is if to have the serialization code available as part of the test. As I said, the goal of polymorphic handling is to support round-trip handling (read what you write). It is still possible there is something else wrong with whatever produces JSON that test uses.
Unfortunately that input can not be made to work, and I think I now fully understand how things go, and I may be able to improve exception reporting. But handling itself can not be made to work: polymorphic values of the `Map` must either be JSON Objects with `@class` property, or simple scalar value for `String`, `Integer`, `Boolean`.
It is quite possible that use of `@JsonTypeInfo` for the map is misplaced so just removing that might work as expected.
