### ISSUE TITLE
Use of @JsonUnwrapped causes a failure in 2.9.0.pr1 when MapperFeature.DEFAULT_VIEW_INCLUDE is disabled

### ISSUE THREAD

**Issue by wilkinsona** [FasterXML/jackson-databind#1559]
The following tests illustrate the problem:

```java
package com.example;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.Test;

public class JsonUnwrappedAndViewInclusionTests {

    @Test
    public void healthCanBeSerialized() {
        new ObjectMapper().canSerialize(Health.class);
    }

    @Test
    public void healthCanBeDeserializedWithDefaultViewInclusionDisabled() {
        new ObjectMapper().configure(MapperFeature.DEFAULT_VIEW_INCLUSION, false)
                .canSerialize(Health.class);
    }

    @JsonInclude(Include.NON_EMPTY)
    public static final class Health {

        private final Status status;

        public Health(Status status) {
            this.status = status;
        }

        @JsonUnwrapped
        public Status getStatus() {
            return this.status;
        }

    }

    public static final class Status {

        private final String code;

        public Status(String code) {
            this.code = code;
        }

        public String getCode() {
            return this.code;
        }

    }

}
```

`healthCanBeSerialized` passes but `healthCanBeDeserializedWithDefaultViewInclusionDisabled` fails with the following exception:

```
java.lang.IllegalStateException: Can not override serializer
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.assignSerializer(BeanPropertyWriter.java:393)
	at com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter.assignSerializer(UnwrappingBeanPropertyWriter.java:137)
	at com.fasterxml.jackson.databind.ser.impl.FilteredBeanPropertyWriter$MultiView.assignSerializer(FilteredBeanPropertyWriter.java:121)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.resolve(BeanSerializerBase.java:361)
	at com.fasterxml.jackson.databind.ser.SerializerCache.addAndResolveNonTypedSerializer(SerializerCache.java:197)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1336)
	at com.fasterxml.jackson.databind.SerializerProvider._findExplicitUntypedSerializer(SerializerProvider.java:1294)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.hasSerializerFor(DefaultSerializerProvider.java:260)
	at com.fasterxml.jackson.databind.ObjectMapper.canSerialize(ObjectMapper.java:2730)
	at com.example.JsonUnwrappedAndViewInclusionTests.healthCanBeDeserializedWithDefaultViewInclusionDisabled(JsonUnwrappedAndViewInclusionTests.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

Both tests pass with Jackson 2.8.x. Both tests also pass with Jackson 2.9.0.pr1 if `@JsonUnwrapped` is removed from `Health.getStatus()`.

**Comment by cowtowncoder** [comment]
Thank you for reporting this! Will figure out what gives.

**Comment by cowtowncoder** [comment]
Interesting... quite fragile for testing, as `final` keyword is actually required (probably to force static typing, early resolution of serializer or something).

**Comment by wilkinsona** [comment]
That is interesting. I can confirm that the problem in Spring Boot can be worked around by removing the `final` keyword.

**Comment by cowtowncoder** [comment]
Still not 100% sure why this did not fail earlier. The way in which assignment is made via delegation etc is still somewhat hairy, but at least this particular combination won't trigger issue again. If similar issue resurfaces may need to consider removing sanity check. But not yet.
Please let me know if there are related remaining issues.
