### ISSUE TITLE
Invalid serializer assignment if default view inclusion disabled and custom filtered properties

### ISSUE THREAD

**Issue by odrotbohm** [FasterXML/jackson-databind#1664]
Assume we have a class like this:

```java
class Foo {
  String id;
  String test;
  MyEnum foo;

  static enum MyEnum { FIRST, SECOND; }
}
```

Assume we have a `BeanSerializerModifier` that removes the `id` property and the ObjectMapper to have `DEFAULT_VIEW_INCLUSION` disabled. The latter causes the default views being an empty array instead of `null` which then causes all properties to end up in `_filteredProps`. I.e. we end up with `_filteredProps` containing `id`, `test`, `foo` and `_props` containing `test` and `foo`. In lines 357, the code then looks up the writer from the filtered props and assigns the serializer from the current property. This means in this case that the `EnumSerializer` determined for `foo` is assigned to the property test, which then fails on serialization. Here's a test to reproduce the issue:

```java
/**
 * @author Oliver Gierke
 */
public class Sample {

	public static void main(String[] args) throws Exception {

		SimpleModule module = new SimpleModule();
		module.setSerializerModifier(new IdRemovingBeanSerializerModifier());

		ObjectMapper mapper = new ObjectMapper();
		mapper.disable(MapperFeature.DEFAULT_VIEW_INCLUSION);
		mapper.registerModule(module);

		Entity entity = new Entity();
		entity.id = "id";
		entity.test = "test";
		entity.foo = Foo.FIRST;

		System.out.println(mapper.writeValueAsString(entity));
	}

	public static class Entity {

		public String id;
		public String test;
		public Foo foo;
	}

	static enum Foo {
		FIRST, SECOND;
	}

	static class IdRemovingBeanSerializerModifier extends BeanSerializerModifier {

		/* 
		 * (non-Javadoc)
		 * @see com.fasterxml.jackson.databind.ser.BeanSerializerModifier#updateBuilder(com.fasterxml.jackson.databind.SerializationConfig, com.fasterxml.jackson.databind.BeanDescription, com.fasterxml.jackson.databind.ser.BeanSerializerBuilder)
		 */
		@Override
		public BeanSerializerBuilder updateBuilder(SerializationConfig config, BeanDescription beanDesc,
				BeanSerializerBuilder builder) {

			builder.setProperties(builder.getProperties().stream()//
					.filter(it -> isId(it))//
					.collect(Collectors.toList()));

			return builder;
		}

		private static boolean isId(BeanPropertyWriter writer) {
			return !writer.getMember().getName().equals("id");
		}
	}
}
```

Stack trace:

```
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: java.lang.String cannot be cast to java.lang.Enum (through reference chain: com.example.Sample$Entity["test"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:724)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:481)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:320)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3881)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3195)
	at com.example.Sample.main(Sample.java:48)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Enum
	at com.fasterxml.jackson.databind.ser.std.EnumSerializer.serialize(EnumSerializer.java:27)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:716)
	... 6 more
```

**Comment by cowtowncoder** [comment]
I assume this is reproduction for 2.8.9 and 2.9.0.pr3?

One minor note: we are still Java 7 only, so tests can't use streams or lambdas. But that's easy enough to change.

As to problem itself: I'll have to see, but the intent really is that properties would be removed or added in `changeProperties()` (called earlier). But if implementation knows what it is doing and wants to change `properties`, it will also need to modify "filtered properties": builder can not really synchronize those two without callers help -- and those are required to match, index-wise.

**Comment by olivergierke** [comment]
The test fails against 2.9, works on 2.8.9. We currently overwrite `updateBuilder(…)` as it seems to grant the most flexibility. `BeanSerializerBuilder` exposes a `setProperties(…)` which leaves me with the impression, I can define which properties are supposed to be considered at all.

The change in behavior leaves Spring Data REST in its upcoming version broken, as Spring Framework upgrades to Jackson 2.9, and in fact we'd like to, too. But it looks like trying to exclude a property from being rendered at all inevitably breaks serializer assignment now.

I also think it's weird to — in case of the two lists having different lengths — blindly assign serializers based on position in the list as — in case of different length — it's more likely that you'll try to assign a serializer to an incompatible property than not, isn't it?

**Comment by olivergierke** [comment]
Good news! I moved our filtering implementation to `changeProperties(…)` and that seams to make the sample provided above work. I'll have to see whether that works on 2.8, but it looks like a decent option to move to for our upcoming GA releases.

**Comment by cowtowncoder** [comment]
@olivergierke Ok good! Sorry for the trouble: problem is that the way that regular, filtered properties are coupled is non-obvious from API perspective; but unfortunately essential from implementation perspective. If linkage was handled differently (like chaining regular, filtered), problem wouldn't exist but it's probably not possible to easily change that.

So if refactoring works that is good. :)

**Comment by cowtowncoder** [comment]
No plans to implement; closing as part of bigger issue clean up.
