### ISSUE TITLE
While we use ObjectMapper with Jackson2HalModule registered and tries to deserialize "Resources<>" , it throws NPE

### ISSUE THREAD

**Issue by GhodasaraChetan** [FasterXML/jackson-databind#1721]
When I try to deserialize `Resources<>` type using `Jackson2HalModule` registered `ObjectMapper`, as shown below, it throws NPE. 

(code snippet)
```
@Test
public void objectMapper_canDeserialize_test() throws IOException {
	ObjectMapper objectMapper = new ObjectMapper();
	objectMapper.registerModule(new Jackson2HalModule());
	JavaType javaType = objectMapper.getTypeFactory().constructType(Resources.class);
	assertTrue(objectMapper.canDeserialize(javaType, null));
}
```
(below is stack trace snippet)
```
java.lang.NullPointerException
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.<init>(StdDeserializer.java:66)
	at com.fasterxml.jackson.databind.deser.std.ContainerDeserializerBase.<init>(ContainerDeserializerBase.java:52)
	at com.fasterxml.jackson.databind.deser.std.ContainerDeserializerBase.<init>(ContainerDeserializerBase.java:60)
	at org.springframework.hateoas.hal.Jackson2HalModule$HalResourcesDeserializer.<init>(Jackson2HalModule.java:618)
	at org.springframework.hateoas.hal.Jackson2HalModule$HalResourcesDeserializer.<init>(Jackson2HalModule.java:613)
	at org.springframework.hateoas.hal.Jackson2HalModule$HalResourcesDeserializer.createContextual(Jackson2HalModule.java:678)
	at com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(DeserializationContext.java:651)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.constructSettableProperty(BeanDeserializerFactory.java:835)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:551)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:256)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:166)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.hasValueDeserializerFor(DeserializerCache.java:191)
	at com.fasterxml.jackson.databind.DeserializationContext.hasValueDeserializerFor(DeserializationContext.java:422)
	at com.fasterxml.jackson.databind.ObjectMapper.canDeserialize(ObjectMapper.java:2863)
```

**Versions Used:** `Jackson-databind-2.9.0.pr4`, `Spring-hateoas-0.23.0.RELEASE`

Actually, I tried to access Spring-Data-Rest API using `ObjectMapper`, `MappingJackson2HttpMessageConverter` and `Resources`. But it throws `no suitable HttpMessageConverter found for response type Resources<Resource<Person>>` error. 
Which directed me to search more on ObjectMapper deserialization.
I have created a demo for duplication of the same at [this GitHub repository](https://github.com/GhodasaraChetan/persontest).

**Note:** It seems working properly with `Jackson-databind-2.8.9`
After digging some more, I feel that the error is due to [this change](https://github.com/FasterXML/jackson-databind/commit/8dd4f8eb48ce757baf4502bc9be763792a5877ee#diff-6dd8e5902055b994d995105a1db20748L51)
` _valueClass = (valueType == null) ? null : valueType.getRawClass();`  
 -->   `_valueClass = valueType.getRawClass();`

Is this behavior as expected? 
OR 
Can you please help me to have any better alternative?

**Comment by cowtowncoder** [comment]
@GhodasaraChetan Could you please file an issue for `jackson-databind` with this information? It sounds like something that should probably be improved, either by accepting `null`, or, if that is invalid (I'll have to look), provide better exception message.
If there was an easy way to reproduce it without external libs, that'd be great too. Or, at least snippet from the custom deserializer constructor to ensure I understand usage.

In the meantime I think custom deserializer should pass proper type; if nothing else available, `java.lang.Object`.

**Comment by GhodasaraChetan** [comment]
Thank you @cowtowncoder  for your quick reply.
I have tried to create [this sample project](https://github.com/GhodasaraChetan/jacksonTest) without external libs.
The usage is shown at [this location](https://github.com/GhodasaraChetan/jacksonTest/blob/master/src/main/java/Main.java#L43) which I am trying to access.

Actual usage with Spring-Data-Rest was shown at the previously mentioned repository in the issue. ([link](https://github.com/GhodasaraChetan/persontest/blob/master/src/test/java/com/example/persontest/repositories/PersonRepositoryTest.java#L57))

Please let me know if any more information is required.

**Comment by shakuzen** [comment]
I believe this issue can be closed as the underlying cause was fixed in Spring HATEOAS https://github.com/spring-projects/spring-hateoas/commit/6bed9bec403f2ca45f4fd319c6ee3d79738f36f7. The `Jackson2HalModule` was passing `null` to the deserializer constructor.
