### ISSUE TITLE
Deserialization date format error with @ConstructorProperties, @JsonFormat, and @JsonIgnore

### ISSUE THREAD

**Issue by jayanderson** [FasterXML/jackson-databind#1722]
Creating new issue from here: https://github.com/FasterXML/jackson-databind/issues/1239#issuecomment-319803549

This issue is present in 2.8.8 and 2.9.0.

Minimal example showing the issue. If either (1) or (2) are commented out then it deserializes correctly. Serialization seems to work correctly.

```java
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.common.base.Objects;

import java.beans.ConstructorProperties;
import java.util.Date;

public class TestJsonDateFormatError {
    public static void main(String[] args) throws Exception {
        TestJsonFormatDate original = new TestJsonFormatDate();
        original.setDate(new Date(0));

        ObjectMapper objectMapper = new ObjectMapper();
        final String json = objectMapper.writeValueAsString(original);
        TestJsonFormatDate after = objectMapper.readValue(json, TestJsonFormatDate.class);

        if (after.equals(original)) {
            System.out.println("Success");
        }
    }

    public static class TestJsonFormatDate {
        @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss.SSS")
        private Date date;

        // (1) Comment out @JsonIgnore on other properties and it deserializes correctly
        @JsonIgnore
        private String foo;

        public TestJsonFormatDate() {
        }

        // (2) Comment out constructor properties and it deserializes correctly
        @ConstructorProperties({"date", "foo"})
        public TestJsonFormatDate(Date date, String foo) {
            this.date = date;
            this.foo = foo;
        }

        public Date getDate() {
            return this.date;
        }

        public void setDate(Date date) {
            this.date = date;
        }

        public String getFoo() {
            return this.foo;
        }

        public void setFoo(String foo) {
            this.foo = foo;
        }

        public boolean equals(Object o) {
            if (!(o instanceof TestJsonFormatDate)) {
                return false;
            }

            TestJsonFormatDate other = (TestJsonFormatDate) o;
            return Objects.equal(this.date, other.date)
                    && Objects.equal(this.foo, other.foo);
        }
    }
}
```

Resulting error:

```
Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.util.Date` from String "1970-01-01 00:00:00.000": not a valid representation (error: Failed to parse Date value '1970-01-01 00:00:00.000': Cannot parse date "1970-01-01 00:00:00.000": while it seems to fit format 'yyyy-MM-dd'T'HH:mm:ss.SSSZ', parsing fails (leniency? null))
 at [Source: (String)"{"date":"1970-01-01 00:00:00.000"}"; line: 1, column: 9] (through reference chain: TestJsonDateFormatError$TestJsonFormatDate["date"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1535)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:910)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseDate(StdDeserializer.java:523)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseDate(StdDeserializer.java:466)
	at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateBasedDeserializer._parseDate(DateDeserializers.java:195)
	at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:285)
	at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:268)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
	at TestJsonDateFormatError.main(TestJsonDateFormatError.java:16)
```

**Comment by cowtowncoder** [comment]
Thank you for reporting this.

**Comment by cowtowncoder** [comment]
Unable to reproduce with `2.9` code (for `2.9.2`) release. Not 100% sure if there's a fix included, or if my inclusion of test code has some subtle difference, but at this point can not reproduce.
