### ISSUE TITLE
ConcurrentModificationException while using  with object mapper

### ISSUE THREAD

**Issue by glragesh** [FasterXML/jackson-databind#1726]
Hi Team,

I was getting below exception while executing below code. Culd you please share your insights on this issue? 

Code:

```java
mapper.writeValueAsString(Collections.synchronizedMap(requestParams));
//where requestParams is a map - Map<String, Object>
```

Exception:

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: [no message for java.util.ConcurrentModificationException]
  at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:303)
  at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3681)
  at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3057)
  at com.itians.gp.api.tierb.item.command.ApiCommand.buildPostRequestEntity(ApiCommand.java:33)
  at com.itians.gp.api.tierb.item.command.ProductCommand.run(ProductCommand.java:36)
  at com.itians.gp.api.tierb.item.command.ProductCommand.run(ProductCommand.java:21)
  at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:301)
  at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:297)
  at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
  ... 28 common frames omitted
Caused by: java.util.ConcurrentModificationException: null
  at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1211)
  at java.util.TreeMap$EntryIterator.next(TreeMap.java:1247)
  at java.util.TreeMap$EntryIterator.next(TreeMap.java:1242)
  at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:600)
  at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:536)
  at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:30)
  at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292)
  ... 36 common frames omitted
```

**Comment by cowtowncoder** [comment]
First things first: which Jackson version are you using?

**Comment by cowtowncoder** [comment]
Exception surely looks like someone else was modifying the value being serialized (and Jackson just tries to iterate over contents).

Can not reproduce at this point.
