### ISSUE TITLE
Get NPE on deserializing values with recursive `@JsonIgnoreProperties`

### ISSUE THREAD

**Issue by Romain-P** [FasterXML/jackson-databind#1755]
I'm using spring-mvc for a `restful` service. By adding the dependency, my rest controllers automatically `generate json` from my `response entities`.

**Dependency**

    jackson = '2.9.0'
    compile "com.fasterxml.jackson.core:jackson-databind:$jackson"

**Objects**

    @Getter @Setter
    public final class UserDTO {
        [...]
    
        private Set<ActivityDTO> activities = Sets.newHashSet();
    }

    @Getter @Setter
    public final class ActivityDTO {
        [...]
    
        private Set<ActivityDTO> subActivities;
    }

**Problem**

Problems come in `special cases`. For example, I want to add an `activity` to an `user`. The following user-json `works` good, `Jackson converts it without error.`

    {
    "id": 1,
      "activities": [
        {
          "id": 1,
          "subActivities": null,
        }
      ]
    }

But if I add an activity with sub activities, it crashes!

    {
      "id": 6,
      "activities": [
        {
          "id": 19,
          "subActivities": [
            {
              "id": 20,
              "subActivities": [
                {
                  "id": 24,
                  "subActivities": null
                },
                {
                  "id": 21,
                  "subActivities": [
                    {
                      "id": 23,
                      "subActivities": null
                    },
                    {
                      "id": 22,
                      "subActivities": null
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }

Indeed, jackson `can't deserialize` this json and I don't understand why. I get the following error.. Any idea?

    13:45:56.890 [http-nio-8080-exec-1] DEBUG org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod - Failed to resolve argument 0 of type 'com.ortec.gta.database.model.dto.UserDTO'
    org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: (was java.lang.NullPointerException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.ortec.gta.database.model.dto.UserDTO["activities"]->java.util.HashSet[2]->com.ortec.gta.database.model.dto.ActivityDTO["subActivities"]->java.util.HashSet[0]->com.ortec.gta.database.model.dto.ActivityDTO["subActivities"])
    	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:238)
    	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:223)
    	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:201)
    	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:150)
    	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:128)
    	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
    	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:158)
    	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:128)
    	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
    	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
    	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
    	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
    	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
    	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
    	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
    	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:883)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:664)
    	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
    	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:176)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:57)
    	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
    	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
    	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
    	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    	at com.ortec.gta.configuration.ServletInitializer$CorsFilter.doFilter(ServletInitializer.java:78)
    	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
    	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
    	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
    	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
    	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
    	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
    	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
    	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
    	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
    	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
    	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
    	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
    	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.ortec.gta.database.model.dto.UserDTO["activities"]->java.util.HashSet[2]->com.ortec.gta.database.model.dto.ActivityDTO["subActivities"]->java.util.HashSet[0]->com.ortec.gta.database.model.dto.ActivityDTO["subActivities"])
    	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
    	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
    	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1689)
    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:370)
    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
    	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:285)
    	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
    	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
    	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:368)
    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
    	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:285)
    	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
    	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
    	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:368)
    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
    	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
    	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3072)
    	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:235)
    	... 77 common frames omitted
    Caused by: java.lang.NullPointerException: null
    	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:271)
    	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
    	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
    	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:368)
    	... 93 common frames omitted

**Comment by Romain-P** [comment]
I had to rollback to 2.7.9. It seems this bug appeared since 2.8.0,
More details: https://stackoverflow.com/questions/45918309/jackson-get-a-null-reference-on-deserializing

**Comment by cowtowncoder** [comment]
I would need a full reproduction here: member in question is the value deserializer, which should not be null. But perhaps there is a custom deserializer that does not properly resolve value deserializer.

**Comment by cowtowncoder** [comment]
Can not reproduce. May be reopened with a reproduction.

**Comment by mileticn** [comment]
Hi, 
I am experiencing the same issue.

Stack trace:

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.xxx.yyy.domain.Action["defaultRejectionUser"]->com.xxx.yyy.domain.User["userRole"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391) ~[jackson-databind-2.9.4.jar:2.9.4]
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351) ~[jackson-databind-2.9.4.jar:2.9.4]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1704) ~[jackson-databind-2.9.4.jar:2.9.4]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:371) ~[jackson-databind-2.9.4.jar:2.9.4]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.4.jar:2.9.4]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.4.jar:2.9.4]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:369) ~[jackson-databind-2.9.4.jar:2.9.4]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.4.jar:2.9.4]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[jackson-databind-2.9.4.jar:2.9.4]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3072) ~[jackson-databind-2.9.4.jar:2.9.4]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:235) ~[spring-web-5.0.0.RELEASE.jar:5.0.0.RELEASE]
        ... 103 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:272) ~[jackson-databind-2.9.4.jar:2.9.4]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[jackson-databind-2.9.4.jar:2.9.4]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[jackson-databind-2.9.4.jar:2.9.4]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.4.jar:2.9.4]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:369) ~[jackson-databind-2.9.4.jar:2.9.4]
        ... 110 common frames omitted
```

dependencies in pom.xml:
```
<dependency>
	<groupId>com.fasterxml.jackson.core</groupId>
	<artifactId>jackson-databind</artifactId>
	<version>2.9.4</version>
</dependency>
<dependency>
	<groupId>com.fasterxml.jackson.core</groupId>
	<artifactId>jackson-core</artifactId>
	<version>2.9.4</version>
</dependency>
<dependency>
	<groupId>com.fasterxml.jackson.core</groupId>
	<artifactId>jackson-annotations</artifactId>
	<version>2.9.4</version>
</dependency>
<spring.version>5.0.0.RELEASE</spring.version>
```

This is request:
```
{  
   ...
   "defaultRejectionUser":{  
      ...
      "userRole":[{
		id: 1, 
		name: "Default"
	  }],
      ...
   }
}
```

As you can see there is a list of objects userRole but I keep getting the error from the stack trace.
Do you know what is the issue here?

**Comment by cen1** [comment]
@cowtowncoder I can also confirm this bug, exact same scenario as SO thread linked above. Specifically, `@JsonIgnoreProperties` with a combination of nested attributes (self-nesting of the same class) causes the NullPointer error mentioned above. Tested on jackson 2.9.5 

This should be reopened.

My case:

```
public class CartItem extends CommonItem {
    @JsonIgnoreProperties({"taxes"})
    private List<CartItem> linkedItems;

    private List<KeyValue> metadata;
}
```

Input JSON:
```
{
  "quantity": 1,
  "metadata": [
        {
            "key": "p",
            "value": "2.5"
        }
   ],
  ],
  "linkedItems": [
        {
            "quantity": 1,
            "metadata": [
                {
                    "key": "p",
                    "value": "3"
                }
            ]
        }
    ]
}
```

**Comment by cen1** [comment]
Updated previus post with all classes.

**Comment by cowtowncoder** [comment]
@cen1 Thanks! We'll see... it is problematic, being recursive self-reference, so may be simple, or might be next to impossible to tackle. Hope it's former :)

**Comment by cowtowncoder** [comment]
I am able to reproduce this. NPE itself is due to recursive definition that somehow either prevents contextualization, or leaves non-contextual instance to be used (`createContextual()` is where value deserializer is fetched, if not constructed from annotations earlier).

**Comment by cowtowncoder** [comment]
Oddly enough, commenting out `metadata` (or changing type, anything to avoid another `List` valued property) prevents problem.

**Comment by cen1** [comment]
Yes, this is how I actually encountered the problem, ater adding another list in my project. This may or may not be connected to https://github.com/FasterXML/jackson-databind/issues/1575 (which I also encountered in v2.8.10 but on a recursive non-list property).

**Comment by cowtowncoder** [comment]
@cen1 Thank you for pointing out #1575, I had a feeling I had worked on similar issue somewhat recently.
Odd thing is that test for it had `Collection` too, so it's not a general problem with container types (which would be unfortunate). Now just need to try to figure out what is different in this case...

**Comment by cowtowncoder** [comment]
@oranheim Could you please file a separate issue as it's not necessarily same problem. I can have a look with reproduction, but things get confusing if it's actually caused by different underlying problem (which seems possible reading descriptions).

**Comment by oranheim** [comment]
@cowtowncoder It turned out to be a serialization issue on our side. So it was not a bug. Please disregard my error report :)

**Comment by cen1** [comment]
Was the bug actually solved or is this wrongly closed again?

**Comment by Romain-P** [comment]
I though it was fixed, isn't it? Issue opened for like 2 years lmao???

**Comment by cowtowncoder** [comment]
I think confusion here is that OP's problem not resolved; but someone who thought they had same issue found out it isn't. So I think this should not yet be closed.

**Comment by SephShom** [comment]
@cowtowncoder we appreciate all your work and we know that is not easy. But this particular feature is a real problem for me. Is there any notice about that?. "(self-nesting of the same class) " is used for a tree a organization design, by example, base of the rest of data, and version 2.7 denies us to work with all new features. Nothing more to aport, same problem deserializing self-nesting of the same class

**Comment by cowtowncoder** [comment]
I don't think there's any feature here, but a bug. If someone has time to figure it out, that'd be great, but at this point there are dozens of other problems to work on so I doubt I will have time to look into this at all on short or even medium term.

**Comment by alexis-puska** [comment]
Still present, i have the same problem, recursive object with @JsonIgnoreProperties and the problem appear.

Methode : 
 public Collection<Object> deserialize(JsonParser p, DeserializationContext ctxt,
    
line 272 : if (valueDes.getObjectIdReader() != null) {

**Comment by mxmlnglt** [comment]
Hello,

I just had the same problem (NPE at that same line 272 in `CollectionDeserializer`) and - omitting the details - I have a custom deserializer implementing interface `ContextualDeserializer`. In the `deserialize(..)` method implementation, I found out that due to reusing code from another serializer which did this:

>     ctxt.findNonContextualValueDeserializer(type);

`type` is a type I constructed via the `TypeFactory` ; I have to do this instead (when possible i.e. when the custom deserializer has been constructed via calling its `createContextual(..)` implemented method :
>     ctxt.findContextualValueDeserializer(collectionType, property);

Otherwise there are bits missing in the serializers leading to the NPE while reading the JSON.

**Comment by Romain-P** [comment]
> Hello,
> 
> I just had the same problem (NPE at that same line 272 in `CollectionDeserializer`) and - omitting the details - I have a custom deserializer implementing interface `ContextualDeserializer`. In the `deserialize(..)` method implementation, I found out that due to reusing code from another serializer which did this:
> 
> > ```
> > ctxt.findNonContextualValueDeserializer(type);
> > ```
> 
> `type` is a type I constructed via the `TypeFactory` ; I have to do this instead (when possible i.e. when the custom deserializer has been constructed via calling its `createContextual(..)` implemented method :
> 
> > ```
> > ctxt.findContextualValueDeserializer(collectionType, property);
> > ```
> 
> Otherwise there are bits missing in the serializers leading to the NPE while reading the JSON.

Ggs maybe open a MR?

**Comment by cowtowncoder** [comment]
I think code referenced would be in custom deserializer, and not in jackson-databind. It is true that the correct way to initialize, orchestrate use of deserializers to delegate to can be... tricky.
Particularly as contextualization (allowing (de)serializers to modify their behavior based on where [on which property, with what annotations] they are used) itself can get complicated, especially for structured types.

**Comment by DejazmachMolla** [comment]
Any update on this?

**Comment by cowtowncoder** [comment]
No updates; no time to actively work on this.

**Comment by JooHyukKim** [comment]
In case this might help anybody working on this, sharing this here.

I took a stab at this issue ([sample in my personal PR](https://github.com/JooHyukKim/jackson-databind/pull/7)) and here are some of my findings+guesses.

- Without `@JsonIgnoreProperties`, we have same `CollectionDeserializer` even with recursive input`
- With `@JsonIgnoreProperties`, two `CollectionDeserializer` instances, that each recursively invokes `valueDes.getObjectIdReader` (second one fails)
- Could it problem with how `BeanPropertyMap` is handled? Where during contextualization, we mutate `BeanPropertyMap` in `BeanDeserializer.withByNameInclusion()`, but do not update the reference pointing to the original `BeanPropertyMap` to the new one?

**Comment by SephShom** [comment]
Old problem but it remains me this working code:

<code>

        @ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "parent_id", insertable = true, updatable = false, referencedColumnName="c_organization_id", foreignKey = @ForeignKey(name = "fk_parent"))
	@Fetch(FetchMode.JOIN)
	@JsonIgnoreProperties(value = "parents", allowSetters = true)
	private Organization parent;
	
	@OneToMany(mappedBy = "parent", orphanRemoval = false, fetch = FetchType.EAGER, cascade = CascadeType.MERGE)
	@JsonIgnoreProperties(value = "parent", allowSetters = true)
	private List<Organization> parents;
</code>
allowSetters = true was the key here

**Comment by cowtowncoder** [comment]
For what it's worth, `allowSetters` likely triggers different code path; probably leading to basically ignoring "ignored properties"  for deserialization.

**Comment by cowtowncoder** [comment]
@JooHyukKim Some reference somewhere does not get updated that much seems certain. `BeanPropertyMap`s cannot be shared between deserializers, although I don't know how necessary/useful creation of defensive copies is (in case a new variant of `CollectionDeserializer` is constructed).

I also spent some time trying to figure this out in the past, without managing to get there.

**Comment by cowtowncoder** [comment]
Tried with Claude Code -- which, eventually, admitted defeat (after spending half an hour figuring things out) -- too big architectural changes needed.

Will attach its conclusions (in 3.0 branch)

-------

Unfortunately, I haven't been able to fix this complex issue. Let me
  summarize my findings for the user:

  Summary

  I've investigated issue #1755 (NPE with recursive @JsonIgnoreProperties) extensively. Here's what I found:

Root Cause

The issue occurs when:
1. A bean (e.g., JackExt) has a recursive collection field with `@JsonIgnoreProperties` (e.g., List<JackExt> linked)
2. During deserialization, when `BeanDeserializer.createContextual()` processes the `@JsonIgnoreProperties` annotation,   it creates a new BeanDeserializer instance via withByNameInclusion()
3. This new deserializer reuses properties from the original deserializer, which may have `CollectionDeserializers` with unresolved (null) `_valueDeserializer` fields
4. When these unresolved deserializers are used, they throw `NullPointerException CollectionDeserializer._deserializeFromArray():335`

Why It Happens

- For recursive types, properties are created with CollectionDeserializers that have _valueDeserializer = null to break the circular dependency
- These deserializers are supposed to be resolved later via BeanDeserializerBase.resolve()
- However, when @JsonIgnoreProperties triggers creation of a new BeanDeserializer via withByNameInclusion(), the new instance reuses the unresolved property deserializers
- The resolve() method is only called on the original deserializer, not on the copy

Attempted Fixes

1. Re-contextualizing in CollectionDeserializer - Caused double-contextualization issues
2. Calling resolve() after withByNameInclusion() - Caused StackOverflowError due to infinite recursion
3. Defensive null checks - Didn't help because the unresolved deserializer is in a different instance

The Issue Remains Open

This is a complex architectural issue in Jackson's deserialization lifecycle that requires careful design to fix properly. The issue affects Jackson 2.8+ through current versions and is documented in:
 
- https://github.com/FasterXML/jackson-databind/issues/1755
- https://github.com/FasterXML/jackson-databind/issues/4417

The proper fix likely requires changes to how bean deserializers handle property resolution when creating copies, potentially by ensuring all copied properties are fully resolved before use.

**Comment by cowtowncoder** [comment]
Fixed for 3.2.0.
