### ISSUE TITLE
fails on forward reference by property mapped to java.util.Optional member variable

### ISSUE THREAD

**Issue by reisners** [FasterXML/jackson-databind#1760]
The following test tries to deserialize a JSON string into a Java model consisting of a Container, a Component and a wrapper (Graph). All references between objects are supposed to be expressed through numeric _ids. The instances property of the wrapper object collects all objects in a flat array.

This test fails for jackson-databind, jackson-datatype-jdk8 versions 2.8.8 and 2.9.0.pr4 (I haven't tried others) with the exception below:

    package test;
    import static org.junit.Assert.assertTrue;

    import java.io.IOException;
    import java.util.Optional;

    import org.junit.Test;

    import com.fasterxml.jackson.annotation.JsonIdentityInfo;
    import com.fasterxml.jackson.annotation.JsonIdentityReference;
    import com.fasterxml.jackson.annotation.JsonSubTypes;
    import com.fasterxml.jackson.annotation.JsonTypeInfo;
    import com.fasterxml.jackson.annotation.JsonTypeName;
    import com.fasterxml.jackson.annotation.ObjectIdGenerators;
    import com.fasterxml.jackson.core.JsonParseException;
    import com.fasterxml.jackson.databind.JsonMappingException;
    import com.fasterxml.jackson.databind.ObjectMapper;
    import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;

    public class ForwardReferenceTest {

        @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_class")
        @JsonTypeName("")
        @JsonSubTypes({ @JsonSubTypes.Type(name = "Container", value = Container.class),
                @JsonSubTypes.Type(name = "Component", value = Component.class),
                @JsonSubTypes.Type(name = "Graph", value = Graph.class) })
        public static abstract class Base {
        }

        @JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class, property = "_id")
        @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_class")
        @JsonTypeName("Container")
        public static class Container extends Base {
            @JsonIdentityReference(alwaysAsId = true)
            public Optional<Component> component = Optional.empty(); // breaks
    //      public Component component; // works
        }

        @JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class, property = "_id")
        @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_class")
        @JsonTypeName("Component")
        public static class Component extends Base {
            public String value;
        }

        public static class Graph extends Base {
            @javax.validation.constraints.NotNull
            public java.util.List<Base> instances = new java.util.ArrayList<>();
        }

        @Test
        public void test() throws JsonParseException, JsonMappingException, IOException {
            ObjectMapper mapper = new ObjectMapper();
            mapper.registerModule(new Jdk8Module());

            String json = "{\"_class\":\"Graph\", \"instances\": [{\"_id\":1, \"_class\":\"Container\", \"component\": 2}, {\"_id\":2, \"_class\":\"Component\", \"value\":\"hello\"}]}";

            Graph graph = mapper.readValue(json, Graph.class);

            assertTrue(graph.instances.get(0) instanceof Container);
        }

    }

Exception:

    com.fasterxml.jackson.databind.JsonMappingException: Unresolved forward reference but no identity info
     at [Source: (String)"{"_class":"Graph", "instances": [{"_id":1, "_class":"Container", "component": 2}, {"_id":2, "_class":"Component", "value":"hello"}]}"; line: 1, column: 79] (through reference chain: test.ForwardReferenceTest$Graph["instances"])
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:277)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:296)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:189)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1156)
        at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4011)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
        at test.ForwardReferenceTest.test(ForwardReferenceTest.java:65)

When the member variable Container.component is declared as Component instead of Optional<Component>, deserialization from JSON works.

**Comment by cowtowncoder** [comment]
This might be something that could be fixed as it affects referential types like `Optional` (and can be tested against `AtomicReference` to allow tests within `jackson-databind`).
I suspect code that exists in `Collection` and `Map` handlers is missing.

**Comment by cowtowncoder** [comment]
Also: one note worth mentioning is that handling of Object Id is defined as round-trip support, meaning that Jackson should read what it writes, but not necessarily read any json structure.
I assume test just uses serialization results for simplicity, and it would be possible to serialize object graph, fail on deserialize.

**Comment by cowtowncoder** [comment]
No plans to implement; closing as part of bigger issue clean up.
