### ISSUE TITLE
@JsonCreator doesn't work when placed on a custom annotation

### ISSUE THREAD

**Issue by bohnman** [FasterXML/jackson-databind#1787]
Jackson versions: 2.8.10 and 2.9.1

I have the following custom annotation:

```java
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@JsonCreator
public @interface Parse {
}
```

and the following enum class:

```java
public enum Test2Enum {
    ONE,
    TWO,
    THREE;

    private final String id;

    Test2Enum() {
        this.id = name().toLowerCase();
    }

    @Parse
    public static Test2Enum parse(String id) {
        return valueOf(id.toUpperCase());
    }
}
```

When I run the following:

```java
System.out.println(mapper.readValue("\"one\"", Test2Enum.class));
```

I get the following exception:

```java
Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `test.Test2Enum` from String "one": value not one of declared Enum instance names: [TWO, ONE, THREE]
 at [Source: (String)""one""; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1535)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:910)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:255)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:179)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
	at test.Test.main(Test.java:10)
```

If I put `@JsonCreator` directly on the parse method, it works fine.

I have attached [test.zip](https://github.com/FasterXML/jackson-databind/files/1359755/test.zip), which demonstrates this issue.  You can run in your favorite IDE or on the command line: `mvn compile exec:java`

Thanks in advance!

**Comment by cowtowncoder** [comment]
The problem here is that custom annotation type does not have `@JacksonAnnotationsInside` marker, and as such annotations it has are not inspected or included in processing.
So adding that marker annotation should solve the problem.

**Comment by bohnman** [comment]
That was it!  Thanks!
