### ISSUE TITLE
InvalidDefinitionException after upgrading from 2.9.1 to 2.9.2

### ISSUE THREAD

**Issue by charleskorn** [FasterXML/jackson-databind#1817]
I'm using Kotlin and I've just upgraded from Jackson version 2.9.1 to 2.9.2. Previously the following was working:

```kotlin
val parsed = jsonMapper.readValue(result.output, DockerHealthCheckStatus::class.java)
```

But now it fails with the following exception:

```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid definition for property `Log` (of type `batect.docker.DockerClient$DockerHealthCheckStatus`): Could not find creator property with name 'Log' (known Creator properties: [log])
 at [Source: (String)"{
                                  "Status": "unhealthy",
                                  "FailingStreak": 130,
                                  "Log": [
                                    {
                                      "Start": "2017-10-04T00:54:23.608075352Z",
                                      "End": "2017-10-04T00:54:23.646606606Z",
                                      "ExitCode": 1,
                                      "Output": "something went wrong"
                    "[truncated 87 chars]; line: 1, column: 1]
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:62)
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadPropertyDefinition(DeserializationContext.java:1446)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:607)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:269)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:179)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
        at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4178)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3997)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
        at batect.docker.DockerClient.getLastHealthCheckResult(DockerClient.kt:249)
```

Parser is set up with:

```kotlin
    private val jsonMapper by lazy {
        val mapper = jacksonObjectMapper()
        mapper.propertyNamingStrategy = PropertyNamingStrategy.UPPER_CAMEL_CASE
        mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)

        mapper
    }
```

`DockerHealthCheckStatus` is defined as:

```kotlin
    private data class DockerHealthCheckStatus(val log: List<DockerHealthCheckResult>)
```

Am I doing something wrong or is this a bug introduced in 2.9.2?

**Comment by cowtowncoder** [comment]
@charleskorn Since this is Kotlin specific, could you please (re)file at `jackson-module-kotlin`:

    https://github.com/FasterXML/jackson-module-kotlin/issues

as it all really depends on how Kotlin module adds various markers: in particular, equivalent of `@JsonCreator`, and distinction between implicit and explicit property names (implicit coming from method name, or, if available, constructor property name; explicit from annotation).

In this case it looks like there's discrepancy between your requesting naming strategy of `PropertyNamingStrategy.UPPER_CAMEL_CASE`, and name from constructor.
It seems to me like your set up should work.

As to work-around, if you can add `@JsonProperty("Log")` for `log` constructor parameter, that would probably solve specific issue.

**Comment by charleskorn** [comment]
OK, I've submitted it over there as https://github.com/FasterXML/jackson-module-kotlin/issues/100.
