### ISSUE TITLE
JsonMappingException when serializing ConstraintViolationException

### ISSUE THREAD

**Issue by bpaczkowski** [FasterXML/jackson-databind#1862]
I'm using jackson with Spring AMQP to send messages between services, exceptions are a type of message that get serialized, but I get an exception when Jackson tries to serialize an ConstraintViolationException:

```
org.springframework.amqp.support.converter.MessageConversionException: Failed to convert Message content
	at org.springframework.amqp.support.converter.Jackson2JsonMessageConverter.createMessage(Jackson2JsonMessageConverter.java:234) ~[spring-amqp-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.amqp.support.converter.AbstractMessageConverter.toMessage(AbstractMessageConverter.java:56) ~[spring-amqp-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at xxx.amqp.Sender.sendResponse(Sender.java:94) ~[classes/:na]
	at xxx.amqp.Receiver.onMessage(Receiver.java:61) [classes/:na]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1457) [spring-rabbit-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1348) [spring-rabbit-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1324) [spring-rabbit-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1303) [spring-rabbit-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:785) ~[spring-rabbit-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:769) ~[spring-rabbit-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$700(SimpleMessageListenerContainer.java:77) ~[spring-rabbit-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1010) ~[spring-rabbit-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: HV000116: getParameterIndex() may only be invoked for nodes of type ElementKind.PARAMETER. (through reference chain: javax.validation.ConstraintViolationException["constraintViolations"]->java.util.HashSet[0]->org.hibernate.validator.internal.engine.ConstraintViolationImpl["propertyPath"]->org.hibernate.validator.internal.engine.path.PathImpl["leafNode"]->org.hibernate.validator.internal.engine.path.NodeImpl["parent"]->org.hibernate.validator.internal.engine.path.NodeImpl["parameterIndex"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:145) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3893) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3207) ~[jackson-databind-2.9.3.jar:2.9.3]
	at org.springframework.amqp.support.converter.Jackson2JsonMessageConverter.createMessage(Jackson2JsonMessageConverter.java:230) ~[spring-amqp-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	... 12 common frames omitted
Caused by: java.lang.IllegalArgumentException: HV000116: getParameterIndex() may only be invoked for nodes of type ElementKind.PARAMETER.
	at org.hibernate.validator.internal.util.Contracts.assertTrue(Contracts.java:66) ~[hibernate-validator-6.0.5.Final.jar:6.0.5.Final]
	at org.hibernate.validator.internal.engine.path.NodeImpl.getParameterIndex(NodeImpl.java:366) ~[hibernate-validator-6.0.5.Final.jar:6.0.5.Final]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:687) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) ~[jackson-databind-2.9.3.jar:2.9.3]
	... 33 common frames omitted
```

Spring AMQP includes Jackson with version 2.9.2, but I also tried updating it to 2.9.3 with the same results.

**Comment by cowtowncoder** [comment]
I don't know how I can help here since there is no way to reproduce the issue.
From stack trace it appears that Hibernate is involved, and it looks like the original exception is by Hibernate validator. So that might be a place to start troubleshooting.

**Comment by bpaczkowski** [comment]
I've put together a small test project using an embedded DB, upon starting it it tries to save an entity without a required property resulting in a ConstraintViolationException, which it then tries to serialize using Jackson resulting in another exception.

[test.zip](https://github.com/FasterXML/jackson-databind/files/1571814/test.zip)

**Comment by cowtowncoder** [comment]
Ok this needs to be filed under `jackson-datatype-hibernate`, since reproduction requires use of Hibernate, even if just as a dependency.

**Comment by xuguang9** [comment]
for hibernate,interface Node's some subType forbid section getter method.
	e.g getter method getContainerClass must be  ElementKind.BEAN ,ElementKind.PROPERTY ,ElementKind.CONTAINER_ELEMENT   ,
	    getter method getParameterIndex must be  ElementKind.PARAMETER .
	so if you serialize to json string ,should use that getter , then occur exception .
	you can config feature fix this.
    for jackson    new ObjectMapper().disable(MapperFeature.AUTO_DETECT_GETTERS).writeValueAsString(object);
    for fastjson   JSON.toJSONString(object, SerializerFeature.IgnoreErrorGetter);
