### ISSUE TITLE
ProblemHandler not invoked on undefined token

### ISSUE THREAD

**Issue by shuawest** [FasterXML/jackson-databind#1863]
Context: jackson-databind v2.8.7

## Problem: 
While trying to consume an external service I found that they inject the `undefined` token [1] into the response for some null values. 

## Expected Behavior: 
In trying to handle this challenge I expected that I could create a custom problem handler  [2] and add it to the mapper configuration [3] to deal with the `undefined` token, however the problem handler is never invoked. 

## Question: 
I could not find any hook for the value token to be handled. If there is a way to resolve this please advise, otherwise I'd recommend a fix to call the problem handler. 

## Appendix 
[1] sample JSON data to be deserialized
```
{
  "id": "0428b97b-bec1-429e-a94c-59232926778d",
  "type": "fills",
  "status": "creating",
  "created_at": "2015-01-06T10:34:47.000Z",
  "completed_at": undefined,
  "expires_at": "2015-01-13T10:35:47.000Z",
  "file_url": undefined,
  "params": {
    "start_date": "2014-11-01T00:00:00.000Z",
    "end_date": "2014-11-30T23:59:59.000Z"
  }
}
```

[2] Custom problem handler
```
public class UndefinedTokenDeserializationProblemHandler extends DeserializationProblemHandler {
  public Object handleUnexpectedToken(..) throws IOException {
        LOG.debug("Handling unexpected token: {}", t);
        ...
  }
}
```

[3] Problem handler initialization
```
ObjectMapper modelMapper = new ObjectMapper();
modelMapper.addHandler(new UndefinedTokenDeserializationProblemHandler());
```

[4] Stack trace
```
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'undefined': was expecting ('true', 'false' or 'null')
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@1d269ed7; line: 6, column: 29]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3528)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2686)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextFieldName(UTF8StreamJsonParser.java:1101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:283)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1583)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:964)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:815)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBodyReader(JAXRSUtils.java:1342)
	at org.apache.cxf.jaxrs.impl.ResponseImpl.doReadEntity(ResponseImpl.java:370)
	... 30 more
```

**Comment by cowtowncoder** [comment]
Problem here is that what you get is not unexpected token (property name is fine for the context), but rather that property it implies does not exist in target. This results in different method getting called:

```java
public boolean handleUnknownProperty(DeserializationContext ctxt, JsonParser p,
            JsonDeserializer<?> deserializer, Object beanOrClass, String propertyName);
```

so you will need to define that method to handle this case.

Also note that in such a case you need to make sure to consume content (for structured values), usually by calling `p.skipChildren()` before returning; otherwise following content will cause problems for further processing.

**Comment by shuawest** [comment]
Just checked and `handleUnknownProperty` isn't called either. UTF8StreamJsonParser._handleUnexpectedValue is coming across the "u" character on the value side.  I'd expect problem handler visitor to be called, either the handleUnknownToken or another new problem handler method, before the _reportInvalidToken is called. Perhaps all text prior to a comma should be matched as the unknown token. 

As a workaround, I had to just brute force replace `undefined` with `null` in my CXF interceptors. I don't see any other hooks to fix malformed/unexpected JSON which I don't control as a client-side user only.

**Comment by cowtowncoder** [comment]
Ah. So it is not valid JSON at all (but something javascript code likely produced?).
I did not notice that, hence confusion.

Jackson does not allow use of unquoted values, so you do need to either add some sort of pre-processing.
Or, preferably, get your clients to fix their crap -- this is not valid JSON, and sending it should (in my opinion) fail. "Your data is bad and you should feel bad", as Dr. Zoidberg would say.

**Comment by cowtowncoder** [comment]
So: this is not unknown property or unexpected token: problem occurs at streaming parser and is not something higher level code can or should deal with. Rather, content should be fixed.
