### ISSUE TITLE
NoClassDefFoundError/ClassNotFoundException with ObjectMapper 

### ISSUE THREAD

**Issue by Florent5929** [FasterXML/jackson-databind#1903]
Hello,

I belong to the staff of a game server and I have a problem with the plugin of the server. It's normally linked with our website, but the link seems breaken. The reason seems to be an "ObjectMapper", from jackson-databind, not found by the plugin : 

```
[04:34:41] [Thread-8/WARN]: Exception in thread "Thread-8" 
[04:34:41] [Thread-8/WARN]: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
[04:34:41] [Thread-8/WARN]: 	at main.java.com.naheulcraft.specific.Ressources.FeatureFunctions$AsynchronousAPISender$APISenderRunnable.run(FeatureFunctions.java:673)
[04:34:42] [Thread-8/WARN]: 	at java.lang.Thread.run(Unknown Source)
[04:34:42] [Thread-8/WARN]: Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
[04:34:42] [Thread-8/WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[04:34:42] [Thread-8/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[04:34:42] [Thread-8/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[04:34:42] [Thread-8/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[04:34:42] [Thread-8/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[04:34:42] [Thread-8/WARN]: 	... 2 more
```

The following dependancies are in the pom.xml, and Maven seems detects it :

```
<dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-annotations</artifactId>
        <version>2.8.7</version>
		<type>jar</type>
	    <scope>compile</scope> 
    </dependency>
    <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-core</artifactId>
        <version>2.8.7</version>
		<type>jar</type>
	    <scope>compile</scope> 
    </dependency>
    <dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.8.7</version>
			<type>jar</type>
			<scope>compile</scope> 
				<exclusions>
					<exclusion> 
						<groupId>com.fasterxml.jackson.core</groupId>
						<artifactId>jackson-annotations</artifactId>
					</exclusion>
					<exclusion> 
						<groupId>com.fasterxml.jackson.core</groupId>
						<artifactId>jackson-core</artifactId>
					</exclusion>
			 </exclusions> 
    </dependency>
```

There isn't error in the import :

```
import com.fasterxml.jackson.databind.ObjectMapper;
[...]

private class APISenderRunnable implements Runnable
        {
            Map<String, String> params;
            APISenderRunnable(Map<String, String> params)
            {
                this.params = params;
            }

            public void run()
            {
                ObjectMapper mapper = new ObjectMapper();
                String url = FeatureFunctions.BuildFullUrl(NCPlugin.API_URL, params);
                try
                {
                    array = mapper.readTree(new URL(url));
                }
                catch(Exception e)
                {
                    System.out.println("ERROR, URL BUILDING FAILED OR API IS DOWN.");
                }
            }
        }
```
But it don't work. I tried many propositions on the internet, as change the version, change the .classpath, add the .jar with buildpath > add external jars, clean and build the project... Without success.

This is the complete pom.xml :

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.naheulcraft</groupId>
    <artifactId>specific</artifactId>
    <url>http://www.naheulcraft.com/</url>
    <build>
	 <sourceDirectory>src</sourceDirectory>
        <resources>
            <resource>
                <filtering>true</filtering>
                <directory>src</directory>
                <includes>
                    <include>plugin.yml</include>
                </includes>
            </resource>
        </resources>
	<plugins>
	    <plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-compiler-plugin</artifactId>
		<version>2.0.2</version>
		<configuration>
		    <source>1.8</source>
		    <target>1.8</target>
		    <encoding>${project.build.sourceEncoding}</encoding>
		</configuration>
	    </plugin>
	    <plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-assembly-plugin</artifactId>
		<version>2.4</version>
		<executions>
		    <execution>
			<phase>package</phase>
			<goals>
			    <goal>single</goal>
			</goals>
		    </execution>
		</executions>		
		<configuration>
		    <descriptorRefs>
			<descriptorRef>jar-with-dependencies</descriptorRef>
		    </descriptorRefs>
		</configuration>
	    </plugin>
	    <plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-resources-plugin</artifactId>
		<version>2.4.3</version>
		<configuration>
		    <encoding>${project.build.sourceEncoding}</encoding>
		</configuration>
	    </plugin>
	</plugins>
    </build>
    <repositories>
	<repository>
	    <id>spigot-repo</id>
	    <url>https://hub.spigotmc.org/nexus/content/groups/public/</url>
	</repository>
	<!--<repository>
	    <id>bukkit-repo</id>
	    <url>http://repo.bukkit.org/content/groups/public</url>
	</repository>-->
	<repository>
	    <id>codehaus-snapshots</id>
	    <url>http://snapshots.repository.codehaus.org</url>
	</repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.1</version>
        </dependency>
	<!--<dependency>
	    <groupId>org.codehaus.jackson</groupId>
	    <artifactId>jackson-mapper-asl</artifactId>
		<version>1.9.11</version>
	    <type>jar</type>
	    <scope>compile</scope> 
	</dependency>-->
    <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-annotations</artifactId>
        <version>2.8.7</version>
		<type>jar</type>
	    <scope>compile</scope> 
    </dependency>
    <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-core</artifactId>
        <version>2.8.7</version>
		<type>jar</type>
	    <scope>compile</scope> 
    </dependency>
    <dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.8.7</version>
			<type>jar</type>
			<scope>compile</scope> 
				<exclusions>
					<exclusion> 
						<groupId>com.fasterxml.jackson.core</groupId>
						<artifactId>jackson-annotations</artifactId>
					</exclusion>
					<exclusion> 
						<groupId>com.fasterxml.jackson.core</groupId>
						<artifactId>jackson-core</artifactId>
					</exclusion>
			 </exclusions> 
    </dependency>
	<!--<dependency>
	    <groupId>org.bukkit</groupId>
	    <artifactId>bukkit</artifactId>
	    <version>LATEST</version>
	</dependency>-->
        <dependency>
            <groupId>com.google.code.google-collections</groupId>
            <artifactId>google-collect</artifactId>
            <version>snapshot-20080530</version>
            <type>jar</type>
        </dependency>
    </dependencies>
    <properties>
	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <name>NaheulcraftFR-Specific</name>
    <version>1.10</version>
</project>
```
And the actual .classpath :

```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry including="**/*.java" kind="src" output="target/classes" path="src">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry exported="true" kind="lib" path="C:/Users/Florent_2/Desktop/Serveur test Spigot/bukkit.jar"/>
	<classpathentry exported="true" kind="con" path="org.eclipse.m2e.MAVEN2_CLASSPATH_CONTAINER">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="org.eclipse.jst.component.dependency" value="/WEB-INF/lib"/>
		</attributes>
	</classpathentry>
	<classpathentry exported="true" kind="lib" path="C:/Users/Florent_2/Desktop/spigot-1.12.2-R0.1-SNAPSHOT-b1577.jar"/>
	<classpathentry exported="true" kind="con" path="org.eclipse.jst.j2ee.internal.web.container"/>
	<classpathentry exported="true" kind="con" path="org.eclipse.jst.j2ee.internal.module.container"/>
	<classpathentry exported="true" kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
	<classpathentry kind="lib" path="C:/Users/Florent_2/Desktop/com.fasterxml.jackson.databind.jar"/>
	<classpathentry kind="output" path="target/classes"/>
</classpath>
```

Thank you in advance for your help.
Florent

P.S. : Sorry for my bad english, I'm french, I'm not english-speaker.

**Comment by cowtowncoder** [comment]
As exception states, class `com.fasterxml.jackson.databind.ObjectMapper` from jar `jackson-databind` is not available. I would be guessing that this:

```xml
	<classpathentry kind="lib" path="C:/Users/Florent_2/Desktop/com.fasterxml.jackson.databind.jar"/>

```

does not refer to valid file location?

**Comment by Florent5929** [comment]
The location is correct, there is this jar at this location. In fact, I added this for try to fix the problem, but normally, the Maven dependancies  are supposed to be sufficient. I searched on the web, I found a lot of potential solutions but neither work so far. It would be a deployment problem, I quote a person who tried to help me : 

> Evidently the code builds successfully, but the program complains about a missing class at runtime. It follows that the needed class, and probably one or more entire jars, is missing from the deployed class's runtime classpath.

I tried to add the jar(s) in "deployement assembly" or WEB-INF/lib, without success.

A person with the same problem said this : 

> I figured out what was wrong.
> 
> It turns out that the environment I am using (Eclipse!) does not properly update the manifest file when you export your code to a JAR file. Without the proper manifest entries, the application cannot "find" the dependent jar files.
> 
> This is, in my opinion, a serious oversight on the part of the Eclipse folks -- especially when you have an application that depends on a lot of jar files. In order to make my application run, I had the following choices:
> 
> 1: Create a script that runs the jvm and has a list of parameters pointing to every needed jar file, or:
> 2: Manually enter each required jar file into the Manifest file
> 
> To my knowledge, there is no way to automatically update the manifest file. This is a serious PITA (Pain In The A**)...

I don't know how to do it.

**Comment by cowtowncoder** [comment]
@Florent5929 It is a deployment problem of some kind, and not really related to Jackson itself in any way. So this does not really belong to Jackson issue tracker.
If you want, you could ask it on Jackson users' list:

groups.google.com/group/jackson-user/

but since it sounds like a more general problem with your deployment -- Maven is only used for building, as you probably know, not running -- I'll close this issue.
