### ISSUE TITLE
Improve feedback "InvalidDefinitionException: Cannot find a (Map) Key deserializer for type [simple type, class [...]]"

### ISSUE THREAD

**Issue by krichter722** [FasterXML/jackson-databind#1968]
I just encountered a situation involving three classes `Entity1`, `Entity2` and `Entity3` where `Entity1` has

    
    @JsonSerialize(using = ValueMapSerializer.class)
    @JsonDeserialize(using = ValueMapDeserializer.class)
    private Map<Entity2, String> valueMap;
    private Entity3 entity3;

properties. `Entity3` has a `Map<Entity2, String> otherValueMap` with missing annotations. When serializing an `Entity1` with

```
Entity1 entity1 = new Entity1();
Entity2 entity2 = new Entity2(1l);
entity1.getValueMap().put(entity2, "test");
ObjectMapper objectMapper = new ObjectMapper();
String serialized = objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(entity1);
Entity1 deserialized = objectMapper.readValue(serialized,
        Entity1.class);
assertEquals(entity1,
        deserialized);
```

the serialization fails due to

```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot find a (Map) Key deserializer for type [simple type, class richtercloud.jackson.map.key.missing.feedback.Entity2]
 at [Source: (String)"{
  "valueMap" : [ {
    "key" : {
      "id" : 1
    },
    "value" : "test"
  } ],
  "entity3" : null
}"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1451)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._handleUnknownKeyDeserializer(DeserializerCache.java:599)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findKeyDeserializer(DeserializerCache.java:168)
	at com.fasterxml.jackson.databind.DeserializationContext.findKeyDeserializer(DeserializationContext.java:500)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.createContextual(MapDeserializer.java:248)
	at com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(DeserializationContext.java:651)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:484)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:467)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:473)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4178)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3997)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
	at richtercloud.jackson.map.key.missing.feedback.TheTest.testJsonSerialization(TheTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

because `Entity3.otherValueMap` is missing annotations. The issue here is that the `Entity1.entity3` field is `null` and it's thus hard to figure out that the failure is referring to `Entity3.otherValueMap` (I extracted the SSCCE from a 300+ classes project over several hours after a few days of wondering and two StackOverflow questions). A hint in the message would spare others this potential work.

An SSCCE can be found at https://gitlab.com/krichter/jackson-map-key-missing-feedback.

experienced with 2.9.4

**Comment by cowtowncoder** [comment]
Ah. As to exception, location can not be reported because this happens before deserialization, only using static type definitions when traversing type hierarchy. If it occurred during reading of values, you would get path. Tricky. I'll have to think about this a bit.

One thing sort of related thing to note: I assume you'd be better off registering key serializer and deserializer for `Entity2`, instead of having to do full typed-Map (de)serializer. That can be registered globally (via module).

**Comment by cowtowncoder** [comment]
@krichter722  Hmmh. One possibility would be to actually create "dummy" key deserializer, one that would only fail when actual attempt was made to use it.

I am bit torn as to whether that would be better or worse, just because sometimes it is better to get failure as soon as things are known not to work -- and in this case this would depend on data.
It would be possible for things to seemingly work for a long time if `Map`s are empty.

But doing that would give source location appropriately as it would only be triggered when there is data to bind.

**Comment by cowtowncoder** [comment]
Not quite sure how to proceed, will close. May be reopened with an idea of concrete improvement(s) to make.
