### ISSUE TITLE
Custom serializer is broken after upgrade to 2.9.X

### ISSUE THREAD

**Issue by test88d** [FasterXML/jackson-databind#1976]
I have customSerializer to format Date Json output, but it is broken when I upgrade to 2.9. version. it throws  error like below:

```
Caused by: com.fasterxml.jackson.core.JsonGenerationException: Current context not Object but Array
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1961)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeEndObject(UTF8JsonGenerator.java:351)
	at com.fasterxml.jackson.core.JsonGenerator.writeTypeSuffix(JsonGenerator.java:1492)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeSerializerBase.writeTypeSuffix(TypeSerializerBase.java:53)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:606)
```

In my customDateSerializer I override serializeWithType,  I have writePrefixForAll method as below. When I debug, I found the error is coming from a Date field is go to  case PROPERTY, and typeSer.writeTypePrefixForScalar will override jsonGenerator._writeContext._type =1. is it a bug?

```java
   private void writePrefixForAll(Timestamp value, JsonGenerator jsonGenerator, TypeSerializer typeSer) throws IOException
    {
        switch(this.typeAs)
        {
            case PROPERTY:
                typeSer.writeTypePrefixForScalar(value, jsonGenerator);
                break;
            case WRAPPER_OBJECT:
                typeSer.writeTypePrefixForObject(value, jsonGenerator);
                break;
            case WRAPPER_ARRAY:
                typeSer.writeTypePrefixForArray(value, jsonGenerator);
                break;
            default:
    			break;
        }
    }
```

**Comment by cowtowncoder** [comment]
@test88d What is missing is matching call to `writeTypeSuffix` after serialization. Pattern to follow can be seen from standard serializers in `jackson-databind`, for example `MapSerializer`: first call to one of `writeTypePrefixXxx()` methods, then value serialization (but omitting enclosing container for values serialized as JSON Objects or Arrays!), and then matching `writeTypeSuffixXxx()`.

In general, also, you serializer should not call different prefix/suffix methods based. This may be misunderstanding regarding how type id is enclosed (determined by `PROPERTY` and other settings) and how VALUE is serialized. Prefix/Suffix calls should be based on latter -- if it's Scalar value in JSON (when writing `String` or simple number), it should be "scalar"; regardless of type id inclusion. `TypeSerializer` will then figure out how to handle combination.
So: although you may get "include as PROPERTY", method to call depends on how value will be written -- as JSON Object (-> "for object"), as JSON Array (-> "for array") or as something else (-> "for scalar").

I don't know how this happened to work in previous versions (2.8), but I am a bit surprised it did.
There are changes to how type ids are propagated (between 2.8 and 2.9), to support binary formats better (to allow more flexibility by underlying stream parser/generator) so it is not entirely surprising behavior varies however, when using sequences different from intent of databind
(meaning: behavior for this could would be undefined).

Finally, if you look at `TypeSerializer`, you can see how methods to call have changed to allow for more flexibility; older methods are now deprecated to mark new ones mean to replace them for 3.0. If possible (i.e. compatibility with 2.8 not needed) you will probably want to upgrade.
But deprecated methods should still work in 2.9 as intended.

**Comment by cowtowncoder** [comment]
I think the explanation above should be enough to fix the serialization part. As of now I do not see a bug in Jackson itself, but rather things "accidentally working" with prior versions.

**Comment by test88d** [comment]
I want to reopen this issue, because I still can't find solution. Actually, my code has the override of serialWithType and writePrefixForAll, writeSuffixForAll. The code is same in both writePrefixForAll and writeSuffixForAll. 

public void serializeWithType(Date date,
                                  JsonGenerator jsonGenerator,
                                  SerializerProvider serializerProvider,
                                  TypeSerializer typeSer)  throws IOException {
        writePrefixForAll(date, jsonGenerator, typeSer);
       .......//print date
        writeSuffixForAll(date, jsonGenerator, typeSer);
    }

I saw writeTypePrefixForScalar, writeTypePrefixForObject and writeTypePrefixForArray are all deprecated in 2.9 but I don't see new method name to replace them.  I can try new methods if you can tell me the replacement.

Anyway, if I comment out writePrefixForAll and writeSuffixForAll, I can generate Json String but Date without type. I really need to keep the date type in output JSON, so I have to keep writePrefixForAll and 
writeSuffixForAll. But I got below errors. Please help.

Caused by: com.fasterxml.jackson.core.JsonGenerationException: Current context not Object but Array
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1961)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeEndObject(UTF8JsonGenerator.java:351)
	at com.fasterxml.jackson.core.JsonGenerator.writeTypeSuffix(JsonGenerator.java:1492)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeSerializerBase.writeTypeSuffix(TypeSerializerBase.java:53)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:606)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:729)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:604)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:147)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase.serializeWithType(AsArraySerializerBase.java:261)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:729)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:604)
	at com.fasterxml.jackson.databind.ser.impl.TypeWrappedSerializer.serialize(TypeWrappedSerializer.java:32)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3893)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3231)
	at com.cme.cdo.io.json.serialize.JacksonJsonSerializer.serialize(JacksonJsonSerializer.java:119)

**Comment by cowtowncoder** [comment]
@test88d I am sure you can find these out if you spend time looking through tests, or, existing standard serializers (grep for `serializeWithType()`).
