### ISSUE TITLE
java.lang.IllegalArgumentException: Unrecognized Type: [null]

### ISSUE THREAD

**Issue by presto9292** [FasterXML/jackson-databind#2003]
The exception below is from 
cxf 3.16
swagger 1.5.15
jackson 2.8.10

Although I have also tried many other combinations including
cxf 3.2.4
swagger 1.5.17
jackson 2.9.5

and in all cases I get this exception intermittently 

Turning on the debug level in swagger seems to point to a specific class file in my model,
I would appreciate any help

Caused by: java.lang.IllegalArgumentException: Unrecognized Type: [null]
	at com.fasterxml.jackson.databind.type.TypeFactory._fromAny(TypeFactory.java:1189)
	at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:622)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClass.resolveType(AnnotatedClass.java:246)
	at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.getParameterType(AnnotatedMethod.java:157)
	at com.fasterxml.jackson.databind.introspect.AnnotatedWithParams.getParameter(AnnotatedWithParams.java:86)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addCreators(POJOPropertiesCollector.java:459)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:307)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:267)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:159)
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:144)
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:219)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:320)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:185)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:100)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:236)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:185)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:100)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:161)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:112)
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:80)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:464)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:185)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:100)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:236)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:185)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:100)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:161)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:112)
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:80)
	at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:58)
	at io.swagger.util.ParameterProcessor.applyAnnotations(ParameterProcessor.java:263)
	at io.swagger.jaxrs.Reader.getParameters(Reader.java:1049)
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:975)
	at io.swagger.jaxrs.Reader.read(Reader.java:322)
	at io.swagger.jaxrs.Reader.read(Reader.java:172)
	at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:242)
	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:221)
	at org.apache.cxf.jaxrs.swagger.Swagger2Feature.addSwaggerResource(Swagger2Feature.java:111)
	at org.apache.cxf.jaxrs.swagger.AbstractSwaggerFeature.initialize(AbstractSwaggerFeature.java:69)
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.applyFeatures(JAXRSServerFactoryBean.java:252)
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:196)

**Comment by cowtowncoder** [comment]
This is not enough information to really help you. We would need a reproduction of some kind.
