### ISSUE TITLE
Unable to serialize an object within a boxed class after 2.5.2

### ISSUE THREAD

**Issue by paulojrp** [FasterXML/jackson-databind#2031]
I noticed a serialization case that was broken from jackson 2.5.1 and 2.5.2.

I created a simple example that can be found in the following [link](https://github.com/Lamouse/jacksoSerializationIssue/blob/master/src/test/java/JacksonTest.java).

Basically, I'm using a boxed class to put an object to serialize/deserialize in a capsule. Then it will use the capsule object in a TypeReference to deserialize the object.
The capsule object is being used to add the class of the generic object to the Json.

Before Jackson 2.5.2 I'm able to serialize and deserialize objects however after that version the deserialization of collection started to fail with the following error. I'm still able to deserialize non-collections objects.

```
com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of java.io.Serializable, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information
 at [Source: [B@b7dd107; line: 1, column: 2] (through reference chain: BaseValue["data"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:892)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:139)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:138)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:82)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:518)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:378)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2836)
	at CustomMap.deserialize(JacksonTest.java:91)
```

Afterwards I tried to define the type of the collection however it failed with a different error.

```
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: [B@670b40af; line: 1, column: 31] (through reference chain: BaseValue["data"]->java.util.ArrayList[1])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:857)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:846)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:190)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:161)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:19)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:378)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2836)
	at CustomMap.deserialize(JacksonTest.java:87)
```

**Comment by paulojrp** [comment]
I found a workaround for this problem, I had to remove the default type from
``@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, defaultImpl = Serializable.class)``

**Comment by cowtowncoder** [comment]
@paulojrp Please note that both versions are very old, and in particular there are many newer patches for 2.5; latest being `2.5.5`. In general it is good idea to always verify at least the latest patch for given minor version -- there are many bug fixes and sometimes reported problem has been resolved.

Declaration of `defaultImpl` looks wrong since there is no way for Jackson to create instances of `Serializable`, unless there is abstract type mapping specified.

Other than that, I would further suggest upgrade to a later minor version; since versions before 2.8 are not open any more (that is, no patches will be merged nor releases made), reproduction of possible remaining problems would need to be for newer versions.

**Comment by paulojrp** [comment]
@cowtowncoder thanks for the quick response. I forgot to said that I also tested with the latest version (2.9.5) and that I found this problem when I was upgrading from 2.4.5 to 2.6.7.

I will change the declaration of `defaultImpl`, once again thanks for your help.
