### ISSUE TITLE
`UnwrappingBeanPropertyWriter` incorrectly assumes the found serializer is of type `UnwrappingBeanSerializer`

### ISSUE THREAD

**Issue by ptahchiev** [FasterXML/jackson-databind#2060]
Hello,
I want to add a bunch of attributes to the resulting JSON file so I create my own `StdSerializer`like this:
````
    class MarkupAwareStandardSerializer extends StdSerializer<AbstractEntityDefinition> {

        private StdSerializer serializer;

        public MarkupAwareStandardSerializer(StdSerializer src) {
            super(src);
            this.serializer = src;
        }

        @Override
        public void serialize(AbstractEntityDefinition bean, JsonGenerator gen, SerializerProvider provider) throws IOException {
            ServletRequestAttributes servletRequestAttributes = ((ServletRequestAttributes) RequestContextHolder.getRequestAttributes());

            if (servletRequestAttributes != null) {
                String filterId = servletRequestAttributes.getRequest().getParameter("filter");

                if (StringUtils.isNotEmpty(filterId) && filterId.equals("search")) {
                    List<ItemMarkup> itemMarkups = entityFacade.getEntityPropertyMarkups(bean.getClass());
                    gen.writeStartObject(bean);
                    for (ItemMarkup itemMarkup : itemMarkups) {
                        if (itemMarkup != null && itemMarkup.isPartOfSearchResult()) {
                            if (StringUtils.isNotEmpty(itemMarkup.getSearchResultExpression())) {
                                gen.writeStringField(itemMarkup.getName(),
                                                     parseExpression(itemMarkup.getSearchResultExpression(), new ExpressionContext(bean)));
                            } else {
                                try {
                                    provider.defaultSerializeField(itemMarkup.getName(), PropertyUtils.getProperty(bean, itemMarkup.getName()), gen);
                                } catch (IllegalAccessException | InvocationTargetException | NoSuchMethodException nsmex) {
                                    LOG.warn(nsmex.getMessage());
                                }
                            }
                        }
                    }
                    gen.writeEndObject();
                } else {
                    serializer.unwrappingSerializer(null).serialize(bean, gen, provider);
                }
            } else {
                serializer.unwrappingSerializer(null).serialize(bean, gen, provider);
            }
        }

        @Override
        public boolean isUnwrappingSerializer() {
            return true;
        }
    }
````

Notice I have overriden the `isUnwrappingSerializer()` method to return true. But now I get this exception:
````
java.lang.ClassCastException: com.nemesis.platform.module.restservices.core.jackson.MarkupAwareSerializerModifier$MarkupAwareStandardSerializer cannot be cast to com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanSerializer
	at com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter._findAndAddDynamic(UnwrappingBeanPropertyWriter.java:214)
	at com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter.serializeAsField(UnwrappingBeanPropertyWriter.java:102)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.SerializerProvider.defaultSerializeValue(SerializerProvider.java:1033)
	at org.springframework.data.rest.webmvc.json.PersistentEntityJackson2Module$PersistentEntityResourceSerializer.serialize(PersistentEntityJackson2Module.java:202)
	at org.springframework.data.rest.webmvc.json.PersistentEntityJackson2Module$PersistentEntityResourceSerializer.serialize(PersistentEntityJackson2Module.java:150)
````

And indeed here:
https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/impl/UnwrappingBeanPropertyWriter.java#L212

you are trying to cast the serializer to `UnwrappingBeanSerializer` which I don't think is correct.

**Comment by ptahchiev** [comment]
After checking if the serializer is of this type seems to fix it:
```
        if (serializer.isUnwrappingSerializer() && serializer instanceof UnwrappingBeanSerializer) {
            t = NameTransformer.chainedTransformer(t, ((UnwrappingBeanSerializer) serializer)._nameTransformer);
        }
```

**Comment by cowtowncoder** [comment]
@ptahchiev Thank you for reporting this! I'll have a quick look and hopefully verify your fix. Or, remember why cast was thought to be necessary.

**Comment by ptahchiev** [comment]
@cowtowncoder Thank you for your fix. Do you know any estimated ETA for the next release?

**Comment by ptahchiev** [comment]
Oh crap.. I tried the 2.9.6 release and I now I get:
````
java.lang.ClassCastException: com.nemesis.platform.module.restservices.core.jackson.MarkupAwareSerializerModifier$MarkupAwareStandardSerializer cannot be cast to com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanSerializer
	at com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter._findAndAddDynamic(UnwrappingBeanPropertyWriter.java:217)
	at com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter.serializeAsField(UnwrappingBeanPropertyWriter.java:102)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.SerializerProvider.defaultSerializeValue(SerializerProvider.java:1033)
	at org.springframework.data.rest.webmvc.json.PersistentEntityJackson2Module$PersistentEntityResourceSerializer.serialize(PersistentEntityJackson2Module.java:202)
	at org.springframework.data.rest.webmvc.json.PersistentEntityJackson2Module$PersistentEntityResourceSerializer.serialize(PersistentEntityJackson2Module.java:15
````
@cowtowncoder  can you please reopen this issue?

**Comment by cowtowncoder** [comment]
Sigh. This is the reason why I usually insist on unit tests before fixing.
My bad, I should have noticed the other place (plus line number was indicated originally).

**Comment by ptahchiev** [comment]
Hi @cowtowncoder when do you plan the 2.9.7 release?

**Comment by cowtowncoder** [comment]
@ptahchiev Since 2.9.6 was just released, probably 2-3 months from now at least.
