### ISSUE TITLE
Using `ObjectReader.withValueToUpdate()` with JsonPOJOBuilder no longer working

### ISSUE THREAD

**Issue by ltalal** [FasterXML/jackson-databind#2100]
I need to merge existing object which uses JsonPOJOBuilder with properties from json. 
In 2.8.6 it was possible by passing builder object to withValueToUpdate method:
```
@JsonDeserialize(builder = POJO.Builder.class)
class POJO {    
    public final int id;
    public final String value;
    public POJO(int id, String value) {
        this.id = id;
        this.value = value;
    }
    @JsonPOJOBuilder
    static class Builder {
        int id;
        String value;
        public Builder withId(int id) {
            this.id = id;
            return this;
        }        
        public Builder withValue(String value) {
            this.value = value;
            return this;
        }        
        public POJO build() { 
            return new POJO(id, value);
        }
    }
}
//This code works with 2.8.6:
        POJO.Builder builder = new POJO.Builder().withId(1).withValue("1");
        new ObjectMapper().readerFor(POJO.class).withValueToUpdate(builder).readValue("{\"value\":\"2\"}");
        Assert.assertEquals(1, builder.id);
        Assert.assertEquals("2", builder.value);
```
After upgrading to 2.9.6 code above fails with
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Deserialization of [simple type, class one.cloud.master.POJO] by passing existing Builder (one.cloud.master.POJO$Builder) instance not supported
 at [Source: (String)"{"value":"2"}"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1451)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:238)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1613)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1219)
```
Other combinations I've tried without success:
```
//Passing builder object (doesn't work)
        new ObjectMapper().readerFor(POJO.Builder.class).withValueToUpdate(builder).readValue("{\"value\":\"2\"}");
//Passing instance of class with declared builder (doesn't work)
        new ObjectMapper().readerFor(POJO.class).withValueToUpdate(new POJO(1, "1")).readValue("{\"value\":\"2\"}");
```
Obvious solution is to remove builder and add setters to POJO. But I want keep class immutable. I think withValueToUpdate should be allowed to work with builders or instances of classes with builders.

**Comment by cowtowncoder** [comment]
Fixed in 3.x for 3.2.0.
