### ISSUE TITLE
Allow coercion of '[ ]' into empty/null String

### ISSUE THREAD

**Issue by ulfandersson** [FasterXML/jackson-databind#2124]
I'm using an API which uses [] as null, therefore I'm using `DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT`.

Sometimes arrays can contain null as well, giving a structure like this example:

```
{
    "test" : [
        "hello",
        []
    ]
}
```

Jackson fails to parse this when trying to parse it to a List\<String\> or String[].

Stack trace for the List\<String\> case:

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
 at [Source: (String)"{"test":["hello",[]]}"; line: 1, column: 18] (through reference chain: AcceptEmptyArrayAsNullObject$StringListTest["test"]->java.util.ArrayList[1])

	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1138)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1092)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:569)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:203)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:169)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:21)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
```

Stack trace for the String[] case:
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
 at [Source: (String)"{"test":["hello",[]]}"; line: 1, column: 18] (through reference chain: AcceptEmptyArrayAsNullObject$StringArrayTest["test"]->java.lang.Object[][1])

	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1138)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1092)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:569)
	at com.fasterxml.jackson.databind.deser.std.StringArrayDeserializer.deserialize(StringArrayDeserializer.java:157)
	at com.fasterxml.jackson.databind.deser.std.StringArrayDeserializer.deserialize(StringArrayDeserializer.java:21)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
```

However, the following _works_ when parsed to List\<Integer\> or Integer[]:
```
{
    "test" : [
        1,
        []
    ]
}
```

Jackson version used: 2.9.4.

Test case for the above:
[JacksonStringArrayTest.zip](https://github.com/FasterXML/jackson-databind/files/2336747/JacksonStringArrayTest.zip)

**Comment by cowtowncoder** [comment]
This may be down to naming problem -- it should probably have been named `ACCEPT_EMPTY_ARRAY_AS_NULL_POJO`, not `_OBJECT` -- but empty Array JSON will only be considered equivalent to `null` for POJOs. And not for scalar types such as `String`s.

So, at this point this is a limitation of implementation, and there are no plans for changing this particular limitation.

I would be interested in figuring out a way forward, and part of this would be understanding why and how is empty array being used as marker. I was under impression that some languages/platforms (PHP?) used it as a marker for structured values, but did not think it would be used in place of scalar values like numbers, booleans or Strings.

**Comment by ulfandersson** [comment]
Thank you for your answer!
What confused me is that it _is_ supported for Integer objects (but perhaps this is only because the handling is similar as for POJOs)? The only case I am really interested in (except for POJOs) is for strings.

The source of the data is a couchbase database document. It's probably due to a null/empty string is somewhere converted to an empty array when storing the document.

Maybe ACCEPT_EMPTY_ARRAY_AS_NULL_STRING could be added? :)

**Comment by cowtowncoder** [comment]
Thinking about this more, I think that coercion into `null` Java `String` makes sense also. Considering this for 3.1.

That is, enabling `DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT` should allow coercion of empty JSON array (`[ ]`) into `null` for `java.lang.String` valued properties; no need to add a new feature.

**Comment by cowtowncoder** [comment]
Quick note: "CoercionConfig" system, added in 2.12.0 via #2113, adds properly configurable mechanism for doing this, see tests in `CoerceEmptyArray.java`.

**Comment by cowtowncoder** [comment]
Ok, it looks like what is specifically requested is already working: and may have been working since 2.12.0, but it is difficult to pinpoint the exact point.

But deserialization into `String` values within `List<String>` was not working so PR will address that edge case and thus this issue will be marked as fixed in 3.1.0.
