### ISSUE TITLE
Type id handling not implemented for type javax.activation.DataHandler 

### ISSUE THREAD

**Issue by RKSuri11** [FasterXML/jackson-databind#2212]
Trying to serialize " javax.activation.DataHandler". Gives below error

Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Type id handling not implemented for type javax.activation.DataHandler (by serializer of type com.fasterxml.jackson.module.jaxb.ser.DataHandlerJsonSerializer) (through reference chain: <Object> )
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:312)
	at com.fasterxml.jackson.databind.JsonSerializer.serializeWithType(JsonSerializer.java:160)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:729)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:604)
	at com.fasterxml.jackson.databind.ser.impl.TypeWrappedSerializer.serialize(TypeWrappedSerializer.java:32)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1396)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1120)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:993)
	at com.ofss.fc.infra.json.JacksonProcessor.serializeToString(JacksonProcessor.java:154)

It seems  serializeWithType(DataHandler value, JsonGenerator jgen, SerializerProvider provider, TypeSerializer typeSer) method is not overridden in DataHandlerJsonDeserializer . kindly help with same

**Comment by cowtowncoder** [comment]
Support for `DataHandler` is provided by JAXB Annotations handler, so I think issue should go:

https://github.com/FasterXML/jackson-modules-base/issues

But fundamentally someone with time would need to add bit more code in `DataHandlerJsonSerializer` to either add support.

**Comment by RKSuri11** [comment]
@cowtowncoder can we expect any changes regarding this issue coming up ?
