### ISSUE TITLE
JsonSerialize/JsonDeserialize ignored when used with mixin class

### ISSUE THREAD

**Issue by rvervaek** [FasterXML/jackson-databind#2263]
Hi,

I'm experiencing an issue with mixin classes when used with the JsonSerialize and JsonDeserialize annotations. The goal is to serialize/deserialize from/to an MeasureVal class without modifying the Measure class. So I defined a MeasureMixin class, annotated with JsonSerialize and JsonDeserialize to support this functionality. But I'm getting the following error when during serialization:

```
com.fasterxml.jackson.databind.JsonMappingException: object is not an instance of declaring class (through reference chain: be.vlaanderen.dov.imjv.integratie.unit.controller.JsonTest$Measure["importeren"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3905)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3219)
	at be.vlaanderen.dov.imjv.integratie.unit.controller.JsonTest.testMixin(JsonTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:67)
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	... 33 more
```

The following test was used to produce the problem:

```java
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import org.junit.Assert;
import org.junit.Test;
import java.io.IOException;
import java.io.Serializable;

public class MixinTest {

    public static class Measure implements Serializable {

        private String example;

        public String getExample() {
            return example;
        }

        public void setExample(String example) {
            this.example = example;
        }
    }

    public static class MeasureVal extends Measure {

        private boolean importeren;

        public boolean isImporteren() {
            return importeren;
        }

        public void setImporteren(boolean importeren) {
            this.importeren = importeren;
        }
    }

    @JsonSerialize(as = MeasureVal.class)
    @JsonDeserialize(as = MeasureVal.class)
    public static class MeasureMixin {

    }

    @Test
    public void testMixin() throws IOException {

        ObjectMapper mapper = new ObjectMapper();
        mapper.addMixIn(Measure.class, MeasureMixin.class);

        Measure measure = new Measure();
        measure.setExample("dummy");

        String json = mapper.writeValueAsString(measure);
        Assert.assertNotNull(json);

        Measure actual = mapper.readValue(json, Measure.class);
        Assert.assertTrue(actual instanceof MeasureVal);
    }
}
```

I'm using jackson-bom 2.9.8 (latest version as of today).

**Comment by cowtowncoder** [comment]
I think that before saying this is due to mix-ins, you try equivalent annotations directly on class(es) and see what happens. It seems to me that use of annotations is wrong here (although I may be missing something): specifically, you can not force a `Measure` instance to become `MeasureValue` for serialization -- type is what it is -- you can only downcast.

For deserialization upcast often makes sense: you ask for more specific target type. For serialization, not so much: type is what it is, and if a cast is attempted, that should fail.

**Comment by rvervaek** [comment]
Ok, I think you are right. The javadoc says explicitely:

> Supertype (of declared type, which itself is supertype of runtime type) to use as type when locating serializer to use.

So I'm not using the annotation correctly. My apologies.

**Comment by cowtowncoder** [comment]
@rvervaek Ok just glad this got resolved.
