### ISSUE TITLE
JsonMerge not work with constructor args

### ISSUE THREAD

**Issue by deblockt** [FasterXML/jackson-databind#2280]
JsonMerge doesn't work when it's used on constructor args.

Using something like that : 
``` java
    static class MergeablePojo {
        public String foo;
        public String bar;

        public MergeablePojo(String foo, String bar) {
            this.foo = foo;
            this.bar = bar;
        }
    }

    static class ConstructorArgsPojo {
        public MergeablePojo mergeableBean;

        @JsonCreator
        public ConstructorArgsPojo(@JsonMerge @JsonProperty("mergeableBean") MergeablePojo mergeableBean) {
            this.mergeableBean = mergeableBean;
        }
    }
```

And a test like that : 
```
ConstructorArgsPojo input = new ConstructorArgsPojo(new MergeablePojo("foo", "bar"));

        ConstructorArgsPojo result = MAPPER.setDefaultMergeable(true)
                                       .readerForUpdating(input)
                                       .readValue(aposToQuotes("{'mergeableBean': {'foo': 'newFoo'}}"));

        assertEquals("newFoo", result.mergeableBean.foo);
        assertEquals("bar", result.mergeableBean.bar);
``` 

fail with error : 
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.fasterxml.jackson.databind.deser.merge.MergeWithNullTest$MergeablePojo` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"mergeableBean": {"foo": "newFoo"}}"; line: 1, column: 20] (through reference chain: com.fasterxml.jackson.databind.deser.merge.MergeWithNullTest$ConstructorArgsPojo["mergeableBean"])

	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1452)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1028)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1297)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.CreatorProperty.deserializeAndSet(CreatorProperty.java:230)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:252)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1613)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1219)
	at com.fasterxml.jackson.databind.deser.merge.MergeWithNullTest.testBeanMergeUsingConstructors(MergeWithNullTest.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

It seem that the `JsonMerge` is ignored.  With a class like that it's work : 

``` java
    static class MergeablePojo {
        public String foo;
        public String bar;

        public MergeablePojo(String foo, String bar) {
            this.foo = foo;
            this.bar = bar;
        }
    }

    static class ConstructorArgsPojo {
        @JsonMerge
        public MergeablePojo mergeableBean;

        public ConstructorArgsPojo(MergeablePojo mergeableBean) {
            this.mergeableBean = mergeableBean;
        }
    }
```

Work with constructor args is needed for scala class definition. Using case class, clasees look like that:
``` scala
case class MergeablePojo(foo: String, bar: String)
case class ConstructorArgsPojo(@JsonMerge mergeableBean: MergeablePojo)
```

**Comment by cowtowncoder** [comment]
Thank you for reporting this, showing the fix! Wish I fully understood why merge info was not being merged properly, but for now I think fix suffices. Will be included in 2.10.0.
