### ISSUE TITLE
JsonMappingException in release build with ProGuard

### ISSUE THREAD

**Issue by johnjohndoe** [FasterXML/jackson-databind#2290]
I am stuck with a `JsonMappingException` which occurs when I compile a **`RELEASE` with ProGuard obfuscation enabled** and run [this Android app](http://github.com/johnjohndoe/Umweltzone). It does not occur when I compile and run a `DEBUG` build.

I was able to narrow the issue down to [this commit](https://github.com/johnjohndoe/Umweltzone/commit/12bfd048ce67ef058a34b1beb5edba46aba8592a) where I introduce `getFileName()` in the `ChildZone` interface being reflected on the concrete `LowEmissionZone` class.

Due to the exception in [`ContentProvider.getContent:128`](https://github.com/johnjohndoe/Umweltzone/blob/polymorphic-child-zones/Umweltzone/src/main/java/de/avpptr/umweltzone/utils/ContentProvider.java#L128) the list of circuits in [`ContentProvider.getCircuits():92`](https://github.com/johnjohndoe/Umweltzone/blob/polymorphic-child-zones/Umweltzone/src/main/java/de/avpptr/umweltzone/utils/ContentProvider.java#L92) becomes and empty array.

The current ProGuard setting can be found [here](https://github.com/johnjohndoe/Umweltzone/blob/polymorphic-child-zones/Umweltzone/proguard.cfg#L196-L220).

Here is the stacktrace which I [deobfuscated](https://developer.android.com/studio/build/shrink-code#decode-stack-trace) from the `RELEASE` build.

``` java
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input 
  at [Source: android.content.res.AssetManager$AssetInputStream@78c8e0; line: 1, column: 0]
    at com.fasterxml.jackson.databind.ObjectMapper._initForReading(Unknown Source)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(Unknown Source)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(Unknown Source)
                                                   readValue
    at de.avpptr.umweltzone.utils.ContentProvider.enforceContentUpdate(Unknown Source)
                                                  getFaqs
                                                  getAdministrativeZoneByName
                                                  getContent
                                                  getContent
                                                  getResourceId
                                                  getFilePath
                                                  lambda$getAdministrativeZoneByName$0
    at de.avpptr.umweltzone.utils.ContentProvider.enforceContentUpdate(Unknown Source)
                                                  getFaqs
                                                  getAdministrativeZoneByName
                                                  getContent
                                                  getContent
                                                  getResourceId
                                                  getFilePath
                                                  lambda$getAdministrativeZoneByName$0
    at de.avpptr.umweltzone.utils.ContentProvider.getAdministrativeZones(Unknown Source)
                                                  getCircuits
                                                  getRawResourceId
    at de.avpptr.umweltzone.map.dataconverters.ChildZonesExtensions.toCircuitViewModels(Unknown Source)
                                                                    toCircuitViewModels
                                                                    toCircuitViewModels
                                                                    toCircuitViewModel
                                                                    toLatLngList
    at de.avpptr.umweltzone.map.dataconverters.ChildZonesExtensions.toCircuitViewModels(Unknown Source)
                                                                    toCircuitViewModels
                                                                    toCircuitViewModels
                                                                    toCircuitViewModel
                                                                    toLatLngList
    at de.avpptr.umweltzone.map.MapFragment.drawPolygonOverlay(Unknown Source)
    at de.avpptr.umweltzone.map.MapFragment.getLayoutResource(Unknown Source)
                                            onAttach
                                            onCreate
                                            onCreateView
                                            zoomToBounds
                                            zoomToLocation
                                            showGooglePlayServicesErrorDialog
                                            onMapReady
                                            onRequestPermissionsResult
                                            setMyLocationActivationViewVisibility
                                            lambda$onCreate$2
                                            access$100
                                            access$400
                                            access$500
    at de.avpptr.umweltzone.map.MapFragment$1.onDrawPolygonOverlay(Unknown Source)
                                              onZoomToBounds
                                              onZoomToLocation
    at de.avpptr.umweltzone.map.MapReadyDelegate.evaluate(Unknown Source)
                                                 storeLastAdministrativeZone
    at de.avpptr.umweltzone.map.MapFragment.getLayoutResource(Unknown Source)
                                            onAttach
                                            onCreate
                                            onCreateView
                                            zoomToBounds
                                            zoomToLocation
                                            showGooglePlayServicesErrorDialog
                                            onMapReady
                                            onRequestPermissionsResult
                                            setMyLocationActivationViewVisibility
                                            lambda$onCreate$2
                                            access$100
                                            access$400
                                            access$500
    at com.google.android.gms.maps.MapView$zza$1.zza(Unknown Source)
    at com.google.android.gms.maps.internal.zzt$zza.onTransact(Unknown Source)
    at android.os.Binder.transact(Binder.java:499)
    at fv.b(:com.google.android.gms.dynamite_mapsdynamite@15090050@15.0.90 (040406-231259764):14)
    at com.google.android.gms.maps.internal.bd.a(:com.google.android.gms.dynamite_mapsdynamite@15090050@15.0.90 (040406-231259764):4)
    at com.google.maps.api.android.lib6.impl.bk.run(:com.google.android.gms.dynamite_mapsdynamite@15090050@15.0.90 (040406-231259764):4)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

# Environment
- **Jackson:** `com.fasterxml.jackson.core:jackson-databind:2.8.10`, [_Cannot update at the moment._](https://github.com/FasterXML/jackson-databind/issues/1802#issuecomment-339780320)
- **Test device:** Nexus 9, Android 7.1.1 (API level 25, Nougat)
- **ProGuard:** `net.sf.proguard:proguard-gradle:6.0.3`
- **Android Gradle plugin: [3.3.2](https://developer.android.com/studio/releases/gradle-plugin#3-3-0)

# Related
- [JacksonPolymorphicDeserialization](https://github.com/FasterXML/jackson-docs/wiki/JacksonPolymorphicDeserialization)

**Comment by johnjohndoe** [comment]
# Explaining the problem
The actual source problem of this issue is not _Jackson_. The code and resource shrinker in the Android build removes resources **not directly referenced** in code. This is the case for files in my project located in the `raw` directory. I made a change in above mentioned commit which moved the file name reference from the Java code into a JSON configuration file.
As a result some of the binary files in the `raw` directory where **shrinked down** as one could see in the console output of the `RELEASE` build:

``` bash
> Task :Umweltzone:transformClassesAndDexWithShrinkResForRelease
Removed unused resources: Binary resource data reduced from 1549KB to 1100KB: Removed 28
```

Also the error message in the stacktrace kind of tells about it .. `column: 0`:

``` java
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input 
  at [Source: android.content.res.AssetManager$AssetInputStream@78c8e0; line: 1, column: 0]
```

Another valuable tool to get insights is the APK analyzer of Android Studio which revealed that the shrinked down files were **still present** in the `raw` folder of the `RELEASE` APK. However, they were **empty**.

# One solution
To prevent the shrinking Google recommends to explicitly tell the build task to **keep** the files. Therefore, I have to put a `keep.xml` file into the `raw` folder as explained in the [documentation](https://developer.android.com/studio/build/shrink-code#keep-resources).

# Related
- [Issue #37137121: shrinkResources removing raw res being used when done via Uri](https://issuetracker.google.com/issues/37137121)

---

All the above findings have been discovered by @cketti. Big thanks for you help! :+1:
