### ISSUE TITLE
Combination of JsonUnwrapped and JsonTypeInfo(include=As.WRAPPER_OBJECT) fails

### ISSUE THREAD

**Issue by pgelinas** [FasterXML/jackson-databind#231]
I was trying to answer [this question](http://stackoverflow.com/questions/16708178/jackson-custom-deserialize/16714128?noredirect=1#comment24077839_16714128) on stackoverflow when encountering the case where `JsonUnwrapped` and `JsonTypeInfo` might work hand-in-hand to solve an issue. Basically, the OP has this class structure

``` java
class School{
  Integer id;
  String schoolName;
}

class Student{
  Integer id;
  Integer schoolId;
  String studentName;
}

public class Pair<V,K>{
   V v;
   K k;
}
```

Which normally serialize into

``` json
{
   "v":{
      "id":1,
      "schoolId":3,
      "studentName":"O. Bas"
   },
   "k":{
      "id":3,
      "schoolName":"School 3"
   }
}
```

What the OP wanted instead was that the 'v' and 'k' field name be the class name (or close enough) of the element. This sounded very much like what `JsonTypeInfo` was for, so I gave it a try. I added `JsonTypeName` on both classes and I added `JsonTypeInfo` on both fields of `Pair` (`include = As.WRAPPER_OBJECT, use = Id.NAME`). I serialize the thing and I get 

``` json
{
  "v" : {
    "student" : {
      "id" : 3,
      "schoolId" : 3,
      "studentName" : "O. Bas"
    }
  },
  "k" : {
    "school" : {
      "id" : 3,
      "schoolName" : "School 3"
    }
  }
}
```

Close enough, I just need to unwrap the thing and we're set, right? It turns out that it's not so simple. Adding `JsonUnwrapped` on `Pair`'s field yields this exception when trying to serialize:

```
Exception in thread "main" com.fasterxml.jackson.core.JsonGenerationException: Can not start an object, expecting field name
    at com.fasterxml.jackson.core.base.GeneratorBase._reportError(GeneratorBase.java:444)
    at com.fasterxml.jackson.core.json.UTF8JsonGenerator._verifyValueWrite(UTF8JsonGenerator.java:970)
    at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeStartObject(UTF8JsonGenerator.java:245)
    at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeSerializer.writeTypePrefixForObject(AsWrapperTypeSerializer.java:43)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:485)
    at com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter.serializeAsField(UnwrappingBeanPropertyWriter.java:102)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:597)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:142)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:222)
    at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:683)
    at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:534)
    at Pair.main(Pair.java:55)
```

AsWrapperTypeSerializer expects the generator to be at a value position when it writes the prefix, so it always start with a `START_OBJECT` token. It seems to me like a valid usage of JsonUnwrapped, although not all JsonTypeInfo/JsonUnwrapped combination are valid: As.EXTERNAL_PROPERTY makes no sense in this context.

---

So, serialization doesn't work, I expect deserialization to not work either. Surprise: it doesn't, but not with the same exception. It complains about an unrecognized field "student" whereas I expected something more along the line of wrong token. I investigated a bit and found out that when resolving an unwrapped property the type info isn't used. In `BeanDeserializerBase#_resolveUnwrappedProperty` line 684, the value deserializer of the property is used, but not its type deserializer. This prevents type resolution when using JsonUnwrapped. After fixing this, I expect that the type deserializer will not work either due to unwrapping.

---

Here's the resulting test case.

``` java
@JsonTypeName("school")
class School {
    Integer id;
    String schoolName;
}

@JsonTypeName("student")
class Student {
    Integer id;
    Integer schoolId;
    String studentName;
}

class Pair<K,V> {
    @JsonUnwrapped
    @JsonTypeInfo(include = As.WRAPPER_OBJECT, use = Id.NAME)
    V v;
    @JsonUnwrapped
    @JsonTypeInfo(include = As.WRAPPER_OBJECT, use = Id.NAME)
    K k;
}

@RunWith(JUnit4.class)
public class PairTest{

    @Test
    public void unwrappedWithTypeInfo() throws Exception {
        School school = new School();
        school.id = 3;
        school.schoolName = "School 3";
        Student student = new Student();
        student.id = 3;
        student.schoolId = 3;
        student.studentName = "O. Bas";
        Pair<School, Student> pair = new Pair<School, Student>();
        pair.k = school;
        pair.v = student;
        ObjectMapper mapper = new ObjectMapper();
        mapper.registerSubtypes(Student.class, School.class);
        mapper.setVisibility(PropertyAccessor.FIELD, Visibility.ANY);
        byte[] result = mapper.writeValueAsBytes(pair);
        Pair<School,Student> pair2 = mapper.readValue(result, Pair.class);
    }
}
```

**Comment by dsinghvi** [comment]
@pgelinas  howdid you get around this issue?
