### ISSUE TITLE
JsonCreator deserialization fails to apply deserializers and coercion

### ISSUE THREAD

**Issue by carterkozak** [FasterXML/jackson-databind#2318]
Given a simple alias type, I would expect it to be handled identically to using `long` directly.

```java
public final class AliasToLong {
    private final long longValue;

    private AliasToLong(long longValue) {
        this.longValue = longValue;
    }

    @JsonValue
    public long get() {
        return longValue;
    }

    @JsonCreator
    public static AliasToLong of(long value) {
        return new AliasToLong(value);
    }
}
```

However custom deserializers for `long` and `Long` are ignored, as well as the coercion preferences.

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `AliasToLong` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('123')
 at [Source: (String)""123""; line: 1, column: 1]

	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1032)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:323)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1373)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:171)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
```

**Comment by carterkozak** [comment]
Failing test: https://github.com/FasterXML/jackson-databind/pull/2319

**Comment by cowtowncoder** [comment]
Thank you for reporting this. I hope to have a look soon.

**Comment by cowtowncoder** [comment]
Hmmh. I'd actually have to say that this is not supported usage, since what test does (but not quite reflected in description) is that input is NOT `long` value but JSON String.
The problem then is that whereas there is coercion for direct `long` and `Long` (there is debate as to whether this should be enabled  by default but that aside) target properties, but such coercion will not be applied to `@JsonCreator`. This because mapping to single-argument creators only maps JSON Integer numbers to `int`/`long` (and wrappers), JSON Strings to Java `String`, and JSON Boolean to `boolean`/`Boolean`.

You could change the creator to something like

```

**Comment by carterkozak** [comment]
That's fair, based on the usage examples it looks like `@JsonCreator` is meant to be used as a replacement for a custom deserializer rather than a lenient deserializer. It would be difficult to provide the behavior I expected as well as custom deserialization logic based on the node type for the example where a string node and a numeric node produce different values.

Thanks for taking a look, it's reasonable to close this out as I misunderstood the feature. It may be worthwhile to explain the expected behavior in documentation.
