### ISSUE TITLE
@JsonProperty causing the parent class serializer to be used

### ISSUE THREAD

**Issue by marcv711** [FasterXML/jackson-databind#2346]
Starting at version 2.9.2 the serializer of the parent class method with the same name as the @JsonProperty is used. This happens regardless of if the @JsonSerialize value is set on the subclass method. There should be a way to override this and ignore the parent class serializer.

Example of the sub class:

```
public class SubClassEntity extends AbstractEntity {

    @JsonView(SubClassEntity.class)
    @JsonProperty("user")
    @JsonSerialize(using = UserSubClassEntitySerialzer.class)
    public Entity getSubClassUser() {
        return super.getEntity();
    }

    @JsonView(SubClassEntity.class)
    @JsonProperty("userAlternative")
    public UserEntity getSubClassUserAlternative() {
        final User user = super.getUserAlternative();
        return null != user ? new UserEntity(user) : null;
    }
}
```
Example of the parent class
```
public class AbstractEntity {

        protected final Entity entity;

    public AbstractEntity (final Entity entity) {
        this.entity = entity;
    }

    public Entity getEntity() {
        return this.entity;
    }

    @JsonView(Object.class)
    @JsonSerialize(using = UserInfoSerializer.class)
    public User getUser() {
        return this.entity.getUser();
    }

    @JsonView(Object.class)
    @JsonSerialize(using = UserInfoSerializer.class)
    public User getUserAlternative() {
        return this.entity.getUserAlternative();
    }
}
```
The UserSubClassEntitySerialzer
```
public class UserSubClassEntitySerialzer extends JsonSerializer<Entity> {

does stuff

}
```
The UserInfoSerializer
```
public class UserInfoSerializer extends JsonSerializer<User> {

does stuff

}
```
When we attempt to serialize the subclass the JsonSerializer set on the parent class of the name found in the JsonProperty is being used regardless of if one is set in the subclass. This cause a ClassCastException:
```
com.fasterxml.jackson.databind.JsonMappingException: package.UserEntity cannot be cast to package.User(through reference chain: package.SubClassEntity["userAlternative"])
```
and
```
com.fasterxml.jackson.databind.JsonMappingException: package.Entity cannot be cast to package.User(through reference chain: package.SubClassEntity["user"])
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
    at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
    at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1396)
    at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1120)
    at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:993)
```

**Comment by cowtowncoder** [comment]
I would need a full unit test to show this: there has been no intended change in behavior in version `2.9.2`; none of listed fixes seems like obvious root cause.

However: note that annotations are fully expected to be inheritable, matching method names, so sub-class definitions should override super-class ones... but with renaming things get complicated, and much depends on exact order of resolution.

So I would also argue that such usage is inherently fragile and if anyone had asked where to try to use this combination of features I would have said "absolute not!" -- definitions seem to rely on fine balance between renaming and overrides of custom handlers, something that is difficult to reason about.
So while change is not intentional it is quite possible that usage as shown is not even supported.
