### ISSUE TITLE
UNWRAP_ROOT_VALUE causes bug when using `JsonParser.readValueAsTree()` in deserializer

### ISSUE THREAD

**Issue by OndraZizka** [FasterXML/jackson-databind#2351]
Jackson 2.9.9, with `UNWRAP_ROOT_VALUE` enabled.

With a JSON `{ "Foo": { "Bar": { ... } } }`, I deserialize `Foo` with a `StdDeserializer` override.

First I read "Bar" with `parser.nextFieldName(new SerializedString("Bar"))`. That works.

Then I want to read the tree:

    TreeNode tree = parser.readValueAsTree();

And here it fails, because it internally deserializes to `JsonNode` and it wants to UNWRAP_ROOT_VALUE, so it looks for a field `"JsonNode": ...` which naturally is not there.

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Root name 'Value' does not match expected ('JsonNode') for type [simple type, class com.fasterxml.jackson.databind.JsonNode]
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 19]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1356)
	at com.fasterxml.jackson.databind.ObjectMapper._unwrapAndDeserialize(ObjectMapper.java:4087)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3982)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2384)
	at com.fasterxml.jackson.core.JsonParser.readValueAsTree(JsonParser.java:1782)
```

This is a bit related to #1022. Maybe the way how the (lack of) root name, resp. `@JsonRootName`, is stored and propagated should be more independent from the actual `PropertyName`s?

This is not critical as there's a way around it, but it's super annoying as I need to parse the whole deep tree token by token :)

**Comment by cowtowncoder** [comment]
Could you provide complete code to reproduce the issue? 

`readTree()` (and related) should ignore `UNWRAP_ROOT_VALUE` completely: Tree Model is expected to be exact unmodified representation of the content, so no failure should occur. I think.

**Comment by cowtowncoder** [comment]
Ok: I think that although this is annoying, it is difficult to change as the contract is for unwrap to be used via that call.

However: a better way to go would be to call `DeserializationContext.readValue(JsonParser, Class)` to read tree content, so I think I will close this for now.
