### ISSUE TITLE
annotating @JsonUnwrapped field with @NonNull throws JsonMappingException during deserialization

### ISSUE THREAD

**Issue by rpmcginty** [FasterXML/jackson-databind#2370]
I am having trouble deserializing data classes with fields that have `@JsonUnwrapped` and `@NonNull` annotations. When the `@NonNull` annotation is present, I receive a JacksonMappingException. If I remove the annotation, everything works fine, but I don't want that, as the field should not be null. 

After debugging, I can see that the JsonUnwrapped field is initially injected with a `null` value, which is what causes the issue. I'm not sure what can be done to avoid this. 

Using following packages
* Jackson-databind-2.8.x
* Lombok-1.16.x

#### Inner.class
```java
@Data
@Builder
public final class Inner {
    @JsonProperty("A")
    @NonNull private final String a;
}
```

#### Outer.class
```java
@Data
@Builder
public final class Outer {
    @JsonProperty("inner")
    @JsonUnwrapped
    @NonNull private Inner inner;
}
```

#### Outer JSON Object
```json
{
  "A": "z"
}
``` 

#### Serialization Test Case that passes
```java
@Test
public void serializePasses() {
    ObjectMapper objectMapper = new ObjectMapper();
    Map<String, String> expectedMap = new HashMap<>();
    expectedMap.put("A", "z");
    Outer outer = Outer.builder().inner(Inner.builder().a("z").build()).build();

    Map<String, String> returnedMap = objectMapper.convertValue(outer, new TypeReference<Map<String, Object>>() {});
    assertEquals(expectedMap, returnedMap); 
}

```

#### Deserialization Test Case that fails
```java
@Test
public void deserializeFailsWithFlattenedMap() {
    ObjectMapper objectMapper = new ObjectMapper();
    Map<String, String> map = new HashMap<>();
    map.put("A", "z");
    objectMapper.convertValue(map, Outer.class);
}
```

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of Outer, problem: inner
 at [Source: N/A; line: -1, column: -1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:277)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1454)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:485)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:504)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:286)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeUsingPropertyBasedWithUnwrapped(BeanDeserializer.java:814)
```

**Comment by cowtowncoder** [comment]
Would it be possible to add post-processed class definitions, to avoid needing a dependency to Lombok, and simplify troubleshooting?
(Lombok not allowed even as a test dependency since it requires addition of a component in classpath, as I recall -- so Jackson should work with Lombok-enabled POJOs, but can't use it as processor)
