### ISSUE TITLE
Type coercion to integer fails for quoted values

### ISSUE THREAD

**Issue by shmosel** [FasterXML/jackson-databind#2375]
I can convert a decimal value to int, or a quoted string to int, but it fails if a decimal value is in quotes.

Demo:
```java
ObjectMapper mapper = new ObjectMapper();
System.out.println(mapper.readValue("1.0", int.class));
System.out.println(mapper.readValue("\"1\"", int.class));
System.out.println(mapper.readValue("\"1.0\"", int.class));
```

Output:
```
1
1
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `int` from String "1.0": not a valid Integer value
 at [Source: "1.0"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1549)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:911)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer._parseInteger(NumberDeserializers.java:522)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:474)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:452)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
```

I'm using version 2.9.9.

**Comment by cowtowncoder** [comment]
Yes, there is only direct conversion from String to specific type, no additional coercion is supported.
At this point this is established behavior and there are no plans to add further automatic conversions.
You may want to use custom deserializer instead to support more advanced matching.

**Comment by cowtowncoder** [comment]
I think that I will formalize this as "only single coercion to reach result type" rule.
