### ISSUE TITLE
Generic Types not properly infered if JsonCreator's generic name is different from that of the class'es generic name

### ISSUE THREAD

**Issue by franz-see** [FasterXML/jackson-databind#2384]
jackson-databind v2.9.9.1

If you use a `@JsonCreator` on a method whose generic name is the same as that of the class, then it works. If the generic name is different, then it fails to solve it. 

Meaning, this works

```
    class JsonCreatorStaticMethod<T> {
        T data;

        ...

        @JsonCreator
        static <T> JsonCreatorStaticMethod<T> of(@JsonProperty("data") T data) {
            return new JsonCreatorStaticMethod<>(data);
        }
    }

```

While this fails

```
    class JsonCreatorStaticMethod<T> {
        T data;

        ...

        @JsonCreator
        static <T2> JsonCreatorStaticMethod<T2> of(@JsonProperty("data") T2 data) {
            return new JsonCreatorStaticMethod<>(data);
        }
    }
```

Note: The only difference is the generic's name

Full test recreating the issue

```
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class StaticCreatorOfDifferentGenericNameTest {

    @Test
    public void jsonCreatorStaticMethod() throws IOException {
        ObjectMapper mapper = new ObjectMapper();

        String json = "{\"data\":{\"name\":\"dummy value\"}}";

        JsonCreatorStaticMethod<Dummy> result = mapper.readValue(json, new TypeReference<JsonCreatorStaticMethod<Dummy>>() {
        });
        assertEquals(Dummy.class, result.getData().getClass());
    }

    static class JsonCreatorStaticMethod<T> {
        T data;

        public JsonCreatorStaticMethod(T data) {
            this.data = data;
        }

        public T getData() {
            return data;
        }

        public void setData(T data) {
            this.data = data;
        }

        @JsonCreator
        static <T2> JsonCreatorStaticMethod<T2> of(@JsonProperty("data") T2 data) {
            return new JsonCreatorStaticMethod<>(data);
        }
    }

    static class Dummy {
        private String name;

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }
    }
}

```

This test results to a 

```
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to StaticCreatorOfDifferentGenericNameTest$Dummy

	at StaticCreatorOfDifferentGenericNameTest.jsonCreatorStaticMethod(StaticCreatorOfDifferentGenericNameTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:105)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
```

**Comment by cowtowncoder** [comment]
Thank you for reporting this, and especially including reproduction.

**Comment by cowtowncoder** [comment]
Ah. Ok, read through the sample case and unfortunately this works as expected: due to Java Type Erasure I do not think this can be made to work as you would expect.

The problem here is this: it's not a matter of type variable naming, but bounds -- `T` is declared for type itself, and is available ultimately via `TypeReference` you give. But `T2` is variable that would only be available to compiler, at compile time: all Jackson can (and does) see is that it's "at least java.lang.Object". As such, databind passes "untyped" value (so JSON is bounds as Maps, Lists, Numbers etc).

I am not sure what the goal here is, actually, but as presented `T2` does not really mean anything and thus can not be used: signature has same behavior as if it was written:

```
       @JsonCreator
       static JsonCreatorStaticMethod<?> of(@JsonProperty("data") Object data) {
```
