### ISSUE TITLE
JsonMappingException: Could not find creator property with name '...'

### ISSUE THREAD

**Issue by cheddar** [FasterXML/jackson-databind#241]
Exception thrown when trying to convertValue().

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Could not find creator property with name 'service' (in class com.metamx.druid.initialization.DruidNodeConfig)
 at [Source: N/A; line: -1, column: -1]
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
    at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:608)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:551)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:267)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:171)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:388)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
    at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:143)
    at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:342)
    at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:2895)
    at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:2511)
```

Code for the class being deserialized is

``` java
/*
 * Druid - a distributed column store.
 * Copyright (C) 2012, 2013  Metamarkets Group Inc.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

package com.metamx.druid.initialization;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.metamx.druid.utils.SocketUtil;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 */
public abstract class DruidNodeConfig
{
  @NotNull
  private String serviceName = null;

  @NotNull
  private String host = null;

  @Min(0) @Max(0xffff)
  private int port = -1;

  @JsonCreator
  public DruidNodeConfig(
      @JsonProperty("service") String serviceName,
      @JsonProperty("host") String host,
      @JsonProperty("port") Integer port
  )
  {
    this.serviceName = serviceName;

    if (port == null) {
      if (host == null) {
        setHostAndPort(null, -1);
      }
      else if (host.contains(":")) {
        try {
          setHostAndPort(host, Integer.parseInt(host.split(":")[1]));
        }
        catch (Exception e) {
          setHostAndPort(host, -1);
        }
      }
      else {
        final int openPort = SocketUtil.findOpenPort(8080);
        setHostAndPort(String.format("%s:%d", host, openPort), openPort);
      }
    }
    else {
      if (host == null || host.contains(":")) {
        setHostAndPort(host, port);
      }
      else {
        setHostAndPort(String.format("%s:%d", host, port), port);
      }
    }
  }

  private void setHostAndPort(String host, int port)
  {
    this.host = host;
    this.port = port;
  }

  @JsonProperty("service")
  public String getServiceName()
  {
    return serviceName;
  }

  @JsonProperty
  public String getHost()
  {
    return host;
  }

  @JsonProperty
  public int getPort()
  {
    return port;
  }
}
```

**Comment by adityaksflipkart** [comment]
Facing the same issue while using jsoncreator (JsonMappingException: Could not find creator property with name)

@Data
public  class AgentRequest<T extends RequestDTO> extends AllocationRequest {

    @JsonCreator
    public AgentRequest(@JsonProperty(value = "entityType") String entityType, @JsonProperty("allocationGroup") String allocationGroup) {
        super(entityType,AllocationGroup);
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXTERNAL_PROPERTY, property = "entityType",visible = true)
    @JsonTypeIdResolver(value=RequestDTOTypeResolver.class)
    private T entityData;
    public T getEntityData() {
        return entityData;
    }
    public void setEntityData(T entityData) {
        this.entityData = entityData;
    }
}

**Comment by cowtowncoder** [comment]
@adityaksflipkart Please do not add notes on closed issues -- if you have problem with reproduction, file a new issue, along with version information.
