### ISSUE TITLE
NoClassDefFound errors when upgrading to version-2.10.0.pr2

### ISSUE THREAD

**Issue by oswaldquek** [FasterXML/jackson-databind#2439]
This upgrade seems to cause
```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/TSFBuilder

	at io.dropwizard.configuration.YamlConfigurationFactory.<init>(YamlConfigurationFactory.java:29)
	at io.dropwizard.configuration.DefaultConfigurationFactoryFactory.create(DefaultConfigurationFactoryFactory.java:18)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:124)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
	at io.dropwizard.testing.DropwizardTestSupport.startIfRequired(DropwizardTestSupport.java:237)
	at io.dropwizard.testing.DropwizardTestSupport.before(DropwizardTestSupport.java:151)
	at io.dropwizard.testing.junit.DropwizardAppRule.before(DropwizardAppRule.java:159)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.github.tomakehurst.wiremock.junit.WireMockClassRule$1.evaluate(WireMockClassRule.java:70)
	at com.github.tomakehurst.wiremock.junit.WireMockClassRule$1.evaluate(WireMockClassRule.java:70)
	at com.github.tomakehurst.wiremock.junit.WireMockClassRule$1.evaluate(WireMockClassRule.java:70)
	at com.github.tomakehurst.wiremock.junit.WireMockClassRule$1.evaluate(WireMockClassRule.java:70)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.TSFBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 28 more
```

**Comment by cowtowncoder** [comment]
I would first verify that version of `jackson-core` you have is `2.10.0.pr2` and not earlier 2.x.

**Comment by oswaldquek** [comment]
yes, you're right. that resolves my issue. thanks.

**Comment by cowtowncoder** [comment]
Ok good! Thank you for following up on this.

**Comment by ClementBareth** [comment]
@cowtowncoder Hello,

I'm using version 2.10.0 and I'm facing the same issue. Could you re-open that issue ?

**Comment by cowtowncoder** [comment]
@ClementBareth This is not something Jackson project can do much about it so I don't think reopening makes much sense. You need to figure out why you have old version(s) of `jackson-core` in classpath.

**Comment by jclarkk** [comment]
@cowtowncoder 
I was able to reproduce this issue in Jackson 2.10.0:

Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/TSFBuilder
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:122)
	at com.azure.core.implementation.serializer.jackson.JacksonAdapter.<init>(JacksonAdapter.java:75)
	at com.azure.core.implementation.serializer.jackson.JacksonAdapter.createDefaultSerializerAdapter(JacksonAdapter.java:108)

azure-core uses Jackson 2.10.0

**Comment by cowtowncoder** [comment]
@jclarkk You have a version incompatibility of some kind: `jackson-core` version is earlier than 2.10.

**Comment by unscrew** [comment]
Which version of `jackson-core` does not cause the issue?
