### ISSUE TITLE
Throw Unknown constant pool tag when upgrade to 2.10.0

### ISSUE THREAD

**Issue by melody792** [FasterXML/jackson-databind#2512]
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unknown constant pool tag [I@d105805e in classfile module-info.class (element size unknown, cannot continue reading class. Please report this on the FastClasspathScanner GitHub page.
	at io.github.lukehutch.fastclasspathscanner.utils.InterruptionChecker.executionException(InterruptionChecker.java:74)
	at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.runWorkLoop(WorkQueue.java:142)
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:347)
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:52)
	Suppressed: java.lang.RuntimeException: Called close() before completing all work units
		at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.close(WorkQueue.java:194)
		at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:348)
		at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:52)
		at java.util.concurrent.FutureTask.run(FutureTask.java:277)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.lang.Thread.run(Thread.java:818)
	Suppressed: java.lang.RuntimeException: Unreleased instances: 1
		at io.github.lukehutch.fastclasspathscanner.utils.Recycler.close(Recycler.java:69)
		at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:348)
		at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:52)
		at java.util.concurrent.FutureTask.run(FutureTask.java:277)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.RuntimeException: Unknown constant pool tag [I@d105805e in classfile module-info.class (element size unknown, cannot continue reading class. Please report this on the FastClasspathScanner GitHub page.
	at io.github.lukehutch.fastclasspathscanner.scanner.ClassfileBinaryParser.readClassInfoFromClassfileHeader(ClassfileBinaryParser.java:561)
	at io.github.lukehutch.fastclasspathscanner.scanner.ClasspathElementZip.openInputStreamAndParseClassfile(ClasspathElementZip.java:306)
	at io.github.lukehutch.fastclasspathscanner.scanner.ClasspathElement.parseClassfiles(ClasspathElement.java:335)
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner$3.processWorkUnit(Scanner.java:337)
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner$3.processWorkUnit(Scanner.java:331)
	at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.runWorkLoop(WorkQueue.java:133)
	... 2 more

**Comment by cowtowncoder** [comment]
@melody792 Perhaps caused by this:

https://github.com/classgraph/classgraph/issues/141

which suggests upgrade to 2.6.1 or later of `classgraph`.

**Comment by melody792** [comment]
@cowtowncoder Thanks for your information
