### ISSUE TITLE
java.lang.NoClassDefFoundError Thrown for compact profile1

### ISSUE THREAD

**Issue by Jon901** [FasterXML/jackson-databind#2544]
Jackson version - 2.9.9.1
```
Exception in thread "DBus Worker Thread-3" java.lang.NoClassDefFoundError: org/w3c/dom/Node
        at com.fasterxml.jackson.databind.ext.OptionalHandlerFactory.<clinit>(OptionalHandlerFactory.java:52)
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findOptionalStdDeserializer(BasicDeserializerFactory.java:1616)
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findDefaultDeserializer(BasicDeserializerFactory.java:1839)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.findStdDeserializer(BeanDeserializerFactory.java:161)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:125)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
        at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4191)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4010)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3005)

```
In OptionalHandlerFactory an assumption is made that DOM classes are always found and this is not true for embedded environments.(compact profile1)
```java
    static {
        Class<?> doc = null, node = null;
        try {
            node = org.w3c.dom.Node.class;
            doc = org.w3c.dom.Document.class;
        } catch (Exception e) {
            // not optimal but will do
            Logger.getLogger(OptionalHandlerFactory.class.getName())
                .log(Level.INFO, "Could not load DOM `Node` and/or `Document` classes: no DOM support");
        }
        CLASS_DOM_NODE = node;
        CLASS_DOM_DOCUMENT = doc;
    }
```
In NoClassDefFoundError is an Error not an Exception (NoClassNotFoundException).

Is there a workaround to disable the checking of optional handlers on embedded environments?

**Comment by cowtowncoder** [comment]
Looks like ode needs to catch `Throwable` instead of `Exception`.
No, there is no separate setting as catch block is supposed to cover the case you are observing: unfortunately it is difficult to test on regular JVMs.
