### ISSUE TITLE
ClassCastException on deserialization of spring jms GenericMessage

### ISSUE THREAD

**Issue by maybeec** [FasterXML/jackson-databind#2545]
Hi there,

I already put some effort in debugging the following exception:

```
Caused by: java.lang.ClassCastException: org.springframework.messaging.support.GenericMessage cannot be cast to com.fasterxml.jackson.databind.JsonNode
	at com.fasterxml.jackson.databind.deser.std.StdNodeBasedDeserializer.deserializeWithType(StdNodeBasedDeserializer.java:84)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3042)
	at org.springframework.jms.support.converter.MappingJackson2MessageConverter.convertFromTextMessage(MappingJackson2MessageConverter.java:385)
	at org.springframework.jms.support.converter.MappingJackson2MessageConverter.convertToObject(MappingJackson2MessageConverter.java:363)
	at org.springframework.jms.support.converter.MappingJackson2MessageConverter.fromMessage(MappingJackson2MessageConverter.java:232)
	at org.springframework.jms.core.JmsTemplate.doConvertFromMessage(JmsTemplate.java:859)
	at org.springframework.jms.core.JmsTemplate.receiveAndConvert(JmsTemplate.java:817)
	at org.springframework.integration.jms.PollableJmsChannel.receive(PollableJmsChannel.java:110)
	at org.springframework.integration.jms.PollableJmsChannel.receive(PollableJmsChannel.java:83)
	at org.springframework.integration.endpoint.PollingConsumer.receiveMessage(PollingConsumer.java:203)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:360)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:329)
	... 14 more
```

**Context**:
I am using spring integration with a JMS queue. I can see the message correctly been written to the database and interestingly the data is also correctly deserialized until https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/deser/std/StdNodeBasedDeserializer.java#L77 where it results in the classCastException shown above.

I am using the following mapper configuration: 

```java
@Bean
  public MessageConverter jacksonJmsMessageConverter() {
    MappingJackson2MessageConverter converter = new MappingJackson2MessageConverter();
    converter.setTargetType(MessageType.TEXT);
    converter.setTypeIdPropertyName("_type");
    ObjectMapper objectMapper = JacksonJsonUtils.messagingAwareMapper("com.github.maybeec");
    // objectMapper.enable(DeserializationFeature.UNWRAP_ROOT_VALUE);
    converter.setObjectMapper(objectMapper);
    return converter;
  }
```
```java
@Bean(name = JMSEmailNotificationConsumer.EMAIL_QUEUE)
  public MessageChannel emailQueue(QueueConnectionFactory jmsConnectionFactory) {

    return Jms.pollableChannel(JMSEmailNotificationConsumer.EMAIL_QUEUE, jmsConnectionFactory)
        .datatype(JMSEmailTo.class).messageConverter(jacksonMessageConverter())
        .jmsMessageConverter(jacksonJmsMessageConverter()).datatype(JMSEmailTo.class).deliveryPersistent(true)
        .destination(JMSEmailNotificationConsumer.EMAIL_QUEUE).get();
  }
```
```java
@Bean
  public JmsTemplate jmsTemplate(QueueConnectionFactory jmsConnectionFactory) throws Exception {
    JmsTemplate jmsTemplate = new JmsTemplate();
    jmsTemplate.setConnectionFactory(jmsConnectionFactory);
    jmsTemplate.setMessageConverter(jacksonJmsMessageConverter());
    jmsTemplate.setPubSubDomain(false);
    jmsTemplate.setDeliveryPersistent(true);
    return jmsTemplate;
  }
```

**Product Versions:**
I am using Spring Integration 5.1.6.RELEASE with the managed version of spring of jackson-databind: 2.9.9. 

**Trials so far:** 
* I tried upgrading to the latest jackson-databind 2.10.1, which did not made any difference
* I tried enabling `UNWRAP_ROOT_VALUE` feature without any success. In that case I got 
```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Root name '@class' does not match expected ('GenericMessage') for type [simple type, class org.springframework.messaging.support.GenericMessage]
 at [Source: (String)"{"@class":"org.springframework.messaging.support.GenericMessage","payload":{"@class":"com.kn.fn.fia.emailadapter.logic.impl.jmsadapter.to.JMSEmailTo","from":"malte.brunnlieb@capgemini.com","to":"malte.brunnlieb@capgemini.com","cc":"malte.brunnlieb@capgemini.com","bcc":null,"replyTo":"malte.brunnlieb@capgemini.com","sentDate":"Thu Nov 21 22:34:58 CET 2019","subject":"                    Quote 111 from SINGAPORE to tokyo \r\n","text":"<!DOCTYPE html> \r\n     <html> \r\n      <head> \r\n      <sty"[truncated 6974 chars]; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1356)
	at com.fasterxml.jackson.databind.ObjectMapper._unwrapAndDeserialize(ObjectMapper.java:4087)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4011)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3042)
	at org.springframework.jms.support.converter.MappingJackson2MessageConverter.convertFromTextMessage(MappingJackson2MessageConverter.java:385)
	at org.springframework.jms.support.converter.MappingJackson2MessageConverter.convertToObject(MappingJackson2MessageConverter.java:363)
	at org.springframework.jms.support.converter.MappingJackson2MessageConverter.fromMessage(MappingJackson2MessageConverter.java:232)
	... 21 more
```
which is also not clear to me why the simple type is being compared with the full qualified type.

Any ideas?

**Comment by cowtowncoder** [comment]
In general, usage questions really, really should go to mailing list:

https://groups.google.com/forum/#!forum/jackson-user

(or Gitter -> https://gitter.im/FasterXML/jackson-databind)

But... to know more, I would really need a stand-alone test case that does not use Spring functionality; that is, to isolate inner-most piece.
From exception I can see that polymorphic typing is used (via `@JsonTypeInfo` or Default Typing enabled), and that would not really work with `UNWRAP_ROOT_VALUE`. But to know how polymorphic id is not found or is misused it'd be necessary to see wrapper class used.

**Comment by maybeec** [comment]
Hi @cowtowncoder, you are right, but I focused more on the idea to report a bug as it it throwing a ClassCastException at a point in code, where a comment says "Quite likely we'd have some issues but... let's try, just in case.". 

I am not using any polymorphic typing. Anyhow the GenericMessage is a parameterized type if this does make any changes. Spring is creating a default type resolver by `JacksonJsonUtils.messagingAwareMapper`. 

I will check whether I can create a minimal example. Let me check my time schedule.

**Comment by maybeec** [comment]
Please find my sample here: https://github.com/maybeec/jackson-databind-2545

**Comment by cowtowncoder** [comment]
Ok one note: although you may not be using polymorphic typing with your types, something is (maybe Spring wrapper?), since:

```
	at com.fasterxml.jackson.databind.deser.std.StdNodeBasedDeserializer.deserializeWithType(StdNodeBasedDeserializer.java:84)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68)
```

method `deserializeWithType()` gets called to handle polymorphic type id wrapping (when Type Id is expected). This makes sense if my guess on intent is correct: "Generic" in class name meaning something like "usable on any Object".

**Comment by maybeec** [comment]
> "Generic" in class name meaning something like "usable on any Object".

Yes, that's the understanding of it.

**Comment by cowtowncoder** [comment]
Ok was hoping that sample contained unit tests, but looks like it's just an app. But going back to the original stack trace, what seems to be the issue is this:

```
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3042)
	at org.springframework.jms.support.converter.MappingJackson2MessageConverter.convertFromTextMessage(MappingJackson2MessageConverter.java:385)
	at org.springframework.jms.support.converter.MappingJackson2MessageConverter.convertToObject(MappingJackson2MessageConverter.java:363)
```

that is, piece of code in a Spring converter class that tries to read some JSON into a Java value.
So what is needed is that specific piece of code (including configuration of `ObjectMapper`) and JSON input data sample. That should be enough for isolated test case.

It is quite possible that polymorphic type handling for `JsonNode` might have edge cases that are not handled well, since that is kind of... odd combination: `JsonNode` is JSON-centric abstraction that is quite different from more usual polymorphic POJOs use case.
This is not saying it shouldn't work, just that test coverage is much more shallow.

**Comment by maybeec** [comment]
You can just execute the spring boot application. Running it will directly show you the error I described.

**Comment by cowtowncoder** [comment]
Yeah I am not going to do that: I see nothing to really suggest specific problem in Jackson. What is needed is piece of code isolate out of Spring; without this my time is better spent with other issues.

**Comment by cowtowncoder** [comment]
Nothing actionable at this point; may be reopened with a reproduction that shows problem in Jackson itself, if any. Based on symptoms seems likely issue would need to be dealt with on Spring side (or application code).

**Comment by cxl98** [comment]
这个问题我也遇到了，加个参数就行了
