### ISSUE TITLE
ObjectMapper.readValue fails for `TreeSet` for byte[] (and other types that are not `Comparable`)

### ISSUE THREAD

**Issue by webbean** [FasterXML/jackson-databind#255]
We use jackson-databind-2.2.2 to serialize and deserialize NavigableSet&lt;byte[]&gt;.
Serializing works fine, but deserializing throws java.lang.ClassCastException:

```
Exception in thread "main" java.lang.ClassCastException: [B cannot be cast to java.lang.Comparable
    at java.util.TreeMap.compare(TreeMap.java:1188)
    at java.util.TreeMap.put(TreeMap.java:531)
    at java.util.TreeSet.add(TreeSet.java:255)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:234)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:207)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2120)
```

Below is the code:

```java
public static void main(String[] args) throws Exception {
    ObjectMapper mapper = new ObjectMapper();
    NavigableSet<byte[]> set = new TreeSet<>(Bytes.BYTES_COMPARATOR);
    set.add(Bytes.toBytes("ROW1"));
    set.add(Bytes.toBytes("ROW2"));
    set.add(Bytes.toBytes("ROW3"));
    byte[] array = mapper.writeValueAsBytes(set);
    NavigableSet<byte[]> result = mapper.readValue(array,
            new TypeReference<NavigableSet<byte[]>>() {
            });
    for (byte[] value : result) {
        System.out.println(Bytes.toString(value));
    }
}
```

It seems that we need provide a Comparator parameter(such as Bytes.BYTES_COMPARATOR) when we create a new TreeSet object, but how can we do that in TypeReference when deserializing by mapper.readValue method.

**Comment by cowtowncoder** [comment]
Actually I think that #1399 is a solution for this: this does require setting of initial value (and either global default for merging, or per-property annotation), but should work fine.
Will close as I do not have a better general-purpose solution in mind; custom deserializer would be next logical choice.
