### ISSUE TITLE
java.lang.NoSuchMethodError: com.fasterxml.jackson.datatype.jsr310.ser.JSR310FormattedSerializerBase.findFormatOverrides(Lcom/fasterxml/jackson/databind/SerializerProvider;Lcom/fasterxml/jackson/databind/BeanProperty;Ljava/lang/Class;)Lcom/fasterxml/jackson/annotation/JsonFormat$Value;

### ISSUE THREAD

**Issue by MacleZhou** [FasterXML/jackson-databind#2582]
**I encounter the problem on MacBook but works well on Wintel**. please help. My environment as below:

**1. MacBook + IntelliJ + SpringMVC5.1.8 + RESTful + Java8 + Tomcat + Jackson version 2.10.1(tried 2.9.x, same problem on MacBook)**

**2. My configuration is below:**
   @Configuration
public class Jackson2ObjectMapperConfig {
    private static final String DATE_FORMAT = "yyyy-MM-dd";
    private static final String DATETIME_FORMAT = "yyyy-MM-dd HH:mm:ss.SSS";
    private static final String ZONED_FORMATTER = "yyyy-MM-dd HH:mm:ss.SSSSSS Z";
    private static final String TIME_FORMAT = "HH:mm:ss";

    @Bean
    Jackson2ObjectMapperBuilder jackson2ObjectMapperBuilder() {
        JavaTimeModule javaTimeModule = new JavaTimeModule();
        javaTimeModule.addSerializer(ZonedDateTime.class, new ZonedDateTimeSerializer(DateTimeFormatter.ofPattern(ZONED_FORMATTER)));
        javaTimeModule.addSerializer(LocalDateTime.class, new LocalDateTimeSerializer(DateTimeFormatter.ofPattern(DATETIME_FORMAT)));
        javaTimeModule.addSerializer(LocalDate.class, new LocalDateSerializer(DateTimeFormatter.ofPattern(DATE_FORMAT)));
        javaTimeModule.addSerializer(LocalTime.class, new LocalTimeSerializer(DateTimeFormatter.ofPattern(TIME_FORMAT)));

        javaTimeModule.addDeserializer(LocalDateTime.class, new LocalDateTimeDeserializer(DateTimeFormatter.ofPattern(DATETIME_FORMAT)));
        javaTimeModule.addDeserializer(LocalDate.class, new LocalDateDeserializer(DateTimeFormatter.ofPattern(DATE_FORMAT)));
        javaTimeModule.addDeserializer(LocalTime.class, new LocalTimeDeserializer(DateTimeFormatter.ofPattern(TIME_FORMAT)));

        return new Jackson2ObjectMapperBuilder()
                .featuresToDisable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
                .featuresToEnable(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY)
                .findModulesViaServiceLoader(true)
                .modulesToInstall(javaTimeModule)
                .modulesToInstall(new ParameterNamesModule())
                .modulesToInstall(new Jdk8Module());
    }

    @Bean
    public ObjectMapper objectMapper(Jackson2ObjectMapperBuilder jackson2ObjectMapperBuilder) {
        ObjectMapper objectMapper = jackson2ObjectMapperBuilder.build();
        return objectMapper;
    }
}

    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        List<HttpMessageConverter<?>> messageConverters = messageConverters();
        converters.addAll(messageConverters);
    }

    @Bean
    public ExceptionHandlerExceptionResolver exceptionHandlerExceptionResolver() {
        ExceptionHandlerExceptionResolver exceptionHandlerExceptionResolver = new ExceptionHandlerExceptionResolver();
        exceptionHandlerExceptionResolver.setMessageConverters(messageConverters());

        return exceptionHandlerExceptionResolver;
    }

    private List<HttpMessageConverter<?>> messageConverters() {
        List<HttpMessageConverter<?>> messageConverters = new ArrayList<>();

        messageConverters.add(new org.springframework.http.converter.xml.Jaxb2RootElementHttpMessageConverter());
        MappingJackson2HttpMessageConverter jackson2Converter = new MappingJackson2HttpMessageConverter();
        jackson2Converter.setSupportedMediaTypes(Arrays.asList(MediaType.APPLICATION_JSON));
        jackson2Converter.setObjectMapper(objectMapper);

        messageConverters.add(jackson2Converter);

        SourceHttpMessageConverter<?> xmlMessageConverter = new SourceHttpMessageConverter<>();
        xmlMessageConverter.setSupportedMediaTypes(Arrays.asList(MediaType.APPLICATION_XML));
        messageConverters.add(xmlMessageConverter);

        return messageConverters;
    }

**3. My dto is below:**
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Data
@ApiModel(value="Response Message Info")
public class Message {
    /**
     * Message type
     * */
    @ApiModelProperty(value="message severity, SUCCESS, WARNING, FAILED, ERROR, INFO")
    private Type type;

    @ApiModelProperty(value="master message code")
    private String code;

    @ApiModelProperty(value="master message text")
    private String text;

    @ApiModelProperty(value="received time")
    private LocalDateTime receivedTime;

    @ApiModelProperty(value="completed time")
    private LocalDateTime completedTime;

    @ApiModelProperty(value="error messages")
    private List<Error> errors = new ArrayList<Error>();

**4. The error logs is below:**
From:org.springframework.web.servlet.DispatcherServlet  Content: GET "/ruleengine-application/api/ping", parameters={}
From:org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping  Content: Mapped to public org.springframework.http.ResponseEntity<com.aia.spring5.api.dto.Message> com.aia.spring5.api.controller.PingController.ping()
From:com.aia.spring5.config.mvc.intercepors.TimeInterceptor  Content: TimeInterceptor.preHandle:com.aia.spring5.api.controller.PingController
From:com.aia.spring5.config.mvc.intercepors.TimeInterceptor  Content: TimeInterceptor.preHandle:ping
From:com.aia.spring5.api.controller.PingController  Content: ping now
From:com.aia.spring5.api.controller.PingController  Content: message: Message(type=SUCCESS, code=B000, text=connected, receivedTime=2020-01-01T09:23:30.813, completedTime=2020-01-01T09:23:30.813, errors=[])
From:org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver  Content: Using @ExceptionHandler public org.springframework.http.ResponseEntity<com.aia.spring5.api.dto.Message> com.aia.spring5.api.controller.RestExceptionHandler.handleGenericException(java.lang.Exception,org.springframework.web.context.request.WebRequest)
From:com.aia.spring5.api.controller.RestExceptionHandler  Content: handling exception...
From:org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver  Content: Failure in @ExceptionHandler public org.springframework.http.ResponseEntity<com.aia.spring5.api.dto.Message> com.aia.spring5.api.controller.RestExceptionHandler.handleGenericException(java.lang.Exception,org.springframework.web.context.request.WebRequest)
java.lang.NoSuchMethodError: com.fasterxml.jackson.datatype.jsr310.ser.JSR310FormattedSerializerBase.findFormatOverrides(Lcom/fasterxml/jackson/databind/SerializerProvider;Lcom/fasterxml/jackson/databind/BeanProperty;Ljava/lang/Class;)Lcom/fasterxml/jackson/annotation/JsonFormat$Value;
	at com.fasterxml.jackson.datatype.jsr310.ser.JSR310FormattedSerializerBase.createContextual(JSR310FormattedSerializerBase.java:132)
	at com.fasterxml.jackson.datatype.jsr310.ser.LocalDateTimeSerializer.createContextual(LocalDateTimeSerializer.java:37)
	at com.fasterxml.jackson.databind.SerializerProvider.handleSecondaryContextualization(SerializerProvider.java:944)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:527)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.resolve(BeanSerializerBase.java:317)
	at com.fasterxml.jackson.databind.ser.SerializerCache.addAndResolveNonTypedSerializer(SerializerCache.java:177)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1166)
	at com.fasterxml.jackson.databind.SerializerProvider._findExplicitUntypedSerializer(SerializerProvider.java:1126)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.hasSerializerFor(DefaultSerializerProvider.java:422)
	at com.fasterxml.jackson.databind.ObjectMapper.canSerialize(ObjectMapper.java:2558)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.canWrite(AbstractJackson2HttpMessageConverter.java:176)
	at org.springframework.http.converter.AbstractGenericHttpMessageConverter.canWrite(AbstractGenericHttpMessageConverter.java:76)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.getProducibleMediaTypes(AbstractMessageConverterMethodProcessor.java:373)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:230)
	at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:225)
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:82)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:122)
	at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:408)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:61)
	at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:140)
	at org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:79)
	at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1298)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1110)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1056)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)

From the error log, I found that the findFormatOverrides is a **protected** method in the topest supper class of StdSerializer in package of com.fasterxml.jackson.databind.ser.std.

Please help! thank you very much

**Comment by cowtowncoder** [comment]
You have some sort of version incompatibility in your dependencies. It is possible some Jackson component have different minor version (they all should have same minor version); or, version of Jackson components is different than what Spring framework requires.
I would start by verifying versions of `jackson-databind` and `jackson-datatype-jsr310` as the first step.

**Comment by MacleZhou** [comment]
My all Jackson packages version are 2.10.1 and spring framework is 5.1.8.RELEASE. But why it works well under Windows 10 but failed on MacBook

**Comment by cowtowncoder** [comment]
I have absolutely no idea. But there is a version incompatibility between jars your system has in classpath, and that is what needs to be resolved. There is nothing Jackson can do about that.

**Comment by MacleZhou** [comment]
Anyway, thank you very much
