### ISSUE TITLE
Cannot deserialize java.util.ArrayList if within java.util.HashMap

### ISSUE THREAD

**Issue by TauCubed** [FasterXML/jackson-databind#2671]
Hi.
I'm currently facing an issue migrating from JAXB to your library.

The issue in question is that I'm unable to deserialize ArrayList when it is within a HashMap.

This is the code needed to reproduce:

Test itself:

```
public class Test {
	public static void main(String[] args) throws JsonGenerationException, JsonMappingException, IOException {
		XmlFactory woodstoxFactory = new XmlFactory(new WstxInputFactory(), new WstxOutputFactory());
		JacksonXmlModule jxm = new JacksonXmlModule();
		XmlMapper mapper = new XmlMapper(woodstoxFactory, jxm);
		
		
		File f = new File("./test.xml");
		XMLTest test = new XMLTest();
		mapper.writeValue(f, test);
		
		mapper.readValue(f, XMLTest.class);
	}
	
}
```

XMLTest class

```
public class XMLTest {
	public HashMap<String, ArrayList<String>> map = new HashMap<String, ArrayList<String>>();
	
	public XMLTest() {
		map.put("foo", new ArrayList<String>(Arrays.asList("bar", "another string")));
	}
}
```

Output:
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<java.lang.Object>` out of VALUE_STRING token
 at [Source: (File); line: 1, column: 23] (through reference chain: XMLTest["map"]->java.util.HashMap["foo"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1452)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1226)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1136)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.handleNonArray(StringCollectionDeserializer.java:274)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:183)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:173)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:21)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4434)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3299)
	at Test.main(Test.java:29)
```

Version(s):
woodstox-core: 6.1.1
jackson: 2.11.0.rc1

**Comment by cowtowncoder** [comment]
Typically I would need to see contents of XML file in question to say much, but in this particular case, problem is that you can not directly embed `Map`/`Collection` values in `Map`/`List` values: there must be one level of POJO/Bean in-between such cases.
So you would need to have, for example, `StringList` type, and `Map<String, StringList>`.
And `StringList` then having (single) field of type `List<String>`.

More generally the way to troubleshoot structural mapping problems is to actually start with serialization: construct kind of value you want to handle, serialize that, see how structure matches with XML you want to read. There are types of XML structures Jackson XML module can not handle, but it should always be able to "read what it writes" (produce kind of XML structures it could read back).

I hope this helps.

**Comment by TauCubed** [comment]
Thanks for the reply, I managed to get that working that way.

What exactly is the reason jackson cannot do that? Because that would be really nice for people who have a whole bunch of nested classes in Collection/Map

Here is my suggestion to fix the problem
The first is the output of jackson, the second is my suggestion of how it could be done.
```
<XMLTest>
	<map>
		<foo>bar</foo>
		<foo>another string</foo>
	</map>
</XMLTest>

<XMLTest>
	<map>
		<foo>
			<!-- Where the value of the map is treated like an any other POJO and put here 
			as if foo was a POJO in an arraylist.
                        If the value where a primitive / string it could just be <foo>val</foo>
                        -->
		</foo>
	</map>
</XMLTest>
```

**Comment by cowtowncoder** [comment]
@TauCubed if you figure out how to implement it, I'm happy to merge in a Pull Request. I do not know how it possibly be supported the way Jackson databinding works.
