### ISSUE TITLE
Class my.app.MyKeySerializer has no default (no arg) constructor 

### ISSUE THREAD

**Issue by danielgindi** [FasterXML/jackson-databind#2690]
Hi!

I have an *very* weird issue with custom `JsonSerializer<MyClass>`.

Let's say I have a class defined like this:
```kotlin
@JsonDeserialize(keyAs = MyKeyDeserializer::class)
@JsonSerialize(keyAs = MyKeySerializer::class)
@Parcelize
data class MyKey(var id: Long? = null, var subId: Long: 0, var phase: Int = 0)
  : Parcelable, Serializable

class MyKeyDeserializer: KeyDeserializer
{
    // Empty constructor required for Jackson
    @Suppress("unused", "ConvertSecondaryConstructorToPrimary")
    @Keep
    constructor() : super()

    override fun deserializeKey(key: String?, ctxt: DeserializationContext?): Any
    {
        if (key == null)
            return MyKey(id = null, subId = 0, phase = 0)

        val keyParts = key.split("_")

        return MyKey(
                id = if (keyParts[0] == "") null else keyParts[0].toLong(),
                subId = keyParts[1].toLong(),
                phase = keyParts[2].toInt()
    }
}

class MyKeySerializer: JsonSerializer<MyKey>
{
    // Empty constructor required for Jackson
    @Suppress("unused", "ConvertSecondaryConstructorToPrimary")
    @Keep
    constructor() : super()

    @Throws(IOException::class, JsonProcessingException::class)
    override fun serialize(value: MyKey,
                           gen: JsonGenerator,
                           serializers: SerializerProvider?)
    {
        val key = (if (value.id == null) "" else "${value.id!!}") +
                "_${value.subId}_${value.phase}"

        gen.writeFieldName(key)
    }
}
```

(I've renamed class names to reduce noise and to obfuscate ;-))

Now some other class that I'm serializing has a member defined like this:

```kotlin
@JsonSerialize(keyUsing = MyKeySerializer::class)
@JsonDeserialize(keyUsing = MyKeyDeserializer::class)
var cacheData: HashMap<MyKey, String> = HashMap()
```

In `debug` mode - serializing (and deserializing) works fine.  
In `assembleRelease` mode - an apk installed on a local device - it works fine.
In `bundleRelease` mode - downloaded from play store - it crashes:

```
IllegalArgumentException: Class my.app.MyClassSerializer has no default (no arg) constructor (through reference chain: my.app.MyActivity$WrapperClass["cacheData"])
at com.fasterxml.jackson.databind.util.ClassUtil.createInstance(ClassUtil.java:557)
at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializerInstance(DefaultSerializerProvider.java:135)
at com.fasterxml.jackson.databind.ser.std.MapSerializer.createContextual(MapSerializer.java:407)
at com.fasterxml.jackson.databind.SerializerProvider.handlePrimaryContextualization(SerializerProvider.java:976)
at com.fasterxml.jackson.databind.SerializerProvider.findPrimaryPropertySerializer(SerializerProvider.java:651)
at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddPrimarySerializer(PropertySerializerMap.java:72)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter._findAndAddDynamic(BeanPropertyWriter.java:895)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:705)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:4094)
at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3404)
```

Now note that:
1. The constructors are annotated with `@Keep`
2. I've also defined proguard rules like `-keepclassmembers my.app.MyClassSerializer { <init>(); }`
3. In java there should be a default constructor auto generated by the compiler anyway
4. Obfuscation is off.
5. These classes are not internal classes of any class.

So I can't see any reason that it won't find a `default (no arg) constructor` in the bundle release.

Anyone knows of something maybe missing in the proguard file? (Currently using [this](https://github.com/FasterXML/jackson-docs/wiki/JacksonOnAndroid))

Thank you very much!

**Comment by cowtowncoder** [comment]
I think this is with Kotlin? If so, needs to start with `jackson-module-kotlin`, unless it can be reproduced with Java-only reproduction. I will transfer issue.
