### ISSUE TITLE
Deserializing enum error by using int/Integer value with @JsonValue

### ISSUE THREAD

**Issue by zzzzbw** [FasterXML/jackson-databind#2754]
When annotating @JsonValue  on the int/Integer value, the enum can be serialized as number successfully. when i deserializing it by using a number JSON string, it will throw exception.

But it work well when using a 'String' type JSON string.

Whether the type of serialized values and deserialized parameters should be consistent？

follow is some sample code:

```java
public class Test {
    public static void main(String[] args) {
        final ObjectMapper mapper = new ObjectMapper();

        try {
            // work well as "10" JSON string
            ColorEnum colorEnum1 = mapper.readValue("\"10\"", ColorEnum.class);
            System.out.println(colorEnum1);
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }
        try {
            // fail as 10 JSON string
            ColorEnfum colorEnum2 = mapper.readValue("10", ColorEnum.class);
            System.out.println(colorEnum2);
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }

        try {
            // fail when using serialized generated string
            String json = mapper.writeValueAsString(ColorEnum.RED);
            ColorEnum colorEnum3 = mapper.readValue(json, ColorEnum.class);
            System.out.println(colorEnum3);
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }
    }

    enum ColorEnum {
        RED(10),
        YELLOW(20),
        GREEN(30);

        ColorEnum(Integer value) {
            this.value = value;
        }

        @JsonValue
        private final Integer value;

        public Integer getValue() {
            return value;
        }
    }
}
```
the result is:
```
RED
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `cn.zzzzbw.springboot.Test$ColorEnum` from number 10: index value outside legal index range [0..2]
 at [Source: (String)"10"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdNumberException(DeserializationContext.java:1710)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdNumberValue(DeserializationContext.java:992)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:200)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3402)
	at cn.zzzzbw.springboot.Test.main(Test.java:23)
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `cn.zzzzbw.springboot.Test$ColorEnum` from number 10: index value outside legal index range [0..2]
 at [Source: (String)"10"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdNumberException(DeserializationContext.java:1710)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdNumberValue(DeserializationContext.java:992)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:200)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3402)
	at cn.zzzzbw.springboot.Test.main(Test.java:31)

Process finished with exit code 0

```

ps: the version is 2.11.0

**Comment by zzzzbw** [comment]
I found the code that caused this situation

int the com.fasterxml.jackson.databind.deser.std.EnumDeserializer#deserialize(JsonParser p, DeserializationContext ctxt)

it will deserialized the enum using index directly if `curr == JsonToken.VALUE_NUMBER_INT`.

```java
public Object deserialize(JsonParser p, DeserializationContext ctxt) throws IOException
    {
        JsonToken curr = p.currentToken();

        // Usually should just get string value:
        if (curr == JsonToken.VALUE_STRING || curr == JsonToken.FIELD_NAME) {
            CompactStringObjectMap lookup = ctxt.isEnabled(DeserializationFeature.READ_ENUMS_USING_TO_STRING)
                    ? _getToStringLookup(ctxt) : _lookupByName;
            final String name = p.getText();
            Object result = lookup.find(name);
            if (result == null) {
                return _deserializeAltString(p, ctxt, lookup, name);
            }
            return result;
        }
        // But let's consider int acceptable as well (if within ordinal range)
        if (curr == JsonToken.VALUE_NUMBER_INT) {
            // ... unless told not to do that
            int index = p.getIntValue();
            if (ctxt.isEnabled(DeserializationFeature.FAIL_ON_NUMBERS_FOR_ENUMS)) {
                return ctxt.handleWeirdNumberValue(_enumClass(), index,
                        "not allowed to deserialize Enum value out of number: disable DeserializationConfig.DeserializationFeature.FAIL_ON_NUMBERS_FOR_ENUMS to allow"
                        );
            }
            if (index >= 0 && index < _enumsByIndex.length) {
                return _enumsByIndex[index];
            }
            if ((_enumDefaultValue != null)
                    && ctxt.isEnabled(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE)) {
                return _enumDefaultValue;
            }
            if (!ctxt.isEnabled(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL)) {
                return ctxt.handleWeirdNumberValue(_enumClass(), index,
                        "index value outside legal index range [0..%s]",
                        _enumsByIndex.length-1);
            }
            return null;
        }
        return _deserializeOther(p, ctxt);
    }
```


It might be a bug? When the int/Integer parameter is annotated by @JsonValue , whether consider using annotations instead of index?

**Comment by cowtowncoder** [comment]
I think this is because currently `@JsonValue` with Enums only supports `String`s. It would be good to allow use you are showing here, as it does make sense, but current deserializer only supports int value used as an index.

For now, workaround would be to create static factory method annotated with `@JsonCreator`, something like:

```java
@JsonCreator(mode = JsonCreator.Mode.DELEGATING)
static ColorEnum find(int value) {
    // find matching isntance
}
```

which is more work but actually works.

We can keep this issue open as request for enhancement; I will change title slightly.

**Comment by zzzzbw** [comment]
This really works using static factory method with `@JsonCreator`. 

But threre are a lot of enum like this in my project. The  factory method  is static mean can‘t be inherit so that i have to write manual for every enum.

Thanks very much if can solve this problem in the next version

**Comment by cowtowncoder** [comment]
Realized that this is a duplicate of #1850 so closing in favor of that one.
