### ISSUE TITLE
Fail to deserialize local Records

### ISSUE THREAD

**Issue by DasBrain** [FasterXML/jackson-databind#2758]
Reproducer:

    record NestedRecord(@JsonProperty("foo")String foo) {
        @JsonCreator
        public NestedRecord(@JsonProperty("foo") String foo) {
            this.foo = foo;
        }
    }
    
    public static void main(String[] args) throws Throwable {
        String json = "{\"foo\":\"bar\"}";
        ObjectMapper mapper = new ObjectMapper();
        System.out.println(mapper.readValue(json, NestedRecord.class));
        
        
        record LocalRecord(@JsonProperty("foo") String foo) {
            @JsonCreator 
            public LocalRecord(@JsonProperty("foo") String foo) {
                this.foo = foo;
            }
        }
        System.out.println(mapper.readValue(json, LocalRecord.class));
    }

Jackson fails with the following error message:

    NestedRecord[foo=bar]
    Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Cannot deserialize Class test.TestMain$1LocalRecord (of type local/anonymous) as a Bean
     at [Source: (String)"{"foo":"bar"}"; line: 1, column: 1]
        at com.fasterxml.jackson.databind@2.11.0/com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:309)
        at com.fasterxml.jackson.databind@2.11.0/com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:268)
        at com.fasterxml.jackson.databind@2.11.0/com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at com.fasterxml.jackson.databind@2.11.0/com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at com.fasterxml.jackson.databind@2.11.0/com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:491)
        at com.fasterxml.jackson.databind@2.11.0/com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4669)
        at com.fasterxml.jackson.databind@2.11.0/com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4478)
        at com.fasterxml.jackson.databind@2.11.0/com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
        at com.fasterxml.jackson.databind@2.11.0/com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3402)
        at test/.test.TestMain.main(TestMain.java:37)
    Caused by: java.lang.IllegalArgumentException: Cannot deserialize Class test.TestMain$1LocalRecord (of type local/anonymous) as a Bean
        at com.fasterxml.jackson.databind@2.11.0/com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.isPotentialBeanType(BeanDeserializerFactory.java:883)
        at com.fasterxml.jackson.databind@2.11.0/com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:137)
        at com.fasterxml.jackson.databind@2.11.0/com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:414)
        at com.fasterxml.jackson.databind@2.11.0/com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
        at com.fasterxml.jackson.databind@2.11.0/com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
        ... 8 more

It seems to identify the local record as a local class, which is incorrect according to [JLS § 14.3](https://docs.oracle.com/en/java/javase/14/docs/specs/records-jls.html#jls-14.3):

> ... A local record is not a local class.

**Comment by cowtowncoder** [comment]
Ok. Not quite sure what would be usable heuristics on JDK 7 to figure out this specific case: inner classes that are not static are considered problematic (since they expect "hidden this parameter" to be passed). Since Jackson can not use JDK functionality for detecting Record identifying aspects, it would have to be based on something else that differs between records and non-static inner classes.

**Comment by DasBrain** [comment]
Records are implicitly static. So `Modifier.isStatic(type.getModifiers())` returns true on them.  
This is not true for local classes, as they can not be static (yet).

In `com.fasterxml.jackson.databind.util.ClassUtil`, change [Line 130](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/util/ClassUtil.java#L130) to:

    if (!Modifier.isStatic(type.getModifiers()) && hasEnclosingMethod(type)) {

**Comment by cowtowncoder** [comment]
Quick question: line 130 on which branch? Or more importantly, in which method? `isNonStaticInnerClass`? If so, that'd make sense, check was probably meant to check for enclosing method

**Comment by GedMarc** [comment]
But

Records don't create getters and setters, it uses fluent and chained syntax, I've noticed jackson doesn't recognize these as properties or getters and setters :)

Is there a way to enable fluent and chained methods for property recognition?

**Comment by DasBrain** [comment]
master branch. I did link the corresponding line.

**Comment by cowtowncoder** [comment]
Thank you.
