### ISSUE TITLE
"no delegate- or property-based Creator" when deserializing into object with 2 implicit constructors

### ISSUE THREAD

**Issue by n11ceo** [FasterXML/jackson-databind#2778]
I'm trying to perform serialization and deserialization of an object that looks something like this:
```
public class Foo {
        private Type type;
        private String name;

        public Foo(Type type, String name) {
            this.type = type;
            this.name = name;
        }

        public Foo(String typeName, String name) {
            this.type = Type.valueOf(typeName);
            this.name = name;
        }

        public enum Type {
            TYPE_1,
            TYPE_2
        }
    }
```

But when I do the following:
```
public static void main(String[] args) throws JsonProcessingException {
        var mapper = JsonMapper.builder()
                .visibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY)
                .addModule(new ParameterNamesModule(JsonCreator.Mode.PROPERTIES))
                .build();

        var json = mapper.writeValueAsString(new Foo(Foo.Type.TYPE_1, "foo"));
        var foo = mapper.readValue(json, Foo.class);
    }
```

It fails with an exception:
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of Example$Foo (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"type":"TYPE_1","name":"foo"}"; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1615)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1077)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1332)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3402)
	at Example.main(Example.java:16)
```

I tried to determine where does the issue come from, but as stated here https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java#L858 multiple implicit constructors are not an error and digging deeper into the sources did not succeed.

Javac -parameters option is enabled.

**Comment by cowtowncoder** [comment]
Jackson can only use one properties-based creator (constructor or static factory method); and even when it has access to parameter names it has no way of knowing which constructor you might want.
So you need to add `@JsonCreator` annotation on one you want to use.

**Comment by n11ceo** [comment]
Thank you for the response! That does make sense. The exception message got me confused :)

**Comment by cowtowncoder** [comment]
@n11ceo Yes, that is true: it is not very useful in pointing out better direction. I hope I can improve it -- there are plans to rewrite creator discovery and it would be good to suggest there are more than one, instead of "none found".
