### ISSUE TITLE
Cannot deserialize enum field

### ISSUE THREAD

**Issue by awildturtok** [FasterXML/jackson-databind#2823]
Using Jackson 2.11.2 (and prior), enum fields fail to deserialize, I've tried to create a minimal test below:

```{java}
public enum AnEnum{
	AnEntry
}

class EnumFieldFailingTest {

	public static class AnObject {
		private final AnEnum field;

		@JsonCreator
		public AnObject(AnEnum when) {
			this.field = when;
		}
	}

	private final String text = "{ \"field\" : \"AnEntry\" }";


	@Test
	public void tryLoad() throws JsonProcessingException {
		ObjectMapper mapper = io.dropwizard.jackson.Jackson.newObjectMapper();

		mapper.readValue(text, AnObject.class);
	}
}
```

```{log}
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.bakdata.conquery.integration.json.AnEnum` from String "field": field was not one of [AnEntry]
 at [Source: (String)"{ "field" : "AnEntry" }"; line: 1, column: 3]

	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1702)
	at io.dropwizard.jackson.FuzzyEnumModule$PermissiveEnumDeserializer.deserialize(FuzzyEnumModule.java:59)
	at io.dropwizard.jackson.FuzzyEnumModule$PermissiveEnumDeserializer.deserialize(FuzzyEnumModule.java:37)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1315)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at com.bakdata.conquery.integration.json.EnumFieldFailingTest.tryLoad(EnumFieldFailingTest.java:26)```


It seems like ther Parser passed to PermissiveEnumDeserializer is advanced once before being passed in?

**Comment by cowtowncoder** [comment]
Ok, I think this might be a problem with DropWizard instead since `io.dropwizard.jackson.FuzzyEnumModule$PermissiveEnumDeserializer` is not Jackson class.

I can look into the issue if the problem can be shown with stand-alone unit test (no use of external classes; fine to embed equivalent in test), but I suspect there is something `PermissiveEnumDeserializer` might be doing that triggers the problem

**Comment by awildturtok** [comment]
Good catch. I was too preoccupied with narrowing the test case down that I acutally missed the dropwizard references! I just replaced  

`ObjectMapper mapper = io.dropwizard.jackson.Jackson.newObjectMapper();` 

with 

`ObjectMapper mapper = new ObjectMapper();`

and am still getting 

```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.bakdata.conquery.integration.json.filter.FailingFilterTest$AnEnum` from String "field": not one of the values accepted for Enum class: [AnEntry]
 at [Source: (String)"{ "field" : "AnEntry" }"; line: 1, column: 3]

	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1702)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:947)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:255)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:179)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1315)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at com.bakdata.conquery.integration.json.filter.FailingFilterTest.tryLoad(FailingFilterTest.java:31)
```

it seems to me, that EnumDeserializer.java misses an advance here:

```
if (curr == JsonToken.VALUE_STRING || curr == JsonToken.FIELD_NAME) {
            CompactStringObjectMap lookup = ctxt.isEnabled(DeserializationFeature.READ_ENUMS_USING_TO_STRING)
                    ? _getToStringLookup(ctxt) : _lookupByName;
            p.nextToken(); // HERE
            final String name = p.getText();
            Object result = lookup.find(name);
            if (result == null) {
                return _deserializeAltString(p, ctxt, lookup, name);
            }
            return result;
        }
```

**Comment by cowtowncoder** [comment]
@awildturtok thank you! I'll have to look -- the expectation for deserializers is that the first token of the value should already be pointed to by `JsonParser` and so normally no advancing should be needed.

But I think I can see the issue here -- it's probably ambiguity of `@JsonCreator` actually (and bit of Enum deserializer's fault too; it should sort of throw exception for mismatched structure...).
I think what you want is "properties-based" creator, but what appears to get detected is "delegating" one.
Latter would expect JSON String object to bind (to delegate to parameter) -- but gets JSON Object. Enum deserializer does not spot the problem (but accepts `FIELD_NAME` -- probably should not).

To resolve this, you either need to change constructor to:

```
@JsonCreator
public AnObject(@JsonProperty("field") AnEnum when) { }
```

or (assuming you have JDK8 parameter names module)

```
@JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
public AnObject(AnEnum field) { }
```

(it is actually possible that in second case `mode` is not absolutely needed because names align, but to me it seems more fragile -- if jdk8 parameter names module is not present, it'd revert to "properties" style)

**Comment by cowtowncoder** [comment]
Interesting... I can reproduce this as shown, will see what can be done to either fix it or give proper error message (if this is related to `@JsonCreator` usage).

**Comment by cowtowncoder** [comment]
Ok, so, yes: the problem is that as declared, it is expected that the WHOLE input (JSON Object) is mapped into enum of type `AnEnum`, which is then passed to `@JsonCreator` annotated constructor. But that is not how Enum serialization works -- they are not Beans but are serialized either as Strings or numbers (index).
But you can annotate constructor like so:

```
        @JsonCreator
        public AnObject(@JsonProperty("field") AnEnum when) {
            this.field = when;
        }
```

and this works as expected (since annotation indicates now that parameters for constructor should be mapped separately (there could be any number; just happens to be that there is one).

Error message is pretty misleading so I will improve handling slightly to remove use of `FIELD_NAME` as accepted.
