### ISSUE TITLE
JsonNode.toString() throws with msgpack value

### ISSUE THREAD

**Issue by fan-tom** [FasterXML/jackson-databind#2824]
**Describe the bug**
After upgrade from 2.9 to 2.10 next code starts throwing exception
```java
JsonNode node = new ArrayNode(new JsonNodeFactory(false), List.of(new POJONode(new MessagePackExtensionType((byte)0, new byte[]{2}))));

System.out.println(node.toString());
// 2.9: [org.msgpack.jackson.dataformat.MessagePackExtensionType@21]
// 2.10: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: 'gen' is expected to be
// MessagePackGenerator but it's class com.fasterxml.jackson.core.json.WriterBasedJsonGenerator
//	at com.fasterxml.jackson.databind.node.InternalNodeMapper.nodeToString(InternalNodeMapper.java:32)
//	at com.fasterxml.jackson.databind.node.BaseJsonNode.toString(BaseJsonNode.java:136)
```
Exception is thrown due to these lines from `org.msgpack:jackson-dataformat-msgpack` package 
```java
//org.msgpack.jackson.dataformat.MessagePackExtensionType.Serializer#serialize
  public static class Serializer extends JsonSerializer<MessagePackExtensionType>
    {
        @Override
        public void serialize(MessagePackExtensionType value, JsonGenerator gen, SerializerProvider serializers)
                throws IOException, JsonProcessingException
        {
            if (gen instanceof MessagePackGenerator) {
                MessagePackGenerator msgpackGenerator = (MessagePackGenerator) gen;
                msgpackGenerator.writeExtensionType(value);
            }
            else {
                throw new IllegalStateException("'gen' is expected to be MessagePackGenerator but it's " + gen.getClass());
            }
        }
    }
```
because `InternalNodeMapper`, used in 2.10 in `toString` implementation doesn't take extensions into account, just uses default `JsonMapper` and so on.

I'm not sure is it bug or intended behaviour, but I tried to update package version and faced this issue. There are a lot of places where `toString` conversion is used (in debug/trace logs, where nodes are simply logged, so no direct calls to `toString` are performed, it is in logger internals) and I'd like to have some workaround to be sure app will not crash due to this issue.
**Version information**
Which Jackson version(s) was this for?
2.10.2
**Expected behavior**
No exception

**Comment by cowtowncoder** [comment]
Note: for Hacktoberfest I would accept a simple unit tests to add on:

https://github.com/FasterXML/jackson-integration-tests

(`master` is for 2.12 compatibility testing)

and no fix is required otherwise. Added "need-test-case" label to indicate this.

**Comment by cowtowncoder** [comment]
@fan-tom I suspect the usage as shown might be unsupportable: `JsonNode.toString()` should only produce JSON, ever, regardless of backend, but type enclosed appears to be MessagePack-specific value.
However, since `MessagePackExtensionType` is defined in `jackson-dataformat-msgpack`, it technically could change behavior, to produce some other representation for diagnostics purposes. And in fact it probably should at least consider possible case of `TokenBuffer` being underlying generator: this is required for buffering.

But this is not something that can be solved by `jackson-databind`, unfortunately.

**Comment by cowtowncoder** [comment]
Related/similar to #3262

**Comment by cowtowncoder** [comment]
Not clear what, if anything, may be done. Closing as wont-fix; may be re-filed with idea(s) for improved handling.
