### ISSUE TITLE
POJO with Data annotation including XML and Json annotations gets ambiguous ISE

### ISSUE THREAD

**Issue by cardonator** [FasterXML/jackson-databind#2855]
**Describe the bug**
Hello all, I've been working on updating our dependencies for an old app and noticed strange behavior with Jackson databind that I can't seem to explain. I essentially have a POJO that looks like this:

```
@Data
@NoArgsConstructor
@XmlRootElement(name = "organizations")
public class OrganizationIdList {
    @XmlElementWrapper(name = "organizations")
    @XmlElement(name = "organization")
    @JsonProperty("organizations")
    private List<Organization> orgIds;

    public OrganizationIdList(List<String> ids) {
        orgIds = new ArrayList<>(ids.size());
        orgIds.addAll(ids.stream().map(Organization::new).collect(Collectors.toList()));
    }
}
```
When I updated to Jackson 2.11, I started seeing an exception whenever deserializing from an Jersey response object (`response.readEntity(OrganizationIdList.class);`) as noted below:
```
java.lang.IllegalStateException: Conflicting/ambiguous property name definitions (implicit name 'orgIds'): found multiple explicit names: [organization, organizations], but also implicit accessor: [method com.digicert.cis.integration.resource.oem.OemTpsOrganizationIdList#getOrgIds(0 params)][visible=true,ignore=false,explicitName=false]

	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder._explode(POJOPropertyBuilder.java:1108)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.explode(POJOPropertyBuilder.java:1088)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._renameProperties(POJOPropertiesCollector.java:845)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:337)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:287)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:186)
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:164)
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:239)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:292)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:276)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:224)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:220)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:143)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:414)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:491)
	at com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:2454)
	at com.fasterxml.jackson.databind.ObjectReader.forType(ObjectReader.java:728)
	at org.glassfish.jersey.jackson.internal.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:825)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:233)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:212)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:885)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:819)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:298)
	at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:91)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:365)
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:240)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:88)
```
I noticed that in an earlier version of Jackson the library gained the ability to automatically annotate Getters/Setters with `@JsonProperty`. I'm suspecting that the above behavior is _expected_ however, I'm unable to figure out the correct way to resolve this issue while also keeping the Xml and Json bindings for the POJO. Any help understanding would be much appreciated.

**Version information**
2.11.2

**To Reproduce**
Hopefully the above information is enough to understand the issue and provide feedback, however I can provide an example project exhibiting the problem if desired.

**Comment by cowtowncoder** [comment]
Ok, this is tricky to investigate due to multiple reasons. Issue itself probably belongs to JAXB module (as that provides support for JAXB annotations); I can move it under `jackson-modules-base`.
But there are 2 other challenges:

1. Use of Lombok (I think?) -- that is fine in itself, should work, but I can't really see POJOs as they are after processing. So it would be necessary to see how they look after processing (the way Jackson sees them). That may be as simple as manually adding equivalent annotations, or configuring Lombok to create java sources for inspection
2. Might need input processed, although not sure; exception is thrown during inspection so this might not be necessary.
3. Configuration of `ObjectMapper`, at least wrt `AnnotationIntrospector`s configured. This is provided by Jersey; it might be Jackson's `jackson-jaxrs-json-provider`. Order of Jackson and JAXB introspectors probably matters.

So, I think I'd need (1) at least. May be able to figure out (3) quite easily and (2) may or may not be relevant.

**Comment by cardonator** [comment]
So I'll give a slight amount more context just to see if it helps 😄 I am including the dependency `jackson-jaxrs-json-provider` in my app.

I am configuring a normal ClientBuilder for the Jersey request:
```
Client client = ClientBuilder.newBuilder().build();
```
The response is collected using a pretty standard HTTP request:
```
response = client.target(webServer)
                    .path(urlPath)
                    .request(MediaType.APPLICATION_JSON)
                    .accept(MediaType.APPLICATION_JSON)
                    .get(Response.class);
```
I believe this implies that it is using a standard ObjectMapper... ❓ 

Also, maybe helpful is I'm on JDK 11 and using Spring Boot 2.3.3.RELEASE.

Now, at this point, can you help me understand how I can collect information that could be helpful? Would it help for me to provide an example project?

**Comment by cowtowncoder** [comment]
An example project with as stripped-down version to use as possible would be good. Ideally without using any external deps, but as simple as possible otherwise. Example project would be good.

jackson-jaxrs-json-provider does configure ObjectMapper slightly, but most likely just with 2 AnnotationIntrospectors (without this, JAXB annotations would have no effect).

**Comment by cardonator** [comment]
Just as an update, I reproduced the main loop of my application in a demo application but I'm not actually getting the same problem. I'm guessing that suggests I have an incompatible version of a dependency somewhere in my other application...

**Comment by cowtowncoder** [comment]
Ah. It is good to verify that compatible set of versions is used -- it should not be very strict ("close enough" minor versions work for many modules), but there are cases where addition of functionality can change behavior for some mismatching combinations (new methods are quite regularly added in `AnnotationIntrospector`, and while deprecated methods are supported, combinations of different versions are not really tested).

**Comment by cardonator** [comment]
Thanks for your help @cowtowncoder and sorry for bothering you on this 😆 I tried removing the jaxb-annotations dependency and that seems to have resolved this issue in my other app. I still don't know what exactly is causing the problem with that dependency included because I included it just fine in my demo project.
