### ISSUE TITLE
Thread struck when deserialize.

### ISSUE THREAD

**Issue by lkqm** [FasterXML/jackson-databind#2892]
I have a big json deserialize with ObjectMapper.readValue. some times thread struck. and restart application then will be ok.

jackson-databind version: 2.8.10
Java version: 
```
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```
os: Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-31-generic x86_64)

Java thread stack:
```
pool-2-thread-3
priority:5 - threadId:0x00007f1304ccc000 - nativeId:0x93b - nativeId (decimal):2363 - state:RUNNABLE
stackTrace:
java.lang.Thread.State: RUNNABLE
at com.sun.jna.Structure.(Structure.java:108)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:119)
at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:260)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:332)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:357)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2858)
at com.wangxiaobao.facesyncfile.basis.RedisDao.get(RedisDao.java:58)
at com.wangxiaobao.facesyncfile.basis.RedisDao$$FastClassBySpringCGLIB$$ae39b934.invoke()
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
at com.wangxiaobao.facesyncfile.basis.RedisDao$$EnhancerBySpringCGLIB$$afc2fec4.get()
at com.wangxiaobao.facesyncfile.listener.PullFileRunnable.run(PullFileRunnable.java:67)
at com.wangxiaobao.facesyncfile.listener.PullFileRunnable$$FastClassBySpringCGLIB$$6a1e524b.invoke()
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:669)
at com.wangxiaobao.facesyncfile.listener.PullFileRunnable$$EnhancerBySpringCGLIB$$15def372.run()
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by cowtowncoder** [comment]
Why do you think thread is stuck? Status is indicated as `RUNNABLE`?
Still, code in question is within JDK, seemingly trying to call constructor of a class, outside of Jackson codebase, so I suspect there would not be much Jackson can do here.

A reproduction of issue would be needed to help.

**Comment by lkqm** [comment]
jstack dump thread stack was not changed at many times, and use alibaba arthas tools watch next line method invoke there is not have any  invoked, so i think thread is stuck.

This is an accidental problem, which cannot be reproduced. It seems that it is stuck in the JDK class library code

**Comment by cowtowncoder** [comment]
Ok that sounds unfortunate.

One thing I would suggest, if possible, would be to upgrade to a later version, ideally at least 2.10(.5).
There have been some concurrency access improvements that might be relevant here, although are not in exact spot (but rather in introspection for constructing (de)serializers.

**Comment by lkqm** [comment]
Thank you for suggest. I will be try it.
