### ISSUE TITLE
Threads WAITING at com.fasterxml.jackson.databind.util.LRUMap.get(LRUMap.java:56)

### ISSUE THREAD

**Issue by mgpandian** [FasterXML/jackson-databind#2993]
We have an application where we read from XML and convert to Java objects. For reading the xml file, we use jackson-databind jar. Version of the jackson-databind Jar is 2.4.2.  Our application is a highly loaded application where there will be lots of operations being performed.  

When we perform a read of the xml, we are facing the issue where the thread is hanging in the particular place and read is not getting completed. From the thread stack, we could see that the thread is hanging at LRUMap.get() method. 

Stack Trace:
-------------
java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00007f75a54b8148> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:964)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1282)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:731)
	at com.fasterxml.jackson.databind.util.LRUMap.get(LRUMap.java:56)
	at com.fasterxml.jackson.databind.type.TypeFactory._fromClass(TypeFactory.java:707)
	at com.fasterxml.jackson.databind.type.TypeFactory._constructType(TypeFactory.java:387)
	at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:354)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2146)

Please let us know if there are any known issues related to this and a way to resolve this issue.

**Comment by cowtowncoder** [comment]
@mgpandian Version 2.4.2 is ancient, released 6 years ago (see https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind/2.4.2). So the very first step with things like this is to upgrade to a somewhat newer version. And in case of performance issues it is unlikely that any change would go to version older than currently actively developed one, which as of now is 2.12 (although in some cases we may choose to backport chances considered safe to earlier minor versions for which patches are expected to be released; this would include 2.11).

So: I would try upgrade first: I think there have been some improvements to handling of caching of resolved types.
If you still see an issue I am happy to continue discussion on how to resolve or work around the issue.
This part should not really become a concurrency hot spot in typical usage.

**Comment by mgpandian** [comment]
Hi ,
Thanks a lot for your reply. We are planning to upgrade to the latest version. However, we would like to understand whether this issue will not resurface again with the latest version of the jackson-databind. 

I'm asking this because, we had upgraded from 2.4.1 version to 2.4.2 version for the same issue after looking at the resolution of the issue (https://github.com/FasterXML/jackson-databind/issues/503). Still the same issue as explained above has resurfaced in 2.4.2 version as well. So, please confirm on whether the issue is resolved in latest version of the jar.

**Comment by cowtowncoder** [comment]
@mgpandian Not to be rude but ... I have absolutely no idea if a stack trace you managed to get on your system for a years old version relates to behavior of new versions. I will not spend any more time on this issue with current premises; it is not my job to do your job.
