### ISSUE TITLE
com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.10.5 requires Jackson Databind version >= 2.10.0 and < 2.11.0

### ISSUE THREAD

**Issue by behruz-b** [FasterXML/jackson-databind#3096]
While migrating Play2  from 2.6 to 2.8.7 I've stuck with issue:

```
[error] com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.10.5 requires Jackson Databind version >= 2.10.0 and < 2.11.0
[error]         at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
[error]         at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
[error]         at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
[error]         at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:818)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider$.$anonfun$configureObjectMapperModules$4(JacksonObjectMapperProvider.scala:223)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider$.$anonfun$configureObjectMapperModules$4$adapted(JacksonObjectMapperProvider.scala:222)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider$.configureObjectMapperModules(JacksonObjectMapperProvider.scala:222)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider$.createObjectMapper(JacksonObjectMapperProvider.scala:246)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider.create(JacksonObjectMapperProvider.scala:333)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider.$anonfun$getOrCreate$1(JacksonObjectMapperProvider.scala:291)
[error]         at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider.getOrCreate(JacksonObjectMapperProvider.scala:291)
[error]         at akka.serialization.jackson.JacksonJsonSerializer.<init>(JacksonSerializer.scala:141)
[error]         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[error]         at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:40)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:35)
[error]         at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$5(ReflectiveDynamicAccess.scala:48)
[error]         at scala.util.Success.flatMap(Try.scala:251)
[error]         at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:47)
[error]         at akka.serialization.Serialization$$anonfun$serializerOf$1$$anonfun$applyOrElse$1.applyOrElse(Serialization.scala:396)
[error]         at akka.serialization.Serialization$$anonfun$serializerOf$1$$anonfun$applyOrElse$1.applyOrElse(Serialization.scala:392)
[error]         at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[error]         at scala.util.Failure.recoverWith(Try.scala:236)
[error]         at akka.serialization.Serialization$$anonfun$serializerOf$1.applyOrElse(Serialization.scala:392)
[error]         at akka.serialization.Serialization$$anonfun$serializerOf$1.applyOrElse(Serialization.scala:390)
[error]         at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[error]         at scala.util.Failure.recoverWith(Try.scala:236)
[error]         at akka.serialization.Serialization.serializerOf(Serialization.scala:390)
[error]         at akka.serialization.Serialization.$anonfun$serializers$2(Serialization.scala:424)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:862)
[error]         at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:370)
[error]         at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:675)
[error]         at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:675)
[error]         at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:861)
[error]         at akka.serialization.Serialization.<init>(Serialization.scala:424)
[error]         at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:18)
[error]         at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:14)
[error]         at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1158)
[error]         at akka.actor.ActorSystemImpl.$anonfun$loadExtensions$1(ActorSystem.scala:1201)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:943)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at akka.actor.ActorSystemImpl.loadExtensions$1(ActorSystem.scala:1195)
[error]         at akka.actor.ActorSystemImpl.loadExtensions(ActorSystem.scala:1214)
[error]         at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1035)
[error]         at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1022)
[error]         at akka.actor.ActorSystemImpl._start(ActorSystem.scala:1022)
[error]         at akka.actor.ActorSystemImpl.start(ActorSystem.scala:1045)
[error]         at akka.actor.ActorSystem$.apply(ActorSystem.scala:272)
[error]         at akka.actor.ActorSystem$.apply(ActorSystem.scala:316)
[error]         at akka.actor.ActorSystem$.apply(ActorSystem.scala:290)
[error]         at play.core.server.DevServerStart$.$anonfun$mainDev$1(DevServerStart.scala:248)
[error]         at play.utils.Threads$.withContextClassLoader(Threads.scala:22)
[error]         at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:76)
[error]         at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:50)
[error]         at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error]         at play.runsupport.Reloader$.startDevMode(Reloader.scala:306)
[error]         at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:98)
[error]         at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:81)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:105)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:67)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
```
I've tried to add different versions to dependency:
- `"com.fasterxml.jackson.core" % "jackson-databind" % "2.10.0"`
- `"com.fasterxml.jackson.core" % "jackson-databind" % "2.10.5.1"`

Before I hadn't add any dependencies of jackson-databind.

Please help to understand and solve the issue. Now server doesn't compile

**Comment by cowtowncoder** [comment]
Moving to Scala module since it adds the check, not databind.
