### ISSUE TITLE
ValueInstantiator and property-based creation cannot co-exist

### ISSUE THREAD

**Issue by ginkel** [FasterXML/jackson-databind#31]
This is a follow-up to the mailing list discussion at: http://markmail.org/thread/g7he2ktbpz4oumtc

Currently, it seems to be impossible to use a `ValueInstantiator` and property-based creation for the same class if registering the `ValueInstantiator` via a `SimpleModule`'s `addValueInstantiator` method as the `ValueInstantiator`'s `configureFromObjectSettings` method never gets called (it gets called for the default `ValueInstantiator` before it gets replaced, though).

In the end this results in the following exception as the `ValueInstantiator` is lacking the defaultCreator required for properety-based creation:

    com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class com.example.model.Cluster]: can not instantiate from JSON object (need to add/enable type information?) at [Source: org.apache.catalina.connector.CoyoteInputStream@2c0bdfc; line: 1, column: 2]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:163)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObjectUsingNonDefault(BeanDeserializer.java:381)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:271)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:112)
        at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:900)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:471)
        at com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider.readFrom(JacksonJsonProvider.java:443)
        at com.sun.jersey.spi.container.ContainerRequest.getEntity(ContainerRequest.java:474)
        at com.sun.jersey.server.impl.model.method.dispatch.EntityParamDispatchProvider$EntityInjectable.getValue(EntityParamDispatchProvider.java:123)
        at com.sun.jersey.server.impl.inject.InjectableValuesProvider.getInjectableValues(InjectableValuesProvider.java:46)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$EntityParamInInvoker.getParams(AbstractResourceMethodDispatchProvider.java:153)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:183)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1483)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1414)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1363)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1353)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:414)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:708)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        [...]

As a workaround, one can expose the `StdValueInstantiators`'s copy constructor (both `*ValueInstantiator` classes in the code sample below are derived from `StdValueInstantiators`) to retrieve the pre-configured defaultCreator from within a `BeanDeserializerModifier`, but this involves some ugly type-casting:

        @Override
        public void setupModule(SetupContext context) {
            context.addBeanDeserializerModifier(new BeanDeserializerModifier() {
                @Override
                public BeanDeserializerBuilder updateBuilder(DeserializationConfig config, BeanDescription beanDesc, BeanDeserializerBuilder builder) {
                    if (beanDesc.getBeanClass() == Cluster.class)
                        builder.setValueInstantiator(new ClusterValueInstantiator((StdValueInstantiator) builder.getValueInstantiator(), clusterService));
                    else if (beanDesc.getBeanClass() == Node.class)
                        builder.setValueInstantiator(new NodeValueInstantiator((StdValueInstantiator) builder.getValueInstantiator(), nodeService));
                    return super.updateBuilder(config, beanDesc, builder);
                }
            });

            super.setupModule(context);
        }

A more elegant solution that can be used within `SimpleModule` without the use of a `BeanDeserializerModifier` would be welcome.

**Comment by cowtowncoder** [comment]
Not quite sure how this should/could/would work; closing since there is no clear understanding of what should be done.
