### ISSUE TITLE
Getting crash "java.lang.NoClassDefFoundError: java.util.stream.Stream"  below Android version 24

### ISSUE THREAD

**Issue by bibink874** [FasterXML/jackson-databind#3263]
**Describe the bug**
I am getting crash "java.lang.NoClassDefFoundError: java.util.stream.Stream"  in marshmallow and lollipop version i.e. Android  version below 24.

the crash is getting while calling this method

ObjectMapper mMapper = new ObjectMapper();
mMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
mMapper.readValue(apiResponse.getData().toString(), Pojo.class); //crashing on this line

Can you please explain how to rid of this bug?

**Version information**
2.11.1

**To Reproduce**
1. run the above mentioned method in Android version less than 24 (i.e.; Marshmallow or lollipop)

**Expected behavior**
Need to run on version below Android version 24

**Comment by yawkat** [comment]
can you give the full stack trace please? Makes it easier to see where the issue is.

**Comment by bibink874** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main       java.lang.NoClassDefFoundError: java.util.stream.Stream
        at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
        at java.lang.Class.getDexCacheType(Class.java:476)
        at java.lang.reflect.Method.getReturnType(Method.java:183)
        at java.lang.Class.getDeclaredMethods(Class.java:672)
        at com.fasterxml.jackson.databind.util.ClassUtil.getClassMethods(ClassUtil.java:1172)
        at com.fasterxml.jackson.databind.introspect.AnnotatedMethodCollector._addMemberMethods(AnnotatedMethodCollector.java:117)
        at com.fasterxml.jackson.databind.introspect.AnnotatedMethodCollector.collect(AnnotatedMethodCollector.java:49)
        at com.fasterxml.jackson.databind.introspect.AnnotatedMethodCollector.collectMethods(AnnotatedMethodCollector.java:40)
        at com.fasterxml.jackson.databind.introspect.AnnotatedClass._methods(AnnotatedClass.java:382)
        at com.fasterxml.jackson.databind.introspect.AnnotatedClass.memberMethods(AnnotatedClass.java:322)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addMethods(POJOPropertiesCollector.java:555)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:323)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueAccessor(POJOPropertiesCollector.java:203)
        at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueAccessor(BasicBeanDescription.java:252)
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._createEnumKeyDeserializer(BasicDeserializerFactory.java:1704)
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.createKeyDeserializer(BasicDeserializerFactory.java:1664)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findKeyDeserializer(DeserializerCache.java:166)
        at com.fasterxml.jackson.databind.DeserializationContext.findKeyDeserializer(DeserializationContext.java:514)
        at com.fasterxml.jackson.databind.deser.std.EnumMapDeserializer.createContextual(EnumMapDeserializer.java:175)
        at com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(DeserializationContext.java:665)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:508)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:491)
        at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4669)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4478)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3402)

**Comment by yawkat** [comment]
That error looks more like your model contains a reference to `Stream` somewhere.

**Comment by bibink874** [comment]
Thanks For the response. Strteam used on models. I cleared it and run again. Now works fine.
