### ISSUE TITLE
works weird when have only getter function but no setter function

### ISSUE THREAD

**Issue by XenoAmess** [FasterXML/jackson-databind#3363]
jackson version 2.13.1

Hi.

I found something weird when using jackson with lombok.

But lombok people thought this be jackson bug, or at least it works weirdly.

Could you please check this?

https://github.com/projectlombok/lombok/pull/2915#issuecomment-1001775172

Thanks

Original test code can be found in that link,

I cast the delomboked test source for you also

```
package jackson;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.Test;

import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertEquals;

class TestDto1 {

    @com.fasterxml.jackson.annotation.JsonProperty("aListJ")
    private List<Integer> aList;

    @com.fasterxml.jackson.annotation.JsonProperty("bIntegerJ")
    private Integer bInteger;

    public TestDto1(List<Integer> aList, Integer bInteger) {
        this.aList = aList;
        this.bInteger = bInteger;
    }

    public List<Integer> getAList() {
        return this.aList;
    }

    public Integer getBInteger() {
        return this.bInteger;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("aListJ")
    public void setAList(List<Integer> aList) {
        this.aList = aList;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("bIntegerJ")
    public void setBInteger(Integer bInteger) {
        this.bInteger = bInteger;
    }

    public boolean equals(final Object o) {
        if (o == this) return true;
        if (!(o instanceof TestDto1)) return false;
        final TestDto1 other = (TestDto1) o;
        if (!other.canEqual((Object) this)) return false;
        final Object this$aList = this.getAList();
        final Object other$aList = other.getAList();
        if (this$aList == null ? other$aList != null : !this$aList.equals(other$aList)) return false;
        final Object this$bInteger = this.getBInteger();
        final Object other$bInteger = other.getBInteger();
        if (this$bInteger == null ? other$bInteger != null : !this$bInteger.equals(other$bInteger)) return false;
        return true;
    }

    protected boolean canEqual(final Object other) {
        return other instanceof TestDto1;
    }

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $aList = this.getAList();
        result = result * PRIME + ($aList == null ? 43 : $aList.hashCode());
        final Object $bInteger = this.getBInteger();
        result = result * PRIME + ($bInteger == null ? 43 : $bInteger.hashCode());
        return result;
    }

    public String toString() {
        return "TestDto1(aList=" + this.getAList() + ", bInteger=" + this.getBInteger() + ")";
    }
}

class TestDto2 {

    @com.fasterxml.jackson.annotation.JsonProperty("aListJ")
    private final List<Integer> aList;

    @com.fasterxml.jackson.annotation.JsonProperty("bIntegerJ")
    private final Integer bInteger;

    public TestDto2(List<Integer> aList, Integer bInteger) {
        this.aList = aList;
        this.bInteger = bInteger;
    }

    public List<Integer> getAList() {
        return this.aList;
    }

    public Integer getBInteger() {
        return this.bInteger;
    }

    public boolean equals(final Object o) {
        if (o == this) return true;
        if (!(o instanceof TestDto2)) return false;
        final TestDto2 other = (TestDto2) o;
        if (!other.canEqual((Object) this)) return false;
        final Object this$aList = this.getAList();
        final Object other$aList = other.getAList();
        if (this$aList == null ? other$aList != null : !this$aList.equals(other$aList)) return false;
        final Object this$bInteger = this.getBInteger();
        final Object other$bInteger = other.getBInteger();
        if (this$bInteger == null ? other$bInteger != null : !this$bInteger.equals(other$bInteger)) return false;
        return true;
    }

    protected boolean canEqual(final Object other) {
        return other instanceof TestDto2;
    }

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $aList = this.getAList();
        result = result * PRIME + ($aList == null ? 43 : $aList.hashCode());
        final Object $bInteger = this.getBInteger();
        result = result * PRIME + ($bInteger == null ? 43 : $bInteger.hashCode());
        return result;
    }

    public String toString() {
        return "TestDto2(aList=" + this.getAList() + ", bInteger=" + this.getBInteger() + ")";
    }
}

public class CopyJsonPropertyAnnotationToGetterTest {

    @Test
    public void test() throws Throwable {
        String jsonString1 = new ObjectMapper().writeValueAsString(
                new TestDto1(
                        Arrays.asList(1, 2, 3),
                        10
                )
        );
        System.out.println(jsonString1);

        String jsonString2 = new ObjectMapper().writeValueAsString(
                new TestDto2(
                        Arrays.asList(1, 2, 3),
                        10
                )
        );
        System.out.println(jsonString2);

        assertEquals(jsonString1, jsonString2);
    }

}
```

results:
```
{"aListJ":[1,2,3],"bIntegerJ":10}
{"binteger":10,"alist":[1,2,3],"aListJ":[1,2,3],"bIntegerJ":10}

org.junit.ComparisonFailure: 
Expected :{"aListJ":[1,2,3],"bIntegerJ":10}
Actual   :{"binteger":10,"alist":[1,2,3],"aListJ":[1,2,3],"bIntegerJ":10}
<Click to see difference>


	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at jackson.CopyJsonPropertyAnnotationToGetterTest.test(CopyJsonPropertyAnnotationToGetterTest.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)


Process finished with exit code -1

```

**Comment by cowtowncoder** [comment]
Problem is almost certainly unfortunate naming of property here:

```
    public List<Integer> getAList() {
        return this.aList;
   }
```

since `getAList()` does NOT infer Bean style property with name `aList` but `AList`, I think (only a single capital character is lower-cased as per bean spec).
This can be rectified by adding annotation but it must be on getter and not on field since field already has intended matching name.

Problem is partly due to frameworks like Lombok starting with field name, generating getter, and Jackson starting with individual pieces (preferably getter/setter) and then trying to unify them with fields.
In theory things could perhaps be improved by offering a case-insensitive matching for accessors but even in such cases it's likely the "real" name to use (for serialization) would be difficult to deduce correctly without annotations.

**Comment by XenoAmess** [comment]
@janrieke so seems we have no choice but must copy the annotations onto getter functions there...

**Comment by cowtowncoder** [comment]
Note that it is likely you need not copy but move the annotations -- there is no real benefit for adding them to fields anyway as getters/setters have precedence anyway. Typically you would annotate accessors to use.

**Comment by XenoAmess** [comment]
> Note that it is likely you need not copy but move the annotations -- there is no real benefit for adding them to fields anyway as getters/setters have precedence anyway. Typically you would annotate accessors to use.

Nope, should not do that, as that is added to field in lombok.
If we add it in sources but remove it after compile, that is not a good thing...

**Comment by janrieke** [comment]
> Problem is almost certainly unfortunate naming of property here

Can confirm. Changing the name such that forward/backward name conversion is consistent fixes the issue. 

> so seems we have no choice but must copy the annotations onto getter functions there...

I'd still say "no", but that's a discussion for projectlombok/lombok#2915.

From my POV, this jackson issue can be closed.
