### ISSUE TITLE
Can't make work: deserialization.read_unknown_enum_values_as_null 

### ISSUE THREAD

**Issue by Chaya56** [FasterXML/jackson-databind#3382]
In a Springboot 2.6.3 project i create an ObjectMapper (Jackson-databind: 2.13.1). I want to deserialize Json object with unknown enum key so i activate : READ_UNKNOWN_ENUM_VALUES_AS_NULL parameters, it's not working via Spring bean configuration or yaml configuration.

Spring bean configuration
```
    @Bean
    @Primary
    public ObjectMapper objectMapper() {
        return new ObjectMapper()
                .enable(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL);
    }
```
OR
Spring YAML configuration
```
spring:
  jackson:
    deserialization:
      read_unknown_enum_values_as_null: true
```

Stacktrace in application when trying to desrialize unknown enum key
```
org.springframework.web.client.RestClientException: Error while extracting response for type [class com.test.currencyrate.model.Rate] and content type [application/json;charset=utf-8]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize Map key of type `com.test.currencyrate.model.CurrencyCode` from String "CLF": not a valid representation, problem: (com.fasterxml.jackson.databind.exc.InvalidFormatException) Cannot deserialize Map key of type `com.test.currencyrate.model.CurrencyCode` from String "CLF": not one of the values accepted for Enum class: [FJD, MXN, STD, SCR, TVD, CDF, BBD, GTQ, CLP, HNL, UGX, ZAR, TND, CUC, BSD, SLL, SDG, IQD, CUP, GMD, TWD, RSD, DOP, KMF, MYR, FKP, XOF, GEL, BTC, UYU, MAD, CVE, TOP, AZN, OMR, PGK, KES, SEK, BTN, UAH, GNF, ERN, MZN, SVC, ARS, QAR, IRR, MRO, CNY, THB, UZS, XPF, BDT, LYD, BMD, KWD, PHP, RUB, PYG, ISK, JMD, COP, MKD, USD, DZD, PAB, GGP, SGD, ETB, JEP, KGS, SOS, VEF, VUV, LAK, BND, XAF, LRD, CHF, HRK, ALL, DJF, ZMW, TZS, VND, SPL, AUD, ILS, GHS, GYD, KPW, BOB, KHR, MDL, IDR, KYD, AMD, BWP, SHP, TRY, LBP, TJS, JOD, AED, HKD, RWF, EUR, LSL, DKK, ZWD, CAD, BGN, MMK, MUR, NOK, SYP, IMP, GIP, RON, LKR, NGN, CRC, CZK, PKR, XCD, ANG, HTG, BHD, KZT, SRD, SZL, SAR, TTD, YER, MVR, AFN, INR, AWG, KRW, NPR, JPY, MNT, AOA, PLN, GBP, SBD, BYN, HUF, BYR, BIF, MWK, MGA, XDR, BZD, BAM, EGP, MOP, NAD, NIO, PEN, NZD, WST, TMT, BRL]; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize Map key of type `com.test.currencyrate.model.CurrencyCode` from String "CLF": not a valid representation, problem: (com.fasterxml.jackson.databind.exc.InvalidFormatException) Cannot deserialize Map key of type `com.test.currencyrate.model.CurrencyCode` from String "CLF": not one of the values accepted for Enum class: [FJD, MXN, STD, SCR, TVD, CDF, BBD, GTQ, CLP, HNL, UGX, ZAR, TND, CUC, BSD, SLL, SDG, IQD, CUP, GMD, TWD, RSD, DOP, KMF, MYR, FKP, XOF, GEL, BTC, UYU, MAD, CVE, TOP, AZN, OMR, PGK, KES, SEK, BTN, UAH, GNF, ERN, MZN, SVC, ARS, QAR, IRR, MRO, CNY, THB, UZS, XPF, BDT, LYD, BMD, KWD, PHP, RUB, PYG, ISK, JMD, COP, MKD, USD, DZD, PAB, GGP, SGD, ETB, JEP, KGS, SOS, VEF, VUV, LAK, BND, XAF, LRD, CHF, HRK, ALL, DJF, ZMW, TZS, VND, SPL, AUD, ILS, GHS, GYD, KPW, BOB, KHR, MDL, IDR, KYD, AMD, BWP, SHP, TRY, LBP, TJS, JOD, AED, HKD, RWF, EUR, LSL, DKK, ZWD, CAD, BGN, MMK, MUR, NOK, SYP, IMP, GIP, RON, LKR, NGN, CRC, CZK, PKR, XCD, ANG, HTG, BHD, KZT, SRD, SZL, SAR, TTD, YER, MVR, AFN, INR, AWG, KRW, NPR, JPY, MNT, AOA, PLN, GBP, SBD, BYN, HUF, BYR, BIF, MWK, MGA, XDR, BZD, BAM, EGP, MOP, NAD, NIO, PEN, NZD, WST, TMT, BRL]
 at [Source: (PushbackInputStream); line: 36, column: 5] (through reference chain: com.test.currencyrate.model.Rate["rates"])

	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:120)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:778)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:334)
	at com.test.currencyrate.repository.OpenExchangeRatesWs.load(OpenExchangeRatesWs.java:31)
	at com.test.currencyrate.repository.OpenExchangeRatesWs.load(OpenExchangeRatesWs.java:20)
	at com.test.currencyrate.repository.OpenExchangeRatesWs$$FastClassBySpringCGLIB$$4cd27f67.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at com.test.currencyrate.repository.OpenExchangeRatesWs$$EnhancerBySpringCGLIB$$1d759f2e.load(<generated>)
	at com.test.currencyrate.repository.OpenExchangeRatesWsTest.shouldLoadData(OpenExchangeRatesWsTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize Map key of type `com.test.currencyrate.model.CurrencyCode` from String "CLF": not a valid representation, problem: (com.fasterxml.jackson.databind.exc.InvalidFormatException) Cannot deserialize Map key of type `com.test.currencyrate.model.CurrencyCode` from String "CLF": not one of the values accepted for Enum class: [FJD, MXN, STD, SCR, TVD, CDF, BBD, GTQ, CLP, HNL, UGX, ZAR, TND, CUC, BSD, SLL, SDG, IQD, CUP, GMD, TWD, RSD, DOP, KMF, MYR, FKP, XOF, GEL, BTC, UYU, MAD, CVE, TOP, AZN, OMR, PGK, KES, SEK, BTN, UAH, GNF, ERN, MZN, SVC, ARS, QAR, IRR, MRO, CNY, THB, UZS, XPF, BDT, LYD, BMD, KWD, PHP, RUB, PYG, ISK, JMD, COP, MKD, USD, DZD, PAB, GGP, SGD, ETB, JEP, KGS, SOS, VEF, VUV, LAK, BND, XAF, LRD, CHF, HRK, ALL, DJF, ZMW, TZS, VND, SPL, AUD, ILS, GHS, GYD, KPW, BOB, KHR, MDL, IDR, KYD, AMD, BWP, SHP, TRY, LBP, TJS, JOD, AED, HKD, RWF, EUR, LSL, DKK, ZWD, CAD, BGN, MMK, MUR, NOK, SYP, IMP, GIP, RON, LKR, NGN, CRC, CZK, PKR, XCD, ANG, HTG, BHD, KZT, SRD, SZL, SAR, TTD, YER, MVR, AFN, INR, AWG, KRW, NPR, JPY, MNT, AOA, PLN, GBP, SBD, BYN, HUF, BYR, BIF, MWK, MGA, XDR, BZD, BAM, EGP, MOP, NAD, NIO, PEN, NZD, WST, TMT, BRL]; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize Map key of type `com.test.currencyrate.model.CurrencyCode` from String "CLF": not a valid representation, problem: (com.fasterxml.jackson.databind.exc.InvalidFormatException) Cannot deserialize Map key of type `com.test.currencyrate.model.CurrencyCode` from String "CLF": not one of the values accepted for Enum class: [FJD, MXN, STD, SCR, TVD, CDF, BBD, GTQ, CLP, HNL, UGX, ZAR, TND, CUC, BSD, SLL, SDG, IQD, CUP, GMD, TWD, RSD, DOP, KMF, MYR, FKP, XOF, GEL, BTC, UYU, MAD, CVE, TOP, AZN, OMR, PGK, KES, SEK, BTN, UAH, GNF, ERN, MZN, SVC, ARS, QAR, IRR, MRO, CNY, THB, UZS, XPF, BDT, LYD, BMD, KWD, PHP, RUB, PYG, ISK, JMD, COP, MKD, USD, DZD, PAB, GGP, SGD, ETB, JEP, KGS, SOS, VEF, VUV, LAK, BND, XAF, LRD, CHF, HRK, ALL, DJF, ZMW, TZS, VND, SPL, AUD, ILS, GHS, GYD, KPW, BOB, KHR, MDL, IDR, KYD, AMD, BWP, SHP, TRY, LBP, TJS, JOD, AED, HKD, RWF, EUR, LSL, DKK, ZWD, CAD, BGN, MMK, MUR, NOK, SYP, IMP, GIP, RON, LKR, NGN, CRC, CZK, PKR, XCD, ANG, HTG, BHD, KZT, SRD, SZL, SAR, TTD, YER, MVR, AFN, INR, AWG, KRW, NPR, JPY, MNT, AOA, PLN, GBP, SBD, BYN, HUF, BYR, BIF, MWK, MGA, XDR, BZD, BAM, EGP, MOP, NAD, NIO, PEN, NZD, WST, TMT, BRL]
 at [Source: (PushbackInputStream); line: 36, column: 5] (through reference chain: com.test.currencyrate.model.Rate["rates"])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:389)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:342)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:105)
	... 83 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize Map key of type `com.test.currencyrate.model.CurrencyCode` from String "CLF": not a valid representation, problem: (com.fasterxml.jackson.databind.exc.InvalidFormatException) Cannot deserialize Map key of type `com.test.currencyrate.model.CurrencyCode` from String "CLF": not one of the values accepted for Enum class: [FJD, MXN, STD, SCR, TVD, CDF, BBD, GTQ, CLP, HNL, UGX, ZAR, TND, CUC, BSD, SLL, SDG, IQD, CUP, GMD, TWD, RSD, DOP, KMF, MYR, FKP, XOF, GEL, BTC, UYU, MAD, CVE, TOP, AZN, OMR, PGK, KES, SEK, BTN, UAH, GNF, ERN, MZN, SVC, ARS, QAR, IRR, MRO, CNY, THB, UZS, XPF, BDT, LYD, BMD, KWD, PHP, RUB, PYG, ISK, JMD, COP, MKD, USD, DZD, PAB, GGP, SGD, ETB, JEP, KGS, SOS, VEF, VUV, LAK, BND, XAF, LRD, CHF, HRK, ALL, DJF, ZMW, TZS, VND, SPL, AUD, ILS, GHS, GYD, KPW, BOB, KHR, MDL, IDR, KYD, AMD, BWP, SHP, TRY, LBP, TJS, JOD, AED, HKD, RWF, EUR, LSL, DKK, ZWD, CAD, BGN, MMK, MUR, NOK, SYP, IMP, GIP, RON, LKR, NGN, CRC, CZK, PKR, XCD, ANG, HTG, BHD, KZT, SRD, SZL, SAR, TTD, YER, MVR, AFN, INR, AWG, KRW, NPR, JPY, MNT, AOA, PLN, GBP, SBD, BYN, HUF, BYR, BIF, MWK, MGA, XDR, BZD, BAM, EGP, MOP, NAD, NIO, PEN, NZD, WST, TMT, BRL]
 at [Source: (PushbackInputStream); line: 36, column: 5] (through reference chain: com.test.currencyrate.model.Rate["rates"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdKeyException(DeserializationContext.java:1968)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdKey(DeserializationContext.java:1173)
	at com.fasterxml.jackson.databind.deser.std.StdKeyDeserializer.deserializeKey(StdKeyDeserializer.java:138)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:531)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:440)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:391)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3682)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:378)
	... 85 more


```

Testing jackson configuration, Deserialization context feature is always false ! and this is this configuration used in StdKeyDeserializer class. The concerned line is: https://github.com/FasterXML/jackson-databind/blame/279d2001db6435ea1e92c48d9e796baa74403dd7/src/main/java/com/fasterxml/jackson/databind/deser/std/StdKeyDeserializer.java#L399

```
    @Autowired
    ObjectMapper objectMapper;

    @Test
    public void testOM() {
        //TRUE
        assertTrue(objectMapper.isEnabled(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL)); 
        //TRUE
assertTrue(objectMapper.getDeserializationConfig().isEnabled(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL));  
        //FALSE ??
assertTrue(objectMapper.getDeserializationContext().isEnabled(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL));  
    }
```

How can we get this ObjectMapper.getDeserializationContext().isEnabled(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL) to TRUE ?

**Comment by yawkat** [comment]
`ObjectMapper.getDeserializationContext()` is not affected by the config, but this is not a problem, because during deserialization a specific context will be created with the right settings.

I've made a simple test case and could not reproduce this issue:

```java
    public static void main(String[] args) throws SQLException, JsonProcessingException {
        ObjectMapper mapper = new ObjectMapper()
                .enable(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL);
        System.out.println(mapper.readValue("{\"FOO\":\"bar\",\"SOURCE\":\"baz\"}", new TypeReference<Map<RetentionPolicy, String>>() {})); // {null=bar, SOURCE=baz}
        System.out.println(mapper.readValue("\"FOO\"", new TypeReference<Map<RetentionPolicy, String>>() {})); // null
    }
```

The test case runs without error.

This is probably a spring issue. If you can make a test case that does not rely on spring, that would help.

**Comment by cowtowncoder** [comment]
As per @yawkat's comment this sounds like integration issue on Spring side. If not, we'd need a stand-alone (Jackson only) test case to show the problem with Jackson itself.

**Comment by Chaya56** [comment]
I got it working in pure jackson.
Indeed it seems related to spring integration, i got some clues in this issue: https://github.com/spring-projects/spring-boot/issues/2566
Thanks for your time !
