### ISSUE TITLE
StackOverflowError when writting POJO with recursive generic that extends Map

### ISSUE THREAD

**Issue by dherrman** [FasterXML/jackson-databind#339]
I have run into an issue that results in a StackOverflowError when trying to write out an object that extends a parent object, with a recursive generic that then extends Map.

```
    class Parent<A, T extends Parent> extends HashMap<String, A> {
        public T setValue(String key, A value) {
            super.put(key, value);
            return (T) this;
        }
    }

    class Child extends Parent<String, Child> {
    }

    public void doError {

        Child c = new Child();
        c.setValue("key", "value");

        ObjectMapper m = new ObjectMapper();
        String s = m.writeValueAsString(c);  // Throws StackOverflowError

        // I have tracked down the root cause to this method:
        m.getTypeFactory().findTypeParameters(Child.class, Map.class);  // Also throws StackOverflowError
    }
```

This give the following output:

```
Process finished with exit code 0
java.lang.StackOverflowError
	at java.lang.Class.getGenericInterfaces(Class.java:793)
	at org.codehaus.jackson.map.type.TypeFactory._doFindSuperInterfaceChain(TypeFactory.java:1114)
	at org.codehaus.jackson.map.type.TypeFactory._findSuperInterfaceChain(TypeFactory.java:1108)
	at org.codehaus.jackson.map.type.TypeFactory._findSuperTypeChain(TypeFactory.java:1062)
	at org.codehaus.jackson.map.type.TypeFactory.findTypeParameters(TypeFactory.java:405)
	at org.codehaus.jackson.map.type.TypeFactory.findTypeParameters(TypeFactory.java:399)
	at org.codehaus.jackson.map.type.TypeFactory._mapType(TypeFactory.java:995)
	at org.codehaus.jackson.map.type.TypeFactory._fromClass(TypeFactory.java:835)
	at org.codehaus.jackson.map.type.TypeFactory._constructType(TypeFactory.java:483)
	at org.codehaus.jackson.map.type.TypeFactory.findTypeParameters(TypeFactory.java:423)
	at org.codehaus.jackson.map.type.TypeFactory.findTypeParameters(TypeFactory.java:399)
	at org.codehaus.jackson.map.type.TypeFactory._mapType(TypeFactory.java:995)
<repeats a couple of hundred times>
```

I was able to reproduct this with version 1.9.13, 2.3.0-rc1 and HEAD.

PS: I don't know what to call the style of the Parent's generics, so I just guess with "recursive generic", if you know of something better, please comment.

**Comment by cowtowncoder** [comment]
Should be fixed for 2.7.
