### ISSUE TITLE
Nested array is not supported reference

### ISSUE THREAD

**Issue by jtamm-red** [FasterXML/jackson-databind#3434]
**Describe the bug**
I am using annotations (JsonManagedReference, JsonBackReference). 
I got error: 

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Problem deserializing property 'parentTable' (expected type: [simple type, class com.example.testspringboot25.models.Column]; actual type: `com.example.testspringboot25.models.Table`), problem: Can not set com.example.testspringboot25.models.Column field com.example.testspringboot25.models.Column.parentTable to java.util.ArrayList (through reference chain: com.example.testspringboot25.models.EditGrid["components"]->java.util.ArrayList[1]->com.example.testspringboot25.models.Table["rows"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:276) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:609) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:634) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.set(FieldProperty.java:193) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.impl.ManagedReferenceProperty.setAndReturn(ManagedReferenceProperty.java:90) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.impl.ManagedReferenceProperty.set(ManagedReferenceProperty.java:73) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.impl.ManagedReferenceProperty.deserializeAndSet(ManagedReferenceProperty.java:62) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:391) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:219) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:186) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:144) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:110) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:357) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.impl.ManagedReferenceProperty.deserializeAndSet(ManagedReferenceProperty.java:62) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:391) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:219) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:186) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:144) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:110) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2051) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1492) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1512) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	at com.example.testspringboot25.TestSpringBoot25Application.lambda$commandLineRunner$0(TestSpringBoot25Application.java:52) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) ~[spring-boot-2.5.6.jar:2.5.6]
	... 5 common frames omitted
Caused by: java.lang.IllegalArgumentException: Can not set com.example.testspringboot25.models.Column field com.example.testspringboot25.models.Column.parentTable to java.util.ArrayList
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[na:na]
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[na:na]
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[na:na]
	at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:75) ~[na:na]
	at java.base/java.lang.reflect.Field.set(Field.java:793) ~[na:na]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.set(FieldProperty.java:190) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]
	... 32 common frames omitted

```

Need to fix class ManagedReferenceProperty for nested array supporting. Possible use recursion method.

**Version information**
Which Jackson version(s) was this for?
2.13.2

**To Reproduce**
If you have a way to reproduce this with:
```java
public class Table {
    private List<List<Column>> rows;

    @JsonManagedReference
    public List<List<Column>> getRows() {
        if(rows == null) {
            rows = new ArrayList<>();
        }
        return rows;
    }
}

public class Column {
    @JsonBackReference
    private Table parentTable;
}

```

**Comment by cowtowncoder** [comment]
Would ideally need a full reproduction (not just class defs), but I think I understand the problem: managed/back references do not work for types  nested deeper than simple `List<Value>` containment.

There are no plans to try to add support for nested types; this is an implementation limitation and will likely remain so.
