### ISSUE TITLE
ObjectMapper#enableDefaultTyping(DefaultTyping, JsonTypeInfo.As) is not working properly

### ISSUE THREAD

**Issue by cemo** [FasterXML/jackson-databind#356]
Hi,

I could not be sure and wanted to report an issue. When I set  `objectMapper.enableDefaultTyping(ObjectMapper.DefaultTyping.NON_FINAL, JsonTypeInfo.As.EXISTING_PROPERTY);` , I am expecting that all types must add `@class` info to the their deserialization text. However some of them are using still using `WRAPPER_ARRAY`.

``` java
   public class HttpCookieDemo {

      private final String name;

      private final String value;

      public HttpCookieDemo(@JsonProperty("name") String name,
                            @JsonProperty("value") String value) {
         this.name = name;
         this.value = value;
      }

      public String getName() {
         return name;
      }

      public String getValue() {
         return value;
      }

   }

   public static HttpCookieDemo getHttpCookieDemo() {
      HttpCookieDemo httpCookieMixin = new HttpCookieDemo("Cemo", "a");
      return httpCookieMixin;
   }

   public static void main(String[] args) throws IOException {
      ObjectMapper objectMapper = new ObjectMapper();
      objectMapper.enableDefaultTyping(ObjectMapper.DefaultTyping.NON_FINAL, JsonTypeInfo.As.EXISTING_PROPERTY);
      objectMapper.enable(SerializationFeature.INDENT_OUTPUT);

      ArrayList<HttpCookieDemo> value = new ArrayList<HttpCookieDemo>();
      value.add(getHttpCookieDemo());
      value.add(getHttpCookieDemo());

      String output =  objectMapper.writeValueAsString(value);
      System.out.println(output);

      // try to deserialize 
      HttpCookieMixin o = objectMapper
                             .reader(HttpCookieDemo.class)
                             .readValue(output);
      System.out.println(o);

   }

```

For example the output is for deserialization:

``` json
[ "java.util.ArrayList", [ {
  "@class" : "com.fasterxml.jackson.support.HttpCookieDemo",
  "name" : "Cemo",
  "value" : "a"
}, {
  "@class" : "com.fasterxml.jackson.support.HttpCookieDemo",
  "name" : "Cemo",
  "value" : "a"
} ] ]
```

This is not what I am expecting. 

Also for deserialization it is raising an exception too. 

```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid type id 'java.util.ArrayList' (for id type 'Id.class'): Class java.lang.Class not subtype of [simple type, class com.fasterxml.jackson.support.HttpCookieDemo]
    at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:68)
    at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:48)
    at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:160)
    at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:104)
    at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromAny(AsArrayTypeDeserializer.java:80)
    at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:145)
    at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:76)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:921)
    at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:41)
    at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1270)
    at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:897)
    at com.fasterxml.jackson.support.Test.main(Test.java:93)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: java.lang.IllegalArgumentException: Class java.lang.Class not subtype of [simple type, class com.fasterxml.jackson.support.HttpCookieDemo]
    at com.fasterxml.jackson.databind.type.TypeFactory.constructSpecializedType(TypeFactory.java:188)
    at com.fasterx
```

I am using latest jackson source code.

**Comment by aniketrb-github** [comment]
**Source: https://segon.cn/jackson-objectmapper-enabledefaulttyping-deprecated.html**

The enableDefaultTyping method in Jackson ObjectMapper has been marked as expired from 2.10.0 for security reasons. It is recommended to use the activateDefaultTyping method instead. If you continue to use enableDefaultTyping, a warning will appear. We need to eliminate this warning now and take a look at the enableDefaultTyping source code (note @ deprecated information) 

```
/**
 * @deprecated Since 2.10 use {@link #activateDefaultTyping(PolymorphicTypeValidator,DefaultTyping)} instead
 */
public ObjectMapper enableDefaultTyping(DefaultTyping dti) {
    return enableDefaultTyping(dti, JsonTypeInfo.As.WRAPPER_ARRAY);
}
```

```
/**
 * @deprecated Since 2.10 use {@link #activateDefaultTyping(PolymorphicTypeValidator,DefaultTyping,JsonTypeInfo.As)} instead
 */
public ObjectMapper enableDefaultTyping(DefaultTyping applicability, JsonTypeInfo.As includeAs) {
    return activateDefaultTyping(getPolymorphicTypeValidator(), applicability, includeAs);
}
```

You can see that enableDefaultTyping actually calls the activateDefaultTyping method. The source code of the getPolymorphicTypeValidator method is as follows:

```
public PolymorphicTypeValidator getPolymorphicTypeValidator() {
    return _deserializationConfig.getBaseSettings().getPolymorphicTypeValidator();
}
```

Just hit a breakpoint in the getPolymorphicTypeValidator method of BaseSettings to see which instance of PolymorphicTypeValidator is used by default, as follows:

**So the code is modified as follows to eliminate the expiration warning:** 
```
Jackson2JsonRedisSerializer jackson2JsonRedisSerializer = new Jackson2JsonRedisSerializer(Object.class);
ObjectMapper om = new ObjectMapper();
om.setVisibility(PropertyAccessor.ALL, JsonAutoDetect.Visibility.ANY);
// om.enableDefaultTyping(ObjectMapper.DefaultTyping.NON_FINAL);  // deprecated method
om.activateDefaultTyping(LaissezFaireSubTypeValidator.instance, DefaultTyping.NON_FINAL);   // Resolution for deprecated enableDefaultTyping (...)
jackson2JsonRedisSerializer.setObjectMapper(om);
```

**Comment by cowtowncoder** [comment]
@aniketrb-github just to make sure: are you pointing out a way to achieve earlier (potentially) unsafe behavior without warning, to help upgrade existing code base? Or something else?
