### ISSUE TITLE
can't deseri enum filed

### ISSUE THREAD

**Issue by dulm** [FasterXML/jackson-databind#3594]
**Describe the bug**

```
@Getter
@AllArgsConstructor
public enum EInsureCataTbl {
    //@JsonProperty("WEST_CN_MED")
    WEST_CN_MED("ins_national_catalog_western_and_chinese_medicine", "1301"),
    //@JsonProperty("CN_HERBAL_SLICE")
    CN_HERBAL_SLICE("pms_build.ins_national_catalog_chinese_herbal_slices", "1302");

    @Setter
    private String tblName;
    @Setter
    private String infono;
}
```

```
@Data
public class TpInsCataSpecVersion {
    EInsureCataTbl eInsureCataTbl;
    String curMaxVer;
}
```

```
       ObjectMapper objectMapper = new ObjectMapper();
        String jsonStr = "{\"eInsureCataTbl\":\"WEST_CN_MED\",\"curMaxVer\":\"20220325\"}";
        TpInsCataSpecVersion tpInsCataSpecVersion =
                objectMapper.readValue(jsonStr, TpInsCataSpecVersion.class);

```

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.4.3.jar:2.4.3]
	at club.walnuts.pms.insure.sheduler.InsureShedulerApp.main(InsureShedulerApp.java:47) ~[main/:?]
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "eInsureCataTbl" (class club.walnuts.pms.insure.sheduler.data.TpInsCataSpecVersion), not marked as ignorable (2 known properties: "einsureCataTbl", "curMaxVer"])
 at [Source: (String)"{"eInsureCataTbl":"WEST_CN_MED","curMaxVer":"20220325"}"; line: 1, column: 20] (through reference chain: club.walnuts.pms.insure.sheduler.data.TpInsCataSpecVersion["eInsureCataTbl"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1212) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1604) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1582) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:299) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3468) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3436) ~[jackson-databind-2.11.4.jar:2.11.4]
	at club.walnuts.pms.insure.sheduler.InsureShedulerApp.run(InsureShedulerApp.java:89) ~[main/:?]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) ~[spring-boot-2.4.3.jar:2.4.3]
	... 5 more

```

**Version information**
Which Jackson version(s) was this for?
2.11.4

**To Reproduce**
If you have a way to reproduce this with:

1. Brief code sample/snippet: include here in preformatted/code section
2. Longer example stored somewhere else (diff repo, snippet), add a link
3. Textual explanation: include here

**Expected behavior**
If reproduction itself needs further explanation, you may also add more details here.

**Additional context**

**Comment by yawkat** [comment]
please make an example that does not rely on lombok. but this is likely the same issue as this one: https://github.com/FasterXML/jackson-databind/issues/3323#issuecomment-966091655

**Comment by dulm** [comment]
> please make an example that does not rely on lombok. but this is likely the same issue as this one: [#3323 (comment)](https://github.com/FasterXML/jackson-databind/issues/3323#issuecomment-966091655)

thank you, fixed
