### ISSUE TITLE
 java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonParser.getReadCapabilities()Lcom/fasterxml/jackson/core/util/JacksonFeatureSet

### ISSUE THREAD

**Issue by pradeepagrawal8184** [FasterXML/jackson-databind#3635]
**Describe the bug**
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonParser.getReadCapabilities()Lcom/fasterxml/jackson/core/util/JacksonFeatureSet;

**Version information**
2.13.3 and 2.13.4

```
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonParser.getReadCapabilities()Lcom/fasterxml/jackson/core/util/JacksonFeatureSet;
	at com.fasterxml.jackson.databind.DeserializationContext.<init>(DeserializationContext.java:212)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.<init>(DefaultDeserializationContext.java:50)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl.<init>(DefaultDeserializationContext.java:391)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl.createInstance(DefaultDeserializationContext.java:413)
	at com.fasterxml.jackson.databind.ObjectMapper.createDeserializationContext(ObjectMapper.java:4737)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4666)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3494)
	at org.cloudera.log4j.redactor.StringRedactor.createFromJsonFile(StringRedactor.java:248)
	at org.cloudera.log4j.redactor.RedactorPolicy.activateOptions(RedactorPolicy.java:52)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:284)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:160)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:140)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:100)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:802)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:738)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:630)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:516)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:577)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:504)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:119)
	at org.apache.log4j.PropertyWatchdog.doOnChange(PropertyConfigurator.java:911)
	at org.apache.log4j.helpers.FileWatchdog.checkAndConfigure(FileWatchdog.java:85)
	at org.apache.log4j.helpers.FileWatchdog.<init>(FileWatchdog.java:59)
	at org.apache.log4j.PropertyWatchdog.<init>(PropertyConfigurator.java:903)
	at org.apache.log4j.PropertyConfigurator.configureAndWatch(PropertyConfigurator.java:479)
```

**Additional context**
Tried all possible combination of 2.13.x and 2.14.x but facing same error.

**Comment by yawkat** [comment]
You have jackson-core < 2.12 somewhere on your classpath.
