### ISSUE TITLE
Add enum features into `@JsonFormat.Feature`

### ISSUE THREAD

**Issue by Anatoly4444** [FasterXML/jackson-databind#3637]
com.fasterxml.jackson.annotation

I have several enum objects which jackson deserialize and requests failed after third company API updated possible values in this object. And also i don't want to add this Feature for whole project cause this feature could broke logic for another requests.

Jackson has com.fasterxml.jackson.annotation.JsonFormat.Feature which could be added on certain class but for now that does not support READ_UNKNOWN_ENUM_VALUES_AS_NULL and READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE. Please add

@cowtowncoder said i should create issue here, not in jackson-annotations

**Comment by cowtowncoder** [comment]
Thank you @Anatoly4444 -- yes, this is slightly better place since support must be added here too; and adding entries in `jackson-annotations` can be done as part of implementation (filing separate issue only when working on making things work).

**Comment by cowtowncoder** [comment]
Adding labels to indicate that help would be welcome here, and that I think this is relatively straight-forward to implement.

**Comment by cowtowncoder** [comment]
Merged, to be included in 2.15.0. Thank you for the contribution @Siwach16!

**Comment by hrishikeshakolkar** [comment]
Hello, i am upgrading my work project to jackson version 2.15.0 to fix vulnerabilities, and have received below error.
Need help... :( 

org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchFieldError: READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1082)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
.............

**Comment by cowtowncoder** [comment]
@hrishikeshakolkar You seem to have version incompatibility between what framework expects (was compiled against) and what is deployed: specifically you likely have `jackson-databind` version older than what is needed.
But like @JooHyukKim said, this is something wrt your deployment or framework; not something Jackson project can help with.
