### ISSUE TITLE
The Jackson problem is happened when i use spark to submit

### ISSUE THREAD

**Issue by chuhaobo** [FasterXML/jackson-databind#3671]
> the method belong to SparkSession , the name is getOrCreate()

deatil exception is
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JsonMappingException.<init>(Ljava/io/Closeable;Ljava/lang/String;)V
    at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
    at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
    at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
    at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:718)
    at org.apache.spark.util.JsonProtocol$.<init>(JsonProtocol.scala:62)
    at org.apache.spark.util.JsonProtocol$.<clinit>(JsonProtocol.scala)
    at org.apache.spark.scheduler.EventLoggingListener.initEventLog(EventLoggingListener.scala:89)
    at org.apache.spark.scheduler.EventLoggingListener.start(EventLoggingListener.scala:84)
    at org.apache.spark.SparkContext.<init>(SparkContext.scala:610)
    at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2690)
    at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:949)
    at scala.Option.getOrElse(Option.scala:189)
    at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:943)
    at com.hiido.server.service.impl.SparkSqlJob.executing(SparkSqlJob.java:56)
    at com.hiido.server.service.impl.SparkSqlJob.main(SparkSqlJob.java:47)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:737)

someone point it's happened at version conflict , I disagree about it. 
because I have checkout my spark version is spark_core_2.12-3.2.1 and jackson version is 2.12.3.
I have on idea about this problem.
thx.

**Comment by pjfanning** [comment]
Check the version of jackson-module-scala_2.12 jar that you have on your classpath.
You should only have version 2.12.3.

Remember that if this was a problem for all users of spark_core_2.12-3.2.1, then noone would be able to use spark_core_2.12-3.2.1. There is something strange about the jar setup that you have.

**Comment by chuhaobo** [comment]
> 
thank you so much
I will check to my version.
I wil back to reply if I solve the problem

**Comment by chuhaobo** [comment]
> Check the version of jackson-module-scala_2.12 jar that you have on your classpath. You should only have version 2.12.3.
> 
> Remember that if this was a problem for all users of spark_core_2.12-3.2.1, then noone would be able to use spark_core_2.12-3.2.1. There is something strange about the jar setup that you have.

thank you so much
I will check to my version.
I wil back to reply if I solve the problem

**Comment by jfrylings-twilio** [comment]
@chuhaobo
I am having the same exact issue during mvn tests and it was indeed a classpath issue.
On my Mac my .bashrc the PATH variable had an old install of spark in there.  The /jars directory in there did in fact have a 2.6 version of jackson-bind.  So I deleted that old directory and now I'm not seeing those errors.

The confusing thing was even with forcing jackson versions in `dependencyManagement`, including the dependency as scope compile (instead of provided), and then running `mvn dependency:tree` it was still showing the 2.12.3 versions
