### ISSUE TITLE
Error when deserializing a class with a property of classMethod

### ISSUE THREAD

**Issue by jsolferreira** [FasterXML/jackson-databind#3713]
**Describe the bug**
When trying to deserialize a class with a property of class Method an InaccessibleObjectException happens

**Version information**
Which Jackson version(s) was this for?
2.1411

**To Reproduce**
If you have a way to reproduce this with:
```java
public static void main(String[] args) throws IOException {
    ObjectMapper objectMapper = new ObjectMapper();

    MessageProperties messageProperties = new MessageProperties();
    Message message = new Message("{}".getBytes(), messageProperties);

    byte[] bytes = objectMapper.writeValueAsBytes(message);

    objectMapper.readValue(bytes, Message.class);
}
```
```java
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-amqp:2.4.1'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.14.1'
}
```

```
Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type `java.lang.reflect.Method`: Failed to call `setAccess()` on Field 'parameters' (of class `java.lang.reflect.Executable`) due to `java.lang.reflect.InaccessibleObjectException`, problem: Unable to make field private transient volatile java.lang.reflect.Parameter[] java.lang.reflect.Executable.parameters accessible: module java.base does not "opens java.lang.reflect" to unnamed module @1572270e
 at [Source: (byte[])"{"messageProperties":{"headers":{},"timestamp":null,"messageId":null,"userId":null,"appId":null,"clusterId":null,"type":null,"correlationId":null,"replyTo":null,"contentType":"application/octet-stream","contentEncoding":null,"contentLength":0,"deliveryMode":"PERSISTENT","expiration":null,"priority":0,"redelivered":null,"receivedExchange":null,"receivedRoutingKey":null,"receivedUserId":null,"deliveryTag":0,"messageCount":null,"consumerTag":null,"consumerQueue":null,"receivedDelay":null,"receivedD"[truncated 237 bytes]; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadTypeDefinition(DeserializationContext.java:1887)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder._handleBadAccess(BeanDeserializerBuilder.java:620)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder._fixAccess(BeanDeserializerBuilder.java:537)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder.build(BeanDeserializerBuilder.java:384)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:151)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:415)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:350)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:638)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:539)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:638)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:539)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:648)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4861)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4731)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3738)
	at org.example.Main.main(Main.java:28)
Caused by: java.lang.IllegalArgumentException: Failed to call `setAccess()` on Field 'parameters' (of class `java.lang.reflect.Executable`) due to `java.lang.reflect.InaccessibleObjectException`, problem: Unable to make field private transient volatile java.lang.reflect.Parameter[] java.lang.reflect.Executable.parameters accessible: module java.base does not "opens java.lang.reflect" to unnamed module @1572270e
	at com.fasterxml.jackson.databind.util.ClassUtil.checkAndFixAccess(ClassUtil.java:1008)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.fixAccess(FieldProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder._fixAccess(BeanDeserializerBuilder.java:535)
	... 23 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private transient volatile java.lang.reflect.Parameter[] java.lang.reflect.Executable.parameters accessible: module java.base does not "opens java.lang.reflect" to unnamed module @1572270e
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.fasterxml.jackson.databind.util.ClassUtil.checkAndFixAccess(ClassUtil.java:995)
	... 25 more
```

**Expected behavior**
If reproduction itself needs further explanation, you may also add more details here.

**Additional context**

**Comment by pjfanning** [comment]
With newer Java versions, you could try adding something like this to your Java call

`--add-opens java.base/java.lang=ALL-UNNAMED`

Or you could try an older Java version, eg Java 11 -- these restrictions on what code can call java.lang.reflect have been added to Java recently.

**Comment by pjfanning** [comment]
You haven't provided your MessageProperties class. It may be possible to avoid Java reflection setAccess calls if you provide setter methods for all the fields in your class.

**Comment by jsolferreira** [comment]
The MessageProperties class is from spring amqp library (https://github.com/spring-projects/spring-amqp/blob/main/spring-amqp/src/main/java/org/springframework/amqp/core/MessageProperties.java). Sorry for not providing it previously.

Adding the add opens flag will indeed fix the error. Is there any plans to avoid adding this flag or this will be the way to go?

**Comment by pjfanning** [comment]
Unfortunately, Java is not providing a way to avoid this. Java users will have to get used to configuring their JVMs to enable features instead of all features being enabled by default (including dangerous features).

Personally, I always create DTO classes so that I can avoid issues with trying to bind to classes that have not been designed for easy binding.

**Comment by cowtowncoder** [comment]
The issue here may have more to do (I think) in certain properties not being excluded than with actual access.
Types referenced do not look like they should ever be serialized. For example:

    Failed to call `setAccess()` on Field 'parameters' (of class `java.lang.reflect.Executable`)

would suggest attempt to serialize `Executable` which really won't work without custom serializer; although more likely whatever is referencing it should indicate ignoral.

Given this I think this is more related to how to add support for 3rd party library types.
