### ISSUE TITLE
[master branch only] InaccessibleObjectException: Unable to make field final int java.math.MathContext.precision accessible

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-databind#3715]
Fails with Jackson master/3.0 code only - works fine in Jackson 2.14 and 2.15 branches.

Fails only with Java 17 (not an issue with Java 8 or 11). I tend to concentrate on LTS versions of Java.

I found this testing deserialising numbers in Scala (Scala basically uses the Java number primitives and classes with some syntactic sugar added).

I'll provide the Scala code now and look at providing a Java equivalent later. I think the code is relatively easy to understand anyway.

```
    val mapper = JsonMapper.builder()
      .enable(StreamReadFeature.USE_FAST_DOUBLE_PARSER)
      .enable(StreamReadFeature.USE_FAST_BIG_NUMBER_PARSER)
      .build()
    Seq("1.0E+2", "1.0e+2", "1.0e2", "1.234e-234").foreach { numString =>
      mapper.readValue(numString, classOf[BigDecimal]) shouldBe BigDecimal(numString)
    }
```

The key part of the stacktrace is when tools.jackson.databind.util.ClassUtil.checkAndFixAccess is called to change the precision field on java.math.MathContext. Somehow, older versions of Jackson avoid this.

Note that this issue only seems to happens with StreamReadFeatures are enabled. I'm not sure why this is the case - nothing in stack trace indicates why there should be a difference in behaviour. 

```
[info] - should deserialize to BigDecimal a number in exponent form (Fast number parsing) *** FAILED ***
[info]   tools.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type `java.math.MathContext`: Failed to call `setAccess()` on Field 'precision' (of class `java.math.MathContext`) due to `java.lang.reflect.InaccessibleObjectException`, problem: Unable to make field final int java.math.MathContext.precision accessible: module java.base does not "opens java.math" to unnamed module @4ec38f1
[info]  at [Source: (String)"1.0E+2"; line: 1, column: 1]
[info]   at tools.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:60)
[info]   at tools.jackson.databind.DeserializationContext.reportBadTypeDefinition(DeserializationContext.java:1848)
[info]   at tools.jackson.databind.deser.BeanDeserializerBuilder._handleBadAccess(BeanDeserializerBuilder.java:611)
[info]   at tools.jackson.databind.deser.BeanDeserializerBuilder._fixAccess(BeanDeserializerBuilder.java:489)
[info]   at tools.jackson.databind.deser.BeanDeserializerBuilder.build(BeanDeserializerBuilder.java:378)
[info]   at tools.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:289)
[info]   at tools.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:151)
[info]   at tools.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:393)
[info]   at tools.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:330)
[info]   at tools.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:244)
[info]   ...
[info]   Cause: java.lang.IllegalArgumentException: Failed to call `setAccess()` on Field 'precision' (of class `java.math.MathContext`) due to `java.lang.reflect.InaccessibleObjectException`, problem: Unable to make field final int java.math.MathContext.precision accessible: module java.base does not "opens java.math" to unnamed module @4ec38f1
[info]   at tools.jackson.databind.util.ClassUtil.checkAndFixAccess(ClassUtil.java:836)
[info]   at tools.jackson.databind.deser.impl.FieldProperty.fixAccess(FieldProperty.java:103)
[info]   at tools.jackson.databind.deser.BeanDeserializerBuilder._fixAccess(BeanDeserializerBuilder.java:487)
[info]   at tools.jackson.databind.deser.BeanDeserializerBuilder.build(BeanDeserializerBuilder.java:378)
[info]   at tools.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:289)
[info]   at tools.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:151)
[info]   at tools.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:393)
[info]   at tools.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:330)
[info]   at tools.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:244)
[info]   at tools.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:225)
[info]   ...
[info]   Cause: java.lang.reflect.InaccessibleObjectException: Unable to make field final int java.math.MathContext.precision accessible: module java.base does not "opens java.math" to unnamed module @4ec38f1
[info]   at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
[info]   at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[info]   at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
[info]   at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
[info]   at tools.jackson.databind.util.ClassUtil.checkAndFixAccess(ClassUtil.java:822)
[info]   at tools.jackson.databind.deser.impl.FieldProperty.fixAccess(FieldProperty.java:103)
[info]   at tools.jackson.databind.deser.BeanDeserializerBuilder._fixAccess(BeanDeserializerBuilder.java:487)
[info]   at tools.jackson.databind.deser.BeanDeserializerBuilder.build(BeanDeserializerBuilder.java:378)
[info]   at tools.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:289)
[info]   at tools.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:151)
[info]   ...
```

**Comment by yawkat** [comment]
this test case passes fine for me on java 17 on the master branch:

```java
    @Test
    public void test() {
        JsonMapper mapper = JsonMapper.builder()
                .enable(StreamReadFeature.USE_FAST_DOUBLE_PARSER)
                .enable(StreamReadFeature.USE_FAST_BIG_NUMBER_PARSER)
                .build();
        Assert.assertEquals(mapper.readValue("1.0E+2", BigDecimal.class), new BigDecimal("1.0E+2"));
        Assert.assertEquals(mapper.readValue("1.0e+2", BigDecimal.class), new BigDecimal("1.0e+2"));
        Assert.assertEquals(mapper.readValue("1.0e2", BigDecimal.class), new BigDecimal("1.0e2"));
        Assert.assertEquals(mapper.readValue("1.234e-234", BigDecimal.class), new BigDecimal("1.234e-234"));
    }
```

**Comment by pjfanning** [comment]
@yawkat thanks for checking. It seems that the scala.math.BigDecimal class is going through a different code path than is followed if java.lang.BigDecimal was used. I can confirm java.lang.BigDecimal works ok.

**Comment by pjfanning** [comment]
Of course, the issue was that I didn't add the DefaultScalaModule. I'll close this - apologies for wasting everyone's time.

**Comment by cowtowncoder** [comment]
Ok just glad you figured it out, @pjfanning!
