### ISSUE TITLE
`@JsonValue` does not work with `@JsonTypeInfo` for subtype values

### ISSUE THREAD

**Issue by Wouter1** [FasterXML/jackson-databind#3777]
I get exceptions and sub-terms disappear when I use @JsonValue.

Here is the code to reproduce
```
package test.java;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class test {
	final ObjectMapper jackson = new ObjectMapper();
	final N n = new N();

	@Test
	public void test1() throws JsonProcessingException {
		doTest(new Y(n));
	}

	@Test
	public void test2() throws JsonProcessingException {
		doTest(new Y(new Y(n)));
	}

	@Test
	public void testWeirdYDisappears() throws JsonProcessingException {
		doTest(new Z(new Y(n)));
	}

	@Test
	public void testFails() throws JsonProcessingException {
		doTest(new Z(n));
	}

	private void doTest(X val) throws JsonProcessingException {
		System.out.println("testing " + val);
		String str = jackson.writeValueAsString(val);
		System.out.println("To json: " + str);
		X obj = jackson.readValue(str, X.class);
		System.out.println("reparsed: " + obj);

		assertEquals(val.toString(), obj.toString());

	}
}

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.WRAPPER_OBJECT)
@JsonAutoDetect(fieldVisibility = Visibility.ANY, getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE)
@JsonSubTypes({ @JsonSubTypes.Type(value = Y.class),
		@JsonSubTypes.Type(value = Z.class),
		@JsonSubTypes.Type(value = N.class) })
interface X {
}

class N implements X {

	@Override
	public String toString() {
		return "N";
	}

}

class Y implements X {

	// NOT @JsonValue - works
	private final X value;

	@JsonCreator
	public Y(@JsonProperty("value") X val) {
		this.value = val;
	}

	@Override
	public String toString() {
		return "Y(" + value + ")";
	}

}

class Z implements X {
	@JsonValue
	private final X value;

	@JsonCreator
	public Z(@JsonProperty("value") X val) {
		this.value = val;
	}

	@Override
	public String toString() {
		return "Z(" + value + ")";
	}

}
``` 
with pom
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>test</groupId>
	<artifactId>test</artifactId>
	<version>2.1</version>
	<packaging>jar</packaging>

	<name>test</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.target>1.8</maven.compiler.target>
		<maven.compiler.source>1.8</maven.compiler.source>
		<basedir>.</basedir>
		<jackson-2-version>2.14.2</jackson-2-version>
	</properties>


	<dependencies>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>${jackson-2-version}</version>
		</dependency>

		<!-- Just the annotations; use this dependency if you want to attach annotations 
			to classes without connecting them to the code. -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>${jackson-2-version}</version>
		</dependency>

		<!-- databinding; ObjectMapper, JsonNode and related classes are here -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson-2-version}</version>
		</dependency>

		<!-- smile (binary JSON). Other artifacts in this group do other formats. -->
		<dependency>
			<groupId>com.fasterxml.jackson.dataformat</groupId>
			<artifactId>jackson-dataformat-smile</artifactId>
			<version>${jackson-2-version}</version>
		</dependency>
		<!-- JAX-RS provider -->
		<dependency>
			<groupId>com.fasterxml.jackson.jaxrs</groupId>
			<artifactId>jackson-jaxrs-json-provider</artifactId>
			<version>${jackson-2-version}</version>
		</dependency>
		<!-- Support for JAX-B annotations as additional configuration -->
		<dependency>
			<groupId>com.fasterxml.jackson.module</groupId>
			<artifactId>jackson-module-jaxb-annotations</artifactId>
			<version>${jackson-2-version}</version>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-all</artifactId>
			<version>1.9.5</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>

	</dependencies>

	<build>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>3.1.0</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>


	</build>


</project>

```

output:
```
testing Z(N)
To json: {"Z":{}}
-exception

testing Z(Y(N))
To json: {"Z":{"value":{"N":{}}}}
-exception

testing Y(N)
To json: {"Y":{"value":{"N":{}}}}
reparsed: Y(N)
- success

testing Y(Y(N))
To json: {"Y":{"value":{"Y":{"value":{"N":{}}}}}}
reparsed: Y(Y(N))
-success
```

The Z(...) all fail with excceptions, like
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Unexpected token (END_OBJECT), expected START_OBJECT: need JSON Object to contain As.WRAPPER_OBJECT type information for class test.java.X
 at [Source: (String)"{"Z":{}}"; line: 1, column: 7]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:1944)
	at com.fasterxml.jackson.databind.DeserializationContext.reportWrongTokenException(DeserializationContext.java:1678)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:100)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromObject(AsWrapperTypeDeserializer.java:52)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1398)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:121)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromObject(AsWrapperTypeDeserializer.java:52)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
	at test.java.test.doTest(test.java:45)
	at test.java.test.testFails(test.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at j...
```

As you can see, the Z(N) when serialized has no N term anymore,
and the Z(Y(N)) term after serialization has not Y(N) but only N

I would expect Z(n) to serialize to json as ```{"Z":{"N":{}}}```
and Z(Y(n)) as ```{"Z":{"Y":{"value":{"N":{}}}}}```

If I use Y instead of Z, which does not have the @JsonValue annotation, it works all fine.

Not sure if it's relevant but something changed recently around @JsonValue so this may be a flawed bug fix,  @JsonValue is a troublesome area for a long time. There previously were issues when used in combination with List where jackson failed to add TypeInfo if it was needed. And previously you had to omit @JsonProperty annotations in the constructor when using together with @JsonValue.

**Comment by cowtowncoder** [comment]
(marking as "need-test-case" to indicate that what'd be great is more _minimal_ test case -- given example is so big it distracts)

**Comment by cowtowncoder** [comment]
I don't think this is a use case that can or should be supported -- it makes no sense to me that the super type `X` would be used via `@JsonValue` for a subtype -- nor how exactly coudl that work via `@JsonCreator`. I don't know what is supposed to the use case but that will not work.

**Comment by cowtowncoder** [comment]
@Wouter1 as per my above comment, I don't think this can work; and I also do not really understand what the intent would be. Your interface type `X` cannot both be a super type and then surrogate to return with `@JsonValue`. Or, similarly, when reading things back via `@JsonCreator`.

**Comment by Wouter1** [comment]
@cowtowncoder  
sorry for the late reply. Maybe I never got an email from this, or maybe it got lost somewhere. Also I switched between projects a number of times which didn't help allocating time for this.

The case I was working on was on serializing boolean expressions X. N is the bottom object, true or false. Y and Z are both something like Not(X). I made a shorter example stripping all of that, to make a short as possible example showing the issue.

So for example in my boolean code the json result should be "Not":{"Not":true} rather than "Not":{"value":{"Not":{"value":true}}. 

FAIK you need to use @JsonValue to prevent jackson to use the field names ("value"). 

I want this to make the terms more human readable.

>Your interface type X cannot both be a super type and then surrogate to return with @JsonValue

I don't see the problem. As I understand it @JsonValue is to tell the (de)serializer that we already know the field name and to just give the value. 
X has the annotation @JsonSubTypes  and @JsonTypeInfo so jackson can insert the type information as required? 

Does that make sense?

**Comment by Wouter1** [comment]
@cowtowncoder was this issue fixed?

**Comment by JooHyukKim** [comment]
@Wouter1 can you try testing out cause you were part of the conversation? From what I see, I don't think so.
