### ISSUE TITLE
Get exception when deserializing generic type as String in jackson-databind 2.13.4.2

### ISSUE THREAD

**Issue by zhiyazw** [FasterXML/jackson-databind#3815]
I have a project which needs to deserialize json with generic type.
I previously deserialize the generic type as String then convert it to the concrete type, it worked in jackson-databind 2.10.4
But when I upgrade it to 2.13.4.2 recently, it throws below exception:
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (URL); line: 1, column: 13] (through reference chain: com.example.jackson.domain.MyMessage$MyMessageBuilder["content"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1420)
	at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:932)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:62)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:158)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3571)
	at com.example.jackson.service.MessageQueue.deserialize(MessageQueue.java:23)
	at Test.main(Test.java:12)
```
I attached a demo project: [jackson.tar.gz](https://github.com/FasterXML/jackson-databind/files/10916943/jackson.tar.gz)

With @cowtowncoder 's kind help in Gitter (thread: https://matrix.to/#/!wakNlZHEuVNSzNedMT:gitter.im/$FoygV-hfwe5OkeJHc0iuE89n7Pvzw2u46q6hiVl6j3g?via=gitter.im&via=matrix.org), I've realized `deserialize generic type as String` might be incorrect.

I had some attempts and recorded them down in the comments in jackson/src/main/java/com/example/jackson/service/MessageQueue.java
. Such as:

- deserializing generic type as Object
- deserializing generic type as generic type.

Could someone help me clarify that, in such use case (deserialize generic type)

1. Which or what approach is the best practice?
2. Is it possible that ObjectMapper.readValue return the concrete type directly instead of LinkedHashMap? So that I don't have to use the subsequent ObjectMapper.convertValue in MessageQueue.java

**Comment by cowtowncoder** [comment]
Ok. This project has some issues

1. Uses print statements to "show" the problem, instead of proper assertions
2. Uses Lombok so my IDE shows errors for missing generated accessors (works from shell with maven) -- I don't want to have to configure things to work with a framework (I know Lombok is popular but I hate that it requires configuration changes)

**Comment by zhiyazw** [comment]
@cowtowncoder Thanks for quick response. 

yeah, print is used instead of assertions.

As to lombok, in recent days investigation, I found "Deserializing generic type as String" didn't work without the generated code from lombok even in jackson-databind 2.10.4, but it did work when annotating MyMessage with lombok annotations. So I keep lombok in order to show this originally worked. Sorry not to expose this in the first post.

I attach a new tar ball which removes lombok: [jackson_nolombok.tar.gz](https://github.com/FasterXML/jackson-databind/files/10918066/jackson_nolombok.tar.gz)
The two questions in my first post are still expected

**Comment by cowtowncoder** [comment]
To answer questions I need to see actual type declarations and code. I hope new tarball makes that easier as I can examine code in Eclipse.

But fundamentally of course JSON Object cannot be deserialized as `String` so there appears to be some structural incompatibility.

**Comment by zhiyazw** [comment]
Agree that it's incorrect to deserialize JSON Object as `String`.

FYI, there're two dummy actual definitions of generic type M, they're `ContentType1` and `ContentType2`

**Comment by cowtowncoder** [comment]
@zhiyazw I do not understand why you think that `MyMessage<String>` would be type to map JSON like:

```
{"content": {"id": 1}}
```

where value is JSON Object ```{"id": 1}```.

Content that would map would be

```
{"content": "string value"}
```

How would that work? JSON Objects are not Strings, and they do map to `java.lang.String`.
They map to all kinds of things, from JDK `Map`s to POJOs and so on. But not to Strings.
I am not sure how that would have worked on 2.10...

But I think I understand what you are trying to do: bind first into intermediate type, then convert.
For that you need to use another target type, most likely either:

* `JsonNode` (to get ObjectNodes etc)
* `java.lang.Object` (Maps, Lists, Strings etc)

either of which can then be converted using `convertValue()`.

So use one of these instead of `String` and I think that'll get you further.

PS. I suspect that perhaps 2.10 had a bug in which `String` nominal type was lost and binding actually used `java.lang.Object` target. If so, it might all have just accidentally worked. Type resolution of generic types has been improved by incremental fixes over time; sometimes types that were lost are being properly resolved. Usually this helps fix broken cases but I guess it can also have hidden some problems.

**Comment by zhiyazw** [comment]
I believe it's a proper guess that `String` has just accidentally worked in 2.10. 

Further more, it only works when MyMessage is annotated with lombok annotations as in the first tar ball: [jackson.tar.gz](https://github.com/FasterXML/jackson-databind/files/10916943/jackson.tar.gz), even in 2.10. Otherwise without lombok it throws the following exception
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (URL); line: 1, column: 13] (through reference chain: com.example.jackson.domain.MyMessage["content"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1445)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1219)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1129)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:63)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:10)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3156)
	at com.example.jackson.service.MessageQueue.deserialize(MessageQueue.java:23)
	at Test.main(Test.java:12)
```
This exception looks similar but slightly different from the one in 2.13.4.2 in my first post. See if this helps if you're trying locating the cause in 2.10.

**Comment by zhiyazw** [comment]
As to my questions, with your guidance, I decide to read generic types as `Object` then convert, I'm good to go

**Comment by cowtowncoder** [comment]
@zhiyazw Thanks!

Yeah 2.10 is pretty old so knowing why behavior appeared to work is probably not something I'll spend a lot of time on. But it is good you can work around the problem.
