### ISSUE TITLE
@JsonIgnoreProperties fails on a property when a property value references its own bean

### ISSUE THREAD

**Issue by benze** [FasterXML/jackson-databind#382]
As per http://jackson-users.ning.com/xn/detail/5286555:Comment:30416

When using @JsonIgnoreProperties at a property level, if a property in the bean references its own bean, the annotation is ignored.

For example:

This fails:
@Entity
public class User {
   long id;
   String name;
   String city;
   ...
   @JsonIgnoreProperties User createdBy;
}

If createdBy references the same instance of User, a cyclic error is thrown by BeanPropertyWriter.  The following stack trace is thrown:

com.fasterxml.jackson.databind.JsonMappingException: Direct self-reference leading to cycle (through reference chain: java.util.HashMap["user"]->com.ia.domain.User["createdBy"])
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter._handleSelfReference(BeanPropertyWriter.java:740)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:537)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:632)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:467)
at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:388)
at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:27)
at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1837)
at org.springframework.web.servlet.view.json.MappingJackson2JsonView.writeContent(MappingJackson2JsonView.java:302)
at org.springframework.web.servlet.view.json.MappingJackson2JsonView.renderMergedOutputModel(MappingJackson2JsonView.java:257)
at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:263)
at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1208)
....
....

The error is generated by the cyclic check in the BeanPropertyWriter since this particular User refers to itself (ie: the createdBy value points back to itself).  The cyclic check checks to ensure that the value being serialized is not the same as the bean, and in this case, it is.

**Comment by fenfangchen** [comment]
Hi, could you tell me the last is how to solve this problem?can

**Comment by cowtowncoder** [comment]
@fenfangchen At this point it is possible to disable `SerializationFeature.FAIL_ON_SELF_REFERENCES` to get rid of the exception.

**Comment by fenfangchen** [comment]
Thanks,maybe I need study more on it.

**Comment by prabhash1785** [comment]
@cowtowncoder What version of Jackson does SerializationFeature.FAIL_ON_SELF_REFERENCES have? I can't find this property here" https://fasterxml.github.io/jackson-databind/javadoc/2.0.0/index.html?com/fasterxml/jackson/databind/ObjectWriter.html

**Comment by cowtowncoder** [comment]
@prabhash1785 Jackson javadocs try to include `@since` tags, so you can have a look at latest javadocs you find to figure this out.

**Comment by prabhash1785** [comment]
thanks found it in version 2.4!
