### ISSUE TITLE
Polymorphic type validator causes error deserializing array of objects to List<Object>

### ISSUE THREAD

**Issue by idoub** [FasterXML/jackson-databind#3881]
**Describe the bug**
When using default deserialization, mapping JSON array of objects to List<Object> works but adding basic polymorphic type validation causes it to fail.

**Version information**
com.fasterxml.jackson.core:jackson-databind:2.14.2

**To Reproduce**
```
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.jsontype.BasicPolymorphicTypeValidator;
import com.fasterxml.jackson.databind.jsontype.PolymorphicTypeValidator;

import java.util.List;

public class Main {
    public static void main(String args[]) throws JsonProcessingException {
        String json1 = "{\"myList\":[\"baz\"]}";
        String json2 = "{\"myList\":[{\"foo\":\"bar\"}]}";

        ObjectMapper mapper = new ObjectMapper();

        // Commenting these two lines out causes it to work.
        PolymorphicTypeValidator ptv = BasicPolymorphicTypeValidator.builder().build();
        mapper.activateDefaultTyping(ptv);

        mapper.readValue( json1, SimpleObj.class ); // <-- Succeeds all the time
        mapper.readValue( json2, SimpleObj.class ); // <-- Succeeds without ptv
    }

    private static class SimpleObj {
        public List<Object> myList;
    }
}
```

**Expected behavior**
Adding a polymorphic type validator with no defined super/sub types should work the same way default deserialization works.

**Additional context**
Get 2 different stack traces depending on whether you deserialize json1 first or not. With the code as it is above, you get the following stack trace.
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'baz' as a subtype of `java.util.List<java.lang.Object>`: no such class found
 at [Source: (String)"{"myList":["baz"]}"; line: 1, column: 17] (through reference chain: Main$SimpleObj["myList"])
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:2078)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1569)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:76)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:66)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:159)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromArray(AsArrayTypeDeserializer.java:53)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserializeWithType(CollectionDeserializer.java:283)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:147)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
	at Main.main(Main.java:19)
```

However, if you comment out json1 and it's "readValue" call and _just_ try to deserialize json2, you get a different stack trace.

```
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Unexpected token (START_OBJECT), expected VALUE_STRING: need JSON String, Number of Boolean that contains type id (for subtype of java.util.List)
 at [Source: (String)"{"myList":[{"foo":"bar"}]}"; line: 1, column: 12] (through reference chain: Main$SimpleObj["myList"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:1944)
	at com.fasterxml.jackson.databind.DeserializationContext.reportWrongTokenException(DeserializationContext.java:1678)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._locateTypeId(AsArrayTypeDeserializer.java:166)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:96)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromArray(AsArrayTypeDeserializer.java:53)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserializeWithType(CollectionDeserializer.java:283)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:147)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
	at Main.main(Main.java:20)
```

Having done a little bit of debugging, it appears adding the PolymorphicTypeValidator causes `CollectionDeserializer._deserializeFromArray` to have a `_valueTypeDeserializer` whereas without the validator, the `_valueTypeDeserializer` is null. So with `ptv` uses the third branch of this if/else and without `ptv` uses the second.

```
                if (t == JsonToken.VALUE_NULL) {
                    ...
                } else if (typeDeser == null) {
                    value = valueDes.deserialize(p, ctxt);
                } else {
                    value = valueDes.deserializeWithType(p, ctxt, typeDeser);
                }
```

**Comment by cowtowncoder** [comment]
I don't understand intended usage here: why are you activating Default Typing if you are not including actual type information? Call you as using is same as:

```
activateDefaultTyping(ptv, DefaultTyping.OBJECT_AND_NON_CONCRETE)
```

meaning that Type information will be expected for anything declared as `Object` (or `?`) as well as abstract types.
So elements in `List` would require type id (Class name).
You could see this by first serializing value, looking at structure.

**Comment by cowtowncoder** [comment]
@idoub Ok. Just saying that the example given should fail, as far as I can see. Structure doesn't match expected -- given exception message may be misleading as code guesses incorrectly, but basically for json1 JSON Array is expected to start with Type Id, which then does not map to known Class. For json2 structure is wrong in different way.

But... GSON does not have anything similar to Default Typing (afaik). Why do you think it needs to be enabled here?
Have you tried just leaving it out?

But assuming you really do need it, I think you have some options.

First, instead of relying on `DefaultTyping.OBJECT_AND_NON_CONCRETE`, pass explicit `DefaultTyping.JAVA_LANG_OBJECT`. I am not 100% sure but `List` being non-concrete type it may be expected to have Type Id included.

Second, only enabling polymorphic handling on specific property/-ies with `@JsonTypeInfo` (still need to configure `PolymorphicTypeValidator`) is often preferable to Default Typing, get more control on where type needs to be added.

**Comment by idoub** [comment]
@cowtowncoder Thanks for the guidance. I'm replacing a usage of GSON's `RuntimeTypeAdapterFactory` which doesn't actually ship with GSON but is [available in the repo](https://github.com/google/gson/blob/master/extras/src/main/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactory.java). It's configured with a specific type property, not a default type, but I've got another deserialization source that already uses jackson default typing effectively and I'm trying to apply the same (or similar) mapper to this data source.

I'll give those suggestions a try. But since this is not actually a bug I'll go ahead and close and if I have further questions I'll try other channels. Thanks again!

**Comment by cowtowncoder** [comment]
@idoub Perfect! This all now makes sense. I hope you can figure it out; I realize there may be some differences wrt GSON's `RuntimeAdapterFactory` (which does allow custom handling that can be used to implement polymorphism f.ex) and Jackson functionality so it may get complicated.
