### ISSUE TITLE
Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token; 

### ISSUE THREAD

**Issue by zhiyiChow** [FasterXML/jackson-databind#3883]
**Version information**
jackson-databind 2.11.2
spring-web 5.2.9.RELEASE

**Describe the bug**

JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token

Request parameters:
{
    "id": 1,
    "companyId": [1,2,3,4,5,7,8,9,10,88,86,87,66,68,6,83,143],
    "roleId":[1,15],
    "timestamp": 1681553468000
}
The roleId array in the argument displays an error if the content value starts at 1:
Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token
No error is displayed if the starting value of the roleId array is not 1. I tried to test it N times and found.

Now when I debug the source code found. It will not get the data of roleId and the jsonToken of roleId is START_OBJ.
 

Error:

Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token
 at [Source: (PushbackInputStream); line: 1, column: 84] (through reference chain: com.pixus.base.platform.api.dto.SysUserDTO["roleId"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1468)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1242)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1148)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer._parseLong(NumberDeserializers.java:598)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:562)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:540)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:291)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:250)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:371)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3519)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:273)
	... 104 common frames omitted

**Comment by pjfanning** [comment]
A JSON array should look like:

```
"RoleId" : [15,43,42,9,4,19,44,29,66],
```

**Comment by zhouweijun** [comment]
> A JSON array should look like:
> 
> ```
> "RoleId" : [15,43,42,9,4,19,44,29,66],
> ```

Sorry, because I made a mistake when I copied it.
My postman test results are as follows:

Request parameters:
{
    "id": 1,
    "companyId": [1,2,3,4,5,7,8,9,10,88,86,87,66,68,6,83,143],
    "roleId":[1,15],
    "timestamp": 1681553468000
}

Response:

{
    "code": -1,
    "msg": "JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token\n at [Source: (PushbackInputStream); line: 1, column: 69] (through reference chain: com.pixus.base.platform.api.dto.SysUserDTO[\"roleId\"]->java.util.ArrayList[0])",
    "data": null
}

I'm surprised that the companyId is resolvable, only the roleId is not

**Comment by zhouweijun** [comment]
> A JSON array should look like:
> 
> ```
> "RoleId" : [15,43,42,9,4,19,44,29,66],
> ```

In addition, my java back end receives Dtos as follows:


@Data 
@EqualsAndHashCode(callSuper = true)
public class SysUserDTO extends SysUser implements Serializable {
    private Long id;
    private List<Long> roleId;
    private List<Long> department;
    private List<Long> companyId;
}

**Comment by cowtowncoder** [comment]
I think we have almost all information, but since class in question is from a framework (Lombok?), we'd need to see actual generated code (we cannot test dependency like Lombok directly in unit tests).
In addition, specific code that does deserialization is needed (something like `objectMapper.readValue(json)`, as well as configuration of `ObjectMapper`, if any.

**Comment by zhouweijun** [comment]
Dtos are getters and setters for tag generation using Lombok.
ObjectMapper using the native, is currently in use org. Springframework. Web. Client. The RestTemplate through @ Bean injection.
Initialization time Settings: MappingJackson2HttpMessageConverter.
And MappingJackson2HttpMessageConverter will build a ObjectMapper:
1:
        public MappingJackson2HttpMessageConverter() {
               this(Jackson2ObjectMapperBuilder.json().build());
        }
2:
	public <T extends ObjectMapper> T build() {
		ObjectMapper mapper;
		if (this.createXmlMapper) {
			mapper = (this.defaultUseWrapper != null ?
					new XmlObjectMapperInitializer().create(this.defaultUseWrapper, this.factory) :
					new XmlObjectMapperInitializer().create(this.factory));
		}
		else {
			mapper = (this.factory != null ? new ObjectMapper(this.factory) : new ObjectMapper());
		}
		configure(mapper);
		return (T) mapper;
	}

**Comment by zhouweijun** [comment]
> I think we have almost all information, but since class in question is from a framework (Lombok?), we'd need to see actual generated code (we cannot test dependency like Lombok directly in unit tests). In addition, specific code that does deserialization is needed (something like `objectMapper.readValue(json)`, as well as configuration of `ObjectMapper`, if any.

Dtos are getters and setters for tag generation using Lombok.
ObjectMapper using the native, is currently in use org. Springframework. Web. Client. The RestTemplate through @ Bean injection.
Initialization time Settings: MappingJackson2HttpMessageConverter.
And MappingJackson2HttpMessageConverter will build a ObjectMapper:
1:
        public MappingJackson2HttpMessageConverter() {
               this(Jackson2ObjectMapperBuilder.json().build());
        }
2:
	public <T extends ObjectMapper> T build() {
		ObjectMapper mapper;
		if (this.createXmlMapper) {
			mapper = (this.defaultUseWrapper != null ?
					new XmlObjectMapperInitializer().create(this.defaultUseWrapper, this.factory) :
					new XmlObjectMapperInitializer().create(this.factory));
		}
		else {
			mapper = (this.factory != null ? new ObjectMapper(this.factory) : new ObjectMapper());
		}
		configure(mapper);
		return (T) mapper;
	}

**Comment by zhouweijun** [comment]
> I think we have almost all information, but since class in question is from a framework (Lombok?), we'd need to see actual generated code (we cannot test dependency like Lombok directly in unit tests). In addition, specific code that does deserialization is needed (something like `objectMapper.readValue(json)`, as well as configuration of `ObjectMapper`, if any.

Back-end receive parameter I use Map to receive, according to debug to the format:
`{"companyId":[1,2,3,4,5,7,8,9,10,88,86,87,66,68,6,83,143],"roleId":[{"$ref":"$.companyId[0]"},15],"id":1,"timestamp":1681553468000}`
Notice that this roleId parses the data into an Obj.

So I was tracing the parsed source code and found that if I received it as a dto, the parsed Start_object would appear.

How do I deal with this?

**Comment by zhiyiChow** [comment]
不是因为jackson 导致的, 目前已找到原因.因为其他的框架导致.
