### ISSUE TITLE
Deserialization wrong when using a generic class with a converter as a property

### ISSUE THREAD

**Issue by XYZboom** [FasterXML/jackson-databind#3915]
**Describe the bug**
Here are three classes and two converters
```
    @NoArg
    class OuterClass(
        val inner: TestClassOri<Int, String>,
    )

    @NoArg
    @JsonSerialize(converter = TestClassConverter::class)
    @JsonDeserialize(converter = TestClassOriConverter::class)
    class TestClassOri<T, K>(
        val name: T,
        val nameMap: HashMap<T, K>,
    )

    @NoArg
    class TestClass<T, K>(val hashMap: HashMap<T, HashMap<T, K>>)

    class TestClassConverter<T, K> : StdConverter<TestClassOri<T, K>, TestClass<T, K>>() {
        override fun convert(value: TestClassOri<T, K>): TestClass<T, K> {
            return TestClass(hashMapOf(value.name to value.nameMap))
        }
    }

    class TestClassOriConverter<T, K> : StdConverter<TestClass<T, K>, TestClassOri<T, K>>() {
        override fun convert(value: TestClass<T, K>): TestClassOri<T, K> {
            val (name, map) = value.hashMap.entries.first()
            return TestClassOri(name, map)
        }
    }
```
when deserialize the `OuterClass`, the generic type of `OuterClass.inner.nameMap` will be `HashMap<String, String>` but not `HashMap<Int, String>` which is expected.

**Version information**
Which Jackson version(s) was this for?
2.14.2

```
    @Test
    fun testDeserialize() {
        val jsonMapper = jsonMapper()
        val jsonHashMap = jsonMapper.writeValueAsString(
            OuterClass(TestClassOri(1, hashMapOf(1 to "1", 12 to "12")))
        )
        val de = jsonMapper.readerFor(OuterClass::class.java)
            .readValue<OuterClass>(jsonHashMap)
        assertEquals(de.inner.nameMap.keys.first()::class.java, Int::class.java)
    }
```
```
org.opentest4j.AssertionFailedError: expected: <java.lang.String> but was: <int>
```

**Comment by XYZboom** [comment]
@JooHyukKim, thank you for your reply. I think this is a problem with a certain part of databind because I did not use kotlin module in the project. Here are the test cases I wrote in Java using junit5.
```
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.json.JsonMapper;
import com.fasterxml.jackson.databind.util.StdConverter;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

public class TestDeserialize {

    static class OuterClass {
        public TestClassOri<Integer, String> inner;

        public OuterClass() {
        }

        public OuterClass(TestClassOri<Integer, String> inner) {
            this.inner = inner;
        }
    }

    @JsonSerialize(converter = TestClassConverter.class)
    @JsonDeserialize(converter = TestClassOriConverter.class)
    static class TestClassOri<T, K> {
        public T name;
        public HashMap<T, K> nameMap;

        public TestClassOri() {
        }

        public TestClassOri(T name, HashMap<T, K> nameMap) {
            this.name = name;
            this.nameMap = nameMap;
        }
    }

    static class TestClass<T, K> {
        public HashMap<T, HashMap<T, K>> hashMap;

        public TestClass() {
        }

        public TestClass(HashMap<T, HashMap<T, K>> hashMap) {
            this.hashMap = hashMap;
        }
    }

    static class TestClassConverter<T, K> extends StdConverter<TestClassOri<T, K>, TestClass<T, K>> {
        @Override
        public TestClass<T, K> convert(TestClassOri<T, K> value) {
            HashMap<T, HashMap<T, K>> hashMap = new HashMap<>();
            hashMap.put(value.name, value.nameMap);
            return new TestClass<>(hashMap);
        }
    }

    static class TestClassOriConverter<T, K> extends StdConverter<TestClass<T, K>, TestClassOri<T, K>> {
        @Override
        public TestClassOri<T, K> convert(TestClass<T, K> value) {
            Map.Entry<T, HashMap<T, K>> entry =
                    value.hashMap.entrySet().stream().findFirst().get();
            return new TestClassOri<>(entry.getKey(), entry.getValue());
        }
    }

    @Test
    public void testDeserialize() throws JsonProcessingException {
        ObjectMapper jsonMapper = new JsonMapper();
        HashMap<Integer, String> map = new HashMap<>();
        map.put(12, "12");
        String jsonStr = jsonMapper.writeValueAsString(
                new OuterClass(new TestClassOri<>(1, map))
        );
        System.out.println(jsonStr);
        OuterClass de = jsonMapper.readerFor(OuterClass.class).readValue(jsonStr);
        Assertions.assertEquals(
                de.inner.nameMap.keySet().stream().findFirst().get().getClass(),
                Integer.class
        );
    }
}
```
The similar exception accured
```
java.lang.String cannot be cast to java.lang.Integer
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at TestDeserialize.testDeserialize(TestDeserialize.java:81)
```

**Comment by XYZboom** [comment]
I tried serialize using `JavaType` without `OuterClass`, `{"hashMap":{"1":{"12":"12"}}}` got. Seems like something wrong in `Converter`.
```
    @Test
    public void testDeserializeWithoutOuter() throws JsonProcessingException {
        ObjectMapper jsonMapper = new JsonMapper();
        HashMap<Integer, String> map = new HashMap<>();
        map.put(12, "12");
        TypeFactory typeFactory = jsonMapper.getTypeFactory();
        JavaType hashMapOfIntStrType = typeFactory.constructMapType(HashMap.class, Integer.class, String.class);
        JavaType intType = typeFactory.constructType(Integer.class);
        JavaType classOriType = typeFactory.constructParametricType(TestClassOri.class, intType, hashMapOfIntStrType);
        String jsonStr = jsonMapper.writerFor(classOriType).writeValueAsString(new TestClassOri<>(1, map));
        System.out.println(jsonStr);
        TestClassOri<Integer, String> de = jsonMapper.readerFor(classOriType).readValue(jsonStr);
        Assertions.assertEquals(
                de.nameMap.keySet().stream().findFirst().get().getClass(),
                Integer.class
        );
    }
```
```
{"hashMap":{"1":{"12":"12"}}}

java.lang.String cannot be cast to java.lang.Integer
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
    at TestDeserialize.testDeserializeWithoutOuter(TestDeserialize.java:102)
```

**Comment by XYZboom** [comment]
Maybe type erasure worked here [com.fasterxml.jackson.databind.util.StdConverter.java:37](https://github.com/FasterXML/jackson-databind/blob/2.14/src/main/java/com/fasterxml/jackson/databind/util/StdConverter.java#L37)

**Comment by pjfanning** [comment]
Can you provide the stacktrace for the exception? Just providing 1 line is pretty uninformative.

**Comment by XYZboom** [comment]
But I think the problem shouldn't be here, because there were no errors during the deserialization process, which only occurred when using the deserialized content

**Comment by pjfanning** [comment]
so the class cast happens in TestDeserialize.java:102 and not in jackson code - can't you write some code in the method that has the class cast to workaround it?

**Comment by XYZboom** [comment]
the `de.nameMap.keySet()` should be type `HashMap<Integer, String>` but actually `HashMap<String, String>` in runtime.
![image](https://user-images.githubusercontent.com/58654313/236241159-a51b5d5a-3f49-4ae9-9f60-31bdab6e25f1.png)

**Comment by XYZboom** [comment]
In fact, in my project, I used custom class with generics to create Map keys. Like `HashMap<Edge<T>, K>`. If I use String, it may bring some new problems

**Comment by pjfanning** [comment]
As @JooHyukKim, JSON keys are Strings. And with type erasure, the Jackson code doesn't know that much about the type params on the Map. I doubt whether Jackson can do much about improving the behaviour or if it is a priority - given the backlog of other issues.

jackson has good support for writing custom serializers and deserializers - maybe you could try working around it using custom code

**Comment by XYZboom** [comment]
I found that Jackson provides classes like `JavaType` to help deserializers understand generic information, but as I said, it doesn't seem to work under the `Converter`. I'll try using a custom deserialization method instead of a `Converter`, which should solve the problem. Or is this not a problem, but a feature that needs to be added to the `Converter`?

**Comment by cowtowncoder** [comment]
This is almost certainly due to Type Erasure on serialization. Exactly where and how I am not sure, but I doubt `Converter` can get actual type parameters since there is nothing actually linking type parameters converter has with declared types -- just because type names (`T`, `K`) happen to be same does not mean they refer to same things.
So `Converter` probably just sees equivalent of `?` for everything, when set via annotations.
I don't think there is way around this as `Class`-valued annotations can not take type parameters (in theory one could try to build support I suppose but I don't think that is feasible wrt Jackson annotation sets unfortunately).

This is just long way of saying that I am not sure the issue can be solved. Although TBH it would be good to fully understand the details.

**Comment by yihtserns** [comment]
<table>
<thead>
<tr>
<th>Serialization</th>
<th>Deserialization</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<pre>TestClassOri<Integer, String>(1, [12: "12"])
➜【TestClassConverter】
➜ TestClass<Object, Object>([1: [12: "12"]])⚠️
➜【???Serializer】
➜ {"hashMap":{"1":{"12":"12"}}}
</pre>
</td>
<td>
<pre>
{"hashMap":{"1":{"12":"12"}}}
➜【???Deserializer】
➜ TestClass<Object, Object>(["1": ["12": "12"]])⚠️
➜【TestClassOriConverter】
➜ TestClassOri<Object, Object>("1", ["12": "12"])⚠️
</pre>
</td>
</tr>
</tbody>
</table>
 
The illustration above is what I think happened:
1. `Converter`s don't have "context" about what they're processing, they just take INPUT and convert it into OUTPUT.
2. Because of that, declaring any generic type `<K>` or `<V>` or `<Whatever>` on a `Converter` is just equivalent to declaring `<Object>`.

Only parameterized types are useful on a `Converter`, e.g.  if you do this:
```
static class TestClassOriConverter extends StdConverter<TestClass<Integer, String>, TestClassOri<Integer, String>> {
    @Override
    public TestClassOri<Integer, String> convert(TestClass<Integer, String> value) {
        Map.Entry<Integer, HashMap<Integer, String>> entry =
                value.hashMap.entrySet().stream().findFirst().get();
        return new TestClassOri<>(entry.getKey(), entry.getValue());
    }
}
```
...your problem will be solved, but I think you don't want that.  You're probably type-parameterizing `TestClassOri` differently in different places, e.g.
```
public TestClassOri<Integer, String> intKeyed;
public TestClassOri<Boolean, String> boolKeyed;
public TestClassOri<String, String> stringKeyed;
```

## Deserializing with "context"
> **Warning**
> **Disclosure**: Whatever I'm sharing below is what I've learned while playing around in [my personal "just for fun" project](https://github.com/yihtserns/records-jackson/blob/main/src/main/java/com/github/yihtserns/records/jackson/RecordsTupleDeserializer.java).<br>
> I don't have experience using them in production/real life, so I don't know if I'm using them correctly - Jackson pros please feel free to correct any mistakes, thanks.

As mentioned above, (I think) `Converter` API does not have any "context" of what they're converting - they don't have info about the "target" e.g. the target field during deserialization.

To access that information, you need to use [StdDeserializer](https://fasterxml.github.io/jackson-databind/javadoc/2.8/com/fasterxml/jackson/databind/deser/std/StdDeserializer.html) + [ContextualDeserializer](https://fasterxml.github.io/jackson-databind/javadoc/2.8/com/fasterxml/jackson/databind/deser/ContextualDeserializer.html) API:
```
...
@JsonDeserialize(using = TestClassOriDeserializer.class)
static class TestClassOri<T, K> {
    ...
}

static class TestClassOriDeserializer extends StdDeserializer<TestClassOri<Object, Object>> implements ContextualDeserializer {

    /**
     * For Jackson to instantiate and call {@link #createContextual(DeserializationContext, BeanProperty)}.
     */
    public TestClassOriDeserializer() {
        super(TestClassOri.class);
    }

    /**
     * Actual constructor to do work.
     */
    private TestClassOriDeserializer(JavaType targetTestClassOriType) {
        super(targetTestClassOriType);
    }

    /**
     * Get the target's (e.g. field) type info and use that to create the actual deserializer.
     */
    @Override
    public JsonDeserializer<?> createContextual(DeserializationContext context, BeanProperty property) {
        JavaType targetTestClassOriType = context.getContextualType();

        return new TestClassOriDeserializer(targetTestClassOriType);
    }

    @Override
    public TestClassOri<Object, Object> deserialize(JsonParser parser, DeserializationContext context) throws IOException {
        JavaType targetTestClassOriType = getValueType();
        TypeBindings targetTestClassOriParameterizedTypes = targetTestClassOriType.getBindings();

        JavaType parameterizedTestClass = context.getTypeFactory().constructParametricType(TestClass.class, targetTestClassOriParameterizedTypes);
        TestClass<Object, Object> value = context.readValue(parser, parameterizedTestClass);

        Map.Entry<Object, HashMap<Object, Object>> entry =
                value.hashMap.entrySet().stream().findFirst().get();
        return new TestClassOri<>(entry.getKey(), entry.getValue());
    }
}
```

**Comment by XYZboom** [comment]
@yihtserns ,thanks a lot, `ContextualDeserializer` can really  indeed solve the problem.

**Comment by XYZboom** [comment]
Possible useful complete test code:
```
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.ContextualDeserializer;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.json.JsonMapper;
import com.fasterxml.jackson.databind.type.TypeBindings;
import com.fasterxml.jackson.databind.type.TypeFactory;
import com.fasterxml.jackson.databind.util.StdConverter;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class TestDeserialize {

    static class OuterClass {
        public TestClassOri<Integer, String> inner;

        public OuterClass() {
        }

        public OuterClass(TestClassOri<Integer, String> inner) {
            this.inner = inner;
        }
    }

    @JsonSerialize(converter = TestClassConverter.class)
    @JsonDeserialize(using = TestClassOriDeserializer.class)
    static class TestClassOri<T, K> {
        public T name;
        public HashMap<T, K> nameMap;

        public TestClassOri() {
        }

        public TestClassOri(T name, HashMap<T, K> nameMap) {
            this.name = name;
            this.nameMap = nameMap;
        }
    }

    static class TestClass<T, K> {
        public HashMap<T, HashMap<T, K>> hashMap;

        public TestClass() {
        }

        public TestClass(HashMap<T, HashMap<T, K>> hashMap) {
            this.hashMap = hashMap;
        }
    }

    static class TestClassConverter<T, K> extends StdConverter<TestClassOri<T, K>, TestClass<T, K>> {
        @Override
        public TestClass<T, K> convert(TestClassOri<T, K> value) {
            HashMap<T, HashMap<T, K>> hashMap = new HashMap<>();
            hashMap.put(value.name, value.nameMap);
            return new TestClass<>(hashMap);
        }
    }

    static class TestClassOriDeserializer extends StdDeserializer<TestClassOri<Object, Object>> implements ContextualDeserializer {

        /**
         * For Jackson to instantiate and call {@link #createContextual(DeserializationContext, BeanProperty)}.
         */
        public TestClassOriDeserializer() {
            super(TestClassOri.class);
        }

        /**
         * Actual constructor to do work.
         */
        private TestClassOriDeserializer(JavaType targetTestClassOriType) {
            super(targetTestClassOriType);
        }

        /**
         * Get the target's (e.g. field) type info and use that to create the actual deserializer.
         */
        @Override
        public JsonDeserializer<?> createContextual(DeserializationContext context, BeanProperty property) {
            JavaType targetTestClassOriType = context.getContextualType();

            return new TestClassOriDeserializer(targetTestClassOriType);
        }

        @Override
        public TestClassOri<Object, Object> deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JavaType targetTestClassOriType = getValueType();
            TypeBindings targetTestClassOriParameterizedTypes = targetTestClassOriType.getBindings();

            JavaType parameterizedTestClass = context.getTypeFactory().constructParametricType(TestClass.class,
                    targetTestClassOriParameterizedTypes);
            TestClass<Object, Object> value = context.readValue(parser, parameterizedTestClass);

            Map.Entry<Object, HashMap<Object, Object>> entry =
                    value.hashMap.entrySet().stream().findFirst().get();
            return new TestClassOri<>(entry.getKey(), entry.getValue());
        }
    }

    @Test
    public void testDeserialize() throws JsonProcessingException {
        ObjectMapper jsonMapper = new JsonMapper();
        HashMap<Integer, String> map = new HashMap<>();
        map.put(12, "12");
        String jsonStr = jsonMapper.writeValueAsString(
                new OuterClass(new TestClassOri<>(1, map))
        );
        System.out.println(jsonStr);
        OuterClass de = jsonMapper.readerFor(OuterClass.class).readValue(jsonStr);
        Assertions.assertEquals(
                de.inner.nameMap.keySet().stream().findFirst().get().getClass(),
                Integer.class
        );
    }

    @Test
    public void testDeserializeWithoutOuter() throws JsonProcessingException {
        ObjectMapper jsonMapper = new JsonMapper();
        HashMap<Integer, String> map = new HashMap<>();
        map.put(12, "12");
        TypeFactory typeFactory = jsonMapper.getTypeFactory();
        JavaType classOriType = typeFactory.constructParametricType(TestClassOri.class, Integer.class, String.class);
        String jsonStr = jsonMapper.writerFor(classOriType).writeValueAsString(new TestClassOri<>(1, map));
        System.out.println(jsonStr);
        TestClassOri<Integer, String> de = jsonMapper.readerFor(classOriType).readValue(jsonStr);
        Assertions.assertEquals(
                de.nameMap.keySet().stream().findFirst().get().getClass(),
                Integer.class
        );
    }
}
```
