### ISSUE TITLE
stackoverflow error serializing ObjectNode of deeply nested data

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-databind#4021]
If we go back to the code for DeepJsonNodeSerTest as it was changed by https://github.com/FasterXML/jackson-databind/commit/ecaf95c33edf901a637f97af47e22ae9a41f2ef6 then we get a stackoverflow error.

```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.036 s <<< FAILURE! - in com.fasterxml.jackson.databind.deser.dos.DeepJsonNodeSerTest
Error:  com.fasterxml.jackson.databind.deser.dos.DeepJsonNodeSerTest.testVeryDeepNodeSer  Time elapsed: 0.025 s  <<< ERROR!
java.lang.StackOverflowError
	at com.fasterxml.jackson.core.json.JsonWriteContext.<init>(JsonWriteContext.java)
	at com.fasterxml.jackson.core.json.JsonWriteContext.createChildObjectContext(JsonWriteContext.java:207)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeStartObject(WriterBasedJsonGenerator.java:334)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:442)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:446)
```

**Comment by pjfanning** [comment]
relates to #4020 and #4017

**Comment by pjfanning** [comment]
We'll probably need the ObjectNode and ArrayNode serialization to be non-recursive. That would involve walking the node graph inside a loop and using a [Stack](https://docs.oracle.com/javase/8/docs/api/java/util/Stack.html) instance to keep track of state.

**Comment by cowtowncoder** [comment]
@pjfanning I do not really like the approach to take there.

But what is odd is why there is a new failure: even older `toString()` would have just used default `JsonMapper` handling and allowed fairly high level of nesting.
So I do not quite understand failures -- especially as test passes locally.
It could be that CI system's thread stack allocation is bigger (per frame), or total available is lower. I'll try lowering nesting still more to try to get this unstuck.

**Comment by cowtowncoder** [comment]
I tried again to resolve the issue, this time via #4026.

**Comment by pjfanning** [comment]
@cowtowncoder this issue is about why #4021 occurs - this issue still exists because ObjectNode.serialize is recursive (as is ArrayNode.serialize) and hits issues with stackoverflow before the JsonGenerator checks for nesting depth fail. That is the default StreamWriteConstraints depth limit of 1000 is too high when you are dealing serializing ObjectNodes or ArrayNodes that have very deep nesting.

It appears that you are #4022 but would you consider supporting a new API that does a non-recursive serialization while leaving the existing ObjectNode/ArrayNode serialization code as is with warning about the potential for Stackoverflow.

An alternative would be for Jackson code to catch the StackOverflowError in ObjectNode/ArrayNode serialize and to throw an IOException instead. This would keep the CVE hunters happy - that deeply nested data fails but that a checked exception is thrown (that users would have to have handling for).

**Comment by cowtowncoder** [comment]
@pjfanning No I understand that recursion is limiting but what I do not understand is why it'd fail at this low level -- formerly serialization with recursive approach had no issue with up to 9k levels. Having nesting of, say, 1100, should be perfectly within reach by recursive serializers.

So of course there is some limit where things won't work but that should not be hit here.
And as per workflow runs now I think 2.16 and master are passing with lowered nesting (1100 from "max-write-nesting-default" + 100).

As to catching SOE, throwing IOException; unless we absolutely must, I don't think so.

But at this point, I do not think we have cases where output nesting level of 1000 would let SOEs be generated.


As to new API, what problem are we trying to solve here? If (but only if) our default writer-side-nesting level fails to prevent SOEs we need to consider alternatives, but as things are I don't see cases of that happening.

This particular issue started (... for some reason) affecting CI with nesting of 9000 levels. Going down to 4000 wasn't enough. 1100 is, as far as I can see.
I suspect Github Action default images use smaller hosts; I do not think we'll see SOEs with nesting of about 1000, regardless.

**Comment by pjfanning** [comment]
I can confirm that the 4000 depth variant of the test works on my laptop (JDK 8 and 11) so maybe the stack limit is something that we are getting from the CI build.

I'll leave this open but it seems less pressing now.

**Comment by cowtowncoder** [comment]
@pjfanning Ok good thank you for verifying. I think I'll further add to test to cover both:

1. Case of "default-max + 100" with defaults -> should fail with stream write constraints
2. Same case but unlimited -> pass (since nesting is modest)

**Comment by cowtowncoder** [comment]
I think this is resolved now, closing.

**Comment by dhanushkaj** [comment]
> 

in wich version is this closed?

**Comment by cowtowncoder** [comment]
This was an intermittent issue for 2.16.0-SNAPSHOT so does not affect published versions.
