### ISSUE TITLE
Deserialization of a certain kinds of parametrized properties fail to resolve `?` into expected bounds, resulting in `LinkedHashMap`

### ISSUE THREAD

**Issue by mariuszpala** [FasterXML/jackson-databind#4118]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Recently our code editor advices as to change the class definition, the deserialization stopped working correctly. 

We have such a class:

```
public class TestAttribute<T extends TestAttribute<?>> {

	protected List<T> attributes;
}
```

When we create a parent object with a list of such properties 2-level deep, on 2rd level the deserialization doesn't work and it deserializes into LinkedHashMap instead of TestAttribute. See the screenshot below. 

<img width="222" alt="image" src="https://github.com/FasterXML/jackson-databind/assets/12190923/60385cca-fa7b-4277-9376-26b1a7600419">

But when I remove the "<?>" from the "extends", then the IDE complains about it, but the deserialization works just fine

<img width="193" alt="image" src="https://github.com/FasterXML/jackson-databind/assets/12190923/560abb4c-57ad-496e-9ebc-729d2a2a7b48">

<img width="246" alt="image" src="https://github.com/FasterXML/jackson-databind/assets/12190923/8a54cb21-a922-4f57-9972-f2d8ff43c3a3">

### Version Information

2.15.2, JDK17

### Reproduction

1. Brief code sample/snippet: include here in preformatted/code section
```
public class TestAttribute<T extends TestAttribute<?> {

	protected List<T> attributes;

	public TestAttribute() {
	}
	public TestAttribute(List<T> attributes) {
		this.attributes = attributes;
	}

	public List<T> getAttributes() {
		return attributes;
	}

	public void setAttributes(List<T> attributes) {
		this.attributes = attributes;
	}
}
```

```
public class TestObject {

	private List<TestAttribute<?>> attributes = new ArrayList<>();

	public TestObject() {
	}

	public TestObject(List<TestAttribute<?>> attributes) {
		this.attributes = attributes;
	}

	public List<TestAttribute<?>> getAttributes() {
		return attributes;
	}

	public void setAttributes(List<TestAttribute<?>> attributes) {
		this.attributes = attributes;
	}
}
```

```
ObjectMapper objectMapper = new ObjectMapper();
		objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
		objectMapper.configure(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY, true);
		objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
		objectMapper.configure(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL, true);
		objectMapper.configure(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS, true);
		objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
		objectMapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
		objectMapper.enable(MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS);

		TestAttribute a = new TestAttribute(null);
		TestAttribute b = new TestAttribute(List.of(a));
		TestAttribute c = new TestAttribute(List.of(b));

		TestObject test = new TestObject(List.of(c));
		String serialized = objectMapper.writeValueAsString(test);
		System.out.println(serialized);

		TestObject deserialized = objectMapper.readValue(serialized, TestObject.class);
		System.out.println(deserialized.getAttributes().get(0).getAttributes().get(0).getClass().getName());
```

3. Textual explanation: include here
When the code above is executed, the last line fails

```
java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class com.me.samples.TestAttribute (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; com.me.samples.TestAttribute is in unnamed module of loader 'app')
	at com.me.samples.PlainTest.main(PlainTest.java:38)
```

### Expected behavior

Deserialization should work just fine and deserialize a list of TestAttribute objects correctly but instead the LinkedHashMap is deserialized instead unless I remove <?> from all my code which keeps the IDE complaining abut the missing raw parameter.

**Comment by cowtowncoder** [comment]
While I appreciate textual explanation of problems, would it be possible to have an isolated test case showing exact problem case and nothing else?

And no printing of values with `System.out.println()` -- assertions only, please.

**Comment by mariuszpala** [comment]
Just try this code:
```
TestAttribute<?> testAttribute = deserialized.getAttributes().get(0).getAttributes().get(0);
```
it throws the error I mentioned above:

```
java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class com.me.samples.TestAttribute (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; com.me.samples.TestAttribute is in unnamed module of loader 'app')
	at com.me.samples.PlainTest.main(PlainTest.java:38)
```

**Comment by yihtserns** [comment]
This is the class chain: `TestObject(attributes=[TestAttribute(attributes=?)]`

When deserializing this JSON using the class chain above:
```
{                                       // TestObject
    "attributes": [               // attributes=[TestAttribute]
        {                               // TestAttribute
            "attributes": [       // attributes=?
                {                       // ? <---- Without the type info, Jackson can only convert this into a Map
                    "attributes": [{}]
                 }
            ]
        }
    ]
}
```

If you remove `<?>` from `TestObject --> attributes --> List<TestAttribute<?>>` to become `TestObject --> attributes --> List<TestAttribute>`, the class chain becomes `TestObject(attributes=[TestAttribute(attributes=T extends TestAttribute(attributes=?))])` so when deserializing:
When deserializing this JSON using the class chain above:
```
{                                       // TestObject
    "attributes": [               // attributes=[TestAttribute]
        {                               // TestAttribute
            "attributes": [       // attributes=T extends TestAttribute
                {                       // T extends TestAttribute <---- Jackson knows to convert this part to TestAttribute
                    "attributes": [{}]
                 }
            ]
        }
    ]
}
```

**Comment by yawkat** [comment]
@yihtserns while the type for the inner object is '?', it is still known statically that it will is bounded by `TestAttribute<?>`, so jackson should have enough type info to read it as such.

**Comment by yihtserns** [comment]
@yawkat I don't understand, can you describe what you mean in detail?  `TestAttribute<?>` is declared in two places, so I don't know what you're referring to.

It'll be good if you also illustrate the class chain (to demonstrate what type info that is available at runtime that can be obtained using Java reflection API).

**Comment by yawkat** [comment]
> `// ? <---- Without the type info, Jackson can only convert this into a Map`

This does not have to be the case. Jackson can infer safely that here, the lowest bound of the wildcard is `TestAttribute<?>`, not `Object`.

**Comment by yihtserns** [comment]
@yawkat 

> This does not have to be the case. Jackson can infer safely that here, the lowest bound of the wildcard is TestAttribute<?>, not Object...

```
public class TestObject {
                                   ⬇ this part declares that TestAttribute.attributes is a List<?>
	private List<TestAttribute<?>> attributes ...
        ...
}
```
The above results in class/field chain: `TestObject(attributes=[TestAttribute(attributes=[?])]`.

**Comment by cowtowncoder** [comment]
> Just try this code:
> 
> ```
> TestAttribute<?> testAttribute = deserialized.getAttributes().get(0).getAttributes().get(0);
> ```
> 
> it throws the error I mentioned above:
> 
> ```
> java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class com.me.samples.TestAttribute (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; com.me.samples.TestAttribute is in unnamed module of loader 'app')
> 	at com.me.samples.PlainTest.main(PlainTest.java:38)
> ```

Sigh. This AND full class definition.

I was hoping for a minimal unit test, not incomplete one-liner.

But I can work with this I suppose.

**Comment by cowtowncoder** [comment]
Ok. I think I can see what is going on.

First of all, yes, it should be possible to figure out typing in this case. And it took some thinking to know why type resolution doesn't work.

And the reason is, I think, that `TypeFactory` is asked to resolve type `List<TestAttribute<?>>` in `TestObject`, wherein resolution of `?` would require finding bounds from within `TestAttribute`, and not only rely on local information (where we do not have bound).

So the fix is probably needed for `TypeFactory`; assuming it is passed enough information to handle this case.

**Comment by yawkat** [comment]
i made a pr with a fix: #4122

**Comment by yihtserns** [comment]
Table of current behaviours when deserializing this JSON:
```{"attributes":[{"attributes":[{"attributes":[{}]}]}]}```
<table>
  <tr>
    <th>Root class</th>
    <th>Output</th>
  </tr>
  <tr>
    <td>
<pre>
public class TestObject {
    private List&lt;TestAttribute&gt; attributes;
    ...
}
</pre>
    </td>
    <td><code>TestObject{attributes=[TestAttribute{attributes=[TestAttribute{attributes=[{}]}]}]}</code>
<br><br>
<strong>NOTE</strong>: Seems like when <code>List&lt;TestAttribute&gt;</code> is not "sub-parameterized", it would use the type parameter info directly from:<pre>class TestAttribute&lt;T extends TestAttribute&gt;</pre>
...to construct the nested entries.
</td>
  </tr>

  <tr>
    <td>
<pre>
public class TestObject {
    private List&lt;TestAttribute&lt;TestAttribute&gt;&gt; attributes;
    ...
}
</pre>
    </td>
    <td><code>TestObject{attributes=[TestAttribute{attributes=[TestAttribute{attributes=[{}]}]}]}</code>
<br><br>
<strong>NOTE</strong>: Seems like when <code>List&lt;TestAttribute&lt;TestAttribute&gt;&gt;</code> is "sub-parameterized", it would use that "sub-parameter" type to construct the nested entries.
</td>
  </tr>

  <tr>
    <td>
<pre>
public class TestObject {
    private List&lt;TestAttribute&lt;SubClassOfTestAttribute&gt;&gt; attributes;
    ...
}
</pre>
    </td>
    <td><code>TestObject{attributes=[TestAttribute{attributes=[SubClassOfTestAttribute{attributes=[TestAttribute{attributes=null}]}]}]}</code>
<br><br>
<strong>NOTE</strong>: Similar to the one up there, it uses the "sub-parameter" type <code>SubClassOfTestAttribute</code> to construct the nested entries.
</td>
  </tr>

  <tr>
    <td>
<pre>
public class TestObject {
    private List&lt;TestAttribute&lt;?&gt;&gt; attributes;
    ...
}
</pre>
    </td>
    <td><code>TestObject{attributes=[TestAttribute{attributes=[{attributes=[{}]}]}]}</code>
<br><br>
<strong>NOTE</strong>: Similar to the two up there, it uses the "sub-parameter" type <code>&lt;?&gt;</code> to construct the nested entries - in this case as <code>Map</code>.
</td>
  </tr>
</table>

So, this issue is about requesting behaviour change for the 4th scenario: if wildcard type is used, look for and use the type parameter info from the class itself, mimicking the behaviour from 1st scenario.

---
### On wildcard as parameter type for a bounded type parameter
I was curious on why would Java compiler allows a bounded type parameter e.g. `<T extends Something>` to be parameterizable by `<?>`  which means "anything" i.e. can be something that does NOT `extends Something`.

Apparently that can be useful: https://en.wikipedia.org/wiki/Wildcard_(Java)#Wildcard_as_parameter_type.  Or maybe someone is trying to sell a Java compiler limitation/bug as a feature.  🤔

Anyway, that's just a trivia, unrelated to the reason why this ticket was created in the first place: he just wanted to stop the code editor warnings and using wildcard was the only practical choice (hey `@SuppressWarnings("rawtypes")` would've worked too 😋).

**Comment by yihtserns** [comment]
BTW, title is currently inaccurate: should be "wildcard parameterized" not "raw parameterized" (which actually means not parameterized).

**Comment by yawkat** [comment]
@JooHyukKim yes the JLS states that `?` is equivalent to `? extends
Object`, that is the problem (getUpperBounds returns Object). But that does
not mean Object is actually the upper bound of all types possible with the
wildcard. With knowledge of the type variable declaration, we can in this
case determine a more specific but still correct upper bound. All possible
"instantiations" of the wildcard have to match the wildcard upper bound AND
the bound defined on the type variable, so if the former is Object, we can
still safely use the latter.

**Comment by cowtowncoder** [comment]
As per #4122 this might now work -- would be great to get an extracted unit test to verify (tests for #4122 reproduce underlying issue, fix).

**Comment by cowtowncoder** [comment]
Fixed via #4122, as shown by unit tests added; closing.

**Comment by cowtowncoder** [comment]
Unfortunately need to revert the fix for 2.16 timeframe -- hoping to re-tackle for 2.17.

**Comment by poolsnowhui** [comment]
env: 
1. spring boot 3.2.0
2. jdk17
My application have this error, too. I have the RequestBody of Map, this Map is '
Map<Long, Set<ViolationResult>> idToViolationResultMap'. Wherein, ViolationResult is the model. 
This Map is the Map<Long, Set<LinkedHashMap>> in the debug mode.
![image2023-12-19_14-33-30](https://github.com/FasterXML/jackson-databind/assets/10153708/7975af79-90e9-46d1-af79-52737871f356)

**Comment by yihtserns** [comment]
@poolsnowhui that looks like a Spring WebMVC problem, not Jackson's.
