### ISSUE TITLE
Cannot deserialize instance of `java.math.BigDecimal` out of START_OBJECT token

### ISSUE THREAD

**Issue by zhaokaiping-github** [FasterXML/jackson-databind#4192]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Caused by: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of `java.math.BigDecimal` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.math.BigDecimal` out of START_OBJECT token
 at [Source: (PushbackInputStream); line: 1, column: 1]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:245) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:227) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:102) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.cloud.openfeign.support.SpringDecoder.decode(SpringDecoder.java:59) ~[spring-cloud-openfeign-core-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
        at org.springframework.cloud.openfeign.support.ResponseEntityDecoder.decode(ResponseEntityDecoder.java:62) ~[spring-cloud-openfeign-core-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
        at feign.optionals.OptionalDecoder.decode(OptionalDecoder.java:36) ~[feign-core-10.4.0.jar!/:?]
        at feign.SynchronousMethodHandler.decode(SynchronousMethodHandler.java:178) ~[feign-core-10.4.0.jar!/:?]
        ... 69 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.math.BigDecimal` out of START_OBJECT token
 at [Source: (PushbackInputStream); line: 1, column: 1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63) ~[jackson-databind-2.9.8.jar!/:2.9.8]
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343) ~[jackson-databind-2.9.8.jar!/:2.9.8]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1139) ~[jackson-databind-2.9.8.jar!/:2.9.8]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1093) ~[jackson-databind-2.9.8.jar!/:2.9.8]
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$BigDecimalDeserializer.deserialize(NumberDeserializers.java:961) ~[jackson-databind-2.9.8.jar!/:2.9.8]
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$BigDecimalDeserializer.deserialize(NumberDeserializers.java:922) ~[jackson-databind-2.9.8.jar!/:2.9.8]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013) ~[jackson-databind-2.9.8.jar!/:2.9.8]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3084) ~[jackson-databind-2.9.8.jar!/:2.9.8]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:239) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:227) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:102) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.cloud.openfeign.support.SpringDecoder.decode(SpringDecoder.java:59) ~[spring-cloud-openfeign-core-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
        at org.springframework.cloud.openfeign.support.ResponseEntityDecoder.decode(ResponseEntityDecoder.java:62) ~[spring-cloud-openfeign-core-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
        at feign.optionals.OptionalDecoder.decode(OptionalDecoder.java:36) ~[feign-core-10.4.0.jar!/:?]
        at feign.SynchronousMethodHandler.decode(SynchronousMethodHandler.java:178) ~[feign-core-10.4.0.jar!/:?]
        ... 69 more

### Version Information

jackson-databind-2.9.8.jar!/:2.9.8

### Reproduction

<-- Any of the following
1. Brief code sample/snippet: include here in preformatted/code section
2. Longer example stored somewhere else (diff repo, snippet), add a link
3. Textual explanation: include here
 -->
```java
public class UserBalanceVo {

    private String marginCoin;
    private BigDecimal accountNormal;
    private BigDecimal accountLock;
    private BigDecimal partPositionNormal;
    private BigDecimal totalPositionNormal;
    private BigDecimal achievedAmount;
    private BigDecimal unrealizedAmount;
    private BigDecimal totalMarginRate;
    private BigDecimal totalEquity;
    private BigDecimal partEquity;
    private BigDecimal totalCost;
    private BigDecimal sumMarginRate;
    private BigDecimal reserveFee;

    private List<PositionVo> positionVos;

    @Data
    @Builder
    public static class PositionVo {
        private Integer contractId;
        private String contractName;
        private String contractSymbol;
        private List<CoPosition> positions;
    }
}

@FeignClient("futures-order-service")
@RequestMapping("/rpc")
public interface BillingRpcClient {
    @GetMapping("find_assets")
    ApiResultVo<List<UserBalanceVo>> findAssets(@RequestParam("uid") Integer uid);


}

List<UserBalanceVo> userBalanceVos = billingRpcClient.findAssets(user.getId()).getData();

// Your code here
```

**Comment by pjfanning** [comment]
our first response when you say you are using v2.9.8 is could you try v2.15.3?
