### ISSUE TITLE
issue parsing 'INF' using readTree

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-databind#4193]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

I tried adding this test - based on the existing test in NumberNodes1770Test.

```    
public void testBigDecimalCoercionInf() throws Exception
    {
        final String value = "INF";
        JsonFactory factory = JsonFactory.builder()
                .enable(JsonReadFeature.ALLOW_NON_NUMERIC_NUMBERS)
                .build();
        final JsonNode jsonNode = new JsonMapper(factory).reader()
                .with(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS)
                .readTree(value);
        assertTrue("Expected DecimalNode, got: "+jsonNode.getClass().getName()+": "+jsonNode, jsonNode.isBigDecimal());
        assertEquals(new BigDecimal(value), jsonNode.decimalValue());
    }
```

It fails with
```
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'INF': was expecting (JSON String, Number (or 'NaN'/'INF'/'+INF'), Array, Object or token 'null', 'true' or 'false')
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 4]

	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2481)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:762)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:3042)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:3020)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchToken2(ReaderBasedJsonParser.java:2810)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchToken(ReaderBasedJsonParser.java:2788)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2069)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:812)
	at com.fasterxml.jackson.databind.ObjectReader._bindAsTree(ObjectReader.java:2157)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndCloseAsTree(ObjectReader.java:2137)
	at com.fasterxml.jackson.databind.ObjectReader.readTree(ObjectReader.java:1839)
```

It looks like it should work and even the exception message says `Unrecognized token 'INF'` but then includes 'INF' in the list of expected values.

### Version Information

2.16.0-rc1

### Reproduction

<-- Any of the following
1. Brief code sample/snippet: include here in preformatted/code section
2. Longer example stored somewhere else (diff repo, snippet), add a link
3. Textual explanation: include here
 -->
```java
// Your code here
```

**Comment by pjfanning** [comment]
> This does sound like a bug.
> 
> I wonder if we could reproduce this at streaming (jackson-core) level... or if it is due to databind-level problem.
> 
> I can see why `DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS` should cause an actual failure, but not with exception message claiming invalid token) -- there not being any way to handle `NaN`s with `BigDecimal`

The DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS does not seem to affect the test. jackson-core has tests for parsing INF value but something about using JsonMapper seems to have an issue.

**Comment by pjfanning** [comment]
Looks like '+INF' works - the issue is with 'INF' and it does appear that in jackson-core that '+INF' is allowed while 'INF' is not.

**Comment by cowtowncoder** [comment]
Right, just saying that if parser did not cause issues, databind should (directly or by triggering access) -- there is no way to represent Infinity as `BigDecimal`.
