### ISSUE TITLE
@JacksonAnnotationsInside doesn't work with records

### ISSUE THREAD

**Issue by lpandzic** [FasterXML/jackson-databind#4196]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

When using @JacksonAnnotationsInside on a property of a class it works as expected, but when the class is switched to a record it simply ignores the annotations and behaves as if it was not there at all. In reproduction below it injects null and doesn't throw any exception.

### Version Information

2.15.3

### Reproduction

Code is compiled with -parameters option.

```java
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.module.paramnames.ParameterNamesModule;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.lang.annotation.*;
import java.util.Objects;

import static org.assertj.core.api.BDDAssertions.then;

public class JacksonTest {

    private final ObjectMapper objectMapper;

    public JacksonTest() {
        this.objectMapper = new ObjectMapper();
        objectMapper.registerModule(new ParameterNamesModule());
    }

    @Test
    void shouldDeserializeARecord() throws JsonProcessingException {
        // given
        var givenValue = new ARecord(1L);
        var givenJson = objectMapper.writeValueAsString(givenValue);

        // when
        var actual = objectMapper.readValue(givenJson, ARecord.class);

        // then
        then(actual).isEqualTo(givenValue);
    }

    @Test
    void shouldDeserializeAClass() throws JsonProcessingException {
        // given
        var givenValue = new AClass(1L);
        var givenJson = objectMapper.writeValueAsString(givenValue);

        // when
        var actual = objectMapper.readValue(givenJson, AClass.class);

        // then
        then(actual).isEqualTo(givenValue);
    }

    record ARecord(
            @LongKey
            Long id
    ) {
    }

    static class AClass {

        @LongKey
        private final Long id;

        @JsonCreator
        AClass(Long id) {
            this.id = id;
        }

        public Long getId() {
            return id;
        }

        @Override
        public boolean equals(Object object) {
            if (this == object) {
                return true;
            }
            if (object == null || getClass() != object.getClass()) {
                return false;
            }
            AClass aClass = (AClass) object;
            return Objects.equals(id, aClass.id);
        }

        @Override
        public int hashCode() {
            return Objects.hash(id);
        }
    }

    @LongToString
    @JsonProperty("key")
    @JacksonAnnotationsInside
    @Target({ElementType.FIELD, ElementType.ANNOTATION_TYPE})
    @Retention(RetentionPolicy.RUNTIME)
    @interface LongKey {

    }

    @JsonDeserialize(using = JsonToStringJsonDeserializer.class)
    @JacksonAnnotationsInside
    @Target({ElementType.FIELD, ElementType.ANNOTATION_TYPE})
    @Retention(RetentionPolicy.RUNTIME)
    public @interface LongToString {

    }

    public static class JsonToStringJsonDeserializer extends JsonDeserializer<Long> {

        @Override
        public Long deserialize(JsonParser jsonParser, DeserializationContext deserializationContext) throws
                IOException {
            return jsonParser.getValueAsLong();
        }
    }
}
```

Result for record case is:
```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "key" (class infobip.jackson.test.JacksonTest$ARecord), not marked as ignorable (one known property: "id"])
 at [Source: (String)"{"key":1}"; line: 1, column: 10] (through reference chain: infobip.jackson.test.JacksonTest$ARecord["key"])

	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1138)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2224)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1709)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1659)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:546)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1409)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
```

For class case test passes.

### Expected behavior

Test passes for record case.
```java
objectMapper.readValue(givenJson, ARecord.class);
```

returns a

```java
new ARecord(1L)
```

**Comment by JooHyukKim** [comment]
> expected, but when the class is switched to a record it stops working.

Could you elaborate further on "stops working"? If exception is thrown, error message and stackstrace would help. If no error, how does it behave?

**Comment by lpandzic** [comment]
Edited original post.

**Comment by pjfanning** [comment]
To be clear, we don't normally accept samples that have lots of dependencies. Could you remove Lombok as a starter?

**Comment by cowtowncoder** [comment]
Yeah, we'd need non-Lombok-depending version -- possibly source of what Lombok would produce (or equivalent). This is needed to add test case, but is also important to rule out possibility that processing by Lombok might be causing the issue itself as well.
(having said that, Jackson and Lombok do work together quite well most of the time)

**Comment by lpandzic** [comment]
Removed lombok and added definition of ObjectMapper.

**Comment by JooHyukKim** [comment]
Thank you for de-lombok-ing! 🙏🏼

So I tried to reproduce the issue with minimal configuration proving that @JacksonAnnotationsInside does work with records. 

```java
public class AnnotationsTest {
    private final ObjectMapper objectMapper = new ObjectMapper();

    @Test
    void shouldDeserializeARecord() throws JsonProcessingException {
        // given
        ARecord rec = new ARecord(3L);
        // when
        var actual = objectMapper.writeValueAsString(rec);
        // then
        assertEquals(actual, "{\"key\":3}");
    }

    record ARecord(@LongKey Long id) { }

    @JsonProperty("key")
    @JacksonAnnotationsInside
    @Target({ElementType.FIELD, ElementType.ANNOTATION_TYPE})
    @Retention(RetentionPolicy.RUNTIME)
    @interface LongKey {

    }
}
```

... and we can tell `@JacksonAnnotationsInside` works by assertion passing. So probably not `@JacksonAnnotationsInside` itself. Instead, could be it be something about....

- What `ParameterNamesModule` does? or
- The `Class` version test having `@JsonCreator` while `Record` version does not?

**Comment by yihtserns** [comment]
```
record ARecord(@LongKey Long id) { }
```
...is equivalent to:
```
public class ARecord {
    @LongKey
    private final String Long id;

    public ARecord(Long id) {
        this.id = id;
    }

    public String getId() {
        return this.id;
    }
}
```

Unlike POJO, Records don't allow value injection for `final` field, so you need to change your annotation to allow for `PARAMETER`:
```
@JsonProperty("key")
@JacksonAnnotationsInside
@Target({ElementType.FIELD, ElementType.ANNOTATION_TYPE, ElementType.PARAMETER}) // <----
@Retention(RetentionPolicy.RUNTIME)
@interface LongKey {
}
```
...which will result in a Record that is equivalent to:
```

```
public class ARecord {
    @LongKey
    private final String Long id;

    public ARecord(@LongKey Long id) {
        this.id = id;
    }

    public String getId() {
        return this.id;
    }
}
```
```

**Comment by lpandzic** [comment]
@yihtserns thanks, that fixed the issue!
