### ISSUE TITLE
Cannot serialize certificates on jdk 17 (works on jdk 11)

### ISSUE THREAD

**Issue by josephks** [FasterXML/jackson-databind#4204]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Attempting to serialize a certificate fails because Jackson tries to make a method public that is already public.  Output is:

```
Java version: 17.0.8+7

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type `sun.security.x509.X509CertImpl`: Failed to construct BeanSerializer for [simple type, class sun.security.x509.X509CertImpl]: (java.lang.IllegalArgumentException) Failed to call `setAccess()` on Method 'getSignature' (of class `sun.security.x509.X509CertImpl`) due to `java.lang.reflect.InaccessibleObjectException`, problem: Unable to make public byte[] sun.security.x509.X509CertImpl.getSignature() accessible: module java.base does not "exports sun.security.x509" to unnamed module @3b81a1bc (through reference chain: net.tupari.CertTest$JksInfo["certs"]->java.util.ArrayList[0])

	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:72)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadTypeDefinition(SerializerProvider.java:1302)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanOrAddOnSerializer(BeanSerializerFactory.java:475)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanOrAddOnSerializer(BeanSerializerFactory.java:295)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:240)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:174)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1525)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1473)
	at com.fasterxml.jackson.databind.SerializerProvider.findContentValueSerializer(SerializerProvider.java:811)
	at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddSecondarySerializer(PropertySerializerMap.java:90)
	at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase._findAndAddDynamic(AsArraySerializerBase.java:314)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:115)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:183)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4793)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:4038)
	at net.tupari.CertTest.showSystemCerts(CertTest.java:78)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

The nature of the way this exception is thrown makes it difficult for me to determine exactly where in the codebase Jackson is attempting this operation that is failing.

### Version Information

2.15.3, 2.16.0-rc1

### Reproduction

Failing unit test:

```java

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.security.KeyStore;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.cert.Certificate;
import java.security.cert.CertificateException;
import java.util.Enumeration;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

import static org.junit.jupiter.api.Assertions.assertTrue;


public class CertTest {

    private static <X> Stream<X> toStream(Enumeration<X> enumeration){
        return StreamSupport.stream(java.util.Spliterators.spliteratorUnknownSize(enumeration.asIterator(), 0), true);
    }

    public static class JksInfo{
        @JsonIgnore
        final KeyStore keyStore;

        public JksInfo(KeyStore keyStore) {
            this.keyStore = keyStore;
        }

        @JsonProperty
        public java.util.List<Certificate> getCerts() throws KeyStoreException {
            return toStream(keyStore.aliases())
                    .map(alias -> {
                        try{
                            return keyStore.getCertificate(alias);
                        } catch (KeyStoreException e) {
                            throw new RuntimeException(e);
                        }
                    })
                    .collect(Collectors.toList());
        }
    }

    @Test
    void showSystemCerts() throws IOException, CertificateException, NoSuchAlgorithmException, KeyStoreException {
        System.out.println("Java version: " + Runtime.version());

        final KeyStore keyStore = KeyStore.getInstance("JKS");
        {
            File cacertsFile = new File(System.getProperty("sun.boot.library.path") +
                    File.separatorChar + "security" + File.separatorChar + "cacerts");
            assertTrue(cacertsFile.canRead());
            keyStore.load(new FileInputStream(cacertsFile), "changeit".toCharArray());
        }

        final ObjectMapper objectMapper = new ObjectMapper();
        {
            objectMapper.registerModule(
                    new com.fasterxml.jackson.datatype.jsr310.JavaTimeModule()
            );
            objectMapper.setConfig(
                    objectMapper.getSerializationConfig().without(SerializationFeature.FAIL_ON_EMPTY_BEANS)
            );
        }

        String json = objectMapper.writeValueAsString(new JksInfo(keyStore));
        System.out.println(json);
    }
}

``` 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>net.tupari</groupId>
    <artifactId>jackson-cert-bug</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jackson.version>2.16.0-rc1</jackson.version> <!-- also fails with 2.15.3 -->
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.10.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
```

### Expected behavior

I expect the certificate to be turned into a json string.

**Comment by pjfanning** [comment]
That's not what the exception says.

It says: `module java.base does not "exports sun.security.x509" to unnamed module @3b81a1bc`

Can you trying playing with your [Java Module](https://www.oracle.com/corporate/features/understanding-java-9-modules.html) settings? If you're not familiar with Java Modules, use your favourite search tool to look up `--add-modules` and `--add-opens` settings.

**Comment by josephks** [comment]
OK that works, but should it be necessary?  Can't Jackson use the public methods from the public interface that X509CertImpl implements (java.security.cert.X509Certificate) ?

**Comment by pjfanning** [comment]
> OK that works, but should it be necessary? Can't Jackson use the public methods from the public interface that X509CertImpl implements (java.security.cert.X509Certificate) ?

The whole point of the Java Modules is to make Java maintainers more aware of what their code is doing under the hood. Certs are one of the most dangerous classes to serialize/deserialize. In my opinion, we should not make any changes to jackson-databind to make it easier to serialize/deserialize Certs.

**Comment by josephks** [comment]
> Quick note: disabling `MapperFeature.OVERRIDE_PUBLIC_ACCESS_MODIFIERS` will prevent Jackson from trying to force access on `public` accessors (fields. methods). 

Yeah I discovered that after I first posted, but it didn't completely make my code work.  Using --add-modules does.

**Comment by cowtowncoder** [comment]
> > Quick note: disabling `MapperFeature.OVERRIDE_PUBLIC_ACCESS_MODIFIERS` will prevent Jackson from trying to force access on `public` accessors (fields. methods).
> 
> Yeah I discovered that after I first posted, but it didn't completely make my code work. Using --add-modules does.

Right, it is likely some other operations still need access (either non-public accessors, or possibly even use of Reflection).

**Comment by cowtowncoder** [comment]
Ok, there is one possible improvement we could consider making (in 2.17, due to timing): making `sun.security.*` (or maybe even `sun.*`) be considered JDK classes, for purposes of handling. This reduces amount of auto-discovery performed, and may avoid some outright failures and/or warnings.
It might also cause issues for some usage that relies on more pervasive auto-discovery, mostly for cases that just "happen to work" assuming Java Bean handling.

I'll create a follow-up ticket for that.

**Comment by cowtowncoder** [comment]
Closing this in preference of the follow-up ticket.

**Comment by josephks** [comment]
> Yeah I discovered that after I first posted, but it didn't completely make my code work. Using --add-modules does.

For future reference: It was --add-exports, not --add-modules

**Comment by cowtowncoder** [comment]
Interesting. Did not require `--add-opens`? (I think that gives more access than `--add-exports`).

**Comment by josephks** [comment]
No just four --add-exports:
* java.base/sun.security.x509=ALL-UNNAMED
* java.base/sun.security.util=ALL-UNNAMED
* java.base/sun.security.rsa=ALL-UNNAMED
* jdk.crypto.ec/sun.security.ec=ALL-UNNAMED
