### ISSUE TITLE
Add details about current node in DeserializationProblemHandler.handleMissingTypeId

### ISSUE THREAD

**Issue by itineric** [FasterXML/jackson-databind#4256]
### Is your feature request related to a problem? Please describe.

When using `handleMissingTypeId `to search for best type to match the baseType passed as parameter it may be helpful to get the JsonNode (or equivalent) of what was just read.
The `DeserializationContext` already points to the end of the JsonNode and there is no way we can get the data that was read for the node with the parameters that are passed to the method.

### Describe the solution you'd like

Another `handleMissingTypeId` with a new parameter containing data of the current JsonNode.

**Comment by yawkat** [comment]
can you give a use case? handleMissingTypeId does not get access to the data at all atm, it's up to the caller how to handle buffering and such

**Comment by itineric** [comment]
Some context using a simple usecase (simpler then the real one I am dealing with but representative enough):

I have `Cat extends Animal` and I am serializing an `Animal.class` using some custom class resolver I am getting the following:
```
{
  "@class":  "com.example.Cat",
  "name": "my-cat"
}
```

But in an earlyer version of my API I have stored something like:
```
{
  "my-type":  "Cat",
  "name": "my-cat"
}
```

I would like to use the `handleMissingTypeId` to deal with all other properties and historical/ignored stuff. I am not far from getting there but I am missing some info about the current JsonNode that is being read.

I do not understand what you mean by _"it's up to the caller how to handle buffering and such"_ since the caller is genuine jackson. See the stack bellow:

```
java.lang.Exception
	at com.example.OldTypeDeserializationProblemHandler.handleMissingTypeId(OldTypeDeserializationProblemHandler.java:19)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingTypeId(DeserializationContext.java:1602)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleMissingTypeId(TypeDeserializerBase.java:307)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:211)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:145)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1306)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4899)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3846)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3814)
	at com.example.JacksonTest.main(JacksonTest.java:32)
```

**Comment by cowtowncoder** [comment]
No such information is available at the point of call, as far as I can remember.

Jackson does not keep track of full object representation; any buffering needed is done using `TokenBuffer`.
Note, too, that in the most efficient use case there is no `JsonNode` involved: content is read from streaming input (like `InputSream`) via `JsonParser`. So there really is no mechanism to provide content tree.

Will close as "can not implement"; this use case unfortunately sounds a lot like "need to write custom deserializer".
