### ISSUE TITLE
Getters needed for ignored properties

### ISSUE THREAD

**Issue by maroony** [FasterXML/jackson-databind#4528]
### Describe your Issue

I'm wondering that I have to write getters for ignored properties. Here's an working example:

```java
import java.io.IOException;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.MappingIterator;
import com.fasterxml.jackson.dataformat.csv.CsvMapper;
import com.fasterxml.jackson.dataformat.csv.CsvSchema;
import com.fasterxml.jackson.module.paramnames.ParameterNamesModule;

@JsonPropertyOrder({
    "text",
    "ignored",
    "number"
})
@JsonIgnoreProperties(ignoreUnknown = true)
public class Example {

  private String text;
  private Integer number;

  @JsonCreator()
  public Example(String text, Integer number) {
    this.text = text;
    this.number = number;
  }

  public String getText() {
    return text;
  }

  public Integer getNumber() {
    return number;
  }

  // jackson needed getter
  public Object getIgnored() {
    return null;
  }

  public static void main(String[] args) throws IOException {

    CsvMapper csvMapper = new CsvMapper();
    csvMapper.registerModule(new ParameterNamesModule());
    CsvSchema csvSchema = csvMapper.schemaFor(Example.class);

    String value = "foo, ignoredValue, 123";

    MappingIterator<Example> iterator = csvMapper.readerFor(Example.class)
        .with(csvSchema)
        .readValues(value);

    var nextValue = iterator.next();

    System.out.println(nextValue.getText() + ", " + nextValue.getNumber());

  }
}
```

If you *delete* the getter `getIgnored()`, the following exception will be thrown:

```
Exception in thread "main" com.fasterxml.jackson.databind.RuntimeJsonMappingException: Cannot deserialize value of type `java.lang.Integer` from String "ignoredValue": not a valid `java.lang.Integer` value
 at [Source: (StringReader); line: 1, column: 5] (through reference chain: de.debeka.aktuariatlv.commons.ssvfile.backup.Example["number"])
        at com.fasterxml.jackson.databind.MappingIterator._handleMappingException(MappingIterator.java:416)
        at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:201)
        at de.debeka.aktuariatlv.commons.ssvfile.backup.Example.main(Example.java:55)
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Integer` from String "ignoredValue": not a valid `java.lang.Integer` value
 at [Source: (StringReader); line: 1, column: 5] (through reference chain: de.debeka.aktuariatlv.commons.ssvfile.backup.Example["number"])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1958)
        at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1245)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:848)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:827)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:531)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:506)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:440)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1493)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:348)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.MappingIterator.nextValue(MappingIterator.java:283)
        at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:199)
        ... 1 more
```

Is this expected behavior? Is there something I can do to omit writing these getters?

**Comment by JooHyukKim** [comment]
1. There is separate repo for csv format repository and ParamNameModules repo. 
2. Ignore unknown option literally means it ignores any undeclared property. Getter may or may not be related?

**Comment by maroony** [comment]
I really don't know, if this is specific to CSV. So I opened the issue here. Feel free to move it to a better place.

**Comment by JooHyukKim** [comment]
Which Jackson version are you using?

**Comment by maroony** [comment]
I'm using version 2.17.0 for all jackson dependencies.

**Comment by maroony** [comment]
Just updated to version 2.17.1: same behavior.

**Comment by JooHyukKim** [comment]
Did it ever work? like in other version?
You may try asking over at Stackoverflow (or similar) first or inquire over at [jackson-dataformats-text](https://github.com/FasterXML/jackson-dataformats-text) repo.
But mind that usage inquiry should be asked vis Github Discussions, not Issue

**Comment by maroony** [comment]
I didn't see this working before. I started a [discussion](https://github.com/FasterXML/jackson-dataformats-text/discussions/475) in [jackson-dataformats-text](https://github.com/FasterXML/jackson-dataformats-text).

**Comment by yihtserns** [comment]
Seems related to https://github.com/FasterXML/jackson-dataformat-csv/issues/82.  Has there been any new enhancement to better support such use case since then?

(Credit: https://stackoverflow.com/a/56067713)

**Comment by cowtowncoder** [comment]
It definitely looks like CSV specific; I will transfer.

Ok so... in general with `ignoreUnknown = true` it should not be necessary to have getter or setter for ignored property.

However. For generating `CsvSchema` there has to be something indicating what is in position, and this might be the source of problem. If you built `CsvSchema` manually, or it was created from header line, things might work better.
But if using `CsvMapper.schemaFor()` I think matching property is indeed needed.
