### ISSUE TITLE
Include owning class + field/getter/setter name in JsonMappingException

### ISSUE THREAD

**Issue by mahendribippo** [FasterXML/jackson-databind#468]
Currently Jackson v2.3.3 throws an exception like this: `Can not find a deserializer for non-concrete Collection type [collection type; class org.eclipse.emf.common.util.EList, contains [simple type, class java.lang.String]]`

which is more helpful than nothing, but it should also specify :

1. which (parent) owning class(es) of the problematic field/getter/setter
2. the parent name(s) (if any)
3. the name of the problematic field/getter/setter

For example, an ideal exception would mention something like:

```
product: id.co.bippo.product.impl.VariedProductImpl
  -> variants: java.util.List<id.co.bippo.product.impl.ProductVariantImpl>
    -> [0]
      -> discounts: java.util.List<id.co.bippo.common.Discount>
        -> [0] (???)
```

Having these additional information is crucial to solving the problem much quicker.

```
com.fasterxml.jackson.databind.JsonMappingException: Can not find a deserializer for non-concrete Collection type [collection type; class org.eclipse.emf.common.util.EList, contains [simple type, class java.lang.String]]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:268)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:243)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:144)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:366)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:699)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:438)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:243)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:144)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:366)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:699)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:438)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:243)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:144)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:366)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:182)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:104)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:87)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:132)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:229)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:204)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2993)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2105)
	at id.co.bippo.product.util.ProductUtils.getProductsFromAPI(ProductUtils.java:42)
	... 24 more
Caused by: java.lang.IllegalArgumentException: Can not find a deserializer for non-concrete Collection type [collection type; class org.eclipse.emf.common.util.EList, contains [simple type, class java.lang.String]]
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.createCollectionDeserializer(BasicDeserializerFactory.java:814)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:392)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:350)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:263)
	... 49 more
```

**Comment by cowtowncoder** [comment]
With Jackson 2.5 and above it is actually possible to find "owner" of property, actual instance. This works via `JsonParser` / `JsonGenerator` method `getCurrentValue()` (or more generally via `getParsingContext()` / `getOutputContext())`.
Type information is not available.

There are no current plans by Jackson team to work on this, but we are always open to PRs if anyone thinks they could help here.

**Comment by cowtowncoder** [comment]
Can not implement currently. May be re-filed with a PR.
