### ISSUE TITLE
Combining JsonDeserialize(as=) with setter throws JsonMappingException: Failed to narrow type 

### ISSUE THREAD

**Issue by ceefour** [FasterXML/jackson-databind#469]
My use case is EMF specific, which many people use, but I don't know how many combine EMF with Jackson.

EMF EList (discussed here) and EMap (maybe some other time) has a rule that it's owned by the parent object and it's instantiated by the parent object. So in the case below, to "set" the `categories` `EList`, what we actually need to do is "get" (which will auto-create the EList) first, then do a `addAll`.

Anyway, trying to ser/deser EMF EList:

```
	@JsonDeserialize(as=ArrayList.class)
	EList<CategoryInfo> getCategories();
```

using the following getter/setter :

```
	@Override
	public EList<CategoryInfo> getCategories() {
		if (categories == null) {
			categories = new EObjectResolvingEList<CategoryInfo>(CategoryInfo.class, this, ProductPackage.PRODUCT__CATEGORIES);
		}
		return categories;
	}
	
	protected void setCategories(List<CategoryInfo> categories) {
		getCategories().clear();
		getCategories().addAll(categories);
	}
```

throws the following exception. Which is not what I expected, since I already told Jackson to `@JsonDeserialize` it as `ArrayList` (or actually, whatever Jackson wants for a normal `List`), then pass it to `setCategories(List<CategoryInfo>)` (which accepts a normal Java `List`, not an `EList`, hence the `@JsonDeserialize`) which will do the right thing.

```
com.fasterxml.jackson.databind.JsonMappingException: Failed to narrow type [collection type; class org.eclipse.emf.common.util.EList, contains [simple type, class org.soluvas.commons.CategoryInfo]] with concrete-type annotation (value java.util.ArrayList), method 'getCategories': Class java.util.ArrayList is not assignable to org.eclipse.emf.common.util.EList
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.modifyTypeByAnnotation(BasicDeserializerFactory.java:1467)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.constructSetterlessProperty(BeanDeserializerFactory.java:809)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:557)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:270)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:168)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:401)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:350)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:263)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:243)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:144)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:381)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3095)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2989)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2098)
	at id.co.bippo.product.web.ProductVariantImplSerializationTest.serDeserProductViaJsonThenXmi(ProductVariantImplSerializationTest.java:372)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.IllegalArgumentException: Class java.util.ArrayList is not assignable to org.eclipse.emf.common.util.EList
	at com.fasterxml.jackson.databind.JavaType._assertSubclass(JavaType.java:428)
	at com.fasterxml.jackson.databind.JavaType.narrowBy(JavaType.java:150)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.modifyTypeByAnnotation(BasicDeserializerFactory.java:1465)
	... 37 more
```

**Comment by cowtowncoder** [comment]
I don't think there is an actual bug here, if `EList` is not an `ArrayList`. I am also not quite sure why the assumption is that there would be linkage between get and set methods; these are usually not used in conjuction. But I suspect converting (de)serializer is what was being attempted.
