### ISSUE TITLE
Can not set java.lang.Long field com.google.api.services.gmail.model.ListMessagesResponse.resultSizeEstimate to java.lang.Integer

### ISSUE THREAD

**Issue by kulame** [FasterXML/jackson-databind#4719]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

i try to convert  "com.google.api.services.gmail.model.ListMessagesResponse",
my convert code 
```java


    public Mono<ListMessagesResponse> fetchGmail(GoogleFetchEvent event) {
        String url = "https://gmail.googleapis.com/gmail/v1/users/me/messages";

        return webClient.get()
                .uri(url)
                .header(HttpHeaders.AUTHORIZATION, "Bearer " + event.getAccessToken())
                .retrieve()

                .bodyToMono(ListMessagesResponse.class)
                .doOnNext(response -> log.info("Fetched Gmail messages: {}", response.getMessages()));

    }
```

it's raise exception 
```bash
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not set java.lang.Long field com.google.api.services.gmail.model.ListMessagesResponse.resultSizeEstimate to java.lang.Integer (through reference chain: com.google.api.services.gmail.model.ListMessagesResponse["resultSizeEstimate"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402) ~[jackson-databind-2.17.2.jar:2.17.2]
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361) ~[jackson-databind-2.17.2.jar:2.17.2]
        at com.fasterxml.jackson.databind.deser.std.ContainerDeserializerBase.wrapAndThrow(ContainerDeserializerBase.java:190) ~[jackson-databind-2.17.2.jar:2.17.2]
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:638) ~[jackson-databind-2.17.2.jar:2.17.2]
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:449) ~[jackson-databind-2.17.2.jar:2.17.2]
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32) ~[jackson-databind-2.17.2.jar:2.17.2]
```
How should I handle this bug?

### Reproduction

<-- Any of the following
1. Brief code sample/snippet: include here in preformatted/code section
2. Longer example stored somewhere else (diff repo, snippet), add a link
3. Textual explanation: include here
 -->
```java
// Your code here
``` 

### Expected behavior

parse  ListMessagesResponse  success!

**Comment by pjfanning** [comment]
Maybe you should also raise this with the maintainers of that Google Mail library. They could have some highly customised Jackson setup. It might also be useful if they knew that this issue could happen.

Generally, we only accept bug reports where the code only involves Jackson usage and not other libraries.

**Comment by pjfanning** [comment]
The ListMessagesResponse class appears to be https://github.com/googleapis/google-api-java-client-services/blob/main/clients/google-api-services-gmail/v1/2.0.0/com/google/api/services/gmail/model/ListMessagesResponse.java

It is not clear from its definition why com.fasterxml.jackson.databind.deser.std.MapDeserializer should be involved.

**Comment by pjfanning** [comment]
ListMessagesResponse does extend these classes and GenericData has a Map.

* https://github.com/googleapis/google-http-java-client/blob/main/google-http-client/src/main/java/com/google/api/client/json/GenericJson.java
* https://github.com/googleapis/google-http-java-client/blob/main/google-http-client/src/main/java/com/google/api/client/util/GenericData.java

**Comment by pjfanning** [comment]
@kulame the following article has details about how to use the Google libs to get a list of messages

https://medium.com/@magnoai/mastering-gmail-api-with-java-a-comprehensive-guide-1a167ad111a9

Would you be tempted to use the code that appears in that article?

**Comment by kulame** [comment]
I am using reactive Java and cannot use this code. Thank you, I will think of other solutions.
