### ISSUE TITLE
Improve error message when @JsonValue and @JsonProperty are applied to the same class

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-databind#498]
Jackson 2.4.1 (data-bind 2.4.1.1)

I attempted to deserialize `["http://example.com/"]` using:

```
public static final class GetAuthentications
{
	private final List<URI> authentications;

	/**
	 * Creates a new GetAuthentications.
	 * <p/>
	 * @param authentications the list of authentications
	 * @throws NullPointerException if authentications is null
	 */
	@JsonCreator
	public GetAuthentications(@JsonProperty("authentications") List<URI> uthentications)
		throws NullPointerException
	{
		Preconditions.requireThat(authentications, "authentications").isNotNull();
		this.authentications = ImmutableList.copyOf(authentications);
	}

	/**
	 * @return the list of authentication tokens
	 */
	@SuppressWarnings("ReturnOfCollectionOrArrayField")
	@JsonValue
	public List<URI> getAuthentications()
	{
		return authentications;
	}
}
```

This resulted in Jackson throwing:

```
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of com.vtlr.backend.entity.AuthenticationsEntities$GetAuthentications out of START_ARRAY token
 at [Source: org.glassfish.jersey.message.internal.EntityInputStream@26c613d1; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:749)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:745)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1210)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:126)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1232)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:676)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:800)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:257)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:229)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:149)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1124)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:851)
	... 26 more
```

Once I removed `@JsonProperty("authentications")` everything worked fine. It took me a couple of hours to figure out what was wrong because the error makes it seem as if the input stream is empty when in fact there was nothing wrong with it.

Is it possible to improve the error message so Jackson says something along the lines of: "@JsonValue and @JsonProperty annotations cannot be applied to the same class. You must remove one of these annotations."?

**Comment by cowtowncoder** [comment]
Not sure what if anything could be done here; may be reopened with suggestions (although probably better to file a new issue to keep it closer to head).
