### ISSUE TITLE
"JsonMappingException: Could not resolve type id"  when registerSubtypes() is used after first serialization/deserialization

### ISSUE THREAD

**Issue by bwaldvogel** [FasterXML/jackson-databind#708]
`ObjectMapper.registerSubtypes()` does not seem to clear all internal state/caches when it is called **after** the first round-trip of serialization/deserialization.
I've written a boiled-down unit test that reproduces the issue: https://github.com/bwaldvogel/jackson-issue

Consider the following two unit tests that should both succeed as far as I understand the `ObjectMapper` API.

### Case 1 (succeeds) ###
```java
@Test
public void successfulTest() throws Exception {
	mapper.registerSubtypes(FirstValue.class);
	mapper.registerSubtypes(OtherValue.class);
	writeReadValue(new FirstValue("some value"));
	writeReadValue(new OtherValue("some other value"));
}
```

### Case 2 (fails) ###
The test fails if the `OtherValue.class` is registered **after** the first JSON serialization/deserialization round-trip in `writeReadValue`:

```java
@Test
public void failingTest() throws Exception {
	mapper.registerSubtypes(FirstValue.class);
	writeReadValue(new FirstValue("some value"));
	mapper.registerSubtypes(OtherValue.class);
	writeReadValue(new OtherValue("some other value"));
}
```

### The stacktrace ###
```
com.fasterxml.jackson.databind.JsonMappingException: Could not resolve type id 'OtherValue' into a subtype of [simple type, class Value]: known type ids = [FirstValue, Value]
 at [Source: {"value":{"@type":"OtherValue","string":"some other value"}}; line: 1, column: 11] (through reference chain: Holder["value"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.unknownTypeException(DeserializationContext.java:948)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:275)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:162)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:110)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:95)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:521)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at JacksonTest.writeReadValue(JacksonTest.java:38)
	at JacksonTest.failingTest(JacksonTest.java:33)
```

**Comment by cowtowncoder** [comment]
This is incorrect usage: registration of subtypes is not allowed after first use. It MUST be done before serialization/deserialization; what happens to registrations afterwards is undefined.

This is expected behavior because such information is cached when (de)serializer is constructed. The only way to get around that is to create a new `ObjectMapper` or `copy()` existing one.

**Comment by bwaldvogel** [comment]
Good to know, thanks.
Were can I read up the correct usage of `ObjectMapper`? I would be also interested in thread-safety for instance.
Would it be possible to throw an exception in case of such incorrect API usage?

**Comment by cowtowncoder** [comment]
Unfortunately it is difficult to enforce such a constraint, although I agree that it would be great to do that -- either prevent, or at least notify.

But as things are, a simple rule that may help is this: anything that can be (re)configured using `ObjectWriter` and `ObjectReader` is safe and may be used concurrently in thread-safe manner without any restrictions.
But anything configured on `ObjectMapper` (including module registrations) need to be done once and before any use: changing once in use is neither thread-safe nor guaranteed to take effect.
This is why I recommend using `ObjectReader` /  `ObjectWriter` as much as possible since there are no odd rules on what can or can be done: they only expose things that can be freely used.

Now: as long as "configure-then-use" is followed, `ObjectMapper` usage is fully thread-safe as well.
It is only configuration phase that is less flexible.

**Comment by kevindavison123** [comment]
I'm a bit late to the party, is there an annotation equivalent for an ObjectMapper.registerSubtypes(Class class)?
Does @JsonSubTypes({...}) fulfill this?

**Comment by cowtowncoder** [comment]
@kevindavison123 Yes, `@JsonSubTypes` is equivalent.

**Comment by singhaman7490** [comment]
While deserialize, please use the same package structure which have been used while serializing.
