### ISSUE TITLE
Issue with loading jackson libraries because of CaSe difference

### ISSUE THREAD

**Issue by nareshsankapellyfkrt** [FasterXML/jackson-databind#748]
There is a dependency on com/fasterxml/jackson/databind/jsonschema/SchemaAware in my project. I have built a fatJar using gradle and dropwizard db migrations give the following error. 

Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/jsonschema/SchemaAware
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:450)
    at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:366)
    at io.dropwizard.jackson.Jackson.newObjectMapper(Jackson.java:19)
    at io.dropwizard.setup.Bootstrap.<init>(Bootstrap.java:61)
    at io.dropwizard.Application.run(Application.java:67)
    at com.flipkart.birbal.BirbalApplication.main(BirbalApplication.java:29)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.jsonschema.SchemaAware
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 30 more

The fatJar has reference to com/fasterxml/jackson/databind/jsonSchema/SchemaAware.class. So, there is a CaSe difference in jsonSchema.

What could be the reason for this?

**Comment by cowtowncoder** [comment]
Sounds like someone has dropped `SchemaAware` from getting included, or something it depends on (looking at interface itself there isn't much it refers to -- `JsonNode`, perhaps).
Maybe fatJar needs prompting to include this class as a dependency?

`SchemaAware` is included by all Jackson 2.x versions, so my first thought (minor version discrepancy) is probably not correct.

**Comment by cowtowncoder** [comment]
I don't know if there is something to fix, or if so, how. Closing; may be re-opened with additional information.
