### ISSUE TITLE
@JsonTypeInfo (de)serialization fails for polymorphic array types and external property

### ISSUE THREAD

**Issue by dashorst** [FasterXML/jackson-databind#753]
Given the following model:

``` java
    @JsonInclude(Include.NON_NULL)
    public static class Foo {
        @JsonTypeInfo(use = Id.CLASS, include = As.EXTERNAL_PROPERTY, property = "type")
        private Object foo;

        @JsonTypeInfo(use = Id.CLASS, include = As.EXTERNAL_PROPERTY, property = "type")
        private Object[] foos;

        public Object getFoo() {
            return foo;
        }

        public void setFoo(Object foo) {
            this.foo = foo;
        }

        public Object[] getFoos() {
            return foos;
        }

        public void setFoos(Object[] foos) {
            this.foos = foos;
        }
    }

    public static class Bar {
        public Bar(String b) {
        }

        @JsonValue
        @Override
        public String toString() {
            return "bar";
        }
    }
```

When running the following serialization/deserialization test:

``` java
    @Test
    public void test1() throws JsonParseException, JsonMappingException, IOException {
        ObjectMapper mapper = new ObjectMapper();

        Foo foo = new Foo();
        foo.setFoo(new Bar(""));
        foo.setFoos(new Object[] { new Bar("")});

        String stringValue = mapper.writeValueAsString(foo);
        System.out.println(stringValue);
        // Assert.assertThat(stringValue,
        // Is.is("{\"foos\":\"bar\",\"type\":\"com.example.JsonTest$Bar\"}"));

        Foo foo2 = mapper.readValue(stringValue, Foo.class);
        Assert.assertThat(foo2.getFoos().length, Is.is(foo.getFoos().length));
        Assert.assertThat(foo2.getFoos()[0], Is.is(CoreMatchers.instanceOf(Bar.class)));
    }
```

test1 fails because the 'external property' is serialized into the array:

``` json
{"foo":"bar","type":"com.example.JsonTest$Bar","foos":["bar","type","com.example.JsonTest$Bar"]}
```

Trying to use an existing property (`JsonTypeInfo(include = As.EXISTING_PROPERTY)`) gives the unexpected result of serializing the type information with each element in the array instead of the existing, external property:

``` json
{"foo":"bar","type":"com.example.JsonTest$Bar","foos":[["com.example.JsonTest$Bar","bar"],["com.example.JsonTest$Bar","bar"]]}
```

(Perhaps naïvely I expected the following JSON serialization:)

Expected **by me, not necessarily any realistic scenario**:

``` json
{"foo":"bar","type":"com.example.JsonTest$Bar","foos":["bar","bar"]}
```

Given that, I suspect the following is an incomplete feature:

When running the following serialization/deserialization test it fails with an Exception:

```
    @Test
    public void test2() throws JsonParseException, JsonMappingException, IOException {
        ObjectMapper mapper = new ObjectMapper();

        Foo foo = new Foo();
        foo.setFoo(new Bar(""));
        foo.setFoos(new Object[] { new Bar(""), new Bar("") });

        String stringValue = mapper.writeValueAsString(foo);
        System.out.println(stringValue);

        Foo foo2 = mapper.readValue(stringValue, Foo.class);
        Assert.assertThat(foo2.getFoos().length, Is.is(foo.getFoos().length));
        Assert.assertThat(foo2.getFoos()[0], Is.is(CoreMatchers.instanceOf(Bar.class)));
    }
```

Running test 2 (using 2 array elements of type Bar) gives a `JsonGenerationException`:

```
com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value
    at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1574)
    at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeFieldName(WriterBasedJsonGenerator.java:102)
    at com.fasterxml.jackson.core.json.JsonGeneratorImpl.writeStringField(JsonGeneratorImpl.java:169)
    at com.fasterxml.jackson.databind.jsontype.impl.AsExternalTypeSerializer._writeScalarSuffix(AsExternalTypeSerializer.java:157)
    at com.fasterxml.jackson.databind.jsontype.impl.AsExternalTypeSerializer.writeTypeSuffixForScalar(AsExternalTypeSerializer.java:99)
    at com.fasterxml.jackson.databind.ser.std.JsonValueSerializer.serializeWithType(JsonValueSerializer.java:212)
    at com.fasterxml.jackson.databind.ser.std.ObjectArraySerializer.serializeTypedContents(ObjectArraySerializer.java:316)
    at com.fasterxml.jackson.databind.ser.std.ObjectArraySerializer.serializeContents(ObjectArraySerializer.java:217)
    at com.fasterxml.jackson.databind.ser.std.ObjectArraySerializer.serialize(ObjectArraySerializer.java:201)
    at com.fasterxml.jackson.databind.ser.std.ObjectArraySerializer.serialize(ObjectArraySerializer.java:25)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:575)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:664)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:156)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
    at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3385)
    at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2779)
    at com.example.JsonTest.test2(JsonTest.java:103)
```

**Comment by rpatrick00** [comment]
I am having a very similar issue with polymorphic types and Jackson 2.6.3 and XML (using JAXB annotations).

If my XML looks like this:

<pre>
&lt;?xml version='1.1' encoding='UTF-8'?&gt;&lt;Company&gt;&lt;employee&gt;
    &lt;employee id="1" name="Jane Doe"&gt;&lt;report&gt;
        &lt;report&gt;2&lt;/report&gt;
        &lt;report&gt;3&lt;/report&gt;
      &lt;/report&gt;
    &lt;/employee&gt;
    &lt;employee id="2" name="John Smith"&gt;
      &lt;computer&gt;computer-1&lt;/computer&gt;
      &lt;manager&gt;1&lt;/manager&gt;
    &lt;/employee&gt;
    &lt;employee id="3" name="Anne Jones"&gt;
      &lt;manager&gt;1&lt;/manager&gt;
    &lt;/employee&gt;
  &lt;/employee&gt;
  &lt;computers&gt;
    &lt;desktop id="computer-1"&gt;
      &lt;location&gt;workstation1&lt;/location&gt;
    &lt;/desktop&gt;
    &lt;laptop id="computer-2"/&gt;
  &lt;/computers&gt;
&lt;/Company&gt;
</pre>

My code to custom serializer code to convert the Java to XML works fine under Jackson 2.4.3 (I did have to use a custom XMLMapper that overwrites the default writeValue() implementation to get around a pretty print issue).  As soon as I switch to Jackson 2.6.3, I get an similar error:

<pre>
Exception in thread "main" com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1649)
	at com.fasterxml.jackson.dataformat.xml.ser.ToXmlGenerator.writeFieldName(ToXmlGenerator.java:418)
	at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1414)
	at derek.xml.employee.customserialization.ComputerListSerializer.serialize(ComputerListSerializer.java:28)
	at derek.xml.employee.customserialization.ComputerListSerializer.serialize(ComputerListSerializer.java:15)
	at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanPropertyWriter.serializeAsField(XmlBeanPropertyWriter.java:143)
	at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializerBase.serializeFields(XmlBeanSerializerBase.java:202)
	at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializer.serialize(XmlBeanSerializer.java:119)
	at com.fasterxml.jackson.dataformat.xml.ser.XmlSerializerProvider.serializeValue(XmlSerializerProvider.java:93)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3559)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2893)
	at derek.xml.employee.RunThis.writeJacksonStdOut(RunThis.java:86)
	at derek.xml.employee.RunThis.main(RunThis.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
</pre>

**Comment by cowtowncoder** [comment]
True, combination of container types (arrays, Collections, Maps) and `EXTERNAL_PROPERTY` is not supported. At this point I do not think it will ever be supported; will close this issue.
But I will add a note on Javadocs to document this limitation.

**Comment by cowtowncoder** [comment]
Added a note on Javadocs for `@JsonTypeInfo.As.EXTERNAL_PROPERTY` in `jackson-annotations`, closing.
