### ISSUE TITLE
IncompatibleClassChangeError on Android Lollipop

### ISSUE THREAD

**Issue by littledot** [FasterXML/jackson-databind#782]
Hi,

We use Jackson 2.5.2 to deserialize json in an Android app. All was fine and dandy until our users started to upgrade to Android Lollipop (5.0). We began seeing the following trace

```
java.lang.IncompatibleClassChangeError: java.lang.IncompatibleClassChangeError: Couldn't find com.fasterxml.jackson.annotation.JsonSubTypes$Type.value
	at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
	at java.lang.Class.getDeclaredAnnotations(Class.java:891)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClass.resolveClassAnnotations(AnnotatedClass.java:300)
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.isIgnorableType(JacksonAnnotationIntrospector.java:103)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.isIgnorableType(BeanDeserializerFactory.java:844)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:401)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:305)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:634)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:438)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:173)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:99)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:106)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:98)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
```

We could not figure out what was going on inside Jackson to cause this error and was hoping if anyone here could provide some insights.

Thank you!

**Comment by cowtowncoder** [comment]
This sounds very peculiar, as there are no changes to annotations in that area. Class referred has been included since 2.0, and I don't think there have been any changes at any point.

You could try 2.5.3 (released a week or so ago), although annotations package hasn't changed. No changes are allowed for annotations in patch releases.

**Comment by grede** [comment]
hey @littledot 
I'm fighting the same issue in my project. Seems to happen on Samsung devices running 5.0 & 5.0.1 only (according to the crashlytics).
Have you been able to solve this somehow?

**Comment by littledot** [comment]
Unfortunately no, we don't have the slightest clue what's going on.

**Comment by cowtowncoder** [comment]
Has anyone tried with 2.5.3 (of all three core pkgs, `jackson-annotations`, `jackson-core`, `jackson-databind`), just to rule out possibility there could be something odd about 2.5.2?

Also: if there is no explicit dependency from project to `jackson-annotations`, make sure it exists so that minor versions match.
But since that property (@JsonSubTypes$Type.value) has existed since 1.x, I don't think this is version incompatibility. Rather it looks like annotation package itself was missing.

So: maybe the best thing to do is to verify that `jackson-annotations` package is included.
