### ISSUE TITLE
Error in @JsonAnySetter @JsonPOJOBuilder

### ISSUE THREAD

**Issue by jeffklassen** [FasterXML/jackson-databind#822]
I'm getting a JsonMappingException when deserializing json to BatchMetricsImpl using the Builder pattern:
```
com.fasterxml.jackson.databind.JsonMappingException: Problem deserializing "any" property 'docStoreRefsMs' of class  dao.impl.BatchMetricImpl$Builder 
(expected type: [simple type, class java.lang.Object]; actual type: java.lang.Integer), 
problem: object is not an instance of declaring class (through reference chain: dao.impl.Builder["docStoreRefsMs"])
```

Integer does inherit from Object, so I'm not sure why I'm getting this error. Can you help?

I've included the relevant JSON and BatchMetricImpl class below.

**JSON**:

```javascript
{  
   "batchId":"testId",
   "comments":[  
      {  
         "comment":"testcomment1",
         "timestamp":"1434034631829"
      },
      {  
         "comment":"testcomment2",
         "timestamp":"1434034631868"
      }
   ],
   "errors":[  
      {  
         "error":"testerror1",
         "timestamp":"1434034631868"
      }
   ],
   "docStoreRefsMs":124,
   "batchType":"sampleType"
}
```

**My annotations around BatchMetricImpl**:
```Java
@JsonDeserialize(builder = BatchMetricImpl.Builder.class)
public class BatchMetricImpl implements BatchMetric {

	private String batchId;
	private Map<MetricProperty, Object> metricsProperties;
	private List<MetricsComment> comments;
	private List<MetricsError> errors;

	public BatchMetricImpl() {
	}

	private BatchMetricImpl(String batchId,
			Map<MetricProperty, Object> metricsProperties,
			List<MetricsComment> comments, List<MetricsError> errors) {
		this.batchId = batchId;
		this.metricsProperties = metricsProperties;
		this.comments = comments;
		this.errors = errors;
	}

	@Override
	public List<MetricsComment> getComments() {
		return this.comments;
	}

	@Override
	public List<MetricsError> getErrors() {
		return this.errors;
	}

	@Override
	@JsonAnyGetter
	public Map<MetricProperty, Object> getAllProperties() {
		return this.metricsProperties;
	}

	@Override
	public String getBatchId() {
		return this.batchId;
	}

	@Override
	public Object getProperty(MetricProperty metricsProperty) {
		if (this.metricsProperties.containsKey(metricsProperty)) {
			return this.metricsProperties.get(metricsProperty);
		} else {
			return null;
		}
	}

	@JsonPOJOBuilder(buildMethodName = "build", withPrefix = "add")
	public static class Builder {

		private String batchId;
		private Map<MetricProperty, Object> metricProperties;
		private List<MetricsComment> comments;
		private List<MetricsError> errors;

		// default constructure to make jackson happy
		public Builder() {
		}

		public Builder(@JsonProperty("batchId") String batchId) {
			this.batchId = batchId;
			this.metricProperties = new HashMap<MetricProperty, Object>();
			this.errors = new ArrayList<MetricsError>();
			this.comments = new ArrayList<MetricsComment>();
		}

		public Builder(BatchMetric batchMetric) {
			this.batchId = batchMetric.getBatchId();
			this.metricProperties = batchMetric.getAllProperties();
			this.comments = batchMetric.getComments();
			this.errors = batchMetric.getErrors();
		}

		@JsonAnySetter
		public Builder addSingleProperty(String key, Object value)
				throws IllegalArgumentException {

			MetricProperty metricProperty = MetricProperty.get(key);

			if (!metricProperty.validateValue(value)) {
				throw new IllegalArgumentException(value
						+ " was not of the type required by " + key + ". "
						+ metricProperty.getExpectedClass() + " expected.");
			}

			this.metricProperties.put(metricProperty, metricProperty
					.getExpectedClass().cast(value));
			return this;
		}

		public Builder addProperties(
				Map<MetricProperty, Object> metricsProperties) {
			if (metricsProperties != null) {
				this.metricProperties.putAll(metricsProperties);
			}
			return this;
		}

		public Builder addComments(List<MetricsComment> comments) {
			if (comments != null) {
				this.comments.addAll(comments);
			}
			return this;
		}

		public Builder addErrors(List<MetricsError> errors) {
			if (errors != null) {
				this.errors.addAll(errors);
			}
			return this;
		}

		public BatchMetricImpl build() {
			return new BatchMetricImpl(this.batchId, this.metricProperties,
					this.comments, this.errors);
		}
	}
}

```

**Comment by cowtowncoder** [comment]
Interesting. I wasn't even sure if Builders did allow any setters... :)

That does look wrong -- thank you for providing the test, I'll see if I can figure out why it fails; and whether it is incorrect reporting or buggy implementation (or perhaps both).

**Comment by cowtowncoder** [comment]
Odd. My first attempt at simplified test passed with flying colors, using 2.6.0-rc2. Will try with your exact test code next.

**Comment by jeffklassen** [comment]
Thanks for looking into this. Is your builder nested inside the class you are trying to serialize? I tried moving mine outside and got the same result.

We are using 2.5.1. We can certainly upgrade.

**Comment by cowtowncoder** [comment]
If you can quickly test with 2.6.0-rc2, that could help isolate the issue, although I can't think of a change that would explain difference. If it's 2.5-only I can look into fixing it there; although verifying the problem with 2.5.4 would then be useful.

**Comment by cowtowncoder** [comment]
And no, builder and value are siblings, static inner classes within test.

**Comment by jeffklassen** [comment]
I’m still getting the same error with 2.6.0-rc2. When you get a chance, would you please send me the source code you are testing with?

**Comment by cowtowncoder** [comment]
It's class `com.fasterxml.jackson.databind.creators.BuilderSimpleTest` from commit listed higher up on this issue.

**Comment by jeffklassen** [comment]
Thanks -- pouring through that now. One thing that confuses me a bit is that in the following error message:
```
com.fasterxml.jackson.databind.JsonMappingException: Problem deserializing "any" property 'archiveDestinationType' of class metrics.business.dao.impl.BatchMetricImpl$Builder (expected type: [simple type, class java.lang.Object]; actual type: java.lang.String), problem: object is not an instance of declaring class (through reference chain: metrics.business.dao.impl.Builder["archiveDestinationType"])
```

metrics.business.dao.impl.Builder seems to be pointing to the incorrect class. Should this be metrics.business.dao.impl.**BatchMetricImpl**$Builder or metrics.business.dao.impl.**BatchMetricImpl**. Builder?

**Comment by cowtowncoder** [comment]
Looking at the point where exception is thrown, this is actually a translation at `SettableAnyProperty` method `_throwAsIOE`, from `IllegalArgumentException`. And underlying exception gives a message pointing to this:

http://stackoverflow.com/questions/13336057/java-reflection-object-is-not-an-instance-of-declaring-class

which does indeed suggest like somewhere beams got crossed, and builder is expected where value is returned or vice versa.

If you could get the stack trace for the root exception, that could be helpful. I don't see anything wrong in class declaration itself.

**Comment by jeffklassen** [comment]
Is this what you are looking for?

```
com.fasterxml.jackson.databind.JsonMappingException: Problem deserializing "any" property 'archiveDestinationType' of class metrics.business.dao.impl.BatchMetricImpl$Builder (expected type: [simple type, class java.lang.Object]; actual type: java.lang.String), problem: object is not an instance of declaring class (through reference chain: metrics.business.dao.impl.Builder["archiveDestinationType"])
	at com.fasterxml.jackson.databind.deser.SettableAnyProperty._throwAsIOE(SettableAnyProperty.java:176) ~[jackson-databind-2.5.1.jar:2.5.1]
	at com.fasterxml.jackson.databind.deser.SettableAnyProperty.set(SettableAnyProperty.java:147) ~[jackson-databind-2.5.1.jar:2.5.1]
	at com.fasterxml.jackson.databind.deser.SettableAnyProperty.deserializeAndSet(SettableAnyProperty.java:118) ~[jackson-databind-2.5.1.jar:2.5.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1296) ~[jackson-databind-2.5.1.jar:2.5.1]
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer._deserialize(BuilderBasedDeserializer.java:230) ~[jackson-databind-2.5.1.jar:2.5.1]
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer._deserializeUsingPropertyBased(BuilderBasedDeserializer.java:353) ~[jackson-databind-2.5.1.jar:2.5.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1073) ~[jackson-databind-2.5.1.jar:2.5.1]
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserializeFromObject(BuilderBasedDeserializer.java:277) ~[jackson-databind-2.5.1.jar:2.5.1]
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:143) ~[jackson-databind-2.5.1.jar:2.5.1]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562) ~[jackson-databind-2.5.1.jar:2.5.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578) ~[jackson-databind-2.5.1.jar:2.5.1]
	at metrics.business.dao.elasticsearch.ElasticSearchMetricsClient.deserializeResponse(ElasticSearchMetricsClient.java:167) ~[bin/:?]
	at metrics.business.dao.elasticsearch.ElasticSearchMetricsClient.getSingleBatchMetric(ElasticSearchMetricsClient.java:185) [bin/:?]
	at metrics.business.dao.elasticsearch.ElasticSearchMetricsClient.main(ElasticSearchMetricsClient.java:73) [bin/:?]
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_67]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_67]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_67]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_67]
	at com.fasterxml.jackson.databind.deser.SettableAnyProperty.set(SettableAnyProperty.java:145) ~[jackson-databind-2.5.1.jar:2.5.1]
	... 12 more
```

**Comment by cowtowncoder** [comment]
Yes, thank you. That line just invokes any setter, but from that and exception it definitely sounds like setter was called on wrong object (like value, not builder).

Any chance you could expand that stack trace bit more? Would be interesting to see where within builder-based deserializer this gets called. I am guessing there must be some sequence where `build()` gets called, and any-setter at some later point. Or something like that.

**Comment by brianjconnolly** [comment]
I am also having this issue and it appears to me that this exception is thrown if a @JsonAnySetter property appears below all the properties that appear in the @JsonCreator annotated constructor. If the @JsonAnySetter property appears before the last @JsonCreator property, deserialization worked correctly.

**Comment by cowtowncoder** [comment]
That is odd.... ordering should not really have any effect, processing should not count on that or be affected by it. Not saying it can not, just that it's a fascinating side-effect of something unintentional. :)

Thank you for mentioning it.

**Comment by cowtowncoder** [comment]
I can not reproduce this. May be reopened with a full, reproducible test case.

**Comment by cowtowncoder** [comment]
Looks like #2415 patch could resolve this issue, will be in `2.10.0.pr2` (and final `2.10.0`)
