### ISSUE TITLE
Custom JsonDeserializer for a primitive breaks default value handling in 2.6.x

### ISSUE THREAD

**Issue by wilkinsona** [FasterXML/jackson-databind#896]
In 2.6, when a primitive property is annotated with `@JsonDeserialize`, the default value for that property becomes `null`, rather than something that's appropriate for the primitive. This causes an `IllegalArgumentException` when calling `Constructor.newInstance`. This is illustrated by the following test:

```java
@Test
public void defaultValueWithCustomDeserializer() throws Exception {
	assertEquals(0, new ObjectMapper().readValue("{}", Pojo.class).value);
}
	
static class Pojo {
		
	private final int value;

	@JsonCreator
	public Pojo(@JsonProperty("value") @JsonDeserialize(using = MyDeserializer.class) int value) {
		this.value = value;
	}
}
	
static class MyDeserializer extends JsonDeserializer<Integer> {

	@Override
	public Integer deserialize(JsonParser p, DeserializationContext ctxt)
			throws IOException, JsonProcessingException {
		return 42;
	}
		
}
```

The test fails with Jackson 2.6.1:

```
com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.example.DefaultValuesTests$Pojo] value failed: null
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapException(StdValueInstantiator.java:399)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:231)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:135)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:440)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3702)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2714)
	at com.example.DefaultValuesTests.defaultValueWithCustomDeserializer(DefaultValuesTests.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.IllegalArgumentException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:125)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:227)
	... 31 more
```

It passes with 2.5.4. It also passes with 2.6.1 if `@JsonDeserialize` is removed from the `value` argument of the `Pojo` constructor.

**Comment by cowtowncoder** [comment]
Ok. This might actually be a sort of feature here, as custom deserializer should define:

    public T getNullValue(DeserializationContext ctxt)

which gets called to find the appropriate null value to use, even with the standard deserializers.

**Comment by wilkinsona** [comment]
If it is a feature, it's an unwelcome one (from my perspective at least), for a couple of reasons:

- It's a change in behaviour between Jackson 2.5 and 2.6 that regresses existing functionality
- If I was previously happy with Jackson's default value for a primitive, I now have to implement an extra method to get the same behaviour. I'd prefer not to have to write more code.

**Comment by cowtowncoder** [comment]
I view it as fixing a flaw, and was not aware that it would cause backwards compatibility issues.
Without calling this method there is/was no way to specify how `null` would be mapped (either for primitives or other types), or, missing value, for that matter. And default implementation of `JsonDeserializer` has no knowledge of actual type being used, and can not provide for defaulting.

So while this is unfortunate in your case (and breakage itself is unintentional), I do not see an immediate way to reconcile goals of allowing null mapping override with a generic way of defaulting for the special case of primitives (for which `null` is not acceptable).

One possibility could be to add handling within `StdScalarDeserializer` or perhaps `StdDeserializer`.
Actually, use of either one as base class would be recommended over directly extending `JsonDeserializer`, but in this case it would not make a difference as things are.
