### ISSUE TITLE
Unable to have two @JsonUnwrapped annotated object of same type within one constructor

### ISSUE THREAD

**Issue by smil2k** [FasterXML/jackson-databind#917]
Most likely this is a leftover work from the prefix/suffix support on JsonUnwrapped:

Test case:

public FullExample(
            @JsonUnwrapped(prefix = "pre_") Unwrapped unwrapped,
            @JsonUnwrapped(prefix = "post_") Unwrapped unwrappedPost) {

The exception generated (in my test class there were more than one properties in the constructor):
com.fasterxml.jackson.databind.JsonMappingException: Duplicate creator property "@JsonUnwrapped" (index 18 vs 19)
	at com.fasterxml.jackson.databind.deser.impl.CreatorCollector.addPropertyCreator(CreatorCollector.java:182)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addDeserializerConstructors(BasicDeserializerFactory.java:458)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:325)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:266)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:266)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:168)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:399)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:348)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:261)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:241)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:394)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3169)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3062)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2161)

**Comment by cowtowncoder** [comment]
Yes, does sound like an edge case that is not correctly handled.
Thank you for reporting this.

**Comment by gauravcb** [comment]
is there any update on this issue ?

**Comment by cowtowncoder** [comment]
@gauravcb No work has been done on this one.

**Comment by gauravcb** [comment]
thanks for quick response @cowtowncoder , is there any ETA or any plans for fixing this anytime soon ?

**Comment by cowtowncoder** [comment]
@gauravcb It's an OSS project, so unless someone has time and itch to work, no. Currently I don't know of anyone working on it or planning to.

**Comment by gauravcb** [comment]
thanks for udpate @cowtowncoder

**Comment by cowtowncoder** [comment]
Looks like this was fixed in 2.19.0.
