### ISSUE TITLE
UnrecognizedPropertyException 

### ISSUE THREAD

**Issue by monusurana** [FasterXML/jackson-databind#920]
I'm getting this UnrecognizedPropertyException for a JSON as simple as:
```
{
Name: "India",
teamid: "4"
}
```
###### Error:
```
9-07 18:00:56.801  9188  9262 I OpenGLRenderer: Initialized EGL, version 1.4
9-07 18:00:58.567  9188  9188 D MainActivityFragment: onDataChange
9-07 18:00:58.567  9188  9188 D MainActivityFragment: 0
9-07 18:00:58.568  9188  9188 D MainActivityFragment: {teamid=4, Name=India}
9-07 18:00:58.588  9188  9188 D AndroidRuntime: Shutting down VM
9-07 18:00:58.594  9188  9188 E AndroidRuntime: FATAL EXCEPTION: main
9-07 18:00:58.594  9188  9188 E AndroidRuntime: Process: com.example.android.firebaseexample, PID: 9188
9-07 18:00:58.594  9188  9188 E AndroidRuntime: com.firebase.client.FirebaseException: Failed to bounce to type
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at com.firebase.client.DataSnapshot.getValue(DataSnapshot.java:183)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at com.example.android.firebaseexample.MainActivityFragment.onDataChange(MainActivityFragment.java:60)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at com.firebase.client.core.ValueEventRegistration.fireEvent(ValueEventRegistration.java:45)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at com.firebase.client.core.view.DataEvent.fire(DataEvent.java:45)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at com.firebase.client.core.view.EventRaiser$1.run(EventRaiser.java:38)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
9-07 18:00:58.594  9188  9188 E AndroidRuntime: Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Name" (class com.example.android.firebaseexample.Se
ies.Past.Team), not marked as ignorable (2 known properties: , "teamid", "name"])
9-07 18:00:58.594  9188  9188 E AndroidRuntime:  at [Source: java.io.StringReader@4f55749; line: 1, column: 23] (through reference chain: com.example.android.firebaseexample.Series.Past.Team["Name
])
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2034)
9-07 18:00:58.594  9188  9188 E AndroidRuntime:        at com.firebase.client.DataSnapshot.getValue(DataSnapshot.java:181)
```

###### How I was using it ?

I created a class Team to get the JSON from firebase server 
```
public class Team {

    // NOTE: The members are same as the ones in JSON 
    private String teamid;
    private String Name;

    public String getTeamid() {
        return teamid;
    }

    public void setTeamid(String teamid) {
        this.teamid = teamid;
    }

    //@JsonProperty("Name")
    public String getName() {
        return Name;
    }

    public void setName(String name) {
        this.Name = name;
    }
}
```

And using it in the code like this and I was getting the above mentioned error:
```
Team match = dataSnapshot.getValue(Team.class);
```

Not sure why I'm getting error for <b>Name</b> field in the first place (the class member variable and JSON member matches and also a getter and setter was implemented for this member): <b>Unrecognized field "Name" </b>

Finally I figured out a workaround, had to use <b>@JsonProperty("Name")</b> to fix it 
```
    @JsonProperty("Name")
    public String getName() {
        return Name;
    }
```

**Comment by cowtowncoder** [comment]
This is not a bug: Java Bean naming dictates that property name is `name`, if accessor name is `getName()`. And JSON names are not case-insensitive.
